### ISSUE TITLE
Should 'state' param use ModifierContextState type?

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1000]
https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/gracenotegroup.ts#L46

@rvilarl I noticed that all other format(...) functions have a `ModifierContextState` as the second param. I assume this is one of the earlier migrations. Should we now change the type of the second param to be `ModifierContextState`?

**Comment by 0xfe** [comment]
Yes, correct -- it should be `ModifierContextState`
