### ISSUE TITLE
undefined vs null: last_bend should be compared against undefined

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1003]
https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/bend.ts#L249-L292

In the first line we set last_bend to `undefined`, but later on we compare it against `null`:

https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/bend.ts#L276
```
        if (last_bend === null) {    // <== this is always false
```

Also, we check 
https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/bend.ts#L290
```
    if (!last_bend || last_bend.x == undefined) {  // use strict equality, or else null will also pass this test
```

I think for checks against `undefined` we should generally use triple equal === for more strict comparisons (especially since we are moving away from usage of `null`).

**Comment by rvilarl** [comment]
Agree with your comments

**Comment by 0xfe** [comment]
Thanks for catching this Ron, do the bend tests catch this?

**Comment by 0xfe** [comment]
i.e., do the visual tests show a difference? (if not, we prob should add a test too.)

**Comment by rvilarl** [comment]
@ronyeh will you do a PR on that?

**Comment by ronyeh** [comment]
Sure, I can do a PR.

**Comment by rvilarl** [comment]
@ronyeh I believe it is better to use !last_bend so as to have backwards compatibility with `null`. I have included the change in #1058

**Comment by ronyeh** [comment]
Hi Rodrigo,

The benefit of !x is that it is very concise. However, !x is true if x is
0, null, false, or undefined. This kind of check for a falsy value can be
buggy if we are not careful.

I think we converted the entire codebase to use undefined if a property was
optional, correct? In the past, vexflow often used null instead.

Here is one case where the not operator would cause a bug.


*export class Modifier extends Element {*
*  protected index?: number;*

So by default, index is undefined. However, the number 0 is a valid value.
So* !mod.index* will return true if the index is undefined, and also true
if the index is 0.

Since we use undefined widely in the vexflow codebase, I think we should
explicitly check for undefined.

This might be overkill, but we could add a utility function
isUndefined()... 😄

...it turns out there is a NPM package for this (I am not recommending that
we npm install it haha). That package has three contributors!? The current
definition is:

https://raw.githubusercontent.com/IonicaBizau/is-undefined/master/lib/index.js

It's actually an interesting implementation. I knew of the void 0 and
typeof solutions, but I never thought to simply compare it against an
uninitialized variable....

Ron

**Comment by rvilarl** [comment]
@ronyeh in order to avoid `any` we would need a template, something like:
```js
function isUndefined<T>(x?: T): boolean {
  return x === undefined;
}
```
the compiler today does not complain about
```js
if (!last_bend || last_bend.x == undefined) {
      throw new RuntimeError('NoLastBendForBend', 'Internal error.');
    }
```
However the compiler will compile about `last_bend.x == undefined` (_last_bend is possibly undefined_) due to the fact that it does not look into the implementation details of `isUndefined`:
```js
 if (isUndefined<BendPhrase>(last_bend) || last_bend.x == undefined) {
      throw new RuntimeError('NoLastBendForBend', 'Internal error.');
    }
```
 Did I understand the proposal right? This would be too complicated, would not it?

I am aware that we have to take care when using `!`. But in this particular case I would say that it is the best approach.

**Comment by sschmidTU** [comment]
I agree `!` is solid in a lot of cases, especially if you're using it on an object, which won't be `0` or `false`.
You wouldn't use `!var` where `var` is a number, it's clear that's a problem with `var == 0`.

**Comment by ronyeh** [comment]
If we had a utility function called isUndefined(), I would just add a
eslint disable in front of it to allow any.

But I am okay with !foo because it is concise. We can just add typings to
the local variable declarations like let last_bend: Bend;

Then we need to be careful to never use !foo if foo is an optional boolean
or an optional number property....

**Comment by rvilarl** [comment]
@ronyeh I agree optional fields should be avoide, however in regards to default values
@0xfe I believe that you expressed your oppinion once with preference on `undefined` rather than invalid default values, is that right?

**Comment by 0xfe** [comment]
Yes, vaild default values are always better, and trying hard to avoid optionality is ideal.

But if the choice is between `undefined` and an invalid default value, then `undefined` is preferred. (Some counterexamples of this are numbers (e.g., indexes) where defaults like -1 or `Number.MAX_SAFE_INTEGER` are better than undefined.)

**Comment by rvilarl** [comment]
@ronyeh I believe that this can be closed
