### ISSUE TITLE
How to tremolo

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1008]
I came across an old Sibelius score I have, it had a tremolo like so.  Is there a way to do this in vex? I didn't see any unit test cases like this.

![image](https://user-images.githubusercontent.com/5438280/119925981-166b3600-bf3c-11eb-87ae-86ffa7a0578e.png)

**Comment by 0xfe** [comment]
I think `strokes.js` will do it?

**Comment by ronyeh** [comment]
In the current percussion tests, I see:

```
vf.StaveNote({ keys: ['c/5'], duration: '4', stem_direction: -1 }).addArticulation(0, new VF.Tremolo(1)),
vf.GraceNote({ keys: ['c/5'], duration: '4', stem_direction: -1 }).addArticulation(0, new VF.Tremolo(1)),
vf.StaveNote({ keys: ['c/5'], duration: '4', stem_direction: -1 }).addArticulation(0, new VF.Tremolo(3)),
vf.StaveNote({ keys: ['c/5'], duration: '4', stem_direction: -1 }).addArticulation(0, new VF.Tremolo(5)),
```

**Comment by AaronDavidNewman** [comment]
Thank you!  I was looking for it in articulation/ornament, but it was in tremolo all along.

**Comment by 0xfe** [comment]
aargh, how did I miss that?! :-)
