### ISSUE TITLE
Duplicate/nested for loop

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1013]
https://github.com/0xfe/vexflow/blob/faf894c4adb650b864d7a10ab02e904fde5fd60e/src/stringnumber.ts#L52-L58

It's late and I'm seeing double. :-D

While working on my PR I ran across these lines which stood out to me and just look wrong.

I believe the outer for loop can just be removed, correct? Since they both iterate on index i, by the time the inner for loop finishes, the outer one will also finish.

**Comment by sschmidTU** [comment]
yeah, looks like one of the loops can be removed, they do the same thing.
It definitely doesn't make sense to have nested loops on the same index variable (i).

**Comment by ronyeh** [comment]
Thanks for the sanity check @sschmidTU . I added a PR with the fix.
