### ISSUE TITLE
Glyphs & Metrics

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1022]
@AaronDavidNewman I believe I need your help to get clarity on the purpose of different structures/interfaces. I already realised that it was complex when I started porting music.ts.

**Comment by rvilarl** [comment]
Issue 1

**Comment by rvilarl** [comment]
Issue 2

https://github.com/0xfe/vexflow/blob/afcbae29d1c4de3cb0cfa0dcbd1accd117f08394/src/glyph.ts#L18-L44

**Comment by rvilarl** [comment]
**Topic 3**
**Should not the function `getGlyphProps` be a static function in `Glyph` returning an instance of `Glyph`?** It is now a complex construction generating objects in the fly.

https://github.com/0xfe/vexflow/blob/afcbae29d1c4de3cb0cfa0dcbd1accd117f08394/src/tables.js#L758-L788

**Comment by AaronDavidNewman** [comment]
>> Here I believe that the second is simply a partial representation of the first one and that only FontGlyph should be used, 

Right now, text font metrics are a proper subset of font metrics.  Probably we shouldn't depend on that to remain so.  We may want to use other information in the font files that aren't a part of glyphs (like hints, kerning, ligatures, etc.) one day.  Also, we probably want the text font structure to be as small as possible because text and music font data is cached separately.  We don't store path information ('o' string field) for textfont for instance.  I am a little ignorant of how typescript works so I don't know if having nullable fields in interfaces affects actual storage space.

So, I think they (textfont metric vs. music font metrics ) should remain separate interfaces.

It does seem like `GlyphMetrics ` and `FontMetrics`  are representing the same thing, but I'd need Mohit to comment on why we have both.

**Comment by 0xfe** [comment]
Topic 1 -- `GlyphMetrics` vs. `FontMetrics` -- yes, absolutely merge. Not sure how those emerged, but we should clean it up.

Topic 2 -- `GlyphProps` vs. `Glyph` -- `GlyphProps` has a whole bunch of semantic properties for each glyph code. `Glyph` encapsulates the logic just to render a single glyph. So typically a `Glyph` is constructed and positioned based on `GlyphProps`.

Topic 3 -- `getGlyphProps` should stay separate from `Glyph`. I think `Glyph` should be agnostic to duration, type, etc.

Maybe there's an opportunity for a new `GlyphBuilder` that takes `GlyphProps` and builds `Glyph` instances?

**Comment by rvilarl** [comment]
> It does seem like `GlyphMetrics ` and `FontMetrics` are representing the same thing, but I'd need Mohit to comment on why we have both.

@AaronDavidNewman what do you refer to with `FontMetrics`? `GlyphProps`?

**Comment by AaronDavidNewman** [comment]
>> @AaronDavidNewman what do you refer to with FontMetrics? GlyphProps or FontGlyph?

I used the wrong class names (I think @0xfe  did the same :)  and I corrected the original post.  Caveat: I know nothing about the history of music font file, just an observation.

**Comment by rvilarl** [comment]
@0xfe @AaronDavidNewman I have spent sometime looking at the files that we have under src/font/ because I believe that this structures model some how the context of these files. We have three different types:
1) **XXX_glyphs.ts** with the following attributes for the different `glyphs` (ie.: `gClef`, `coda`...):
```js
x_min: number;
x_max: number;
y_min?: number;
y_max?: number;
ha: number;
o?: string;
leftSideBearing?: number;
advanceWidth?: number;
```
I guess that this is the aim of `FontGlyphs`

2) **XXX_textmetrics.ts** with the following attributes for the different `glyphs` which happen to be characters (ie.: `A`, ... `a`, `b`, ... `#`...):
```js
x_min: number;
x_max: number;
y_min: number;
y_max: number;
ha: number;
leftSideBearing: number;
advanceWidth: number;
```
Note that the attributes are not optional and that `o` the _recipe_ to draw is missing.

3) **XXX_metrics.ts** with an heterogeneus set of attributes related with potisionins for different elements (ie.: `stave`, `clef`, `pedalmarkings`, ... ):
```js
padding?:number;
point?:number;
shiftX?: number;
shiftY?: number;
scale?:number;
line?:number;
width?:number;
smuflCode?:string;
shiftLine?:number;
tuplePoint?:number;
...
```
Those values are accessed normally using `lookupMetric`. However in `GlyphMetrics` we see a few of those.

**Comment by rvilarl** [comment]
@0xfe Taking into account the explanation above. I know how to resolve your comment on #1011. `TextFontMetric` makes sense for 2) and there `advanceWidth` is not optional. I will adjust #1011.

**Comment by 0xfe** [comment]
👍 Thanks
