### ISSUE TITLE
Visual Regressions

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1030]
This is a meta item that will track multiple issues with visual regressions / differences from 3.0.9 or the version on [vexflow.com](https://vexflow.com/).

I've noticed some possible regressions, which we can tackle post TS migration.

I'll post them here (others can feel free to contribute and I'll edit this post). Then we can categorize them and turn them into individual issues or PRs when the time comes.

I don't know which exact version is hosted on https://www.vexflow.com/tests/
The banner in vexflow-tests.js says `VexFlow 1.2.77 built on 2016-08-21.` while vexflow-debug.js.map lists `"version":3`.

Regardless, `master` and `3.0.9` both have some differences relative to `vexflow.com`.

**Comment by ronyeh** [comment]
I did some digging and it looks like the version on vexflow.com is between releases:

A. https://unpkg.com/vexflow@1.2.77/releases/vexflow-debug.js
B. https://www.vexflow.com/build/vexflow-debug.js
C. https://unpkg.com/vexflow@1.2.78/releases/vexflow-debug.js

A has VibratoBracket which B does not have. C has EasyScore which B does not have. For the purposes of the comparisons below, I'll refer to B as version **1.2.77X**.

**Comment by ronyeh** [comment]
### TextNote Superscript and Subscript
* some superscripts (e.g., +5) are offset to the right in version 3.0.9.
* the superscripts/subscripts on the Canvas test case are not visible. This was addressed in PR https://github.com/0xfe/vexflow/pull/1027 
* This is possibly due to issues with measuring text height & width.

1.2.77X
<img width="200" src="https://user-images.githubusercontent.com/239113/121610414-d2336780-ca0a-11eb-824f-74312e2dd41a.png">
3.0.9

<img width="200" src="https://user-images.githubusercontent.com/239113/121610666-630a4300-ca0b-11eb-9f0c-c95f62f8171b.png" style="border: 12px solid red;">

**Comment by rvilarl** [comment]
@ronyeh why did you select 1.2.77 rather than 1.2.93 to look into differences?

**Comment by ronyeh** [comment]
Good question. I can actually put as many versions as you want on my demo
site, if we need to narrow down when a bug was introduced.

While migrating CanvasContext, I happened to discover a bug in the TextNote
test case, and noticed that on VexFlow.com, the same test case looked fine.
Then I tried to look into which version was hosted on VexFlow.com.... After
some detective work, I decided it was somewhere between releases 1.2.77 and
1.2.78, but I might be wrong.

For example, for the buggy test case:
This is the VexFlow.com version:
https://vexflow-demo.vercel.app/tests/flow-1.2.77X.html?module=TextNote&filter=superscript
This is the current master:
https://vexflow-demo.vercel.app/tests/flow-master.html?module=TextNote&filter=superscript
This is the 3.0.9 release:
https://vexflow-demo.vercel.app/tests/flow-3.0.9.html?module=TextNote&filter=superscript

Let me know if there are any specific versions you want me to put up on my
test site!

**Comment by ronyeh** [comment]
I added support for loading any version that is hosted on unpkg.com.

So you can compare test cases between all released versions with URLs that look like:

https://vexflow-demo.vercel.app/tests/version/1.2.93?module=Articulation&filter=accent
https://vexflow-demo.vercel.app/tests/version/3.0.4?module=Articulation&filter=accent

https://vexflow-demo.vercel.app/tests/version/3.0.1?module=TextNote&filter=superscript
https://vexflow-demo.vercel.app/tests/version/1.2.93?module=TextNote&filter=superscript

So you can see the superscript bug was probably introduced sometime in between versions 1.2.93 and 3.0.1.
You can get a list of all releases under the dropdown list at the top right of:
https://unpkg.com/browse/vexflow/releases/

**Comment by ronyeh** [comment]
You can also see that the ledger lines got thinner sometime between releases 1.2.83 and 1.2.84.

https://vexflow-demo.vercel.app/tests/version/1.2.83?module=EasyScore

https://vexflow-demo.vercel.app/tests/version/1.2.84?module=EasyScore

**Comment by 0xfe** [comment]
@ronyeh thanks so much for this analysis. How do we turn these into issues that we can fix one-by-one?

**Comment by ronyeh** [comment]
Sure, feel free to turn them into individual github issues. I was just throwing together a quick and dirty way to track possible regressions.

I'll be out most of next week. When I get back I can open some GitHub issues if you and Rodrigo haven't done so already.

**Comment by ronyeh** [comment]
I created individual GitHub issues for the bugs:
* TextNote Superscript and Subscript: https://github.com/0xfe/vexflow/issues/1118
* Missing Ledger Line: https://github.com/0xfe/vexflow/issues/1119
* With Petaluma font, quarter notes extend past the end of the measure: https://github.com/0xfe/vexflow/issues/1120
