### ISSUE TITLE
MultiMeasureRest.Simple_Test regression due to recent merge

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1034]
MultiMeasureRest.Simple_Test.Bravura.png
![MultiMeasureRest Simple_Test Bravura](https://user-images.githubusercontent.com/239113/121789584-02564400-cb8c-11eb-8f78-e9012ddbdb02.png)

MultiMeasureRest.Simple_Test.Petaluma.png
![MultiMeasureRest Simple_Test Petaluma](https://user-images.githubusercontent.com/239113/121789585-02eeda80-cb8c-11eb-8981-f6d19140b4f5.png)

**Comment by 0xfe** [comment]
@rvilarl

**Comment by 0xfe** [comment]
@rvilarl if you could take a look please. Let's fix this before merging the rest.

@ronyeh thanks for keeping an eye on this.

**Comment by rvilarl** [comment]
@ronyeh I did not get any difference using `npm run test:reference` what have you used?

**Comment by rvilarl** [comment]
Confirmed `visual_regression.sh` does not pick the error with the current threshold (0.01):
```
MultiMeasureRest.Simple_Test.Bravura 0.000967953
MultiMeasureRest.Simple_Test.Petaluma 0.00860469
```
yesterday looking at #1030 I was thinking on how to compare automaticaly the web pages and I came to the idea that a textual comparison on SVG could more accurate and quicker that the current visual regression using imagemagick, **@0xfe & @ronyeh what do you think?**

**Comment by ronyeh** [comment]
Interesting idea about diffing the actual SVG paths :-) I could imagine cases where the SVG path could be different yet somehow produce the same visual result.

However, it might be a good 1st pass diff. If the SVG paths didn't change, it should be the same output. However, if the SVG path changes by even 1 character, we can flag it and then run the actual PNG diff.

**Comment by 0xfe** [comment]
It's def worth a try, as a pass, but not as a full replacement, since we've frequently reworked the drawing to generate the same images (but with different paths, ordering, element grouping, etc.)
