### ISSUE TITLE
Problem with chord accidental on wrong line.

### ISSUE THREAD

**Issue by thinkingspace** [0xfe/vexflow#104]
Based on my understanding the following code should add a flat to the A, but it is rendered on the B
![chord](https://f.cloud.github.com/assets/4070453/444555/d044f504-b1a6-11e2-9e65-68df60440963.jpg)
 

	var notes = [
    	new Vex.Flow.StaveNote({ keys: ["B/4", "A/4"], duration: "q",  stem_direction: 1})
  	];	
  	
	//Add flat to the A  
  	notes[0].addAccidental(1, new Vex.Flow.Accidental('b'));

**Comment by 0xfe** [comment]
Okay, implemented option 3, which is least likely to break users. This displays a warning on the console if keys are not provided in order.

**Comment by stephaneeybert** [comment]
Is there any way to keep the keys in their original order ?

**Comment by stephaneeybert** [comment]
To replicate sorting also be done on a custom data model I would need to know what is meant with "sorting by pitch".

I have a chroma value as string and an octave value as number. Can I render the same pitch with these two ? 

I need to sort my notes to replicate the sorted keys.

Or can I pass in the dotted boolean when creating a multi keys stave note ?

**Comment by rowild** [comment]
It seems that the re-write of a chord is triggered, when there are at least 5 notes in minor/major second distance. A rendering of `tonal.js`'s h11 chord shows a wrong result. Would love to know how to fix this. Any ideas?

**Comment by gristow** [comment]
@stephaneeybert, you need to sort the keys before creating a `StaveNote` and give a sorted array to the constructor. The sorting used by VexFlow is sort by lowest-to-highest placement on the staff. So, E# should be sorted lower than Fb.

@rowild it seems you may be asking about a different issue.  Can you post pictures & or code for the problem you're describing as a new issue?

**Comment by rowild** [comment]
@gristow Thank you for your feedback! - I prepared a codesandbox here and a screenshot:

https://codesandbox.io/s/list-of-tonaljs-chords-ntjye

If you hit a key (e.g. "C4") and the select the chrod "h11" (m11b5), you can examine the results. In the case of "C4", there should be a "g flat" somewhere, but isn't. In the case of "F4" there should be an "e-flat" etc.

I thought this problem would be related to this issue here, which is why I posted my comment. If not and you still think it is an issue, please let me know, what you want me to do (opening a new issue...)

Thank you and stay save!!!

![Bildschirmfoto 2020-03-25 um 16 46 53](https://user-images.githubusercontent.com/213803/77556281-97521c00-6eb8-11ea-9a24-e9e10f2c3d3e.png)

**Comment by rowild** [comment]
EDIT: Actually - I think my calculation with the accidentals is not correct... need to check that... refering to the example screenshot: The "D4" and "F4" seem to be placed to a position in the array that comes before the notes that are in the 5th register. This is probably the reason why I get the warning message: "Warning:  Unsorted keys in note will be sorted. See https://github.com/0xfe/vexflow/issues/104 for details."

How would I have to write an array that gets sorted correctly?

**Comment by gristow** [comment]
Yes, that's exactly it: You'll need to sort the notes into pitch order (ignoring accidentals), in this case as:
- C4-D4-Eb4-F4-Bb4-Gb5

(Although, I have to say... that's a pretty gnarly spacing for an 11b5 chord!)

**Comment by rowild** [comment]
@gristow Do you know if I have to write my own function to sort the pitches or if VexFlow provides some helper methods? So far I have been unsuccessfull...

And I agree: the voicing is ... different...

**Comment by 0xfe** [comment]
You can use the `keyProperties` table to get the values for the pitches -- here's a sorting example:

```js
function getValue(note) {
  parts = note.split("/");
  return Vex.keyProperties.note_values[parts[0].toUpperCase()].int_val * parseInt(parts[1]);
}

notes = ['a/4', 'a/3', 'b/4']
notes.sort((a, b) => getValue(a) - getValue(b)))
// output: ["a/3", "a/4", "b/4"]
```

**Comment by 0xfe** [comment]
Also note that `Array.sort` is not stable ordering, so if you have multiple pitches with the same value, the ordering is not deterministic.

**Comment by rowild** [comment]
@0xfe Thank you for sharing the code, but I am not sure, if it works correctly? I keep getting incorrect results...

![Bildschirmfoto 2020-03-25 um 21 27 47](https://user-images.githubusercontent.com/213803/77582341-849f0d80-6edf-11ea-8cbb-0f38ef703598.png)

The code is implemented in this codesandbox:
https://codesandbox.io/s/list-of-tonaljs-chords-ntjye
in the `NoteDisplay.vue` component, in case you want to have a look.

I should mention that the `m11b5` (`h11`) chord in the tonal.js library seems to be the only one that is ordered incorrectly.

**Comment by rowild** [comment]
I am stuck! Is the algorithm wrong or am I doing something wrong!
Please advice!

**Comment by 0xfe** [comment]
Your line 226 in `NoteDisplay.vue` should be:

```javascript
return (VF.keyProperties.note_values[parts[0].toUpperCase()].int_val + parseInt(parts[1], 10) * 12);
```

My fault, the code snippet I give you was wrong. I fixed it. Basically you're sorting by value, where `value = octave * 12 + key.int_val`

**Comment by SalahAdDin** [comment]
It seems so interesting.
