### ISSUE TITLE
API documentation: VoiceGroup, is it required?

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1042]
I was looking into making an example for the documentation of the API. I selected this class as it is small.

Looking into details to understand the aim of it I got to the conclusion that it is not required and could be deleted.

Am I missing something?

**Comment by rvilarl** [comment]
@0xfe perhaps you missed this one

**Comment by 0xfe** [comment]
I dug into this, and I think you're right -- I don't see it used anywhere. I'd say go ahead and remove it. If someone complains about it, then'll we'll deal with it then.

**Comment by rvilarl** [comment]
Ok I will create a PR
