### ISSUE TITLE
Bach Demo Regression

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1043]
![BachDemo](https://user-images.githubusercontent.com/239113/124036145-695c6100-d9b2-11eb-8d2b-cf4acb82778d.gif)

The current HEAD has a formatting regression. I checked out an older commit from June 13, revision fa6641af53e69b333cc748ba852bcfd0d699acc0 and it looks fine.

Are we currently in the midst of modifying the formatting & padding? (i.e., is this a temporary regression that we don't need to worry about?)

**Comment by AaronDavidNewman** [comment]
This is a bug in system.js.  It was probably introduced when I partially backed out the big formatting change.  I'll try to push a fix tonight.

In system.format we have:
``` javascript
    const justifyWidth = this.options.noPadding
      ? this.options.width - Stave.defaultPadding
      : this.options.width - (startX - this.options.x) - this.musicFont.lookupMetric('stave.padding');
```
It should be this:

``` javascript 
const justifyWidth = this.options.noPadding
      ? this.options.width - this.options.x
      : this.options.width - (startX - this.options.x) - Stave.defaultPadding;
```

**Comment by AaronDavidNewman** [comment]
This is pushed.  Also, if someone is already making system.ts, you can just copy the lines above to `format()`.

**Comment by 0xfe** [comment]
Thanks Ron and Aaron -- is there a PR for this fix?

**Comment by AaronDavidNewman** [comment]
https://github.com/0xfe/vexflow/pull/1044

**Comment by ronyeh** [comment]
The bug seems to still exist on revision f8967def06c2a710658ede34d43413835f4aea0f 

![BACH2](https://user-images.githubusercontent.com/239113/124346298-dd555f80-db92-11eb-9be4-920be7344c54.gif)

The above image compares the current HEAD vs the 3.0.9 release.

**Comment by ronyeh** [comment]
Looks OK in the current version.
