### ISSUE TITLE
You have a terrible documentation. 

### ISSUE THREAD

**Issue by zshimanchik** [0xfe/vexflow#1049]

**Comment by ronyeh** [comment]
Thanks for the feedback! I agree we can always strive for better documentation and code examples. If you have a particular use case for what you want to do, perhaps you can describe it and we can point you in the right direction?

**Comment by 0xfe** [comment]
Closing this as unactionable. Feel free to reopen if there are specific things you'd like to see improved.

**Comment by mscuthbert** [comment]
Illegitimi non carborundum!
