### ISSUE TITLE
Ledger Lines

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1051]
I would like to go with the proposal to make the ledger lines more visible:
- the proposal from @mscuthbert on #806 is to double the width
- the visual regression from @ronyeh shows 30% of width with black colour in 1.2.77

@0xfe @mscuthbert @AaronDavidNewman @ronyeh  what is your preference? Please vote on images below

**Comment by rvilarl** [comment]
Master
![Accidental Accidental_Arrangement_Special_Cases Bravura_Reference](https://user-images.githubusercontent.com/22865285/124373201-833ac400-dc90-11eb-8374-6f721fe73782.png)

**Comment by rvilarl** [comment]
Double width + black
![Accidental Accidental_Arrangement_Special_Cases Bravura_Current](https://user-images.githubusercontent.com/22865285/124373221-b1200880-dc90-11eb-8b80-4796ec0629c3.png)

**Comment by rvilarl** [comment]
**Double width**
![Accidental Accidental_Arrangement_Special_Cases Bravura_Current](https://user-images.githubusercontent.com/22865285/124373280-402d2080-dc91-11eb-823a-d150a7eda7a9.png)

**Comment by 0xfe** [comment]
I like the double width (same colour as background as default).

**Comment by rvilarl** [comment]
@0xfe done on #1052
