### ISSUE TITLE
Runtime error when crotchet (q) triplet followed by semiquaver (16)

### ISSUE THREAD

**Issue by thinkingspace** [0xfe/vexflow#106]
I have some code which works fine when you diplays a 1/4 note triplet followed by a 1/8 note. However, if you make a single change to the code to alter the 1/8 note to a 1/16 note you get a runtime error: 'Beams can only be applied to notes shorter than a quarter note'. (I am using automatic beamimg.)

Code to reproduce this error is provided below. 

    
    //Contructor
    function maTest2 (){
		this.renderer = new Vex.Flow.Renderer('canvas1', Vex.Flow.Renderer.Backends.CANVAS);
		this.ctx = this.renderer.getContext();	
		
		this.vStave1 = new Vex.Flow.Stave(25, 10, 850);
	  	this.vStave1.addClef("treble");
	  	this.vStave1.addTimeSignature("4/4");
		this.vStave1.addKeySignature('C');
		
	  	var notes1 = [
	    	new Vex.Flow.StaveNote({ keys: ["c/4"], duration: "q",  stem_direction: -1}),
	    	new Vex.Flow.StaveNote({ keys: ["c/4"], duration: "q", stem_direction: -1}),
	    	new Vex.Flow.StaveNote({ keys: ["c/4"], duration: "q",  stem_direction: -1}),
	    	//new Vex.Flow.StaveNote({ keys: ["e/4"], duration: "8",  stem_direction: -1}),
	    	new Vex.Flow.StaveNote({ keys: ["e/4"], duration: "16",  stem_direction: -1}),
	  	];	
	  	
		 var voice1 = new Vex.Flow.Voice({
	    	num_beats: 4,
	    	beat_value: 4,
	    	resolution: Vex.Flow.RESOLUTION
	 	 });
	
	  	var tuplet1 = new Vex.Flow.Tuplet(notes1.slice(0, 3));
		
		voice1.setStrict(false);		
		voice1.addTickables(notes1);
		
		var beams1 = Vex.Flow.Beam.applyAndGetBeams(voice1);
		
		var formatter = new Vex.Flow.Formatter().
	    	joinVoices([voice1]).format([voice1], 420);
		
		this.vStave1.setContext(this.ctx).draw();	
	  	voice1.draw(this.ctx, this.vStave1);
	  	  	
		tuplet1.setContext(this.ctx).draw();
	
		for(var i = 0; i < beams1.length; i++){
	 		beams1[i].setContext(this.ctx).draw();
	 	}	 
	}

**Comment by 0xfe** [comment]
This was fixed a while ago: See  http://jsfiddle.net/47528Luv/

![screen shot 2015-10-14 at 8 23 16 am](https://cloud.githubusercontent.com/assets/241299/10483323/d8ff6ca6-724c-11e5-8bda-1e85cf126304.png)
