### ISSUE TITLE
SMuFL - size of vexflow-min.js 

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1060]
Are the applications using VexFlow combining different Music Fonts?

The size of vexflow-min.js (which is now beyond 1Mb) could be reduced drastically if we generated dedicated libraries:

ie.: vexflow-petaluma-min.js vexflow-bravura-min.js ...

@0xfe @ronyeh @AaronDavidNewman @mscuthbert @sschmidTU what do you think?

**Comment by sschmidTU** [comment]
These per-font libraries could be optional builds in addition to the main build with all fonts. You probably meant it like that already.
I like this a lot, especially if it reduces the size to the build significantly (100kb+). We're always trying to keep the bundle size low in our projects, but vexflow takes up a lot of it.
It seems like vexflow 1.2.93 was around 675kb when built into OSMD (the min.js was 494kb), so the 3.x versions are already a lot larger than that.

**Comment by 0xfe** [comment]
+1 for breaking it up. Here's what would be ideal:

1) One build type that separates core from fonts:

```
import 'vexflow-core.min.js'
import 'vexflow-font-bravura.min.js`
```

2) One build type that includes the fonts:

```
import 'vexflow-bravura.min.js'
```

or

```
// All fonts
import 'vexflow-full.min.js'
```

Would be great if we can support both build types.

**Comment by rvilarl** [comment]
I am still having problems with the initialisation of tests but looks good:
```
Running "webpack:build" (webpack) task
assets by status 656 KiB [big]
  asset vexflow-petaluma-min.js 356 KiB [emitted] [minimized] [big] (name: petaluma) 1 related asset
  asset vexflow-min.js 301 KiB [emitted] [minimized] [big] (name: main) 1 related asset
asset vexflow-bravura-min.js 178 KiB [emitted] [minimized] (name: bravura) 1 related asset
asset vexflow-gonville-min.js 136 KiB [emitted] [minimized] (name: gonville) 1 related asset
asset vexflow-custom-min.js 12.9 KiB [emitted] [minimized] (name: custom) 1 related asset
```

**Comment by rvilarl** [comment]
@0xfe @ronyeh I have an issue with your proposal, I do not know how to make use of dynamic imports:
https://webpack.js.org/guides/code-splitting/
and at the same time supporting the option 2 above. 
I would need to change `font.ts` depending on the compilation. How would you suggest to do that?
