### ISSUE TITLE
Potential bug: comparing a number against null

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1061]
https://github.com/0xfe/vexflow/blob/faf894c4adb650b864d7a10ab02e904fde5fd60e/src/stavehairpin.ts#L52-L66

I think the pixelsPerTick is declared as a number, but checked against null.

This is a code smell / potential bug that is similar to the last_bend issue. Perhaps we need to audit the code base for comparisons with null, since our migration is switching away from using nulls?

**Comment by rvilarl** [comment]
yes, this is a good idea

**Comment by rvilarl** [comment]
@ronyeh I have reviewd all the `null` (I removed 5) and `?:` (I found two unused attributes) in the files where I updated the comments and I will continue with that as part of the task. I think we can close now this issue and #1003 and keep on improving the code base! Happy Holidays!

**Comment by 0xfe** [comment]
Thanks @rvilarl for fixing, and @ronyeh for reporting. Closing.
