### ISSUE TITLE
Visual differences: 1.2.93 vs 8d8137ee

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1062]
@AaronDavidNewman @0xfe @ronyeh 
I decided to recompile my App with 8d8137ee in order to see how it looks compared to 1.2.93. It has improved a lot in comparison to 3.0.9 but there are still some problems.

Good news, @types/vexflow is no longer required!

@AaronDavidNewman would it help to get this musicxml files so that you can look into it with smoosic?

**Comment by rvilarl** [comment]
**1.2.93**
![Captura de pantalla de 2021-07-10 14-06-38](https://user-images.githubusercontent.com/22865285/125162446-26f00c80-e188-11eb-8729-57eeacab485f.png)
**8d8137ee**
![Captura de pantalla de 2021-07-10 14-08-34](https://user-images.githubusercontent.com/22865285/125162527-a1b92780-e188-11eb-81a2-c1e8a7365c78.png)
**Issues:**
**- Alignment between staves is wrong**
**- Notes go beyond measures**
@0xfe I think you resolved this one in the past

**Comment by rvilarl** [comment]
**1.2.93**
![Captura de pantalla de 2021-07-10 14-17-00](https://user-images.githubusercontent.com/22865285/125162671-8b5f9b80-e189-11eb-9969-e8fdfec6c903.png)
**8d8137ee**
![Captura de pantalla de 2021-07-10 14-18-08](https://user-images.githubusercontent.com/22865285/125162716-b0540e80-e189-11eb-8031-45b75d9cb24f.png)
**Issues:**
**- Two many free space at the end of measure 1**
**- Accidentals overlap**

**Comment by AaronDavidNewman** [comment]
It looks like there is too much or too little padding.  Can I ask how you're calculating the voice and stave width?

The stave width should be voice width + Stave.defaultPadding + width of clef and other left-hand things.  And you can use preCalculateMinWidth to calculate the voice width.

The Satie looks ok when I render it in Smoosic using this build, and the formatter test cases based on these pieces look fine, too.  (Smoosic doesn't know how to ignore time signatures rn)

![image](https://user-images.githubusercontent.com/5438280/125168953-a9b79e00-e16d-11eb-83e9-84af4ab4a5d0.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman  I use OSDM from @sschmidTU , I will send you an email with both scores to make sure that we are the same ones.

**Comment by rvilarl** [comment]
[Gnossienne_No._3.zip](https://github.com/0xfe/vexflow/files/6795589/Gnossienne_No._3.zip)

**Comment by rvilarl** [comment]
[M_Book_1_Part_1_The_Open_Well_Tempered_Clavier.zip](https://github.com/0xfe/vexflow/files/6795599/M_Book_1_Part_1_The_Open_Well_Tempered_Clavier.zip)

**Comment by rvilarl** [comment]
@AaronDavidNewman I found that zip is allowed here. There you have both files could you try? Thanks.

**Comment by AaronDavidNewman** [comment]
Here' s the Gnossienne in Smoosic.  Looks good.  I would need to know more about what OSMD is doing to see what is wrong.

Also, keep in mind that the last part, formatting correct width from the factory or easy score, isn't done yet.  So if OSMD is using that, this is expected.  I am looking into that now. 

[Gnossienne No. 3.pdf](https://github.com/0xfe/vexflow/files/6795622/Gnossienne.No.3.pdf)

**Comment by rvilarl** [comment]
Can you try the Bach one to see if both staves align the notes correctly?

**Comment by AaronDavidNewman** [comment]
Seems fine.

![image](https://user-images.githubusercontent.com/5438280/125170334-4846fd80-e174-11eb-84c8-5e11b4e0358b.png)

**Comment by rvilarl** [comment]
Thanks. 
@sschmidTU is OSMD using Factory and Easy Score?

**Comment by rvilarl** [comment]
I have updated to the latest OSMD 1.0 and both look fine. 
@sschmidTU there is a bug in OSMD both using 1.2.93 and current, look at the location of the notes in the second voice of the first stave.

**Comment by sschmidTU** [comment]
@rvilarl no, OSMD is not using Factory or Easy Score.
