### ISSUE TITLE
Display issues with triplets

### ISSUE THREAD

**Issue by rgonski** [0xfe/vexflow#107]
While experimenting with triplets in vexflow, I came across two anomalies in the display which I have reproduced in Vextab. They are:

1) Inserting a 16th note(s) after a quarter note triplet - the beaming starts on the second 16th note, leaving the first one an orphan and upsetting the relationship with the (quarter note) beat.

(In our vexflow code, inserting a 16th note after a crotchet triplet causes a runtime error)

This can be reproduced with:

tabstave notation=true tablature=false time=4/4 key=Ab tuning=eb
notes :q 5/5 5/4 5/3 ^3^ :16 5/5 5/5 6/5 7/5 6/5

![example1](https://f.cloud.github.com/assets/4353219/466106/86270c7e-b650-11e2-9b12-3cfbd53b50da.jpg)

2) Creating two 16th note triplets, one after the other, causes the first to have a 3 over it (correct) but the second to be bracketed 3¬ which doesn't look right. 

tabstave notation=true tablature=false time=4/4 key=Ab tuning=eb
notes :16 5/5 5/4 5/3 ^3^  :16 5/5 5/5 6/5 ^3^

![example2](https://f.cloud.github.com/assets/4353219/466108/92bfbc24-b650-11e2-9260-3b268de80a1e.jpg)

One would expect either:
a) both to have a simple 3 above them
b) or better, for the beaming to be in 2 sets of 3 notes, (ie: 2 separate 16th note triplets) with a 3 above each of the triplets. Inserting ^6^ after the second set, is a workaround, but not what one wants always:

tabstave notation=true tablature=false time=4/4 key=Ab tuning=eb
notes :16 5/5 5/4 5/3   :16 5/5 5/5 6/5 ^6^

![example3](https://f.cloud.github.com/assets/4353219/466140/84aa4a4a-b651-11e2-93c0-5ef3e64396f9.jpg)

Apologies if I have missed something here.

Regards,

Richard Gonski

**Comment by Silverwolf90** [comment]
It's entirely possible that these issues may have been resolved, as there have been lots of changes around all involved elements. We'll need to assess if this is still a problem.

**Comment by 0xfe** [comment]
Closing this as obsolete.
