### ISSUE TITLE
Accidentals: hash and sharp right location in Note.

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1075]
Notes can have the accidentals hash and sharp in two different attributes:
- `keys` i.e.: `c#/5`
- `modifiers` (defined in tickable) as instance of `Accidental`

The function `Accidental.applyAccidentals` expects it to be in `keys`.

@0xfe what is the right location?

**Comment by rvilarl** [comment]
@AaronDavidNewman @mscuthbert @sschmidTU how do you use this on your applications? 

A) Do you build StaveNotes using 1) or 2)?
1) `new StaveNote({keys: ['e#/4'],duration: '16'})`
2) `new StaveNote({keys: ['e/4'],duration: '16'}).addAccidental(0, new Accidental('#'))`

B) Do you use `Accidental.applyAccidentals`?

**Comment by rvilarl** [comment]
Ok I would propose the following options:
1) The accidentals should always be placed in the attribute `modifiers`. If an accidental is provided in the constructor with `keys`, it should be translated as a modifier in `modifiers`.
2) The modifiers should have an attribute indicating if it should be rendered or not. `Accidental.applyAccidentals` should act on this attribute.

What do you think?

**Comment by AaronDavidNewman** [comment]
>> A) Do you build StaveNotes using 1) or 2)?

The second one.  I never use applyAccidentals, didn't even know it existed until now.

**Comment by sschmidTU** [comment]
@rvilarl OSMD uses A2 as well, `new StaveNote`, later `.addAccidental`. `applyAccidentals` is never used in OSMD. Also didn't know it.

**Comment by mscuthbert** [comment]
> A) Do you build StaveNotes using 1) or 2)?
> 
> 1. `new StaveNote({keys: ['e#/4'],duration: '16'})`
> 2. `new StaveNote({keys: ['e/4'],duration: '16'}).addAccidental(0, new Accidental('#'))`

I do both 1 and 2 -- I figure that the first one tells us what the note actually is, and the second defines whether an accidental should be displayed or not.    The first is like musicxml "alter" and the second like musicxml "`<accidental>`" tag.

> B) Do you use `Accidental.applyAccidentals`?

Never heard of it.

**Comment by rvilarl** [comment]
> I do both 1 and 2 -- I figure that the first one tells us what the note actually is, and the second defines whether an accidental should be displayed or not. The first is like musicxml "alter" and the second like musicxml "`<accidental>`" tag.

@mscuthbert thanks a lot I have changed #1081 I did not have this difference in mind! I will look into alter and accidental in musicxml and how EasyScore works, because it might be that this is the one that needs to be adapted.

@0xfe is the explanation above also your understanding?

**Comment by mscuthbert** [comment]
Ah, now I see what `applyAccidentals` does -- it's similar to music21's `makeAccidentals` which performs the calculations for which accidentals should be shown or not.  Very cool.  Since I have my own algorithms, I won't be using it, but it's important that VexFlow have it since not everyone wants to use an external library to do these calculations.  It's similar to the applyBeams algorithm in spirit, which was super helpful to me when I was first starting out before I could translate my own makeBeams algorithms into Typescript.

**Comment by rvilarl** [comment]
@mscuthbert Yes. But EasyScore does not work as you described above in regards to 'alter' and 'accidental'

@0xfe I made #1081 because I assumed that EasyScore was working fine. But this might not be the case. If you provide `Ab5/8`, you end up with a note with keys 'A/5' and an accidental type 'b'. According to the description from @mschubert it should produce a keys 'Ab/5' , shouldn't it?

**Comment by rvilarl** [comment]
> A) Do you build StaveNotes using 1) or 2)?
> 
> 1. `new StaveNote({keys: ['e#/4'],duration: '16'})`
> 2. `new StaveNote({keys: ['e/4'],duration: '16'}).addAccidental(0, new Accidental('#'))`

@AaronDavidNewman @sschmidTU do you follow the interpretation from @mscuthbert with A2? Do you do a or b?
a `new StaveNote({keys: ['e#/4'],duration: '16'}).addAccidental(0, new Accidental('#'))`
b `new StaveNote({keys: ['e/4'],duration: '16'}).addAccidental(0, new Accidental('#'))`

@mscuthbert I understan you use a, is that right?

**Comment by mscuthbert** [comment]
yes, I do (a) when I want to show the accidental, and the previous "1" option when it's an E# without accidental.  I never do (b).

**Comment by rvilarl** [comment]
@mscuthbert what about microtones? Do you use them?

**Comment by 0xfe** [comment]
I think we need a consistent story here for 1) EasyScore with key changes, and 2) mid-staff key changes. I think VexFlow doesn't do the right thing by default in either case, and users end up building their own.

I do want the string in `StaveNote.keys` to be semantically correct and include the accidental -- this makes a lot of other things work (like audio players, transposition, etc.) The `addAccidental` is strictly for rendering, and may or may not exist depending on the key, cancellation state, etc.

> @0xfe I made #1081 because I assumed that EasyScore was working fine. But this might not be the case. If you provide Ab5/8, you end up with a note with keys 'A/5' and an accidental type 'b'. According to the description from @mschubert it should produce a keys 'Ab/5' , shouldn't it?

Yes, correct, it should be `Ab/5`.

**Comment by rvilarl** [comment]
@0xfe I agree! Then there is a open question: What do we do with microtones in keys? `Cbbs/4` ?

https://github.com/0xfe/vexflow/blob/7a682f7075017ccdcebd30d06dcc0f9661126dd2/tests/easyscore_tests.ts#L244

**Comment by 0xfe** [comment]
I think the same, no? We should be preserving the semantics.

**Comment by rvilarl** [comment]
I agree, I have been looking into that and it requires to complete `Tables.KeyProperties` I will need help with the `int_val` for the microtones.

**Comment by 0xfe** [comment]
Microtones will not have an `int_val` -- we might have to create a new property to represent a subdivision. Maybe a fraction or a decimal representing a pitch shift.

@mscuthbert any thoughts here? how are microtonal pitches typically represented semantically?

(BTW, Rodrigo, for now we can treat microtonals as out of scope, and just use the closest `int_val`.)

**Comment by AaronDavidNewman** [comment]
>> or now we can treat microtonals as out of scope, and just use the closest int_val

I agree.  fwiw I treat microtones more like ornaments in smoosic, just affecting the immediate note.  Because I don't know how to deal with things like: 'does a `koron` cancel a `sori`?  I doubt "Behind Bars" will be of much help there.  

That said, I think those use cases are really great for Vexflow (and smoosic), since the commercial packages won't focus on them so much.

**Comment by rvilarl** [comment]
> Microtones will not have an `int_val` -- we might have to create a new property to represent a subdivision. Maybe a fraction or a decimal representing a pitch shift.
> 
> @mscuthbert any thoughts here? how are microtonal pitches typically represented semantically?
> 
> (BTW, Rodrigo, for now we can treat microtonals as out of scope, and just use the closest `int_val`.)

`int_val` allow decimal values like alter in musicxml so it should be enough @mscuthbert do you agree?

**Comment by 0xfe** [comment]
I wouldn't put decimals in `int_val` -- there's too many things that might break in weird ways. I'd prefer to use an additional `decimal_val` or (better still) `fractional_val` for microtonals.
