### ISSUE TITLE
Notes with no modifiers need some padding

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1078]
For notes with sharps/flats or really any modifiers, the modifiers leave enough padding between them and the thing behind them.  But a note with no modifier will only have the width of the notehead.

![image](https://user-images.githubusercontent.com/5438280/127232372-dda48673-cfa7-4206-ad51-5973677db125.png)

**Comment by sschmidTU** [comment]
See PR #1080

**Comment by AaronDavidNewman** [comment]
I'm not a Mac person so I can't run the tests (it would be great if we could run them with puppeteer) but from my observation of the formatting tests, It will be different by 2px per notehead in spots, as you'd expect.  

This does not factor into the width calculation, so the overall width of measures shouldn't change.

Without:
![image](https://user-images.githubusercontent.com/5438280/127262989-996ed77f-fad0-4ea6-952b-fda29e41e294.png)

With:
![image](https://user-images.githubusercontent.com/5438280/127263018-ad492bae-8f83-43e9-8459-4317ddce5729.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman I was wondering how the notes without modifiers would look with #1077. I have run the tests and as expected almost everything is slightly modified.
Without:
![Accidental Accidental_Padding Bravura_Reference](https://user-images.githubusercontent.com/22865285/127267194-75193e73-9ad2-4152-b135-8097082b2480.png)
With:
![Accidental Accidental_Padding Bravura_Current](https://user-images.githubusercontent.com/22865285/127267209-dbdfeb09-c039-4927-9615-7b2e0317aeeb.png)
Without:
![Accidental Automatic_Accidentals___C_major_scale_in_Ab Gonville_Reference](https://user-images.githubusercontent.com/22865285/127267335-0364f4c0-552b-4a44-ba3c-2afce036781e.png)
With:
![Accidental Automatic_Accidentals___C_major_scale_in_Ab Gonville_Current](https://user-images.githubusercontent.com/22865285/127267344-8d05b918-e865-4c56-9471-c2438e568b6d.png)
...

**Comment by AaronDavidNewman** [comment]
@rvilarl are you saying with #1077 this fix is not required?  I may have time to try this out later tonight.  Meanwhile I fixed the return type of `minNoteHeadPadding`.

**Comment by rvilarl** [comment]
@AaronDavidNewman no I did not mean at all that this is not required. I find it very good. I am just curious about the wrong calculation on Bounding Box.

**Comment by rvilarl** [comment]
@AaronDavidNewman @0xfe this one can be closed
