### ISSUE TITLE
: [0] should not be used as a type specifier.

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1079]
https://github.com/0xfe/vexflow/blob/2315e7aba40a9bd0328ccb0b6c155eeff4489417/src/factory.ts#L546-L547

@rvilarl what does the [0] mean?

Is it equivalent to number[]?

I'm migrating bach_tests and fixing some minor bugs (e.g., these two params will be changed to optional).

Can I change it to number[]? Does the [0] have a special meaning in TS?

**Comment by sschmidTU** [comment]
`[0]` is just an array with the number 0 in it.
So, the first_indices is a list which contains the number 0.

**Comment by ronyeh** [comment]
I think it was a slight bug during the TS migration. In my branch I have verified that it should be number[] instead.

**Comment by rvilarl** [comment]
This is just the default value, an array with one element which is 0. The indices are required for chords to indicate which notes are tied. In the example below [0,1] would be reuired.
![image](https://user-images.githubusercontent.com/22865285/127263724-e2f8e388-e028-4058-b24e-0d9d65562e81.png)

In notes not belonging to chords the indices defaults to [0]. However it might be that the code support `undefined`, I do not know. If this is the case `xxx_indices?: Number[]` might be  another option.

**Comment by ronyeh** [comment]
Does TS support default values in this manner? It looks like a type specifier the way it appears right after the colon. 

Default value would look like:

```
first_indices: number[] = [0]; 
```

**Comment by sschmidTU** [comment]
> This is just the default value, an array with one element which is 0.

That's what i thought at first too, but this is in a type declaration section, there shouldn't be concrete values here. Look at the code around it.

**Comment by rvilarl** [comment]
> Does TS support default values in this manner? It looks like a type specifier the way it appears right after the colon.
> 
> Default value would look like:
> 
> ```
> first_indices: number[] = [0]; 
> ```

I believe that this only works with simple parameters, not wit attributes from objects used as parameters.

**Comment by rvilarl** [comment]
> > This is just the default value, an array with one element which is 0.
> 
> That's what i thought at first too, but this is in a type declaration section, there shouldn't be concrete values here. Look at the code around it.

I thought that this was possible with parameter initialisation where the type is intrinsic determined, but I am not 100% sure.

**Comment by rvilarl** [comment]
I suggest the following that I believe will produce no doubts:
```js
  StaveTie(params: {
    from: Note;
    to: Note;
    first_indices?: number[];
    last_indices?: number[];
    text?: string;
    options?: { direction?: number };
  }): StaveTie {
    const tie = new StaveTie(
      {
        first_note: params.from,
        last_note: params.to,
        first_indices: params.first_indices ?? [0],
        last_indices: params.last_indices ?? [0],
      },
      params.text
    );
```

**Comment by rvilarl** [comment]
@ronyeh @sschmidTU do you like the proposed change?

**Comment by ronyeh** [comment]
Yes I like how explicit this change is.

However, in `StaveTie` `setNotes()` it already provides the default of `[0]` if first_indices / last_indices are not provided. So technically the ?? [0] is not needed.

https://github.com/0xfe/vexflow/blob/2315e7aba40a9bd0328ccb0b6c155eeff4489417/src/stavetie.ts#L80-L81

**Comment by rvilarl** [comment]
Then it might be easier, go for it!
