### ISSUE TITLE
Add accessors for protected variables? Or make the variables public?

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1082]
https://github.com/0xfe/vexflow/blob/2315e7aba40a9bd0328ccb0b6c155eeff4489417/tests/dot_tests.js#L96

In migrating all the tests, I have discovered some small issues with how we have set instance variables to **protected**.

Are the tests considered "the official API"? If so, then the above example means that .width should be publicly accessible.

However, TypeScript says:

```
Property 'width' is protected and only accessible within class 'Modifier' and its subclasses.ts(2445)
(property) Modifier.width: number
```

So what should the ideal solution be? Just remove the 'protected' keyword from the width property? Or should we have a readonly getter, and change the tests to reflect this?

**Comment by rvilarl** [comment]
I would vote to use `getWidth()` which already defined. This what we did in the code migration.
@0xfe what do you think?

**Comment by ronyeh** [comment]
I'm okay with using these getters, but thus far I have treated the tests as the de facto public API.

For example, if a test omits a parameter that we have not marked as optional while migrating, I'll verify that it's okay to do so, and then go ahead and add the ? to the method signature. Most times, the method actually assumes it is optional, because it'll check if it's undefined and then set a default value.

So the bigger question is, should we in general treat the tests as the public API that we should try to not break?

**Comment by 0xfe** [comment]
It's a good question. The tests currently use implementation details, and are not representative of the public API. I agree that we should use `getWidth()` in the tests instead.

This was never enforceable in JS, but we did specify in the docs never to reach into the internals -- use the provided accessors.

All this said, sometimes we do need to reach inside for the tests to verify state, and I don't know what the TS recommended approach is. (In C++ there's the notion of _Friend Classes_ where specific members can be made available to tests.)

**Comment by ronyeh** [comment]
OK if there is an existing accessor, I agree the test should favor the accessor (and I can make the change when it's obvious).

If the test is exercising part of the private API, then we can simply drop some `// eslint-disable-next-line` or simply eslint disable an entire block or the entire tests file. Luckily it then just falls back to standard JS where everything is accessible :-).

**Comment by ronyeh** [comment]
Closing this issue for now.

Decision: modify tests to use accessors where appropriate. If no accessor, either implement the accessor, or directly access the private/protected variable but note that we are only exercising the internals of the VexFlow library. Hide warnings with eslint-disable comments.

**Comment by mscuthbert** [comment]
@ronyeh and @0xfe : The other way in TS to access something private or protected is to cast `as any` before violating the API:

```
class X {
    private _x: int = 4;
    setX(new_x) { this._x = new_x}
    getX() { return this._x + 1}
}

// debug script trying to figure out why x is always too big.
class Test {
    testX(assert) {
           const x = new X();
           x.setX(10)
           // assert.equal(x.getX(), 10);  // failed, so we try to debug with...
           // assert.equal(x._x, 10);  // but now TypeScript complains about private access!
           assert.equal((x as any)._x, 10);  // TypeScript's happy to let us do this.
     }
}
```

This won't work with true pure-JS ES2020 `#private` variables, but I highly suggest not using them anywhere in the code even when we can trust that browsers support them.

**Comment by 0xfe** [comment]
Maybe we can wrap that into a method: `unsafe(v: T) : any` so we have an indirection that we can grep/log/mass edit.
