### ISSUE TITLE
What happened to VF.Music.noteValues?

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1084]
It seems some of the theory routines that used to be in vex are gone, or maybe just changed and I don't understand their new form.  I used to use to get Object.keys(VF.Music.noteValues) to cycle through enharmonics, for instance.  I can create a new class that contains what it used to contain, but I'm wondering, is it there and I'm just not seeing it?

**Comment by rvilarl** [comment]
`VF.music.noteValues` overlapped with `Tables.KeyProperties`, I suggested to use only one and we went for the one in Tables. 

If you are using the array directly I would suggest to put it back.
@0xfe do you agree?

**Comment by rvilarl** [comment]
@AaronDavidNewman is there anything else that you miss in Music. I will make a PR to get the missed elements back.

**Comment by AaronDavidNewman** [comment]
That's all that I've noticed so far.  I couldn't figure out a way to iterate through KeyProperties to get the enharmonics so I moved the legacy table into smoosic.   If no one else has a use for it I will just close this.

**Comment by rvilarl** [comment]
@0xfe it was unintended to chnage the interface to users and I have made a PR to restore it.
