### ISSUE TITLE
vexflow-core-min.js has an unnecessary banner

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1086]
@rvilarl can you help investigate why vexflow-core-min.js has an extra 14-line microsoft comment header? None of the other minified JS output files has this header.

**Comment by rvilarl** [comment]
Seems to be connected to in tsconfig.dynamic.json:

"importHelpers": true,
    
See 

https://stackoverflow.com/questions/52849894/how-to-handle-copyright-notice-in-javascript-bundle

**Comment by rvilarl** [comment]
yes importHelpers requires tslib which includes the copyright

**Comment by rvilarl** [comment]
importHelpers are not necessary, fixed.
