### ISSUE TITLE
Error when adding custom music fonts

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1089]
I have been using Leland in the Smoosic vex branch.  It was working before, but there is some webpack magic that I am missing.  Here is what I have done:
I already had leland_glyphs and leland_metrics
Added `leland.ts` following the pattern in the other fonts
Added `loadLeland` method in `loadStatic` and `loadDynamic` that reference that
Added `@leland` packages in `tsconfig.dynamic.json` and `tsconfig.json`.
Added loading functions to `font.ts` that follows the pattern in the other fonts.

What am I missing?  Or can I save myself having to change the vex code and add it dynamically somehow from Smoosic?  

Here is the error:

```
ERROR in C:\Users\Daddy\Documents\GitHub\vex_smoosic\vexflow_smoosic\src\fonts\leland.ts
./src/fonts/leland.ts 9:15-21
[tsl] ERROR in C:\Users\Daddy\Documents\GitHub\vex_smoosic\vexflow_smoosic\src\fonts\leland.ts(9,16)
      TS2304: Cannot find name 'Leland'.
```

**Comment by rvilarl** [comment]
@AaronDavidNewman I created #1092 so that you can check what is missing.

I had to increase the memory to get it compiled:

`export NODE_OPTIONS=--max_old_space_size=4096`

**Comment by 0xfe** [comment]
@rvilarl would you mind updating https://github.com/0xfe/vexflow/wiki/VexFlow-Font-Rendering with the additional instructions for adding fonts please?

**Comment by rvilarl** [comment]
I will please leave this open.

**Comment by AaronDavidNewman** [comment]
The thing is, I'm pretty sure I've done all this stuff and it still isn't working for me.
How are you guys generating: `vexflow-font-gonville-min.js`, etc.  I think the webpack complains about '@leland not found', it means that.  Maybe that is the missing element.

**Comment by AaronDavidNewman** [comment]
It is appearing now.  I am  sure why it is working now and it wasn't before.  I am going to try a test with a blank environment and see if it still give me issues.

**Comment by rvilarl** [comment]
@AaronDavidNewman if you commit your code in a branch of vexflow_smoosic I could review it for you. Simply:
git checkout -b font/leland
git add .
git commit -m "WIP"

**Comment by rvilarl** [comment]
> @rvilarl would you mind updating https://github.com/0xfe/vexflow/wiki/VexFlow-Font-Rendering with the additional instructions for adding fonts please?

@0xfe done, please review
@AaronDavidNewman I think this can be close now.
