### ISSUE TITLE
TabNoteStruct's str & fret should probably be numbers instead of strings.

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1093]
https://github.com/0xfe/vexflow/blob/7a682f7075017ccdcebd30d06dcc0f9661126dd2/src/tabnote.ts#L21-L23

In tabslide_tests.ts, str and fret are consistently provided as numbers (which makes sense to me).

I did a quick search in the tests for "new TabNote(" and it looks like other tests also assume `str` and `fret` are numbers.

**Comment by ronyeh** [comment]
https://github.com/0xfe/vexflow/blob/7a682f7075017ccdcebd30d06dcc0f9661126dd2/tests/tabslide_tests.ts#L90-L101

https://github.com/0xfe/vexflow/blob/7a682f7075017ccdcebd30d06dcc0f9661126dd2/tests/vibrato_tests.ts#L70-L89

**Comment by 0xfe** [comment]
Actually, `fret` takes `X` too (muted notes), which is rendered into a glyph via `Flow.tabToGlyph` (which prob should be moved to `tabnote.ts`.)

**Comment by ronyeh** [comment]
I changed `str` to `number`.
I changed `fret` to `number | string`.

...I don't believe this changes any of the public APIs (at least the tests aren't affected). These type labels were introduced during the TS migration.
