### ISSUE TITLE
Voice contains Tickables or Notes?

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1097]
https://github.com/0xfe/vexflow/blob/37e70ad84f26ebce2546c52ac0c9c3e7c4a127c9/src/voice.ts#L40

I've made some more progress cleaning up the tests, and ran into this question. In the tests, we create a `MockTickable` object that gets added to a `Voice` or a `TickContext`.

`Voice` and `TickContext` both assume that tickables are all `Note` objects. **Is this always true**?

If so, that's fine and I was just confused on terminology. I can put an eslint-disable in `MockTickable` to hide the errors.

But if there is any other type of Tickable, then we will need to change references to `Note` to `Tickable` instead, and then add instanceof type checks into `Voice` where necessary.

**Comment by rvilarl** [comment]
I believe that `Note` is the right answer. `Tickable` does not have `setStave` and `Note` does. `MockTickable` implements `setStave`.

**Comment by rvilarl** [comment]
`Voice` contains Notes I believe. It does not contain TickContexts which is the only other class taht extends `Tickable`

**Comment by ronyeh** [comment]
That's fine if Note[] is the intended type. I was just confused by naming. Since it's called tickables, setTickables, etc.... I assumed the original intention was to use the more generic Tickable class.

**Comment by rvilarl** [comment]
I assume the same.

**Comment by 0xfe** [comment]
It was supposed to be a derivative of `Tickable`.

`Tickable` is supposed to be an abstract class (hence `MockTickable`), but the lack of type enforcement caused some drift over time.

With Typescript now, I think we should specify `abstract class Tickable` and add `abstract` methods `setStave`, `getStave`, etc. Can we try that?

**Comment by rvilarl** [comment]
@ronyeh This will also work but then we should remove them from `Note`.

**Comment by ronyeh** [comment]
OK I will explore making Tickable abstract and add appropriate abstract methods. 

I can do this with my continued cleanup of the tests.

The reason I got stuck here was because TS was complaining about MockTickable not being compatible with methods that expect a Note or a Tickable.

**Comment by ronyeh** [comment]
I had to add some abstract methods to Tickable, to avoid adding too many type guards.

Additionally, there was a method signature incompatibility which requires us to break the existing API (which might be OK if we log it under **Breaking Changes** in a CHANGELOG.md).

Tickable had:
`addModifier(mod: Modifier): this {`

StaveNote (which extends StemmableNote ❮ Note ❮ Tickable) had:
`addModifier(a: number | Modifier, b: number | Modifier): this {`

That method's internals said that addModifier(index, modifier) is deprecated, and to use addModifier(modifier, index) instead.

I ended up making the method signatures compatible, and turned the deprecation notice into a RuntimeError. We will have to log this breaking change as well (a CHANGELOG.md is included in my PR).

**Comment by 0xfe** [comment]
That sounds good @ronyeh

**Comment by ronyeh** [comment]
My opinion is biased, since I already put in substantial work into this PR. 🤪

Let me try my best to analyze it objectively, but I am not familiar with the original intent of `Tickable` and `TickContext`.

---

### There are only two classes that `extends Tickable` (i.e., Note and TickContext). 
If we could make `TickContext` an independent type, then `Tickable` and `Note` could be merged.

So I investigated whether we can make `TickContext` not extend Tickable, by commenting it out `/*extends Tickable*/`.

This produces errors with these missing methods and properties:
```
this.setAttribute('type', 'TickContext'); 
this.width 
this.ignore_ticks = false;
this.setPreFormatted(false);
this.preFormatted
this.postFormatted
```

TickContext has similarities to ModifierContext. In `Formatter`, they are used in preFormat() and postFormat() to lay out tickables on a score. The ModifierContext is actually used inside Note's getMetrics(), which Formatter relies on.

**ModifierContext does NOT extend Modifier.** So if the classes are truly mirrors of each other, maybe TickContext should also not extend Tickable.

It's worth noting that ModifierContext implements its own fields for things like:
```
protected preFormatted: boolean = false;
protected postFormatted: boolean = false;
protected width: number;
```

So maybe TickContext can just implement the fields it needs, without extending Tickable. It does seem weird that a TickContext is a Tickable..... isn't it just a helper class for the Formatter to use?

Looking at the class comment for `Tickable`, we see "Tickable represents a element that sit on a score and has a duration, i.e., Tickables occupy space in the musical rendering dimension."

This suggests that indeed TickContext shouldn't really be a Tickable, since I don't think the TickContext sits on the score.

However, we could argue that other things that extend Note should actually be extending Tickable instead. For example, is a Crescendo a Note? **Shouldn't Crescendo extend Tickable?** The class comment for Note includes "Notes have some common properties: All of them have a value (e.g., pitch, fret, etc.)" So while a crescendo has a duration like Notes and Tickables, it doesn't really have a pitch.


--- 

So in my professional, extremely biased opinion, I think we can merge the current Tickables PR, and then continue to think about what things should `extends Tickable` vs `extends Note`.

My hunch is that Tickable and Note should still be separate entities, but that TickContext should not extend Tickable, and implement the fields it needs to help the Formatter do its magic.
