### ISSUE TITLE
More display issues - semiquaver beaming and grouping and beaming in 6/8 time

### ISSUE THREAD

**Issue by rgonski** [0xfe/vexflow#110]
In a time signature where the beats are quarter notes, (eg: 4/4, 3/4 etc.) 16th notes are beamed in 4's. This works fine until you put a rest instead of a note either in the 4th semiquaver position, or the 1st semiquaver position. ie:

tabstave notation=true tablature=false
notes :16 Cn-D-E/4 ## ##-D-E/4 F#/5

![example3](https://f.cloud.github.com/assets/4353219/491958/ff4753f8-ba6e-11e2-88a2-d77dc9ae5a47.jpg)

You would expect either the groups of 3 16th notes to be beamed, or even better to retain the beaming over groups of 4, with the beam 'hanging over' the rest. 

Also in 6/8 time, the 8th notes are grouped (beamed) in 3 groups of 2, rather than in 2 groups of 3. ie:

tabstave notation=true tablature=false time=6/8 
notes :8 5/4 7/4 8/5 :8 6/3 5/4 5/5

![example4](https://f.cloud.github.com/assets/4353219/491955/ae406b2a-ba6e-11e2-8a78-7368f2ba534e.jpg)

Regards,

Richard Gonski

**Comment by Silverwolf90** [comment]
This issue is quite old, and [I believe that beaming is full-featured enough now to properly handle these cases.](https://github.com/0xfe/vexflow/wiki/Automatic-Beaming)

If the current functionality is not sufficient please open a new issue.
