### ISSUE TITLE
Rests in Tabstaves

### ISSUE THREAD

**Issue by Tails** [0xfe/vexflow#1101]
I recall VexFlow having support for rests in Tabstaves a few years back. Has that been removed?

**Comment by sschmidTU** [comment]
It hasn't been removed. You can still display tabs.
https://github.com/0xfe/vexflow/wiki/The-VexFlow-Tutorial#step-6-guitar-tablature

**Comment by Tails** [comment]
Thanks for your response. I know tabs can still be displayed as described in the wiki and in the tests (went through them to verify before asking this question). 

I'm specifically asking about _rests_ in tabs. I did not find a test (anymore) displaying the possibility, nor do I see rendering support for it in tabnote.js, nor is a rest rendered (unless an empty space is intended to be a rest) when I create a TabNote with a rest position:

```javascript
            new VF.TabNote({
                clef: "treble",
                positions: [{fret: 0}],
                duration: "wr"
            })
```

**Comment by sschmidTU** [comment]
Oh, i overlooked the "rests" part, sorry. Yeah, i've never seen rests in tabs, they seem to be a recent addition.
This article goes into it a little bit (and shows how "Twinkle Twinkle Little Star" used to be notated without explicit rests):
https://www.guitarforbeginners.com/tab.html

**Comment by sschmidTU** [comment]
@Tails by the way, "wr" would be a whole rest, have you tried `duration: 16r`?
Also, have you tried `new VF.TabNote(...., true)`, where `true` means `draw_stem`?

**Comment by sschmidTU** [comment]
Inserting StaveNote rests instead of TabNotes seems to work.
![image](https://user-images.githubusercontent.com/33069673/129031783-7db7ab6e-3d3e-48d0-9cc9-9ab971ce025a.png)

**Comment by Tails** [comment]
Super! I was still messing around with the first suggestion and I had expected TabStave to reject NoteStaveNotes. Thanks!
