### ISSUE TITLE
Music notation with guitar tab accompaniment.

### ISSUE THREAD

**Issue by abalter** [0xfe/vexflow#1102]
With vexflow or easyscore is it possible to have a melody in staff notation with guitar tab for the accompaniment?

I was not able to find any examples of this.

**Comment by 0xfe** [comment]
You can do that -- however it's probably better to use VexTab, since it takes care of a lot of the complexity.

**Comment by abalter** [comment]
Using VexTab, how would I place a notation score above the tab? Not the notes that are in the tab. Say a tune in the notation and the guitar accompaniment in the tab.
