### ISSUE TITLE
getCategory() and this.setAttribute('type', ...) should use the same strings

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1107]
This is a proposal for a PR to standardize `CATEGORY` and `getCategory()` and `this.setAttribute('type', elementType)` 

### PROPOSAL
- Standardize the static CATEGORY property to always be lowercase and singular. (If you prefer UpperCamelCase, that's fine too. As long as we are consistent!)
- Make sure every class that has a CATEGORY property also has a getCategory() method (and vice versa).
- this.setAttribute('type', ...) should use the CATEGORY property, instead of using a separate hard-coded string.

### BACKGROUND INFO

I discovered this issue while working on https://github.com/0xfe/vexflow/pull/1098

There are 33 classes that implement the static `CATEGORY` property:

https://github.com/0xfe/vexflow/search?q=%22static+get+CATEGORY%28%29%22

There are 33 **slightly different** classes that implement the `getCategory()` method:

https://github.com/0xfe/vexflow/search?q=%22getCategory%28%29%22

For example: 
- stavemodifier.ts has a getCategory() (which returns an empty string) but it does NOT have the static CATEGORY property. 
- textfont.ts has the static CATEGORY property, but it does not implement getCategory(). TextFont.CATEGORY is currently unused.

Additionally, the capitalization & number (singular/plural) of the category string is not consistent.

For example: 
- Bend.CATEGORY === 'bends'
- Stem.CATEGORY === 'stem'
- ChordSymbol.CATEGORY === 'chordSymbol'
- TimeSignature.CATEGORY === 'timesignatures'

I also noticed that 63 subclasses of `Element` call `this.setAttribute('type', elementTypeString)` in the constructor. The string here is always UpperCamelCase, and always singular. 

### RISKS
If there are projects out there that rely on the CATEGORY and 'type' attribute being a certain way, this PR could break those projects. 

`.getAttribute('type')` is used only once in the core library, and once in the tests (accidental_tests.ts). That test case can be updated to use isCategory() instead. 

`.getCategory()` is used more often (13 core library files and 2 test files). Those can be updated to use `isCategory()`.

**Comment by mscuthbert** [comment]
My thought is:

1.  Standardize the case to be the same as the class name -- thus UpperCamelCase -- risk the compatibility failure
2. Make a static property CATEGORY that appears in every class that `.getCategory()` was in
3. Mark getCategory() as deprecated but for now just return `.CATEGORY`.

**Comment by ronyeh** [comment]
I like standardizing to the ClassName. Makes much sense and the
this.setAttribute already mostly looks like that.

Do we need to deprecate getCategory? It might be a useful way for a
developer to get a string representation of an instance of an unknown
object. Or should we make developers use obj.constructor.name?

**Comment by ronyeh** [comment]
@mscuthbert if we end up deciding that CATEGORY is the same as the ClassName, can we just do something like this?

```
class MyClass {
  
  static get CATEGORY() {
    return this.name;
  }

  
  getCategory() {
    return MyClass.CATEGORY;
  }

}

console.log(MyClass.CATEGORY);      // => 'MyClass'

const obj = new MyClass();
console.log(obj.getCategory());     // => 'MyClass'
console.log(obj.constructor.name);  // => 'MyClass'
console.log(obj.constructor === MyClass);  // => true
```

Would this break your use case where there might be two copies of VexFlow on the same page? I don't know if the WebKit bundling process somehow messes up the obj.constructor.name, or if it's possible to have two copies of a class on the same page with the same exact name....

**Comment by 0xfe** [comment]
The category is not meant to be the class name. It's really a signal (e.g., to formatters) for how to treat elements  -- it's used in different ways by different projects (including inside Vexflow), but it lets you quickly derive (or create) custom elements, and have the formatters still recognize them and do the right thing with them.

E.g., you might derive a `CustomAccidental` from `Accidental`, and Vexflow's standard formatting still works. Or you may create a new `CustomAccidental` not derived for `Accidental`, but categorize it as an `accidental`, which signals to VexFlow how to treat it.

With Typescript, we could use interfaces give us some compile time support for this, but I think it would make the code more messy. (It also wouldn't address some other common use cases, where a robust string representation is required.)

I'm +1 for rationalizing the naming convention, and the conflict with `setAttribute`, so this is a good discussion, but just want to be clear that category and class name are not the same.

**Comment by ronyeh** [comment]
Got it.

Let me know if the below works for everyone, and I can put together a PR:


I will make sure all `.CATEGORY` properties are standardized to UpperCamelCaseSingular. For example:
```
static get CATEGORY(): string {
  return 'StaveNote';
}
```

this.setAttribute will always use this.getCategory() for consistency. For example:
```
constructor(...) { 
  ...
  this.setAttribute('type', this.getCategory()); 
  ...
}
```

getCategory() will always return the static `.CATEGORY` property. For example:
```
getCategory(): string {
  return StaveNote.CATEGORY; 
}
```

It will be a coincidence that the `.CATEGORY` properties look like the ClassName, but we will not explicitly tie them to the ClassName, to allow for future flexibility.

I will also note this in the CHANGELOG.md as a breaking change (in case any projects were checking against specific category strings).

**Comment by ronyeh** [comment]
@0xfe @rvilarl FYI my next PR will be standardizing the Category and setAttribute 'type' string in accordance with the above comment: https://github.com/0xfe/vexflow/issues/1107#issuecomment-902970168
