### ISSUE TITLE
Change: check<Stave>(this.stave) => defined(this.stave)

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1115]
I just recently learned that the TypeScript compiler does "type argument inference" on generics, so that you don't have to explicitly pass in the `<T>` in functions like `check<T>(obj)` and `isCategory<T>(obj, ...)`

Search for "type argument inference" here:
https://www.typescriptlang.org/docs/handbook/2/generics.html#:~:text=type%20argument%20inference

For example:
`const stave = check<Stave>(this.stave);`

Can be written as:
`const stave = check(this.stave);`

The compiler knows that the first argument is `Stave | undefined`, so the return type will be `Stave`.

Going forward, should we slowly remove the `<T>` from functions like `check<T>(obj)` when possible? Or should we keep the `<T>` so that it is more explicit?

**Comment by ronyeh** [comment]
@rvilarl would love to hear your opinion on this, since you implemented the check() function.

**Comment by ronyeh** [comment]
Advantages of each approach:

`const stave = check<Stave>(this.stave);`
* explicitly states the expected type
* TS compiler will show an error if `this.stave` does not match the type `<T>`

`const stave = check(this.stave);`
* shorter and possibly easier to read, because it makes use of TS type inference.

**Comment by 0xfe** [comment]
What happens if the variable has a union type? (e.g., `number | string | undefined`)?

**Comment by 0xfe** [comment]
Thinking about this more, the goal of those check statements is to assert that they have values set. The type system does the rest. So, yeah `check(this.stave)` should be sufficient I think.

**Comment by ronyeh** [comment]
The implementation of check() verifies that it is NOT undefined. So the compiler is actually pretty smart about this.

```
      const x: number | string | undefined = Math.random() < 0.33 ? 1 : Math.random() < 0.5 ? 'hello' : undefined;
      const y = check(x);
```

If you hover the mouse pointer over the const y, the VS code tooltip says "const y: string | number". So the compiler decided that it can no longer be undefined, but it can still be either of the other two types.

**Comment by 0xfe** [comment]
That's great, this is way better. While we're at it should we rename it to something clearer, like `defined(x)` or `assertDefined(x)`? The latter sounds more like an assertion, but assertions don't typically return values, so I like the former.

**Comment by ronyeh** [comment]
`const stave = defined(this.stave)` looks fine to me (or `checkDefined(this.stave)` if we want to be more verbose, haha).

`isDefined()` would imply returning a boolean.
`assertDefined()` implies returning void, and a possible exception being thrown.

**Comment by 0xfe** [comment]
Let's go with `defined` :-)

(I thought it did throw an exception on failure -- is that not the case?)

**Comment by ronyeh** [comment]
Yes it does throw an exception. I was just commenting that assertDefined()
is the clearest re: exception throwing, but asserts usually return void.

**Comment by rvilarl** [comment]
> @rvilarl would love to hear your opinion on this, since you implemented the check() function.

The original idea was to avoid doing more functions like checkContext, which only checks against `undefined`. I find it a good idea to use "type argument inference".

**Comment by rvilarl** [comment]
I would also replace the `checkContext` by this new `defined`.

**Comment by ronyeh** [comment]
There's also a `Note.checkStave()`. :-)

Seems like we can look for all our checkXXX() methods and then replace them with defined(obj) and take advantage of type inference where possible.

I can work on this PR after the pending ones are reviewed & merged. Since there are too many in the pipeline already, there's a risk for extra conflicts that I'll have to resolve, haha.

**Comment by ronyeh** [comment]
On second thought.... checkStave() might not be one that we can replace easily. Other classes depend on Note.checkStave() to get a valid stave. Anyways, we can tackle this in multiple PRs (for easier code review).  The first step would be to simply replace uses of check<T>(obj) to defined(obj). Then a separate PR can be for removing unnecessary checkXXX() methods.
