### ISSUE TITLE
TextNote Superscript and Subscript are shifted to the right

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1118]
* Superscripts (e.g., +5) are offset toward the right in master (as of 2021-08-27) and version 3.0.9.
* The bug is not present in version 1.2.93
* This is possibly due to issues with measuring text width.

To repro, run grunt on your local copy of VexFlow, and then open `flow.html`. Then change the query params to load different versions of VexFlow:

Click the images below to open in a new tab:
* ❌ 3.0.9: `flow.html?filter=superscript&module=TextNote&ver=unpkg@3.0.9`
* ❌ Master: `flow.html?filter=superscript&module=TextNote`
<img width="200" src="https://user-images.githubusercontent.com/239113/121610666-630a4300-ca0b-11eb-9f0c-c95f62f8171b.png" style="border: 12px solid red;">

* ✅ 1.2.93: `flow.html?filter=superscript&module=TextNote&ver=unpkg@1.2.93`
<img width="200" src="https://user-images.githubusercontent.com/239113/121610414-d2336780-ca0a-11eb-824f-74312e2dd41a.png">

**Comment by AaronDavidNewman** [comment]
I wonder if we need super/subscript with text note, since we can do the same thing with ChordSymbol?

**Comment by ronyeh** [comment]
Fixed by https://github.com/0xfe/vexflow/pull/1137
