### ISSUE TITLE
Missing Ledger Line

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1119]
Middle C note under the stave is missing a ledger line.

This bug has existed since version 1.2.93:
See: `flow.html?module=NoteHead&ver=unpkg@1.2.93`

However, the test case seems to be OK in an older version, circa August 2016:
✅ https://vexflow-demo.vercel.app/tests/flow-1.2.77X.html?module=NoteHead
❌ https://vexflow-demo.vercel.app/tests/flow-3.0.9.html?module=NoteHead
❌ https://vexflow-demo.vercel.app/tests/flow-master.html?module=NoteHead

**Comment by ronyeh** [comment]
Additionally, in the SVG test cases, the middle C note is not visible because it has been pushed off the right edge of the stave. The formatting seems to be inconsistent between the Canvas and SVG renderers for the same test case (NoteHeadTests.basic).

**Comment by 0xfe** [comment]
Yikes, the inconsistent formatting is worrying.

**Comment by rvilarl** [comment]
I believe that this is not an error. Ledger lines are drawn for Stave Notes and `NoteHead` derives from `Note`, not `StaveNote`.

**Comment by sschmidTU** [comment]
Yeah, this doesn't happen for StaveNotes with Vexflow 1.2.93 (OSMD), I think.
![image](https://user-images.githubusercontent.com/33069673/132347867-08d71312-93cf-4411-aff9-0494c58c3021.png)

**Comment by ronyeh** [comment]
OK, makes sense. StaveNote can use multiple NoteHead objects, so it should not be NoteHead's responsibility to draw the ledger.

So maybe 1.2.77 was "buggy" (because a lone NoteHead drew a ledger), and now 3.0.9 is not.

However, maybe `StaveNote` should not be drawing the ledger lines either?? Should it be the responsibility of the Stave to render ledger lines where appropriate?

There are some multi-voice test cases where if you draw the voices out of order, multiple ledger lines will be drawn in the same place, and the ledger line in the later voice will be draw on top of the notehead in the earlier voice.

See: rests_tests.ts
https://github.com/0xfe/vexflow/blob/490970b96aace865669d5d2d44acfeb349bc112f/tests/rests_tests.ts#L369-L372

**Comment by ronyeh** [comment]
> Yikes, the inconsistent formatting is worrying.

The inconsistent formatting is this bug: https://github.com/0xfe/vexflow/issues/1126

**Comment by ronyeh** [comment]
We can revisit ledger line drawing in a future release. At the moment, multiple ledger lines can be drawn in the same place when there are multiple voices.
