### ISSUE TITLE
Petaluma Font: Notes extend past the end of the measure.

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1120]
Test Case: **Articulation - Accent/Tenuto › SVG + Petaluma**

When using the **Petaluma** font, the layout of quarter notes is incorrect, as it extends past the end of each measure.

Notes
* 1.2.93 does not support Petaluma.
* Broken in 3.0.9: `flow.html?ver=unpkg@3.0.9&module=Articulation&filter=accent`
* Broken in Master (2021-08-27): `flow.html?module=Articulation&filter=accent`

<img width="596" alt="AccentTenuto" src="https://user-images.githubusercontent.com/239113/121665855-81009380-ca5d-11eb-90cd-3d11f68a6cd5.png">

It is possible that the Petaluma glyphs take up too much horizontal space, and that we simply need to make the stave wider.
Or maybe we need to make the accent symbols take less horizontal space?

**Comment by 0xfe** [comment]
I think you're right that Petaluma might just be too wide a font for the stave width. @AaronDavidNewman for thoughts.
