### ISSUE TITLE
Question about EasyScore / Accidentals from recent PR.

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1121]
https://github.com/0xfe/vexflow/blob/e7f0426a662cc9fb28760b3c547cd3a2b357e0da/src/easyscore.ts#L356-L363

Hi Rodrigo,

Just a question, I'm trying to resolve a conflict in my PR and I ran across this new line from your recent PR.

I confess I don't completely understand it since the line of code is a bit long:

```
// BEFORE
const keys = chord.map((notePiece) => notePiece.key + '/' + notePiece.octave);

// AFTER
const keys = chord.map((notePiece) => notePiece.key + (['bb', 'b', '##', '#', 'n'].includes(notePiece.accid ?? '') ? notePiece.accid : '') + '/' + notePiece.octave);
    
// THE DIFF
(['bb', 'b', '##', '#', 'n'].includes(notePiece.accid ?? '') ? notePiece.accid : '')

```

From skimming your PR, it looks like we are now handling regular accidentals separately from the microtonal accidentals now?

So if the current notePiece's .accid is one of the regular accidentals, then we will keep it. Otherwise, we squash it (turn it into the empty string)?

Thanks!

**Comment by ronyeh** [comment]
@rvilarl Looking at the EasyScore tests, it looks like we are now also including the accidental information into the `.keys` field of the StaveNote. Was this a bug fix?

**Comment by ronyeh** [comment]
Is it okay if I rewrite the line as follows?

```
    const notePieceAccidental = ['bb', 'b', '##', '#', 'n'].includes(notePiece.accid) ? notePiece.accid : '';
    const keys = chord.map((notePiece) => notePiece.key + notePieceAccidental + '/' + notePiece.octave);
```

I simplified `notePiece.accid ?? ''` to `notePiece.accid` because .includes() returns the same result even if `.accid` is undefined or null.

**Comment by ronyeh** [comment]
OK, I couldn't think of any cleaner way to write that line of code. I guess I'll add a comment as follows:

```
    // Create a string[] that will be assigned to the .keys property of the StaveNote.
    // Each string in the array represents a note pitch and is of the form: {NoteName}{Accidental}/{Octave}
    const keys = chord.map(
      (notePiece) =>
        notePiece.key +
        (['bb', 'b', '##', '#', 'n'].includes(notePiece.accid ?? '') ? notePiece.accid : '') +
        '/' +
        notePiece.octave
    );
```

Let me know if the comment is OK.

**Comment by rvilarl** [comment]
HI @ronyeh the dis cussion is in #1091 there the difference between `ACCIDEBTALS` and `MICROTONES` was made. Youur comment is fine. It is only missing the fact that microtones accidentals are not icluded in the keys.
Could you also look into my last comment in #1097?

**Comment by ronyeh** [comment]
Thanks. I updated it as follows. It seems like we already have an array of accidental strings, so I used that constant instead.

```
   // Create a string[] that will be assigned to the .keys property of the StaveNote.
    // Each string in the array represents a note pitch and is of the form: {NoteName}{Accidental}/{Octave}
    // Only standard accidentals are included in the .keys property. Microtonal accidentals are not included.
    const standardAccidentals = Music.accidentals;
    const keys = chord.map(
      (notePiece) =>
        notePiece.key +
        (standardAccidentals.includes(notePiece.accid ?? '') ? notePiece.accid : '') +
        '/' +
        notePiece.octave
    );
```

**Comment by rvilarl** [comment]
@ronyeh this one can be closed, change is alerady in master
