### ISSUE TITLE
TextDynamics breaks if preFormat is called twice.

### ISSUE THREAD

**Issue by Xonok** [0xfe/vexflow#1122]
I have a workflow whereby stave sizes are based on preCalculateMinTotalWidth.
Later I draw the staves with formatToStave.
The issue is that doing so will call preFormat on TextDynamics twice. Unlike StaveNotes, TextDynamics break if preFormatted more than once. Here's how:

An array is created in the constructor:
this.glyphs = [];
preFormat pushes glyphs into the array:
this.glyphs.push(glyph);

There is no check for whether preFormat has already been called, unlike in StaveNote.
I added a check for this.preFormatted, but it returned false, which means something else reset it. I assume that's intentional, so the problem seems to be that TextDynamics can't handle being preFormatted more than once.
That is, this.glyphs will get longer each time.

The result is that when TextDynamics are drawn, VexFlow tries to draw them more than once, which results in dynamics being drawn several times, and an error at this line:
letter_x += TextDynamics.GLYPHS[current_letter].width;

Solution:
Reset this.glyphs to [] at the start of preFormat

There are probably things I haven't considered, hence why this isn't a pull request.

**Comment by AaronDavidNewman** [comment]
It sounds getting the check for `preFormat` to be called is the correct behavior.  Do you have a fiddle or small example where I could reproduce this?

**Comment by Xonok** [comment]
Currently no. It will take a bit until I can produce one, since I am quite busy.
The general idea is that you'd just need to call preCalculateMinTotalWidth and formatToStave on a note that has TextDynamics.
Anything that makes the TextDynamics object preFormat more than once will cause the bug, because the issue is that the glyphs array is created once, but added to in preFormat.

**Comment by Xonok** [comment]
Here it is https://jsfiddle.net/0pzhuLtv/28/

**Comment by AaronDavidNewman** [comment]
Yep!

**Comment by ronyeh** [comment]
@Xonok can you confirm if @AaronDavidNewman fixed this issue in https://github.com/0xfe/vexflow/pull/1132

The fix has been merged into master so we will close off this issue once you confirm from your end.

**Comment by Xonok** [comment]
I'm working off of the debug release. How do I get an updated one?

**Comment by ronyeh** [comment]
We haven't released anything new to npm or unpkg, so the best way to get the newest fixes is:

```
git clone git@github.com:0xfe/vexflow.git
cd vexflow
npm install
grunt
```

Then grab the `vexflow-debug.js` from the build folder.

**Comment by Xonok** [comment]
It works properly now. Thanks.
