### ISSUE TITLE
Possible small issue with draw() checking if (!this.x)

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1124]
In the draw() method of clef.ts, keysignature.ts, and timesignature.ts:

We have code that looks like `if (!this.x) throw new RuntimeError()`.

However, StaveModifier.x is a number that defaults to 0. That means !this.x will throw a RuntimeError if x is zero.

Is that the intention of this check? Can this.x ever be set to undefined?

If the code is correct as is, we should probably add a comment that says if x is 0 or undefined, we'll throw an error.

In any case, even if it's a bug, it's probably an edge case that no one ever encounters (since they would immediately get a RuntimeError() if they did encounter it).

**Comment by ronyeh** [comment]
https://github.com/0xfe/vexflow/blob/a3ac41ef4041d5d321d10eaf96b1b52857349b58/src/clef.ts#L196

https://github.com/0xfe/vexflow/blob/a3ac41ef4041d5d321d10eaf96b1b52857349b58/src/keysignature.ts#L312-L314

https://github.com/0xfe/vexflow/blob/a3ac41ef4041d5d321d10eaf96b1b52857349b58/src/timesignature.ts#L121-L123

**Comment by 0xfe** [comment]
I think it should be a `defined` test not a `0` test, so those checks are wrong.

But also, as you pointed out, it's super unlikely `this.x` is ever 0. My vote is to clean it up for correctness, but low priority.

**Comment by rvilarl** [comment]
All the instances of `this.x` cannot be `undefined`. I believe the lines have to be removed. I will make a PR.

**Comment by ronyeh** [comment]
It's probably a leftover from old JS, where x was just not assigned.

Now that we are in TS and have typed the x field as a number, it is either
0 or a nonzero number. I agree it should never be undefined.
