### ISSUE TITLE
Failure to build latest

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1130]
There are a couple of places like this in the test code.  Am I doing something wrong?

``` javascript
 catch (e) {
    equal(e.code, 'BadArguments', 'Invalid note: r');
  ...
```
```
ERROR in C:\Users\Daddy\Documents\GitHub\vexflow\tests\music_tests.ts
49:12-13
[tsl] ERROR in C:\Users\Daddy\Documents\GitHub\vexflow\tests\music_tests.ts(49,13)
      TS2571: Object is of type 'unknown'.
```

Easy to fix by making `catch (e: any)`, but I'd imagine the CI tool does not see this, so what's different with me?   
 
```
+ typedoc@0.21.9
+ @typescript-eslint/eslint-plugin@4.30.0
+ npm@7.22.0
+ webpack@5.52.0
+ @typescript-eslint/parser@4.30.0
```

**Comment by 0xfe** [comment]
All the tests are now Typescript. Thanks Aaron, did you try `npm i` again?

@ronyeh FYI

**Comment by ronyeh** [comment]
I just pulled down master @ c712ef340fbc7de8f34a951561c47ad0584abe0e to a new directory and it builds:

```
git clone git@github.com:0xfe/vexflow.git .

npm install

grunt

>> webpack 5.48.0 compiled with 2 warnings in 10719 ms

grunt watch
```

Then I opened `flow.html` in a browser:
```
>> Tests completed in 16571 milliseconds. 6864 assertions of 6864 passed, 0 failed.
```

What version of TypeScript are you running?

**WAIT!!**: Now that I open the fresh git clone in my vs code, I do see the red squiggly underlines with `catch(e) {` and `Object is of type 'unknown'.ts(2571)`

Sorry we missed this. I can put a PR together with typings for the try / catch statements (unless there is a better solution).

**Comment by ronyeh** [comment]
These were the library versions in my fresh git clone / npm install:
```
typescript@4.3.5
typedoc@0.21.5
@typescript-eslint/eslint-plugin@4.29.0
@typescript-eslint/parser@4.29.0
webpack@5.48.0
npm@7.20.3
```

I'm not a eslint / webpack guru. I wonder if there's a good way to throw errors or warnings for this issue.

**Comment by ronyeh** [comment]
I'll submit a PR to fix this later this evening.

I'm converting all the try catch clauses to use the QUnit throws assertion. All we are doing is using the try catch to verify that the RuntimeError code is matching what we expect, and that's exactly what QUnit's throws does:

`throws(() => music.getKeyParts('r'), /BadArguments/, 'Invalid key: r');`

See: https://api.qunitjs.com/assert/throws/

**Comment by AaronDavidNewman** [comment]
Great, thanks.  I have another PR to push but I'll wait for this first.

>> I'm not a eslint / webpack guru. I wonder if there's a good way to throw errors or warnings for this issue.

Me neither  But I think the difference is probably a function of which typescript version is in package-lock.json when you run `npm update`, since this is a compile error and not a lint error.  The version in package.json is 4.4.2, while the version in package.lock is 4.3.8.

For the key tools, like typescript, grunt, etc. it would be good to update the version in package-lock.json so we all have the latest, but I don't know how to do that without blowing the whole thing away.
