### ISSUE TITLE
Clean up Options object interfaces, add documentation.

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1146]
While working on removing Partial, I encountered some fields in `export interface StaveOptions { ... }` that are not used.
```
position_end?: number;
invert?: boolean;
```

These are actually part of `CurveOptions`. I have removed them from my PR after verifying they are not used anywhere.

All of these interface declarations were created while we migrated VexFlow to TypeScript 5-6 months ago. There are probably more cases where the interfaces can be tightened up / documented.

This is just a TODO issue, to remind us to review all the interfaces, document them, remove anything that doesn't belong, etc.

**Comment by rvilarl** [comment]
In `Accidentals` the following field:
```
  stroke_px: number;
```
