### ISSUE TITLE
Semibreve misspelled :-)

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1147]
"semibrave" shows up 23 times in VexFlow.

All but one are private names that we can change.

However, `MultimeasureRestRenderOptions` contains a field `semibrave_rest_glyph_scale` that is part of the public API, and has been since version 1.2.88:

https://www.unpkg.com/browse/vexflow@1.2.88/src/multimeasurerest.js

Can we rename it to `semibreve_rest_glyph_scale`? :-) It would be a breaking change.

**Comment by mscuthbert** [comment]
Let us not be semibrave but fully brave and make this change.

**Comment by 0xfe** [comment]
Yes, let's rename. (Especially if it'll stop @mscuthbert from making more terrible jokes!)

**Comment by mscuthbert** [comment]
Just for that you get my gif illustrating how the semibreve rest put on weight over the centuries:

![semibreve_rests_get_fat](https://user-images.githubusercontent.com/3521479/134780041-3d88fcef-0dca-4b67-8786-d62a046dfb4d.gif)
