### ISSUE TITLE
Draw vertical bar

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1156]
In Stave the following methods:
- `drawVertical` & `drawVerticalFixed` are identical
- `drawVerticalBar` & `drawVerticalBarFixed` are also identical

There is a comment in the source code:
```
// Draw Simple barlines for backward compatability
// Do not delete - draws the beginning bar of the stave
```

However the Bars of a stave are drawn in reality by the method `drawVerticalBar` from `BarLine` and the four methods from `Stave` are used only in specific tests which aim to test them.

I suggest to delete the four methods.

**Comment by 0xfe** [comment]
I think this was an effort to maintain compatibility with an older API -- agreed that we can delete for 4.0.
