### ISSUE TITLE
 this.element.appendChild is not a function error when using a Vexflow in react-pdf

### ISSUE THREAD

**Issue by tommy-banana** [0xfe/vexflow#1157]
Hi I am using Vexflow successfully in a react app and Vexflow is displaying successfully on the screen.
I am trying to find a way to allow users to download a PDF and each route seems to run into problems one way or another.

I am looking at react-pdf/renderer and they have a couple of methods that should work.

<PDFDownloadLink />

You can see more about this on  https://react-pdf.org/advanced#page-wrapping

But if I use this I get this error from inside the Vexflow code (below) for each Vexflow component:
NB the components are all displaying correctly on the Screen, it is only when trying to download that this error is thrown.

Just wondered if the error looks familiar to anyone or if anyone has any suggestions.

```
TypeError: this.element.appendChild is not a function
new SVGContext
node_modules/vexflow/src/svgcontext.js:41
  38 | this.svgNS = 'http://www.w3.org/2000/svg';
  39 | const svg = this.create('svg');
  40 | // Add it to the canvas:
> 41 | this.element.appendChild(svg);
     | ^  42 | 
  43 | // Point to it:
  44 | this.svg = svg;
View compiled
new Renderer
node_modules/vexflow/src/renderer.js:145
  142 | } else if (this.backend === Renderer.Backends.RAPHAEL) {
  143 |   this.ctx = new RaphaelContext(this.element);
  144 | } else if (this.backend === Renderer.Backends.SVG) {
> 145 |   this.ctx = new SVGContext(this.element);
      | ^  146 | } else {
  147 |   throw new Vex.RERR('InvalidBackend', `No support for backend: ${this.backend}`);
  148 | }
View compiled
(anonymous function)
src/interactives/pitch-composer-master/components/score/index.js:26
  23 | 
  24 | useEffect(() => {
  25 |   if (rendererRef.current == null) {
> 26 |     rendererRef.current = new Renderer(
     | ^  27 |       container.current,
  28 |       Renderer.Backends.SVG
  29 |     );
View compiled
▶ 17 stack frames were collapsed.
updateContainer
src/index.js:30
  27 | 
  28 | this.registerEmojiSource = ({ url, format = 'png' }) => {
  29 |   emojiSource = { url, format };
> 30 | };
     | ^  31 | 
  32 | this.registerHyphenationCallback = callback => {
  33 |   hyphenationCallback = callback;
View compiled
update
src/dom.js:68
  65 | }, [state.url]);
  66 | 
  67 | const update = () => {
> 68 |   pdfInstance.current.updateContainer(document);
     | ^  69 | };
  70 | 
  71 | return [state, update];
View compiled
▶ 17 stack frames were collapsed.
(anonymous function)
http://localhost:3000/static/js/132.chunk.js:377:7
  374 | const [isLoaded, setLoadedState] = Object(react__WEBPACK_IMPORTED_MODULE_0__["useState"])(false);
  375 | Object(react__WEBPACK_IMPORTED_MODULE_0__["useEffect"])(() => {
  376 |   shared_audio_engine_scheduler_pitch__WEBPACK_IMPORTED_MODULE_2__["default"].setup(_config_sounds__WEBPACK_IMPORTED_MODULE_7__["default"], _app_state_store__WEBPACK_IMPORTED_MODULE_6__["default"]).then(() => {
> 377 |     setLoadedState(true);
      |     ^  378 |   });
  379 | }, []);
  380 | return /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(react_redux__WEBPACK_IMPORTED_MODULE_1__["Provider"], {
View source
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.  Click the 'X' or hit ESC to dismiss this message.
```

**Comment by tommadams** [comment]
Please edit your post and wrap the stack trace in triple backticks, it's completely unreadable as posted.

\`\`\`
Put three backticks at the top and bottom
of the error like this.
\`\`\`

```
It will then be displayed in a monospace font with
all the spaces preserved like this.
```

**Comment by tommy-banana** [comment]
Thanks Tom. That is much better. Every day is a school day....

**Comment by tommadams** [comment]
I'm not familiar with React, so I can't help with that part of things.

What is the type of `container.curent` in this call?

```javascript
rendererRef.current = new Renderer(
    container.current,
    Renderer.Backends.SVG
);
```

The first argument to the `Renderer` constructor needs to be either:
  - an `HTMLElement` (most commonly a div)
  - the string ID of an `HTMLElement` in your document.

Judging from the callstack you posted, `container.current` is neither of these things.

**Comment by tommy-banana** [comment]
Yes - I think you are right that is the issue. It sis interesting though that everything works fine in the browser it is only when downloading a file that the error is thrown.

The way React works  (and my level of understanding of it) makes that a not straightforward question for me to answer. I will see if I can find out. Many thanks.

**Comment by ronyeh** [comment]
Are you using SVG context? If so, can you send the SVG element through a package like: https://github.com/yWorks/svg2pdf.js/

Also, are you comfortable building VexFlow from the source? We are currently working on preparing a 4.0 release. It looks like you're probably using the 3.0.9 release at the moment. 4.0 has lots of good stuff, we promise. :-)

**Comment by tommy-banana** [comment]
The complexity is working out  what React and webpack are doing… I will have a go. I have been looking at svg2pdf and look forward to trying version 4. Thanks very much for the suggestions.

**Comment by sschmidTU** [comment]
@tommy-banana the OSMD debugging demo is [using jspdf and svg2pdf](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/develop/demo/index.js#L857). It's not ideal but it works. You should be able to get the SVG via `context.svg` or something.

**Comment by rvilarl** [comment]
@tommy-banana have you tried with `Renderer.Backends.CANVAS` for the pdf?

**Comment by ronyeh** [comment]
The OP can try taking a look at:
https://github.com/0xfe/vexflow/blob/master/src/rendercontext.ts
https://github.com/0xfe/vexflow/blob/master/src/renderer.ts
https://github.com/0xfe/vexflow/blob/master/demos/node/customcontext.js

See if you can pass in a custom rendercontext into the renderer to handle PDF renderering. If we can identify a concrete bug in VexFlow, then we can take action.

I'm closing this one as "not a VexFlow bug" for now.

**Comment by ronyeh** [comment]
That said, I'm sure we would welcome a PR contributing a demo for a custom PDF RenderContext. :-) I think there are npm packages for canvas to PDF, or svg to PDF that might help with this endeavor.

**Comment by tommy-banana** [comment]
Thanks Ron - will get back to this soon.

Best

Tom Bancroft
+447974 983701
