### ISSUE TITLE
camelCaseEverything includingFunctionsAndMethods() and also fieldsInOptionsObjects

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1166]
I was going through old issues to categorize them for 4.0 | 4.x | 5.0.

https://github.com/0xfe/vexflow/issues/348
https://github.com/0xfe/vexflow/issues/1070

I think for the future 5.0 release, we should make a pass through the entire code base and `banish_the_underscores` so that we can `useCamelCaseForEverything`.

We can add a big warning to the CHANGELOG for version 5.0, including a list of changed public members (the_old_way => theNewWay), so developers can easily search and replace in their projects.

Hopefully, now that we are in TypeScript, compiler errors will help catch any issues with migrating from 4.x to 5.0.

**Comment by ronyeh** [comment]
@rvilarl If we are going for a major revision bump (VexFlow 5.0), do you think this is worth pursuing?

It would be cool to make the code base look like a modern JS/TS library, where everything is in `camelCase`.

This would be a **huge breaking change**, so we would have to get buy-in from 0xfe / OSMD / music21j / smoosic and other interested parties, but I think it's worth it if we want VexFlow to fit in alongside the other top JS/TS libraries.

**Comment by sschmidTU** [comment]
I'm fine with unifying the style to camelCase with a major version update!
I've kind of come to like snake_case as it can be `quite_readable_for_long_names`,
but well, I also like camel case, and if vexflow is camel case heavy and most web libraries gravitate towards camel case, it seems reasonable to unify.

**Comment by ronyeh** [comment]
For camelCase conventions, I would suggest following the Google Typescript style guide:

https://google.github.io/styleguide/tsguide.html#identifiers



If anything is still unclear, we fall back to:

https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/capitalization-conventions

As a secondary backup, we can use this guide for contributors to the TypeScript compiler (even though Microsoft says to not use it, haha):

https://github.com/microsoft/TypeScript/wiki/Coding-guidelines

**Comment by mscuthbert** [comment]
I put some comments on the general #1498 Vexflow 5 note.

**Comment by rvilarl** [comment]
Done in https://github.com/vexflow/vexflow/tree/vexflow5
