### ISSUE TITLE
Missing accidentals when using "VF.Accidental.applyAccidentals"

### ISSUE THREAD

**Issue by cldevlin** [0xfe/vexflow#1169]
There seems to be an issue with `VF.Accidental.applyAccidentals` where accidentals are not following the "octave rule".

Example code below, which adds the following notes:

```
c/4, c#/4, c#/5, c/5
```

and then calls `applyAccidentals` with a keySignature value of `C`.

Here is the VF output:

![Screen Shot 2021-10-01 at 6 03 38 PM](https://user-images.githubusercontent.com/71520213/135691002-343cb407-30dc-48c9-91ce-75fee8f87db5.png)

Here are the same notes in the same key signature in Sibelius:

![Screen Shot 2021-10-01 at 6 00 15 PM](https://user-images.githubusercontent.com/71520213/135691039-a1fb4fb3-0a91-4528-9d6c-136d966c119c.png)

As you can read [here](https://music.stackexchange.com/a/80512/65668) (quoted from "Behind Bars" by Elaine Gould), "[...] each additional octave requires a further accidental". The same rule is explained elsewhere, see [here](https://courses.lumenlearning.com/musicappreciation_with_theory/chapter/theory-lesson-music-basics/) -- "Accidentals apply within the measure and octave in which they appear [...]"

---

I believe that the issue may be with [this line](https://github.com/0xfe/vexflow/blob/961f26aca6e1ad5244382925d2ece1d8d1837a09/src/accidental.ts#L431) which checks identical *pitches*, not taking octaves into account.

But I may be wrong.

---

Repro source code:

```
import Vex from 'vexflow';

const VF = Vex.Flow;

const div = document.getElementById("vf")
const renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);

renderer.resize(1000, 1000);
const context = renderer.getContext();
context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");
const stave = new VF.Stave(0, 0, 300);
stave.addClef("treble").addTimeSignature("4/4");
stave.setContext(context).draw();

var notes = [
  new VF.StaveNote({clef: "treble", keys: ["c/4"], duration: "q" }),
  new VF.StaveNote({clef: "treble", keys: ["c#/4"], duration: "q" }),
  new VF.StaveNote({clef: "treble", keys: ["c#/5"], duration: "q" }),
  new VF.StaveNote({clef: "treble", keys: ["c/5"], duration: "q" })
];

var voice = new VF.Voice({num_beats: 4,  beat_value: 4});
voice.addTickables(notes);

// apply accidentals
VF.Accidental.applyAccidentals([voice], 'C');

var formatter = new VF.Formatter().joinVoices([voice]).format([voice], 200);

voice.draw(context, stave);
```

**Comment by ronyeh** [comment]
Nice catch. I agree VexFlow should follow the octave convention for accidentals.

However, from the page you posted, one of the answers far down says:

> My Berklee College of Music instructor says that in classical music, an accidental does not carry through to other octaves, but in jazz it does.


So I think we should follow classical music convention by default, but add a flag to switch it to the jazz convention (if that comment is true).

**Comment by cldevlin** [comment]
I actually did my Master's degree in Jazz Performance and Composition at McGill University, and all of my professors there followed the octave convention as well!

**Comment by ronyeh** [comment]
Yeah... 🇺🇲 jazz musicians don't like rules. 

Just kidding, haha. In your example, it's definitely safer to add the accidental symbol. Plus, if it's the convention in classical music and in most countries other than the USA, we should follow the rule.

(Montreal is a beautiful city with yummy food!)

**Comment by rvilarl** [comment]
To me, without knowing the theory, it also makes more sense the indication from @cldevlin.

I have looked into the testing and the test `automaticAccidentalsMultiVoiceOffset` with the following notes:
```
const notes0 = [
    { keys: ['c/4'], duration: '4', stem_direction: -1 },
    { keys: ['d/4'], duration: '4', stem_direction: -1 },
    { keys: ['e/4'], duration: '4', stem_direction: -1 },
    { keys: ['f/4'], duration: '4', stem_direction: -1 },
    { keys: ['g/4'], duration: '4', stem_direction: -1 },
    { keys: ['a/4'], duration: '4', stem_direction: -1 },
    { keys: ['b/4'], duration: '4', stem_direction: -1 },
    { keys: ['c/5'], duration: '4', stem_direction: -1 },
  ].map(f.StaveNote.bind(f));

  const notes1 = [
    { keys: ['c/5'], duration: '8' },
    { keys: ['c/5'], duration: '4' },
    { keys: ['d/5'], duration: '4' },
    { keys: ['e/5'], duration: '4' },
    { keys: ['f/5'], duration: '4' },
    { keys: ['g/5'], duration: '4' },
    { keys: ['a/5'], duration: '4' },
    { keys: ['b/5'], duration: '4' },
    { keys: ['c/6'], duration: '4' },
  ].map(f.StaveNote.bind(f));
```
is producing the following output:

![Accidental Automatic_Accidentals___Multi_Voice_Offset Bravura_Reference](https://user-images.githubusercontent.com/22865285/135746354-9246cb60-4fa8-4cc5-9c0b-ca2fa12b1ad5.png)

following the proposal in this thread, it should rather be:

![Accidental Automatic_Accidentals___Multi_Voice_Offset Bravura_Current](https://user-images.githubusercontent.com/22865285/135746412-76a2aa4a-f513-45ce-978f-be96d197618a.png)

@mscuthbert @AaronDavidNewman @0xfe what is your oppinion in this topic?
