### ISSUE TITLE
Use puppeteer for visual regression tests

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1176]
**Problem:** The command line visual regression tests don't produce the same output as running flow.html in a browser.
* The system fonts look different. When indicating "Helvetica Neue", a Chrome browser on macOS looks fine, but generate_png_images.js produces a really thin font weight.
* No support for web fonts. ChordSymbol test cases use *.woff files. The visual regression tests fall back to a default serif font.

---

For 4.x, we should consider dropping JSDOM from our visual regression tests, and opt for either direct use of node canvas, or a full headless chrome browser (puppeteer).

While working on fonts, I learned that JSDOM does not provide a way to load custom fonts so that we can use it in the canvas element. ([document.fonts not implemented](https://github.com/jsdom/jsdom/blob/0778616c35b698e72a125993545576f00a8e7155/test/web-platform-tests/to-run.yaml#L87))

I believe JSDOM uses node canvas for its underlying canvas implementation. Node canvas does in fact support custom font loading.

I have been able to load and render custom fonts like so:

```
const { registerFont, createCanvas } = require('canvas');
registerFont('Bravura_1.392.woff', { family: 'Bravura' });
registerFont('Petaluma_1.065.woff', { family: 'Petaluma' });
registerFont('PetalumaScript_1.10.woff', { family: 'PetalumaScript' });

...
...

ctx.font = '128px PetalumaScript';
ctx.fillText(String.fromCharCode(gClef), 20, 220);
```

With Tom's PR, we could pass in a RenderContext that uses a custom node canvas (and ditch JSDOM). 

A different solution would be to run the local test cases in puppeteer (headless chromium browser) and then save out PNGs. The advantage of this approach is that it provides a full browser API (i.e., no special calls to registerFont on node canvas). It should be able to reuse most of the test creation code in `vexflow_test_helpers.ts`.

We could also have a flag which enables saving screenshots of the SVG files too, if we ever want to do a 100% test coverage pass before shipping a new release.

Currently:
* flow.html tests Canvas+Bravura, and SVG+Bravura/Petaluma/Gonville.
* visual_regression.sh / generate_png_images.js tests Canvas+Bravura/Petaluma/Gonville only. SVG tests are ignored.

**Proposal:** Keep the current procedure, but add a flag for an ultimate test which run as a sanity check before releasing new versions. The ultimate test uses a headless browser and tests Canvas+Bravura/Petaluma/Gonville and also SVG+Bravura/Petaluma/Gonville.

**Comment by 0xfe** [comment]
@h-sug1no for thoughts on this

If it keeps us current, works on Mac/Linux/Windows, and allows us to test the various rendering backends, then SGTM.

**Comment by rvilarl** [comment]
@ronyeh this can be closed now
