### ISSUE TITLE
Dots are gone in svg

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1177]
Top is canvas.
Bottom is svg :(

![image](https://user-images.githubusercontent.com/5438280/136119539-55b5e343-e21d-4ff3-a057-4b6ee09001ff.png)

**Comment by ronyeh** [comment]
I see this on my head revision too, and apparently it's all of the tests, since I'm looking at Bach Demo. 

Our visual regression tests don't check SVG. :-) :-(

**Comment by AaronDavidNewman** [comment]
It seems like the issue is in svg.arc.  I'm not sure what other modifiers use arc...

**Comment by ronyeh** [comment]
Possible related PR https://github.com/0xfe/vexflow/pull/1142

This was before @tommadams and I discussed the fact that visual diffs don't cover SVG modifications. We should address that at some point. 😉

**Comment by ronyeh** [comment]
This discussion reminds me that I think SVGContext and CanvasContext could extend an abstract RenderContext which defines a high level API like `fillCircle(x, y, radius)` or other useful methods VexFlow needs. 

Then the individual subclasses can implement those high level methods whichever way they please. CanvasContext could use arc() and SVGContext could call circle().

Currently we have a common.d.ts which defines the RenderContext interface. It could be easily moved out to its own abstract class file when we fix this bug. 

Thoughts? @0xfe @tommadams @rvilarl

**Comment by tommadams** [comment]
Sorry I haven't been communicative the past few days, work's been taking up all my time. I'll take a look at this first thing tomorrow morning.

**Comment by ronyeh** [comment]
@tommadams no worries! Work is important.

You can help review https://github.com/0xfe/vexflow/pull/1178

The main change is adding two equal signs: >= instead of >

"No visual diffs!" The bigger problem here is that our visual regression tests don't catch SVG regressions or bug fixes.
