### ISSUE TITLE
Make `RenderContext` an abstract base class

### ISSUE THREAD

**Issue by tommadams** [0xfe/vexflow#1179]
I'm opening this issue to see how folks feel about making `RenderContext` an abstract base class instead of an interface.

When submitted, #1161 will allow users to pass their own custom `RenderContext` to the `Renderer` constructor.

Because `RenderContext` is currently an interface we have to use a fairly obscure type guard to figure out if an argument passed to the `Renderer` constructor is a `RenderContext`:
 ```typescript
    function isRenderContext(obj: any): obj is RenderContext {
      return obj.setShadowBlur !== undefined;
    }
```

It would be more readable if we could write `obj instanceof RenderContext`.

Work required:
 - Remove the `RenderContext` interface from `types/common.d.ts` and create a new `src/rendercontext.ts` file containing the abstract class definition.
 - Change `SVGContext` and `CanvasContext` to extend `RenderContext` instead of implement it.
 - Update `RenderContext` imports to point to the new location.

The last step will require touching a lot of files but the changes are pretty straight forward.

**Comment by ronyeh** [comment]
Agree!

**Comment by ronyeh** [comment]
I think this is a 4.0 feature. (Not counting the fillCircle() idea above, which can be added in 4.1).
