### ISSUE TITLE
custom font glyphs (custom.js)

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1188]
This issue is just a reminder to myself to figure out how to handle custom.js going forward. Are there glyphs we should remove from custom.js (in case Bravura includes them already?). Which projects are using these glyphs?

---

The first four glyphs defined in custom.js are also present (and identical) in gonville.js.
```
v39: {
  x_min: -171.5,
  x_max: 251.8125,
  ha: 257,
  o: '...',
},
v7a: {
  x_min: -1.359375,
  x_max: 386.5625,
  ha: 394,
  o: '...',
},
v8d: {
  x_min: -1.359375,
  x_max: 255.890625,
  ha: 261,
  o: '...',
},
vb7: {
  x_min: -176.9375,
  x_max: 251.8125,
  ha: 257,
  o: '...',
},
```

Looking into valid_codes.js, we see that:
* v39 == accidentalBuyukMucennebFlat
* v7a == vexAccidentalMicrotonal2
* v8d == accidentalKucukMucennebSharp
* vb7 == accidentalBakiyeFlat

I don't know why just these four are duplicated between custom and gonville, but we can investigate at some point.

The rest of the custom glyphs are not duplicated anywhere else. The mappings are:
* vd0 == accidentalSori
* vd1 == accidentalKoron
* vd2 == noteheadSquareBlack
* vd3 == noteheadSquareWhite
* vd4 == vexNoteHeadRectBlack
* vd5 == vexNoteHeadRectWhite
* vd6 == vexAccidentalMicrotonal3
* vd7 == vexAccidentalMicrotonal4

```
vd0: {
  x_min: -10.890625,
  x_max: 299.4375,
  ha: 294,
  o:
},
vd1: {
  x_min: -20,
  x_max: 320,
  ha: 257,
  o:
},
vd2: {
  x_min: 0,
  x_max: 430.75,
  ha: 386, 
  o:
},
vd3: {
  x_min: 0,
  x_max: 430.75,
  ha: 386,
  o:
},
vd4: {
  x_min: 0,
  x_max: 430.75,
  ha: 360, 
  o:
},
vd5: {
  x_min: 0,
  x_max: 430.75,
  ha: 360,
  o:
},
vd6: {
  x_min: 0,
  x_max: 430.75,
  ha: 360,
  o:
},
vd7: {
  x_min: 0,
  x_max: 430.75,
  ha: 360,
  o:
},
```

**Comment by rvilarl** [comment]
The glyphs details are different, I believe that with the new approach in #1242 where there is no glyph for the undefined ones (NOGLYPHS) there is no need to reduce the custom glyphs further.
