### ISSUE TITLE
use VexFlow to flutter?

### ISSUE THREAD

**Issue by tangtao007** [0xfe/vexflow#1224]
I want to use vexflow in the flutter project? It is ok?

thanks

**Comment by AaronDavidNewman** [comment]
No need to ask permission :)  I guess you're planning to create a Dart wrapper around the library so you can access it from Flutter?  I know nothing about these technologies, but I'm sure it's possible.  Please share more...

**Comment by rvilarl** [comment]
@tangtao007 as @AaronDavidNewman said, it is ok. Will you share more in this thread?

**Comment by rvilarl** [comment]
@0xfe I suggest to close this one

**Comment by rvilarl** [comment]
@0xfe you missed this one.
