### ISSUE TITLE
Export VexFlow classes as `VFClassName` in addition to (or instead of) `ClassName`

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1228]
While migrating Music21J and OSMD, Rodrigo and I discovered that some projects have lots of name collisions with vexflow classes. This makes sense, since a music project that includes vexflow might declare their own Note class or Articulation class.

This means that developers have to do things like:
```
import { Articulation as VFArticulation } from "vexflow";
```

It's fine for a one off, but maybe it gets annoying if they have to import 10 classes, and do this repeatedly across all of their class files?

Maybe we can have our index.ts file also export these `VF****` aliases? It seems like it'd be a nice little refinement, so that @sschmidTU and @mscuthbert don't have to constantly alias their imports to avoid name collisions.

@rvilarl @0xfe what do you think about this idea? It's slightly more maintenance on our part, but I think developers would appreciate this.

**Comment by rvilarl** [comment]
Would it be possible just to use: 
```
import * as VF from "vexflow";
```
and then use VF.Classname?

**Comment by 0xfe** [comment]
Not a fan of putting aliases in this codebase -- these things tend to be very opinionated, and we have one more moving part to maintain (and support forever.) It's easy enough for consumers to create their own alias files.

**Comment by ronyeh** [comment]
OK, sounds good to me. It seemed like a nice little usability feature for developers who npm install vexflow, but I can see how it can be extra work to maintain, and also possibly confusing to the developer.

**Comment by mscuthbert** [comment]
I'm okay with doing `import * as VF from 'vexflow'` -- I tend to like having everything namespaced that I import anyhow.
