### ISSUE TITLE
Do we keep the build/* or releases/* in the repository?

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1231]
Hey everyone,

I just wanted to make sure we are all aligned with what we plan to do with generated files (e.g., `build/*` and `releases/*`).

Currently, the output files are stored in `build/*` and then npm published. The package.json specifies these two folders to publish:
```
"files": [
  "build",
  "src"
],
```

If a developer wants to use a script tag for one of the bundled JS files, they can use a CDN that delivers NPM packages:
* https://cdn.jsdelivr.net/npm/vexflow@4.0.0/
* https://cdn.jsdelivr.net/npm/vexflow@4.0.0/build/vexflow.js
* https://unpkg.com/browse/vexflow@4.0.0/
* https://unpkg.com/vexflow@4.0.0/build/vexflow.js

In the past (3.0.9 and earlier), we kept the final release in `releases/*`. These files were checked into the git repository.

Having older releases around could be useful for convenient visual diffing between versions. Currently, the `releases/` folder contains versions 1.2.90 and 3.0.9.

### Question 2: Do we keep older releases/* checked into the repository?

@0xfe @sschmidTU @rvilarl @tommadams @mscuthbert for comments on your preferences.

---

Honestly I don't know what's the best practice, since I'm not a pro at publishing NPM packages.

Here are a few projects I surveyed:

## [Vue](https://github.com/vuejs/vue)

Build files are checked into the repo, and stored in `dist/`. Their [package.json](https://github.com/vuejs/vue/blob/dev/package.json) specifies the following files to be sent to NPM:

```
"files": [
  "src",
  "dist/*.js",
  "types/*.d.ts"
],
```

## [TypeScript](https://github.com/Microsoft/TypeScript)

Build files are checked into the repo and stored in `lib/`. Their [package.json](https://github.com/microsoft/TypeScript/blob/main/package.json) tells NPM that these are the main files:

```
"main": "./lib/typescript.js",
"typings": "./lib/typescript.d.ts",
```

They use [.npmignore](https://github.com/microsoft/TypeScript/blob/main/.npmignore) to exclude a large list of files, and the remaining files are published to NPM. (So Vue uses a whitelist while TypeScript uses a blacklist approach to npm publish.)

## [d3 Data Driven Documents](https://github.com/d3/d3)

Builds are NOT checked in to the source repo. They are built to `dist/` and included in npm. Their [package.json](https://github.com/d3/d3/blob/main/package.json) uses the files whitelist:

```
"files": [
  "dist/**/*.js",
  "src/**/*.js"
],
```

They also make use of the GitHub releases page: https://github.com/d3/d3/releases

Note: d3 is an unusual case in that the root project actually npm installs all of their sub projects. The main d3 repo is a master project that depends on a huge list of their own subprojects.

## TensorFlow JS and Core API
Builds are NOT checked in to the repo.
They are output to `dist/` and uploaded to NPM. See:

* https://github.com/tensorflow/tfjs/tree/master/tfjs
* https://github.com/tensorflow/tfjs/blob/master/tfjs/package.json
* https://github.com/tensorflow/tfjs/tree/master/tfjs-core
* https://github.com/tensorflow/tfjs/blob/master/tfjs-core/package.json

## [Tone JS](https://github.com/Tonejs/Tone.js)
Tone is a smaller project than all of the above, but it still has [15,920 weekly downloads](https://www.npmjs.com/package/tone).
Build files are NOT checked into the repository. Their [package.json](https://github.com/Tonejs/Tone.js/blob/dev/package.json) uses the files whitelist and sends the `build/` folder up to npm.

---

So there are a number of different approaches here!

# Proposal:
* `build/` is sent up to NPM, but is NOT checked into the repository.
* Assume the build files for each release will live on forever on the NPM servers (since like GitHub, they are owned by Microsoft).
* `releases/` is kept as an empty folder.
* Add a new script called `vexflow/tools/getReleases.js` that will download the requested releases directly from NPM into the `releases/` folder. This can be useful for visual regression testing.

What do folks think about this idea? I think it would be kind of nice to keep the repository free of build files.

However, I understand the reassurance that is provided by checking in the release files (i.e., what if we can't replicate an old build for some reason?). If we are worried about not being able to access older builds, perhaps we can check them into a separate GitHub repo called `vexflow-releases`, and include it as an optional git submodule? Or maybe we can stick the release files into a git orphan branch inside the vexflow repo?

But for now I will assume that NPM will live on, so hopefully our production builds will have a home forever.

We can also make use of the **[VexFlow GitHub releases page](https://github.com/0xfe/vexflow/releases)** to make the build files easily available).

**Comment by sschmidTU** [comment]
I would like to keep the repository (and npm release) small and avoid adding big build files, if possible.
If you're worried about build preservation or not being able to replicate a release, you can publish the release on Github. (OSMD always publishes releases both to NPM and Github Releases)

For example, The Vexflow 1.2.93 npm package is 12.6MB, which seems a bit unnecessary.
![image](https://user-images.githubusercontent.com/33069673/141766668-0f8eb1d9-f9a9-434c-8aea-3765945bed87.png)
We probably only needed the minified build and the source map there. With the source map, you can do debugging, no need for a debug release.

On the Github Release, you can be more generous and include all kinds of build files people might need.
(For OSMD, we don't include a sourcemap on NPM, just on Github Releases, because it's 4MB, and the OSMD NPM package otherwise sits nicely at 1.5MB size. Though adding it to NPM also wouldn't be a big deal)

**Comment by 0xfe** [comment]
Ron, I like the idea of using [github releases](https://github.com/0xfe/vexflow/releases) for this. I've used it for other projects, and it's designed for exactly this kind of thing. With that, we can go with your proposal. (Although, I don't get why `releases/` needs to be an empty directory -- why don't we just delete it?)

**Comment by ronyeh** [comment]
Sounds good. Yes, we can definitely delete the releases/ directory. Then any script we run that pulls down releases can make that directory again and stick the downloads in there.

**Comment by rvilarl** [comment]
@ronyeh you can close this one
