### ISSUE TITLE
TypeDoc issues with HTML tags in the comments

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1235]
<img width="1404" alt="S 2021-11-20 at 10 30 22 " src="https://user-images.githubusercontent.com/239113/142737322-f25e3061-583c-4d62-a1c7-088593ff0c6e.png">

The above issue is in `vexflow/docs/api/classes/CanvasContext.html#canvas` although I'm sure it shows up in other files as well.

Scroll down to the **canvas** property and it looks like the comment is broken. If you use the dev tools dom inspector, you'll see that there is a random canvas element inside the comment.

DOM:
```
<p>The HTMLCanvasElement or OffscreenCanvas that is associated with the above context.
If there was no associated <canvas> element, just store the default WIDTH / HEIGHT.</canvas></p>
```

Our canvascontext.ts source file looks like:
```
  /**
   * The HTMLCanvasElement or OffscreenCanvas that is associated with the above context.
   * If there was no associated <canvas> element, just store the default WIDTH / HEIGHT.
   */
  canvas: HTMLCanvasElement | OffscreenCanvas | { width: number; height: number };
```

So it looks like typedoc isn't escaping these tags properly. It looks like typedoc is using markdown parsing for the comments, so an HTML tag will be sent straight to the final output. I guess we need to be using single backticks to make sure the code is rendered properly.

```
`<canvas>`
```

@rvilarl at some point we should review our typedoc generated documentation to see if there are any other issues like this. I can fix this one instance in my next PR.

**Comment by rvilarl** [comment]
Yes the documentation is auto generated and I am sure that we will find quite a few issues in the TS sources. But now that they are there we will fix the issues little by little. Good finding! Go for the fix!
