### ISSUE TITLE
WIKI: references to public.vexflow.com

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1236]
@0xfe I have seen that the wiki points to a server public.vexflow.com do you maintain this one?

_Originally posted by @rvilarl in https://github.com/0xfe/vexflow/issues/1229#issuecomment-974657468_

**Comment by rvilarl** [comment]
I have been looking at options and I recommend to setup pages:

https://rvilarl.github.io/vexflow/api/index.html

I have done it in my fork and it works well:

https://rvilarl.github.io/vexflow/api/index.html

icons are not working properly because LF was adjusted by git, but this should be solvable

**Comment by 0xfe** [comment]
Thanks Rodrigo, I can do that. (I own public.vexflow.com, I can redirect it here.)

**Comment by 0xfe** [comment]
And this works: https://0xfe.github.io/vexflow/api/index.html :-)

**Comment by rvilarl** [comment]
Then I will move the references to the API in the wiki to pages.gitHub, if you agree. With this method the API will be always up to date.

**Comment by 0xfe** [comment]
Sounds perfect!

**Comment by rvilarl** [comment]
There is now no reference to public.vexflow.com in the wiki.
