### ISSUE TITLE
flow.html: Font.setFont test failed: macOS safari

### ISSUE THREAD

**Issue by h-sug1no** [0xfe/vexflow#1240]
```
commit e3d0eb8f7eab7900b645245adfa61a2a680fc015 (HEAD -> master, origin/master, origin/HEAD)
Merge: 7174bcaa 5c6602b8
Author: Mohit Cheppudira <0xfe@users.noreply.github.com>
Date:   Sun Nov 28 08:28:55 2021 -0500

    Merge pull request #1238 from rvilarl/test/411
    
    Add test for issue #411
```
- buid e3d0eb8f7eab7900b645245adfa61a2a680fc015  and load flow.html by using macOS safari
- Font.setFont test failed
```
QUnit 1.19.0; Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.0 Safari/605.1.15


582. Font: setFont (1, 8, 9)Rerun6 ms
failed@ 4 ms
Expected: 	
"bold 100px PetalumaScript"
Result: 	
"100px PetalumaScript"
Diff: 	
"bold 100px PetalumaScript"
Source: 	
@http://192.168.1.13:8080/github/0xfe/vexflow/tests/support/qunit.js:1988:24
setFont@http://192.168.1.13:8080/github/0xfe/vexflow/build/vexflow-debug-with-tests.js:37950:10
run@http://192.168.1.13:8080/github/0xfe/vexflow/tests/support/qunit.js:813:37
@http://192.168.1.13:8080/github/0xfe/vexflow/tests/support/qunit.js:950:21
process@http://192.168.1.13:8080/github/0xfe/vexflow/tests/support/qunit.js:630:29
next@http://192.168.1.13:8080/github/0xfe/vexflow/tests/support/qunit.js:619:14
```
![image](https://user-images.githubusercontent.com/59550999/143790754-1ef50da9-30d7-4e88-b6d7-e61638d7bd02.png)

**Comment by rvilarl** [comment]
Did you try in Chrome?

**Comment by sug1no** [comment]
No problem with chrome and fx.

**Comment by h-sug1no** [comment]
No problem with chrome and fx.

**Comment by 0xfe** [comment]
Interesting that adding a test broke this.

**Comment by rvilarl** [comment]
@h-sug1no could you try if a44b7818de42be1fded3fd741088e809a47fa687 also produces the error?

**Comment by h-sug1no** [comment]
4bcaa2e4839d37b1d84ee3eadb28c6e222228 also produces the error.

As the message indicates, here's the error:

https://github.com/0xfe/vexflow/blob/7174bcaa2e4839d37b1d84ee3eadb28c6e222228/tests/font_tests.ts#L46

**Comment by rvilarl** [comment]
Ok so the problem is not the new test.
@0xfe FYI
@ronyeh can you reproduce that in your mac?

**Comment by ronyeh** [comment]
Thanks for the bug report. I will investigate this. (This is my test case that failed). Maybe I should use Safari more!!!

**Comment by sschmidTU** [comment]
> Maybe I should use Safari more!!!

If you want to see a lot of errors that never appear in Chrome, Firefox or Edge, definitely ;) Safari and all iOS browsers also have issues with audio playback (different topic).

**Comment by ronyeh** [comment]
https://stackoverflow.com/questions/51440257/safari-missing-font-weight-component-when-retrieving-font-property-from-canvas

So it looks like Safari might be buggy? According to that stackoverflow question, if you set the canvas context's font to bold, and then read the font, Safari doesn't report that the font is bolded.

I guess.... I can just change the test case?

**Comment by ronyeh** [comment]
I have confirmed the Safari bug with this example:

http://jsfiddle.net/41f6otya/5/

On Chrome it shows 80px bold Arial.
On Safari it shows 80px Arial, even though the font is actually bolded. 

On this example: 
http://jsfiddle.net/2h0cdLug/1/

We see that Safari correctly reports that the font is italic. However, it still misses the "bold". Chrome correctly reports "italic bold 80px Arial".

I'll just change the test case.
