### ISSUE TITLE
OSMD VexflowPatch: Beam

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1252]
With this one I will start a set of open issues that were resolved patching in OSMD. @sschmidTU we will need your help to get examples, etc...

Description:
add flat_beams, flat_beam_offset, flat_beam_offset_per_beam render_option

@sschmidTU please provide screen shots

**Comment by rvilarl** [comment]
@sschmidTU no noticiable differences on Beams
**Blessed**
![test_percussion_beamed_notes_tuplet_stem_direction musicxml_1](https://user-images.githubusercontent.com/22865285/146453744-d33343dc-77f8-4b79-b3d3-2df50b2af1c4.png)
**Current**
![test_percussion_beamed_notes_tuplet_stem_direction musicxml_1](https://user-images.githubusercontent.com/22865285/146453594-03282bf0-5bd8-493d-bc36-e6392f8aa4ba.png)
**Blessed**
![test_drum_tuplet_beams_measure1 musicxml_1](https://user-images.githubusercontent.com/22865285/146453747-81185427-e4e6-4505-a1ad-5b7afadb5579.png)
**Current**
![test_drum_tuplet_beams_measure1 musicxml_1](https://user-images.githubusercontent.com/22865285/146453596-7111109a-a0d7-4af5-a959-227ff3328abe.png)
**Blessed**
![test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1](https://user-images.githubusercontent.com/22865285/146453748-7291dafb-0074-4236-9ee8-e0b90dc12bec.png)
**Current**
![test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1](https://user-images.githubusercontent.com/22865285/146453597-4fa2abb0-8d2c-450d-b207-871737e867cd.png)
**Blessed**
![OSMD_function_test_autobeam musicxml_1](https://user-images.githubusercontent.com/22865285/146453749-d91f1a69-8298-4257-99ea-67f85a18f025.png)
**Current**
![OSMD_function_test_autobeam musicxml_1](https://user-images.githubusercontent.com/22865285/146453599-02e2c343-8d34-49fb-8d42-bca8686c0709.png)

**Comment by sschmidTU** [comment]
flat_beams are optional, you have to set the setting: `osmd.EngravingRules.FlatBeams = true`
![image](https://user-images.githubusercontent.com/33069673/146456824-744d0d76-067e-4ace-af9a-cb69b0539bb0.png)

with false:
![image](https://user-images.githubusercontent.com/33069673/146456895-4da82dbc-1d19-41b5-8289-0bd79d204466.png)

**Comment by rvilarl** [comment]
@sschmidTU flat beams are already supported(`flat_beams=true`), see associated tests below. Is there anything else required?

**Auto_Beaming Flat_Beams_Up**
![Auto_Beaming Flat_Beams_Up Gonville](https://user-images.githubusercontent.com/22865285/146498554-1d2d647a-f062-45ca-9432-acc13a6adbe7.png)

**Auto_Beaming Flat_Beams_Down**
![Auto_Beaming Flat_Beams_Down Gonville](https://user-images.githubusercontent.com/22865285/146498592-8ee3c075-e7fd-4da7-8a2f-edf052bf2672.png)

**Auto_Beaming Flat_Beams_Up_Bounds**
![Auto_Beaming Flat_Beams_Up_Bounds Gonville](https://user-images.githubusercontent.com/22865285/146498605-cdd98e6c-fa1b-41a2-a2e2-198e0948bd5f.png)

**Auto_Beaming Flat_Beams_Down_Bounds**
![Auto_Beaming Flat_Beams_Down_Bounds Gonville](https://user-images.githubusercontent.com/22865285/146498632-7446489a-6f53-4e2b-a45a-0661a803943f.png)

**Auto_Beaming Flat_Beams_Up__uniform**
![Auto_Beaming Flat_Beams_Up__uniform_ Gonville](https://user-images.githubusercontent.com/22865285/146498649-a4eb1a51-8d73-40d6-99bb-b1f09d16cbd8.png)

**Auto_Beaming Flat_Beams_Down**
![Auto_Beaming Flat_Beams_Down__uniform_ Gonville](https://user-images.githubusercontent.com/22865285/146498671-1becd113-8293-437d-b95d-187b2217765e.png)

**Auto_Beaming Flat_Beams_Mixed_Direction**
![Auto_Beaming Flat_Beams_Mixed_Direction Gonville](https://user-images.githubusercontent.com/22865285/146498684-10872123-a843-40e7-a8c9-af7b21fc06fa.png)

**Comment by sschmidTU** [comment]
You're right, flat_beams were already an option, we just fixed them with the offset, which is new.

Without a 10 pixel offset to the notes, flat beams overlap notes (Vexflow 1.2.93):
![image](https://user-images.githubusercontent.com/33069673/146526781-47da11e0-25ae-4764-aade-43c05e53e3ae.png)

This is Vexflow 4 by the way, oops. Looks like there's another issue there.
![image](https://user-images.githubusercontent.com/33069673/146526934-783eefea-e1ca-4983-8fdc-1e6d2c60c230.png)

Diff of our patch to Vexflow 1.2.93 beam.js:

```diff
diff --git a/src/beam.js b/src/beam.js
index fca6bf4d..34cc4f72 100644
--- a/src/beam.js
+++ b/src/beam.js
@@ -590,13 +590,13 @@ export class Beam extends Element {
       offset = extremeY - extremeTest;
     }
 
-    if (!flat_beam_offset) {
+    if (!(flat_beam_offset + this.render_options.flat_beam_offset_per_beam > 0)) {
       // Set the offset for the group based on the calculations above.
       this.render_options.flat_beam_offset = offset;
-    } else if (stem_direction === Stem.DOWN && offset > flat_beam_offset) {
-      this.render_options.flat_beam_offset = offset;
-    } else if (stem_direction === Stem.UP && offset < flat_beam_offset) {
-      this.render_options.flat_beam_offset = offset;
+    } else if (stem_direction === Stem.DOWN && offset > flat_beam_offset && !this.render_options.flat_beams) {
+       this.render_options.flat_beam_offset = offset;
+    } else if (stem_direction === Stem.UP && offset < flat_beam_offset && !this.render_options.flat_beams) {
+       this.render_options.flat_beam_offset = offset;
     }
 
     // for flat beams, the slope and y_shift are simply 0
@@ -611,8 +611,19 @@ export class Beam extends Element {
 
     // For flat beams, set the first and last Y to the offset, rather than
     //  using the note's stem extents.
-    if (this.render_options.flat_beams && this.render_options.flat_beam_offset) {
-      beamY = this.render_options.flat_beam_offset;
+    if (this.render_options.flat_beams && this.render_options.flat_beam_offset + this.render_options.flat_beam_offset_per_beam > 0) {
+        let offset = this.render_options.flat_beam_offset;
+        if (this.render_options.flat_beam_offset_per_beam) {
+            offset += this.render_options.flat_beam_offset_per_beam * this.getBeamCount();
+        }
+        let maxY = this.notes[0].note_heads[0].y;
+        const minOrMax = this.stem_direction > 0 ? Math.min : Math.max;
+        for (const note of this.notes) {
+            for (const note_head of note.note_heads) {
+                maxY = minOrMax(maxY, note_head.y);
+            }
+        }
+      beamY = maxY + (offset * -this.stem_direction);
     }
     return beamY;
   }
```

**Comment by rvilarl** [comment]
@sschmidTU  `flat_beam_offset` is not new. `flat_beam_offset_per_beam` is new. How can I reproduce the issue above with **Siebener Endstreich**?

**Comment by sschmidTU** [comment]
@rvilarl yes. set `flat_beam_offset_per_beam` to 10 (fixed) or 0 (collisions).

**Comment by rvilarl** [comment]
@sschmidTU where do I set that I am not familiar with the OSMD test system. I have located the file but I do not know where to set `flat_beam_offset_per_beam`

**Comment by rvilarl** [comment]
@sschmidTU this patch makes the tests fail. I have looked into the handling of Beams in `VexFlowMeasure` and it is messy. I believe that the problem is there, the need for the `finalizeBeams` is also quite cuestionable, it is even stated in the comment:
```
// The following line resets the created Vex.Flow Beams and
// created them brand new. Is this needed? And more importantly,
// should the old beams be removed manually by the notes?
``` 
See how the patch breaks the tests in Vexflow (some examples):
![Auto_Beaming Flat_Beams_Down Bravura_Current](https://user-images.githubusercontent.com/22865285/147968166-7313c3ed-6e74-4609-8e88-907ed5a04502.png)
![Auto_Beaming Flat_Beams_Down_Bounds Bravura_Current](https://user-images.githubusercontent.com/22865285/147968185-8e70f52a-84a8-4aa9-aacb-b4f4090a1a98.png)
![Auto_Beaming Flat_Beams_Down__uniform_ Bravura_Current](https://user-images.githubusercontent.com/22865285/147968228-a446515f-a918-4323-a7d0-33cc2108910c.png)
![Auto_Beaming Flat_Beams_Mixed_Direction Bravura_Current](https://user-images.githubusercontent.com/22865285/147968268-1b6ea64f-d91c-4a20-9770-6c8f4172ee4f.png)

![Auto_Beaming Flat_Beams_Up_Bounds Bravura_Current](https://user-images.githubusercontent.com/22865285/147968371-46783249-8dd8-4357-b450-14ecf8a2f9e5.png)

**Comment by rvilarl** [comment]
@sschmidTU I modified OSMD to use `generateBeams` and the result below. In any case seems to be a OSMD issue, I cloe it here.

![test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1](https://user-images.githubusercontent.com/22865285/148027731-4dc780f4-a0a3-4e76-add4-c5a3de768545.png)

**Comment by sschmidTU** [comment]
@rvilarl The settings in the original patch are completely optional, so I don't see how it should break any tests.
It looks like you made a mistake while porting it to Vexflow 4.
Here's the diff:
```diff
diff --git a/src/beam.js b/src/beam.js
index fca6bf4d..34cc4f72 100644
--- a/src/beam.js
+++ b/src/beam.js
@@ -590,13 +590,13 @@ export class Beam extends Element {
       offset = extremeY - extremeTest;
     }
 
-    if (!flat_beam_offset) {
+    if (!(flat_beam_offset + this.render_options.flat_beam_offset_per_beam > 0)) {
       // Set the offset for the group based on the calculations above.
       this.render_options.flat_beam_offset = offset;
-    } else if (stem_direction === Stem.DOWN && offset > flat_beam_offset) {
-      this.render_options.flat_beam_offset = offset;
-    } else if (stem_direction === Stem.UP && offset < flat_beam_offset) {
-      this.render_options.flat_beam_offset = offset;
+    } else if (stem_direction === Stem.DOWN && offset > flat_beam_offset && !this.render_options.flat_beams) {
+       this.render_options.flat_beam_offset = offset;
+    } else if (stem_direction === Stem.UP && offset < flat_beam_offset && !this.render_options.flat_beams) {
+       this.render_options.flat_beam_offset = offset;
     }
 
     // for flat beams, the slope and y_shift are simply 0
@@ -611,8 +611,19 @@ export class Beam extends Element {
 
     // For flat beams, set the first and last Y to the offset, rather than
     //  using the note's stem extents.
-    if (this.render_options.flat_beams && this.render_options.flat_beam_offset) {
-      beamY = this.render_options.flat_beam_offset;
+    if (this.render_options.flat_beams && this.render_options.flat_beam_offset + this.render_options.flat_beam_offset_per_beam > 0) {
+        let offset = this.render_options.flat_beam_offset;
+        if (this.render_options.flat_beam_offset_per_beam) {
+            offset += this.render_options.flat_beam_offset_per_beam * this.getBeamCount();
+        }
+        let maxY = this.notes[0].note_heads[0].y;
+        const minOrMax = this.stem_direction > 0 ? Math.min : Math.max;
+        for (const note of this.notes) {
+            for (const note_head of note.note_heads) {
+                maxY = minOrMax(maxY, note_head.y);
+            }
+        }
+      beamY = maxY + (offset * -this.stem_direction);
     }
     return beamY;
   }
```

It looks to me like this should be reopened.

I'm guessing your alternative doesn't offer the *optional* offset per beam arguments etc.

**Comment by sschmidTU** [comment]
> @sschmidTU I modified OSMD to use `generateBeams` and the result below. In any case seems to be a OSMD issue, I cloe it here.
> 
> ![test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1](https://user-images.githubusercontent.com/22865285/148027731-4dc780f4-a0a3-4e76-add4-c5a3de768545.png)

These stems are way too long.

If you want to close this issue, you should be able to replicate this:

> flat_beams are optional, you have to set the setting: `osmd.EngravingRules.FlatBeams = true` ![image](https://user-images.githubusercontent.com/33069673/146456824-744d0d76-067e-4ace-af9a-cb69b0539bb0.png)
> 
> with false: ![image](https://user-images.githubusercontent.com/33069673/146456895-4da82dbc-1d19-41b5-8289-0bd79d204466.png)

**Comment by rvilarl** [comment]
@sschmidTU I close this issue here because I believe that it is a OSMD issue and does not belong to VexFlow. The flat tests in VexFlow work fine.
If I happen to be wrong I will reopen the issue to propose a VexFlow fix.

**Comment by sschmidTU** [comment]
> ![test_drum_tuplet_flat_beams_Siebener_Endstreich_testFlam musicxml_1](https://user-images.githubusercontent.com/22865285/148027731-4dc780f4-a0a3-4e76-add4-c5a3de768545.png)

@rvilarl This is not fine. The stems are way too long.
Also, without the offset you'll probably get issues like this with 32nd and 64th notes:


> Without a 10 pixel offset to the notes, flat beams overlap notes (Vexflow 1.2.93):
> ![image](https://user-images.githubusercontent.com/33069673/146526781-47da11e0-25ae-4764-aade-43c05e53e3ae.png)
