### ISSUE TITLE
OSMD VexflowPatch: StaveNote

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1254]
Fix stem/flag formatting. Instead of shifting notes by default, update the stem/flag rendering to render different voices aligned.
Only offset if a note is the same voice, same note.

**Comment by sschmidTU** [comment]
This is mostly just required for the StemmableNote fix (#414) to share noteheads.
The other change is not shifting notes x-wise if they are in different voices.
So for example, an A/4 in voice 1 and an A/5 in voice 2 will be at the same x position.

Here's a diff:
[stavenote_diff.zip](https://github.com/0xfe/vexflow/files/7730838/stavenote_diff.zip)

In general, you can create diffs for all the OSMD VexFlowPatch files by diffing them to Vexflow 1.2.93.
