### ISSUE TITLE
OSMD VexflowPatch: StaveRepetition

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1255]
add TO_CODA enum to type() and draw()
fix x-positioning for TO_CODA and DS_AL_CODA in drawSymbolText()
fix y-shift

**Comment by sschmidTU** [comment]
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/920

Patch:
![image](https://user-images.githubusercontent.com/33069673/146459044-0fb470f0-a3cd-4cbf-84c0-8f33444a9e57.png)

Vexflow 4:
![image](https://user-images.githubusercontent.com/33069673/146459089-fa1f2fea-4e01-410a-8305-0fa07dc13676.png)

[test_staverepetitions_coda_etc_positioning.zip](https://github.com/0xfe/vexflow/files/7730800/test_staverepetitions_coda_etc_positioning.zip)

**Comment by rvilarl** [comment]
@sschmidTU I have made a prerelease including all the pending PRs for Vexflow Patches and this one is resolved. Could you look into other issues if any?

![test_staverepetitions_coda_etc_positioning musicxml_1](https://user-images.githubusercontent.com/22865285/147958182-a5f696ad-dab7-4276-8aa8-3cc62a11cc27.png)

**Comment by sschmidTU** [comment]
Where is this prerelease? How should i test it?

**Comment by rvilarl** [comment]
I packed it in my PR in OSMD under redist/ as a tgz file.
