### ISSUE TITLE
OSMD VexflowPatch: StaveSection

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1256]
stavesection.draw():
adjust rectangle positioning, make height depend on text height

**Comment by sschmidTU** [comment]
Patch:
![image](https://user-images.githubusercontent.com/33069673/146458533-813b256e-1402-490e-a24e-ee0c43fd4f1a.png)

Vexflow 4:
![image](https://user-images.githubusercontent.com/33069673/146458546-668b8dfe-d402-437f-95a7-d1a7654a4b3a.png)

Patch:
![image](https://user-images.githubusercontent.com/33069673/146458666-2b731661-0372-4204-8ebd-8a3993309283.png)

Vexflow 4:
![image](https://user-images.githubusercontent.com/33069673/146458606-6503263b-3ad9-4979-a152-bd101bbb0929.png)

[test_rehearsal_marks_2_samples.zip](https://github.com/0xfe/vexflow/files/7730789/test_rehearsal_marks_2_samples.zip)
