### ISSUE TITLE
OSMD VexflowPatch: StemmableNote

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1257]
Add manual flag rendering variable so we can choose not to render flags if notes are sharing a stem.

**Comment by sschmidTU** [comment]
patched:
![image](https://user-images.githubusercontent.com/33069673/146457727-8c0762b2-2eb0-4b4d-a67d-fd85c987e68a.png)

vexflow 4:
![image](https://user-images.githubusercontent.com/33069673/146457749-c08051f6-3d29-4b18-8250-40dc9f414046.png)
[shared_stems.musicxml.zip](https://github.com/0xfe/vexflow/files/7730761/shared_stems.musicxml.zip)

**Comment by 0xfe** [comment]
I like this change, seems like it might be straightforward for the common cases -- we should pull this in.
