### ISSUE TITLE
OSMD VeflowPatch: Tremolo

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1258]
Add extra_stroke_scale, y_spacing_scale

**Comment by rvilarl** [comment]
@sschmidTU what is the intended feature. In OSMD there is only one test dedicated to Tremolo and there is not really a difference between blessed and current.

**Blessed**
![OSMD_Function_Test_Tremolo_2bars musicxml_1](https://user-images.githubusercontent.com/22865285/146452140-5d5c6170-c0e8-482b-b6b7-f70c0ee3b66f.png)
**Current**
![OSMD_Function_Test_Tremolo_2bars musicxml_1](https://user-images.githubusercontent.com/22865285/146452178-8c8100d5-2abd-425b-b3a3-86afe1639adc.png)

**Comment by sschmidTU** [comment]
It's optional stroke scaling (making the strokes bigger), and y spacing of the strokes, which needs to increase when the strokes get bigger. See here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/887#issuecomment-695809315

**Comment by rvilarl** [comment]
@sschmidTU I have made the following change:
```diff
     x += musicFont.lookupMetric(`${category}.offsetXStem${stemDirection === Stem.UP ? 'Up' : 'Down'}`);
+
+    // Scaling for bigger strokes
+    y_spacing = y_spacing * this.y_spacing_scale;
+    fontScale = fontScale * this.extra_stroke_scale;
+
     for (let i = 0; i < this.num; ++i) {
       Glyph.renderGlyph(ctx, x, y, fontScale, this.code, { category });
       y += y_spacing
    }
```
And created a new "tremolo big" test based on the "tremolo basic" using your proposed values 1.7 and 1.5. Do you get the same bug with stems up in OSMD?

**Tremolo Tremolo___Basic**
![Tremolo Tremolo___Basic Gonville](https://user-images.githubusercontent.com/22865285/146505757-a27b3db6-a1ec-44d1-a183-16ef41aa6830.png)

**Tremolo Tremolo___Big**
![Tremolo Tremolo___Big Gonville](https://user-images.githubusercontent.com/22865285/146505773-592b529c-920a-404e-97eb-0104391be10d.png)

**Comment by rvilarl** [comment]
@0xfe would you agree to get this additional settings in VexFlow once the bug is resolved?

**Comment by sschmidTU** [comment]
@rvilarl I'm not getting that y positioning bug with Vexflow 1.2.93, not sure what's happening there. See my comment above.
