### ISSUE TITLE
Annotation Test_Justification_Annotation_Stem_Up&Down Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1308]
Text overlapping notes

![Annotation Test_Justification_Annotation_Stem_Up Bravura](https://user-images.githubusercontent.com/22865285/151691581-13475fc0-c72e-491f-b81e-54d3e0cdb1e8.png)
![Annotation Test_Justification_Annotation_Stem_Down Bravura](https://user-images.githubusercontent.com/22865285/151691600-69065615-9dd2-494b-8b6c-d60fd34ced5b.png)

**Comment by rvilarl** [comment]
Already present in 3.0.9

![image](https://user-images.githubusercontent.com/22865285/151751240-ae1d5f45-48e4-467d-bbff-71c4b3824542.png)

**Comment by rvilarl** [comment]
@0xfe is this a bug or just expected behaviour?

**Comment by 0xfe** [comment]
Yes, expected. They're the full combination of positions and alignments, and some of them don't make sense.

**Comment by AaronDavidNewman** [comment]
If the text is centered and not top or bottom vertically, by definition it's going to collide with the note or stem.  So I think that's expected, although I don't know that it's a very useful test :)
