### ISSUE TITLE
SVG example needed!

### ISSUE THREAD

**Issue by nybbs2003** [0xfe/vexflow#131]
I need an example of how to use vexflow to display scores in svg.

**Comment by violetlight** [comment]
Following what @Silverwolf90 suggested worked for me, but as for the first argument, I can't tell what it uses the `<div>` for in place of the `<canvas>` selection you would be passing in when using HTML5 Canvas. 

If I select the `<div>` I would like the `<svg>` to be rendered inside with jQuery and pass that as the first argument, the stave is rendered, but not inside the `<div>` I passed in. The `<svg>` is a child of the `<body>`. If I select a `<p>` or `<img>` contrived for this purpose (or even if I do `$('body')`) and pass that in, it renders the `<svg>` the same. If I select an element that does not exist and pass that in (essentially passing in `null`), then it does not render anything. 

So it seems to need a valid selection of an element, but I am not sure what the best one to use is or what the Renderer uses the element for.
