### ISSUE TITLE
Style Basic_Style Petaluma Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1311]
Clef and note overlapping (Petaluma only)
![Style Basic_Style Petaluma](https://user-images.githubusercontent.com/22865285/151692086-196f19dc-0585-4034-882d-f2bd9eafe79e.png)

**Comment by 0xfe** [comment]
This also has the clef too far out, which might be a separate issue.

**Comment by rvilarl** [comment]
Problem already present in 3.0.9. The clef is not that far out, it should be a bit to the right between note 1 and note 2, like with Bravura:
![Style Basic_Style Bravura](https://user-images.githubusercontent.com/22865285/151720063-d750cd1e-6d98-4515-a83f-d108d42118e4.png)

**Comment by 0xfe** [comment]
Okay, so this is formatting problem with `ClefNote` not a `Clef`.
