### ISSUE TITLE
StaveNote StaveNote_BoundingBoxes___Treble Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1312]
Wrong bounding box with Bravura and Petaluma
![StaveNote StaveNote_BoundingBoxes___Treble Bravura](https://user-images.githubusercontent.com/22865285/151692197-e3943e3c-3310-471e-8cf1-910fccc472bd.png)
![StaveNote StaveNote_BoundingBoxes___Treble Petaluma](https://user-images.githubusercontent.com/22865285/151692202-447ccabf-6483-4a2a-9974-44010bd36550.png)

**Comment by 0xfe** [comment]
This one is weird -- it seems like flags aren't included in the calculations.

**Comment by rvilarl** [comment]
That was already present in 3.0.9

![image](https://user-images.githubusercontent.com/22865285/151748333-a04a2215-cc5e-46b0-b6db-7dd15f274a8d.png)

**Comment by rvilarl** [comment]
> This one is weird -- it seems like flags aren't included in the calculations.

the problem was that the stem lengths were not calculated correctly. It is partly a regression, if we look in detail at the bounding boxes of 3.0.9 they were right and they are based on the stem length.
