### ISSUE TITLE
Stave Multiple_Staves_Volta_Test Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1313]
Segno and section overlapping
![Stave Multiple_Staves_Volta_Test Bravura](https://user-images.githubusercontent.com/22865285/151692307-98971be6-f3d5-4f9e-8569-7b5452dcde3d.png)

**Comment by 0xfe** [comment]
This is also a regression.

**Comment by rvilarl** [comment]
This was fine in 3.0.9
![image](https://user-images.githubusercontent.com/22865285/151748024-557e2655-c034-462a-aeba-f18c8bde63bd.png)

**Comment by ronyeh** [comment]
[VexFlow 4](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=stave&filter=multiple%20staves%20volta)

[VexFlow 3.0.9](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=stave&filter=multiple%20staves%20volta&ver=unpkg@3.0.9)
