### ISSUE TITLE
Ornament With_Upper_Lower_Accidentals Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1314]
Segno and accidentals overlapping.
![Ornament With_Upper_Lower_Accidentals Bravura](https://user-images.githubusercontent.com/22865285/151692410-7c8cf098-e3e3-45b1-9896-7bfa3b6c6dea.png)

**Comment by rvilarl** [comment]
This one was fine in 3.0.9, interesting the duplication of segnos
![image](https://user-images.githubusercontent.com/22865285/151720428-509086e8-0ce1-4768-8ad5-b2783e817b1e.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman that might be related with vertical positioning also.

**Comment by AaronDavidNewman** [comment]
Huh...maybe?  But I didn't change anything with ornament.   And the double helix thing, looks like an issue with the test case, maybe a merge issue.  Or maybe something with the glyph itself.  I'll check when I'm done working.

Also, this should have shown up on the visual regressions.  I think it either happened very recently, or longer ago.

**Comment by rvilarl** [comment]
Probably long ago. Do you want me to check when?

**Comment by AaronDavidNewman** [comment]
Just look at the test case.

``` typescript
  notes[1].addModifier(new Ornament('turn_inverted').setLowerAccidental('b').setUpperAccidental('b'), 0);
  notes[1].addModifier(new Ornament('turn_inverted').setLowerAccidental('b').setUpperAccidental('b'), 0);
```

It looks like that line was duplicated during a merge.
