### ISSUE TITLE
Accidental Multi_Voice Test - Visual Error

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1316]
Accidentals too far from notes on third group
![Accidental Multi_Voice Gonville](https://user-images.githubusercontent.com/22865285/151693423-9c421636-f888-49bc-9328-f988a163618b.png)

**Comment by 0xfe** [comment]
This looks like a recent regression.

**Comment by rvilarl** [comment]
The problem was already there in 3.0.9

**Comment by ronyeh** [comment]
WIth the most recent release (4.0.1-alpha.2), we can now look at the flow.html page on unpkg.com.

Version 4.0.1-alpha.2
https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=accidental&filter=multi

Version 3.0.9
https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=accidental&filter=multi&ver=unpkg@3.0.9

Notice in the above link that we are using the flow.html from VexFlow 4, but it loads the 3.0.9 library and tests (specified by the ver=unpkg@3.0.9).

We can also load the 3.0.9 library from the jsdelivr CDN:

https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=accidental&filter=multi&ver=jsdelivr@3.0.9


Note that unpkg.com swallows query strings (e.g., `?a=b&hello=world`), so we have to use the hash symbol to forward params to the page (e.g., `#module=accidental&filter=multi`).


Anyways.... TLDR: the test pages above show that this error is not a regression.
You can open the [VexFlow 4 page](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=accidental&filter=multi) and the [3.0.9 page](https://unpkg.com/vexflow@4.0.1-alpha.2/tests/flow.html#module=accidental&filter=multi&ver=unpkg@3.0.9) in different tabs and flip between the tabs quickly to spot visual changes.

**Comment by rvilarl** [comment]
Wow Ron, this way of looking differences is very convenient!
