### ISSUE TITLE
patch-package not found while trying to install 4.0.1-alpha.1

### ISSUE THREAD

**Issue by SmallHollow** [0xfe/vexflow#1318]
`npm install vexflow@alpha` (on npm 8.1.2) results in `patch-package: command not found`. Previous version (`alpha.0`) installs fine.

**Comment by ronyeh** [comment]
Thanks for your bug report. I'll look into it asap!

**Comment by ronyeh** [comment]
Whoops, this was my fault. I added a `"postinstall": "patch-package"` script to the package.json which fixes one of our dependencies, but this script is only useful for VexFlow maintainers. Unfortunately it broke the npm install process.

I'll fix this in the next release. For now, this still works `npm install vexflow@4.0.1-alpha.0`

Or if you really want to use the bleeding edge, you can clone from the repo and then do a npm install from your local clone.

**Comment by rvilarl** [comment]
> npm install vexflow@4.0.1-alpha.0

Thanks Ron! The workaround works.

**Comment by ronyeh** [comment]
I added a PR which should fix this one. The PR improves the release process, but also removes the "postinstall" script which was breaking your npm install. Instead, I moved `npx patch-package` into the release script, since the patch doesn't affect anyone other than a maintainer who's trying to release to GitHub.

**Comment by ronyeh** [comment]
Hopefully it works now. I tested on my example project with `npm install vexflow@alpha` and now my package.json shows:
```
    "dependencies": {
        ...
        "vexflow": "^4.0.1-alpha.2"
    },

```

**Comment by SmallHollow** [comment]
Working fine now!

**Comment by ronyeh** [comment]
Thanks for reporting the issue!

We are currently working on comparing VexFlow 4 to 3.0.9 to check for any possible visual layout regressions. If you find any issues with your projects, please file more bugs.

We're trying to move toward a beta / rc release, before shipping VexFlow 4 officially.
