### ISSUE TITLE
Jianpu(Numberic) Notation support needed!

### ISSUE THREAD

**Issue by nybbs2003** [0xfe/vexflow#132]
http://en.wikipedia.org/wiki/Numbered_musical_notation
http://lists.gnu.org/archive/html/lilypond-user/2012-11/msg00083.html
http://people.ds.cam.ac.uk/ssb22/mwrhome/jianpu-ly.html

**Comment by imiskolee** [comment]
I am starting working on it:

![微信图片_20200909011928](https://user-images.githubusercontent.com/4303880/92508077-97fa2700-f23a-11ea-8614-3007458cc8a6.png)

please join us if you are also inestered it.

**Comment by yasz** [comment]
> I am starting working on it:
> 
> ![微信图片_20200909011928](https://user-images.githubusercontent.com/4303880/92508077-97fa2700-f23a-11ea-8614-3007458cc8a6.png)
> 
> please join us if you are also inestered it.

can u push this features now?

**Comment by imiskolee** [comment]
@yasz it's not finished, and you can check it on our branch now: https://github.com/noise-labs/vexflow/tree/numbered-music-notation-supports
