### ISSUE TITLE
addDot() and addDotToAll()

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1355]
These methods were removed during our squashing of circular dependencies.

While fixing wiki tutorials / JSFiddles and porting over Music21j, I realized not having the method is a bit of a pain.

Perhaps we can revisit a way to add this utility method back again? Perhaps it should be a static method on the Dot class?

However, in 3.0.9 the method was chainable with other methods on StaveNote, which led to a very consistent feel of the API.

## **Question for the music experts:**

How often do you have a note group where some of the notes are dotted, but others are not? Don't we normally want to add a dot to all notes within a particular StaveNote object?

See [this image that I found in the tutorial](https://camo.githubusercontent.com/ccde0b458549e3bf372d9fc5f4928d37175482538b5adbc004590e474655d83c/687474703a2f2f696d6775722e636f6d2f3377564c5278782e706e67
):
<img src="https://camo.githubusercontent.com/ccde0b458549e3bf372d9fc5f4928d37175482538b5adbc004590e474655d83c/687474703a2f2f696d6775722e636f6d2f3377564c5278782e706e67">

The third `StaveNote` only has one dot on the bottom note (at index 0). Is this an uncommon case?

**Comment by rvilarl** [comment]
I believe that this not possible with one voice, like in the example above. With two voices this would be possible but the two notes would be independent (not presented like a chord above).
`addDot()` and `addDotToAll()` were removed to remove circular dependencies. They were replaced by `Dot.buildAndAttach(...)` proposed by Mohit

**Comment by mscuthbert** [comment]
I add dots to noteheads individually sometimes so that I can have them fade in at different times in animations, or to create examples of, "What is wrong with this notation" -- but that's not a major use case for the system.  But yes, music21j will need to be updated to no longer use the code.

**Comment by ronyeh** [comment]
For my Music21j PR, I replaced addDotToAll with a new utility function
(since I forgot that Dot.buildAndAttach(...) existed). We could change it
to use Dot.buildAndAttach(...) instead, if that is more convenient.

**Comment by rvilarl** [comment]
Dot.buildAndAttach(...) also supports setting the number of dots independently
