### ISSUE TITLE
OSMD: Squeezed notes in implicit/precount measure

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1359]
>   Squeezed notes in implicit/precount measure in Mozart - Clarinet Quintet (measure 0/1):
>   ![image](https://user-images.githubusercontent.com/33069673/153035016-719b06b6-3220-462e-9d78-b703363b9836.png)
>   develop:
>   ![image](https://user-images.githubusercontent.com/33069673/153035086-eed71386-98d2-406e-b0b5-4c933d90bd8f.png)
>   It looks like Vexflow thinks the measure end is much sooner than it really is.
> 
> also in Mozart - An Chloe (measure 0/1), though less pronounced: ![image](https://user-images.githubusercontent.com/33069673/153034590-4102da40-a33b-48e8-82c6-0a71eb497cee.png) develop: ![image](https://user-images.githubusercontent.com/33069673/153034635-9151adfb-2407-4ffa-bf08-b1368bbd4b50.png)

**Comment by rvilarl** [comment]
@sschmidTU I believe that the first issue (Clarinet Quintet) is related to #1389. The second one is a generic problem like in #1362. What do you think?

**Comment by AaronDavidNewman** [comment]
> I believe that the first issue (Clarinet Quintet) is related to https://github.com/0xfe/vexflow/issues/1389.

I agree, Smoosic has the same issue probably because of the key signatures.

> The second one is a generic problem like in https://github.com/0xfe/vexflow/issues/1362

Smoosic doesn't have an issue with that one using the latest vexflow.  It may have been addressed with the right padding changes.

![image](https://user-images.githubusercontent.com/5438280/168638846-a785f9dd-c901-425f-a711-9e74616f644c.png)
