### ISSUE TITLE
OSMD: String numbers colliding

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1364]
> * [ ]  String numbers colliding vertically in test_grace_note_fingerings_and_strings
>   ![image](https://user-images.githubusercontent.com/33069673/153038369-a075fbf0-c25d-4c41-ba9c-5929eda5badc.png)

**Comment by rvilarl** [comment]
@sschmidTU without the OSMD manipulations of stringNumber, radius and offsets the result is fine. Is that fine with you? Why do you use roman numbers?

![test_grace_note_fingerings_and_strings](https://user-images.githubusercontent.com/22865285/166090876-f35c691b-9870-4d4f-8a23-b01a7c104ff9.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman there is some overlap though with beams when leaving the modifiers above on the grace notes

https://jsfiddle.net/f5wznar9/

**Comment by sschmidTU** [comment]
@rvilarl Roman numbers are the default for string instruments, because arabic numbers indicate the fingering (fingers used), roman numbers indicate which string to play on. (I, II, III or IV for violin/viola/cello/etc)

**Comment by rvilarl** [comment]
@sschmidTU I believe that the standard is Arabic with circle. Do you mean that without circle Roman numbers should be used?

**Comment by sschmidTU** [comment]
@sschmidTU For violin/viola/cello, arabic without circles is the only version for string numbers I've seen and seems to be the standard. Maybe it differs from America to Europe or something, but I don't think so.
(ignore the red circle for fingerings, I just did a quick search)
![image](https://user-images.githubusercontent.com/33069673/169365819-c9fe57f2-0607-4cd9-b518-ae7fa06aa06a.png)

![image](https://user-images.githubusercontent.com/33069673/169365841-9057d9fa-60eb-4c0b-84c9-8c2e9bf44a91.png)
