### ISSUE TITLE
OSMD: Rest position

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1368]
> * [ ]  Rest position way too far left in test_sorted_notes_chord
>   ![image](https://user-images.githubusercontent.com/33069673/153039298-56dfb2e8-6ed0-440e-946a-d72cd0e61189.png)
>   There is a general issue with rests positioned too far left apparently, also in other samples.
>

**Comment by rvilarl** [comment]
@sschmidTU I see no problem with this file using Vexlflow directly. I do not understand thougth where the time signature in OSMD is coming from, it is not in the musicxml file.

https://jsfiddle.net/wempuknj/5/
![image](https://user-images.githubusercontent.com/22865285/162535619-de9188a9-ccfd-43e2-ad3d-c110fb1d911a.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman however I found a problem with the rest positions and another with the associated width

**with `width` (rests are not in the middle of the measure):**
https://jsfiddle.net/wempuknj/6/
![image](https://user-images.githubusercontent.com/22865285/162536138-e796c07a-ed06-448d-8fb7-4d71b6989cd7.png)

**without `width` (rests are not in the middle of the measure, and the measures with rest take too much width compare to the third one)**
https://jsfiddle.net/wempuknj/7/
![image](https://user-images.githubusercontent.com/22865285/162536492-fad52fcf-c500-466f-8426-437afb89efbb.png)

**Comment by AaronDavidNewman** [comment]
You need to:
`note = (score.notes('B4/w/r', {})[0]).setCenterAlignment(true);`
