### ISSUE TITLE
VexFlow render guitar tab with beam, but I don't wanna render stem

### ISSUE THREAD

**Issue by yunfengsa** [0xfe/vexflow#1374]
My code is 

```

const div = document.getElementById('mContainer');
        const renderer = new Renderer(div, Renderer.Backends.SVG);
        renderer.resize(380, 300);
        const context = renderer.getContext();

        const stave = new TabStave(0, 40, 320);
        stave.setContext(context).draw();
        const noteData = [
            // { keys: ['f/4'], duration: 'q' },
            { keys: ['f/4'], duration: '8' },
            { keys: ['e/4'], duration: '8' },
            { keys: ['d/4'], duration: '8' },
            { keys: ['c/4'], duration: '16' },
            { keys: ['c/4'], duration: '16' },
            { keys: ['c/5'], duration: '8' },
            { keys: ['b/4'], duration: '8' },
            { keys: ['c/5'], duration: '8' },
            { keys: ['c/5'], duration: '32' },
            { keys: ['c/5'], duration: '32' },
            { keys: ['b/4'], duration: '32' },
            { keys: ['f/4'], duration: '32' }
        ];

        function createNote(data) {
            const tabNode = new TabNote({
                ...data,
                positions: [{ str: 2, fret: 'x' }],
            }, true);
            // tabNode.render_options.draw_stem_through_stave = true;
            return tabNode;
        }

        // const formatter = new Formatter();
        const notes = noteData.map(createNote);
        const voice = new Voice({
            num_beats: 4,
            beat_value: 4,
        }).addTickables(notes);
        new Formatter().joinVoices([voice]).format([voice], 300);
        voice.draw(context, stave);
        const beams = Beam.generateBeams(notes, {
            stem_direction: Stem.DOWN,
        });
        beams.forEach((b) => {
            b.setContext(context).draw();
        });

```

the Result is 
![image](https://user-images.githubusercontent.com/10361986/163543165-b9eab149-26dc-4d90-a0ec-3ef84e07a117.png)

But I don't want to render the highlight part

![image](https://user-images.githubusercontent.com/10361986/163543220-c78ab529-0881-43e2-be7e-fb3c0fb1d7bc.png)

If I close render stem

```

const tabNode = new TabNote({
                ...data,
                positions: [{ str: 2, fret: 'x' }],
            }, false);


```

the render result is false
![image](https://user-images.githubusercontent.com/10361986/163543488-96abe866-ca1e-4c26-b2e8-4e3bf27dfdb8.png)

so how can i correct it?

**Comment by rvilarl** [comment]
Tabnote stems up is currently providing this output. @0xfe @mscuthbert might it be that an error was introduced?

![TabNote TabNote_Stems_Up Bravura](https://user-images.githubusercontent.com/22865285/163586905-879ae3a6-9ac2-47ea-9120-711cb9d2ae6b.png)

**Comment by Akellaz** [comment]
Please, help me beaming this notes!

<script src="https://cdn.jsdelivr.net/npm/vexflow@5.0.0/build/cjs/vexflow.min.js"></script>
<script type="text/javascript">

document.addEventListener("DOMContentLoaded", function(event) {
  const div = document.getElementById("container");

  const renderer = new VexFlow.Renderer(div, VexFlow.Renderer.Backends.SVG);
  renderer.resize(600, 200);

  const stave = new VexFlow.Stave(30, 40, 500);
  stave.addClef("percussion");
  stave.setContext(renderer.getContext());
  stave.draw();

  const notes = [
    new VexFlow.StaveNote({
      keys: ['f/5/x', 'd/4/n'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x'],
      duration: '8'
    }),

    new VexFlow.StaveNote({
      keys: ['f/5/x', 'c/5/n'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x', 'd/4/n'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x', 'c/5/n'],
      duration: '8'
    }),
    new VexFlow.StaveNote({
      keys: ['f/5/x'],
      duration: '16'
    }),
	  new VexFlow.StaveNote({
      keys: ['f/5/x'],
      duration: '16'
    }),

  ];

  const voice = new VexFlow.Voice({ beats: 4, beatType: 4 });
  voice.addTickables(notes);

  const formatter = new VexFlow.Formatter();
  formatter.joinVoices([voice]);
  formatter.formatToStave([voice], stave);

  voice.draw(renderer.getContext(), stave);

});

<img width="649" height="239" alt="Image" src="https://github.com/user-attachments/assets/0ead5ddd-b42f-46b9-ba0d-c06be44bed22" />
