### ISSUE TITLE
Alignment between staffs with different key signature. (unofficial musicxml test suite 72a)

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1389]
The time signatures and the notes should be aligned but they are not.

https://jsfiddle.net/Lahcqngb/

![image](https://user-images.githubusercontent.com/22865285/168122566-ec2c09f7-c24f-4069-a70f-b004628f14fa.png)

@AaronDavidNewman @sschmidTU @ronyeh any idea? This problem is also present in the version 1.2.93 used in OSMD.

**Comment by AaronDavidNewman** [comment]
Smoosic has the same issue.  I had always assumed it is the responsibility of the application to set the startX of the staff, just like the application is responsible for setting the width of the staff to compensate for the accidentals in the first place.   

When the formatting/justification is done by vexflow, the width of the notes is supplied but nothing about start X is known, in fact it is not even required that the measure is associated with a staff.

It _is_ unintuitive to have the voices justified vertically for formatting but then they don't line up, but I don't see an automated solution that works with all the existing formatting interfaces.

**Comment by rvilarl** [comment]
Thanks Aaron, and how do you do it manually? Could you adapt the fiddle? The problem is not only that the notes should aligned, but also the time signatures.

**Comment by AaronDavidNewman** [comment]
something like:

``` javascript
staves.get('P1_1').setNoteStartX(120);
formatter.format(voicesArr, 200);
factory.draw();
```

that moves the start bar line also, so...not sure about that.  I haven't addressed this in Smoosic yet.

**Comment by sschmidTU** [comment]
Iirc OSMD solves this by always printing a clef, but making it invisible (alpha 0) when it shouldn't be shown.
We didn't know how to solve this issue either.
Setting the startX of the staff is an interesting idea, as Aaron mentioned.

**Comment by sschmidTU** [comment]
This is not solved in OSMD, right?
For clefs, OSMD solves this by always printing a time signature, but making it invisible (alpha 0) when it shouldn't be shown.
That's not ideal, but we didn't know how else to solve this issue either.
Setting the startX of the staff is an interesting idea, as Aaron mentioned.
I think OSMD hasn't done the same for key signatures yet, even though it should at least go for the same workaround.

**Comment by AaronDavidNewman** [comment]
> I think OSMD hasn't done the same for key signatures yet, even though it should at least go for the same workaround.

I think the invisible key signature is more problematic because the measure may have a differently-sized key signature like in Rodrigo's example.

I'm not sure why you'd ever want the start bar line to be anywhere other than the right side of the measure, that part seems like a bug to me.  How could you tell if it was another measure end vs. start?  Maybe for special bar lines like start repeat, there are use cases.

But it doesn't seem like such a problem for aligning the voices.  If the voices are justified, I would usually use a system bracket for the staves and wouldn't use a start bar line.  If they weren't justified, the notes wouldn't be aligned anyway so I wouldn't bother aligning the start X.

**Comment by rvilarl** [comment]
@sschmidTU this is what you get with OSMD (development branch)
![72a-TransposingInstruments xml_1](https://user-images.githubusercontent.com/22865285/168158956-8f37bc17-5f08-4457-b9c6-d2b99df19bf7.png)

the right result is in (test 72a)

https://lilypond.org/doc/v2.20/input/regression/musicxml/collated-files#test-cases

**Comment by ronyeh** [comment]
Cool, thanks all for explaining the issue.

Should we treat this as a bug? Or is it a feature request for 4.1? If it's a Feature Request, what do you think the API should be to make all the voices aligned across the staves?

Or if it's a "bug" then perhaps the formatter needs to figure out a way to align the voices on different staves. It would need to know the key signatures and time signatures and how much horizontal space each takes. Then the formatter would have to take the MAX width of each, to ensure everything aligns.

**Comment by rvilarl** [comment]
I think that we should treat that as a  bug. Specially the fact that `setNoteStartX` also moves the start bar line as described by Aaron above.

> something like:
> 
> ```js
> staves.get('P1_1').setNoteStartX(120);
> formatter.format(voicesArr, 200);
> factory.draw();
> ```
> 
> that moves the start bar line also, so...not sure about that. I haven't addressed this in Smoosic yet.

This movement is only required by one test **Strokes Strokes___Notation_and_Tab**
 
![Strokes Strokes___Notation_and_Tab Bravura](https://user-images.githubusercontent.com/22865285/168410538-ed2b1412-4b5e-4201-ad09-ae912844aafb.png)

However I believe that this movement is nor required, according to what I found in internet, this looks better to me (@mscuthbert what  do you think)

![pptr-canvas_Strokes Strokes___Notation_and_Tab Bravura_current](https://user-images.githubusercontent.com/22865285/168410598-55e6ce60-993f-4ed7-bf4d-c2eb02bb5da9.png)
