### ISSUE TITLE
Leland font

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1391]
@AaronDavidNewman I believe that the only difference between vexflow_smoosic and vexflow is the support to leland font. Would you like to include it here and use vexflow directly?

**Comment by ronyeh** [comment]
Hey, I can advise on this PR, since I worked on adding font plugin support to VexFlow 4. (Or maybe Aaron is the actual expert now since he's actually done it with his fork.)

What is the goal of this PR? I assume we do not want to make the default VexFlow bigger....

Is the goal to include Leland as a run-time plugin? Or just include an example in the repo to illustrate how to add a SMuFL font such as Leland?

**Comment by ronyeh** [comment]
When I last tried integrating Leland, it seemed like the most work was tweaking the metric files by hand since each glyph can have a size and offset tweak. Some of the metric fields are actually required (nothing is rendered if they are omitted)... but we don't actually document this anywhere.

**Comment by rvilarl** [comment]
> What is the goal of this PR? I assume we do not want to make the default VexFlow bigger....
I would suggest to make a Leland only variant and not to include it in the default.

> Is the goal to include Leland as a run-time plugin? Or just include an example in the repo to illustrate how to add a SMuFL font such as Leland?
Just the variant perhaps.

**Comment by rvilarl** [comment]
> When I last tried integrating Leland, it seemed like the most work was tweaking the metric files by hand since each glyph can have a size and offset tweak. Some of the metric fields are actually required (nothing is rendered if they are omitted)... but we don't actually document this anywhere.

The metrics file is already available in vexflow_smoosic

**Comment by ronyeh** [comment]
I think we should start small and just add Leland directly to our repo. We can follow Rodrigo's suggestion re: adding a Leland-only variant, but not including it in our main bundle due to library size.

Whoever wants to tackle this, I would suggest copying the approach we use to produce the `vexflow-petaluma.js` file. You can search for "vexflow-petaluma" in the code base.

We don't need to add Leland to the main tests yet. Instead, we can duplicate `demos/fonts/petaluma.html` and make it work for `vexflow-leland.js`.

The key is that `vexflow/entry/vexflow-petaluma.ts` produces the Petaluma-only library. So we'll need a `vexflow/entry/vexflow-leland.ts` that takes the same approach. We will also need to update the Gruntfile.js to add this target.

Line 349:
```
  function prodConfig(watch = false) {
    return getConfig([VEX, VEX_BRAVURA, VEX_GONVILLE, VEX_PETALUMA, VEX_CORE], PRODUCTION_MODE, BANNER, 'Vex', watch);
  }
```

Let me know if you guys get stuck and need help. If there are any gotchas we encounter, please add to this thread. We can collect any learnings and put it on the wiki.

**Comment by rvilarl** [comment]
@AaronDavidNewman this font is missing a lot of glyphs. When converting I get
No glyph for  barlineTick
No glyph for  breathMarkTick
No glyph for  timeSigPlusSmall
No glyph for  timeSigMinus
No glyph for  timeSigParensRight
No glyph for  timeSigParensRightSmall
No glyph for  timeSigParensLeft
No glyph for  timeSigParensLeftSmall
No glyph for  noteheadXWhole
No glyph for  noteheadXHalf
No glyph for  noteheadTriangleUpWhole
No glyph for  noteheadTriangleUpHalf
No glyph for  noteheadParenthesis
No glyph for  accidentalKomaSharp
No glyph for  accidentalKoron
No glyph for  accidentalSori
No glyph for  breathMarkUpbow
No glyph for  ornamentPrecompDoubleCadenceUpperPrefixTurn
No glyph for  brassScoop
No glyph for  brassDoitMedium
No glyph for  brassFallLipShort
No glyph for  brassLiftMedium
No glyph for  brassFallRoughMedium
No glyph for  brassBend
No glyph for  brassFlip
No glyph for  brassJazzTurn
No glyph for  brassSmear
No glyph for  pluckedLeftHandPizzicato
No glyph for  pictChokeCymbal
No glyph for  arrowheadBlackUp
No glyph for  arrowheadBlackDown
No glyph for  arpeggiatoUp
No glyph for  arpeggiatoDown
No glyph for  csymMinor
No glyph for  csymParensLeftTall
No glyph for  csymParensRightTall
No glyph for  csymBracketLeftTall
No glyph for  csymBracketRightTall
No glyph for  csymParensLeftVeryTall
No glyph for  csymParensRightVeryTall
No glyph for  csymDiagonalArrangementSlash
No glyph for  accSagittal5v7KleismaUp
No glyph for  accSagittal5v7KleismaDown
No glyph for  accSagittal5CommaUp
No glyph for  accSagittal5CommaDown
No glyph for  accSagittal7CommaUp
No glyph for  accSagittal7CommaDown
No glyph for  accSagittal25SmallDiesisUp
No glyph for  accSagittal25SmallDiesisDown
No glyph for  accSagittal35MediumDiesisUp
No glyph for  accSagittal35MediumDiesisDown
No glyph for  accSagittal11MediumDiesisUp
No glyph for  accSagittal11MediumDiesisDown
No glyph for  accSagittal11LargeDiesisUp
No glyph for  accSagittal11LargeDiesisDown
No glyph for  accSagittal35LargeDiesisUp
No glyph for  accSagittal35LargeDiesisDown
No glyph for  accSagittalSharp25SDown
No glyph for  accSagittalFlat25SUp
No glyph for  accSagittalSharp7CDown
No glyph for  accSagittalFlat7CUp
No glyph for  accSagittalSharp5CDown
No glyph for  accSagittalFlat5CUp
No glyph for  accSagittalSharp5v7kDown
No glyph for  accSagittalFlat5v7kUp
No glyph for  accSagittalSharp
No glyph for  accSagittalFlat
No glyph for  accSagittalSharp5v7kUp
No glyph for  accSagittalFlat5v7kDown
No glyph for  accSagittalSharp5CUp
No glyph for  accSagittalFlat5CDown
No glyph for  accSagittalSharp7CUp
No glyph for  accSagittalFlat7CDown
No glyph for  accSagittalSharp25SUp
No glyph for  accSagittalFlat25SDown
No glyph for  accSagittalSharp35MUp
No glyph for  accSagittalFlat35MDown
No glyph for  accSagittalSharp11MUp
No glyph for  accSagittalFlat11MDown
No glyph for  accSagittalSharp11LUp
No glyph for  accSagittalFlat11LDown
No glyph for  accSagittalSharp35LUp
No glyph for  accSagittalFlat35LDown
No glyph for  accSagittalDoubleSharp25SDown
No glyph for  accSagittalDoubleFlat25SUp
No glyph for  accSagittalDoubleSharp7CDown
No glyph for  accSagittalDoubleFlat7CUp
No glyph for  accSagittalDoubleSharp5CDown
No glyph for  accSagittalDoubleFlat5CUp
No glyph for  accSagittalDoubleSharp5v7kDown
No glyph for  accSagittalDoubleFlat5v7kUp
No glyph for  accSagittalDoubleSharp
No glyph for  accSagittalDoubleFlat
No glyph for  accSagittal7v11KleismaUp
No glyph for  accSagittal7v11KleismaDown
No glyph for  accSagittal17CommaUp
No glyph for  accSagittal17CommaDown
No glyph for  accSagittal55CommaUp
No glyph for  accSagittal55CommaDown
No glyph for  accSagittal7v11CommaUp
No glyph for  accSagittal7v11CommaDown
No glyph for  accSagittal5v11SmallDiesisUp
No glyph for  accSagittal5v11SmallDiesisDown
No glyph for  accSagittalSharp5v11SDown
No glyph for  accSagittalFlat5v11SUp
No glyph for  accSagittalSharp7v11CDown
No glyph for  accSagittalFlat7v11CUp
No glyph for  accSagittalSharp55CDown
No glyph for  accSagittalFlat55CUp
No glyph for  accSagittalSharp17CDown
No glyph for  accSagittalFlat17CUp
No glyph for  accSagittalSharp7v11kDown
No glyph for  accSagittalFlat7v11kUp
No glyph for  accSagittalSharp7v11kUp
No glyph for  accSagittalFlat7v11kDown
No glyph for  accSagittalSharp17CUp
No glyph for  accSagittalFlat17CDown
No glyph for  accSagittalSharp55CUp
No glyph for  accSagittalFlat55CDown
No glyph for  accSagittalSharp7v11CUp
No glyph for  accSagittalFlat7v11CDown
No glyph for  accSagittalSharp5v11SUp
No glyph for  accSagittalFlat5v11SDown
No glyph for  accSagittalDoubleSharp5v11SDown
No glyph for  accSagittalDoubleFlat5v11SUp
No glyph for  accSagittalDoubleSharp7v11CDown
No glyph for  accSagittalDoubleFlat7v11CUp
No glyph for  accSagittalDoubleSharp55CDown
No glyph for  accSagittalDoubleFlat55CUp
No glyph for  accSagittalDoubleSharp17CDown
No glyph for  accSagittalDoubleFlat17CUp
No glyph for  accSagittalDoubleSharp7v11kDown
No glyph for  accSagittalDoubleFlat7v11kUp
No glyph for  accSagittal23CommaUp
No glyph for  accSagittal23CommaDown
No glyph for  accSagittal5v19CommaUp
No glyph for  accSagittal5v19CommaDown
No glyph for  accSagittal5v23SmallDiesisUp
No glyph for  accSagittal5v23SmallDiesisDown
No glyph for  accSagittalSharp5v23SDown
No glyph for  accSagittalFlat5v23SUp
No glyph for  accSagittalSharp5v19CDown
No glyph for  accSagittalFlat5v19CUp
No glyph for  accSagittalSharp23CDown
No glyph for  accSagittalFlat23CUp
No glyph for  accSagittalSharp23CUp
No glyph for  accSagittalFlat23CDown
No glyph for  accSagittalSharp5v19CUp
No glyph for  accSagittalFlat5v19CDown
No glyph for  accSagittalSharp5v23SUp
No glyph for  accSagittalFlat5v23SDown
No glyph for  accSagittalDoubleSharp5v23SDown
No glyph for  accSagittalDoubleFlat5v23SUp
No glyph for  accSagittalDoubleSharp5v19CDown
No glyph for  accSagittalDoubleFlat5v19CUp
No glyph for  accSagittalDoubleSharp23CDown
No glyph for  accSagittalDoubleFlat23CUp
No glyph for  accSagittal19SchismaUp
No glyph for  accSagittal19SchismaDown
No glyph for  accSagittal17KleismaUp
No glyph for  accSagittal17KleismaDown
No glyph for  accSagittal143CommaUp
No glyph for  accSagittal143CommaDown
No glyph for  accSagittal11v49CommaUp
No glyph for  accSagittal11v49CommaDown
No glyph for  accSagittal19CommaUp
No glyph for  accSagittal19CommaDown
No glyph for  accSagittal7v19CommaUp
No glyph for  accSagittal7v19CommaDown
No glyph for  accSagittal49SmallDiesisUp
No glyph for  accSagittal49SmallDiesisDown
No glyph for  accSagittal23SmallDiesisUp
No glyph for  accSagittal23SmallDiesisDown
No glyph for  accSagittal5v13MediumDiesisUp
No glyph for  accSagittal5v13MediumDiesisDown
No glyph for  accSagittal11v19MediumDiesisUp
No glyph for  accSagittal11v19MediumDiesisDown
No glyph for  accSagittal49MediumDiesisUp
No glyph for  accSagittal49MediumDiesisDown
No glyph for  accSagittal5v49MediumDiesisUp
No glyph for  accSagittal5v49MediumDiesisDown
No glyph for  accSagittal49LargeDiesisUp
No glyph for  accSagittal49LargeDiesisDown
No glyph for  accSagittal11v19LargeDiesisUp
No glyph for  accSagittal11v19LargeDiesisDown
No glyph for  accSagittal5v13LargeDiesisUp
No glyph for  accSagittal5v13LargeDiesisDown
No glyph for  accSagittalSharp23SDown
No glyph for  accSagittalFlat23SUp
No glyph for  accSagittalSharp49SDown
No glyph for  accSagittalFlat49SUp
No glyph for  accSagittalSharp7v19CDown
No glyph for  accSagittalFlat7v19CUp
No glyph for  accSagittalSharp19CDown
No glyph for  accSagittalFlat19CUp
No glyph for  accSagittalSharp11v49CDown
No glyph for  accSagittalFlat11v49CUp
No glyph for  accSagittalSharp143CDown
No glyph for  accSagittalFlat143CUp
No glyph for  accSagittalSharp17kDown
No glyph for  accSagittalFlat17kUp
No glyph for  accSagittalSharp19sDown
No glyph for  accSagittalFlat19sUp
No glyph for  accSagittalSharp19sUp
No glyph for  accSagittalFlat19sDown
No glyph for  accSagittalSharp17kUp
No glyph for  accSagittalFlat17kDown
No glyph for  accSagittalSharp143CUp
No glyph for  accSagittalFlat143CDown
No glyph for  accSagittalSharp11v49CUp
No glyph for  accSagittalFlat11v49CDown
No glyph for  accSagittalSharp19CUp
No glyph for  accSagittalFlat19CDown
No glyph for  accSagittalSharp7v19CUp
No glyph for  accSagittalFlat7v19CDown
No glyph for  accSagittalSharp49SUp
No glyph for  accSagittalFlat49SDown
No glyph for  accSagittalSharp23SUp
No glyph for  accSagittalFlat23SDown
No glyph for  accSagittalSharp5v13MUp
No glyph for  accSagittalFlat5v13MDown
No glyph for  accSagittalSharp11v19MUp
No glyph for  accSagittalFlat11v19MDown
No glyph for  accSagittalSharp49MUp
No glyph for  accSagittalFlat49MDown
No glyph for  accSagittalSharp5v49MUp
No glyph for  accSagittalFlat5v49MDown
No glyph for  accSagittalSharp49LUp
No glyph for  accSagittalFlat49LDown
No glyph for  accSagittalSharp11v19LUp
No glyph for  accSagittalFlat11v19LDown
No glyph for  accSagittalSharp5v13LUp
No glyph for  accSagittalFlat5v13LDown
No glyph for  accSagittalDoubleSharp23SDown
No glyph for  accSagittalDoubleFlat23SUp
No glyph for  accSagittalDoubleSharp49SDown
No glyph for  accSagittalDoubleFlat49SUp
No glyph for  accSagittalDoubleSharp7v19CDown
No glyph for  accSagittalDoubleFlat7v19CUp
No glyph for  accSagittalDoubleSharp19CDown
No glyph for  accSagittalDoubleFlat19CUp
No glyph for  accSagittalDoubleSharp11v49CDown
No glyph for  accSagittalDoubleFlat11v49CUp
No glyph for  accSagittalDoubleSharp143CDown
No glyph for  accSagittalDoubleFlat143CUp
No glyph for  accSagittalDoubleSharp17kDown
No glyph for  accSagittalDoubleFlat17kUp
No glyph for  accSagittalDoubleSharp19sDown
No glyph for  accSagittalDoubleFlat19sUp
No glyph for  accSagittalShaftUp
No glyph for  accSagittalShaftDown
No glyph for  accSagittalAcute
No glyph for  accSagittalGrave
No glyph for  accSagittal1MinaUp
No glyph for  accSagittal1MinaDown
No glyph for  accSagittal2MinasUp
No glyph for  accSagittal2MinasDown
No glyph for  accSagittal1TinaUp
No glyph for  accSagittal1TinaDown
No glyph for  accSagittal2TinasUp
No glyph for  accSagittal2TinasDown
No glyph for  accSagittal3TinasUp
No glyph for  accSagittal3TinasDown
No glyph for  accSagittal4TinasUp
No glyph for  accSagittal4TinasDown
No glyph for  accSagittal5TinasUp
No glyph for  accSagittal5TinasDown
No glyph for  accSagittal6TinasUp
No glyph for  accSagittal6TinasDown
No glyph for  accSagittal7TinasUp
No glyph for  accSagittal7TinasDown
No glyph for  accSagittal8TinasUp
No glyph for  accSagittal8TinasDown
No glyph for  accSagittal9TinasUp
No glyph for  accSagittal9TinasDown
No glyph for  accSagittalFractionalTinaUp
No glyph for  accSagittalFractionalTinaDown
No glyph for  accidentalWilsonPlus
No glyph for  accidentalWilsonMinus

**Comment by rvilarl** [comment]
@AaronDavidNewman do you fall back to another font?

**Comment by AaronDavidNewman** [comment]
> @AaronDavidNewman this font is missing a lot of glyphs

That's what I meant by 'incomplete'.   Sorry if that wasn't clear. 

 > @AaronDavidNewman do you fall back to another font?

That's what the font stack is for.  If a glyph is missing for a font, it will use the fallback.  Most of the fonts missing in Leland (and used by VexFlow) are pretty specialized, and so not much is lost by falling back to the other fonts  This is the font stack for Leland in Smoosic.

``` typescript
      Leland: () => { VF.setMusicFont('Leland', 'Bravura', 'Gonville', 'Custom'); }
```

**Comment by ronyeh** [comment]
I am okay with the Leland-only variant not having a fallback for the rarer symbols. I assume it has most of the symbols that a normal score would use, such as clefs, note heads, etc. We can just document this as a current limitation of using the Leland-only VexFlow build.

**Comment by rvilarl** [comment]
Perhaps it would make sense to generate mixed fonts. I mean a single font Leland + Bravura where the missing glyphs from Leland would be picked from Brabura.
I have also looked into some examples and there are missing glyphs which are not so uncommon and others taht seem not to be used at all in VexFlow.

**Comment by ronyeh** [comment]
In the interest of making the PR more targeted and manageable, I would suggest just using Leland as is, and generating only the `vexflow-leland.js` variant.

Afterward, we can look to see which missing glyphs we really really need, and then generate a subset of Bravura to cover for those missing glyphs. Then we can have the vexflow-leland.js include the missing glyphs, like we currently do with the "Custom" font in the vexflow-petaluma.js library.

**Comment by ronyeh** [comment]
Once Leland is merged, I would suggest bumping the release version to 4.1 since we are adding notable functionality.

I'll work with @0xfe to make sure he can run the release for 4.1.0. I've been doing the releases so far, and we need to make sure everyone can run the same script and get the same results. :-)
