### ISSUE TITLE
Copying the script for vexflow 4.0 doesn't allow using addAccidental.

### ISSUE THREAD

**Issue by CosmeValera** [0xfe/vexflow#1394]
If I put in my html the following script>
`<script src="https://cdn.jsdelivr.net/npm/vexflow/build/cjs/vexflow.js"></script>`
Then when I try to use addAccidental() (e.g. to add a sharp to a StaveNote),  then nothing is printed in screen and this will appear in console.
![image](https://user-images.githubusercontent.com/80126839/170026566-c6a13867-e505-4e5d-8666-b236f7552214.png)
However if I use this script:
`<script src="https://unpkg.com/vexflow/releases/vexflow-min.js"></script>`
It works as expected, but it throws a warning in the console saying that it is a version that soon will stop being supported.
What script should I put in my HTML?

**Comment by ronyeh** [comment]
Hi!

Are you upgrading an existing site to use VexFlow 4?

Your first script URL is correct (jsdelivr.net). The bottom one is version 3.0.9, and is kept around for supporting legacy deployments.

Either of these two URLs will get you the most recent release:
* https://cdn.jsdelivr.net/npm/vexflow@4.0.3/build/cjs/vexflow.js
* https://unpkg.com/vexflow@4.0.3/build/cjs/vexflow.js

`.addAccidental()` was removed in the VexFlow 4 release in favor of `note.addModifier(modifier, index)`.

**See the note here:**
https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.0#stavenote-removed-addaccidental-addarticulation-addannotation-adddot

The reasoning behind this breaking change was that we were removing some circular dependency issues from the code base. Plus, the "addAccidental" helper function was an empty helper function that just called addModifier anyways.

In the future, we may explore adding back "addAccidental()" as long as it doesn't cause any issues. I agree it seems like a friendlier name!

But for now, use `addModifier(modifier, index)`

**Comment by CosmeValera** [comment]
Hi, Ronyeh thank you for answering, now I see it more clearly.
I appreciate that you and other people have developed this js/ts framework to deal with creating music scores from scratch. Right now I'm using it for my Final Degree Project, in which you can compose scores like Sibelius or Finale.
Personally, I'm not too fond of the change in naming to addAccidental().
