### ISSUE TITLE
Fonts - missing glyphs 

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1398]
The table below shows the missing glyphs for each of the fonts. `Bravura` is the only complete one (expect for the vexflow custom glyphs). Looking at this result I would suggest to redefine the font stacks as follow:

```js
static FONT_STACKS: Record<string, string[]> = {
    Bravura: ['Bravura', 'Custom'],
    Gonville: ['Gonville', 'Bravura', 'Custom'],
    Petaluma: ['Petaluma', 'Bravura', 'Custom'],
    Leland: ['Leland', 'Bravura', 'Custom'],
  };

```

we should also consider the inclusion of `Bravura` in the 1 font libraries.

@ronyeh @AaronDavidNewman what do you think?

Gonville | Bravura | Petaluma | Leland
-- | -- | -- | --
  |   |   | accidentalKomaSharp
  |   |   | accidentalKoron
accidentalNarrowReversedFlat |   |   |  
accidentalNarrowReversedFlatAndFlat |   |   |  
  |   |   | accidentalSori
accidentalWilsonMinus |   |   | accidentalWilsonMinus
accidentalWilsonPlus |   |   | accidentalWilsonPlus
accSagittal11LargeDiesisDown |   | accSagittal11LargeDiesisDown | accSagittal11LargeDiesisDown
accSagittal11LargeDiesisUp |   | accSagittal11LargeDiesisUp | accSagittal11LargeDiesisUp
accSagittal11MediumDiesisDown |   | accSagittal11MediumDiesisDown | accSagittal11MediumDiesisDown
accSagittal11MediumDiesisUp |   | accSagittal11MediumDiesisUp | accSagittal11MediumDiesisUp
accSagittal11v19LargeDiesisDown |   | accSagittal11v19LargeDiesisDown | accSagittal11v19LargeDiesisDown
accSagittal11v19LargeDiesisUp |   | accSagittal11v19LargeDiesisUp | accSagittal11v19LargeDiesisUp
accSagittal11v19MediumDiesisDown |   | accSagittal11v19MediumDiesisDown | accSagittal11v19MediumDiesisDown
accSagittal11v19MediumDiesisUp |   | accSagittal11v19MediumDiesisUp | accSagittal11v19MediumDiesisUp
accSagittal11v49CommaDown |   | accSagittal11v49CommaDown | accSagittal11v49CommaDown
accSagittal11v49CommaUp |   | accSagittal11v49CommaUp | accSagittal11v49CommaUp
accSagittal143CommaDown |   | accSagittal143CommaDown | accSagittal143CommaDown
accSagittal143CommaUp |   | accSagittal143CommaUp | accSagittal143CommaUp
accSagittal17CommaDown |   | accSagittal17CommaDown | accSagittal17CommaDown
accSagittal17CommaUp |   | accSagittal17CommaUp | accSagittal17CommaUp
accSagittal17KleismaDown |   | accSagittal17KleismaDown | accSagittal17KleismaDown
accSagittal17KleismaUp |   | accSagittal17KleismaUp | accSagittal17KleismaUp
accSagittal19CommaDown |   | accSagittal19CommaDown | accSagittal19CommaDown
accSagittal19CommaUp |   | accSagittal19CommaUp | accSagittal19CommaUp
accSagittal19SchismaDown |   | accSagittal19SchismaDown | accSagittal19SchismaDown
accSagittal19SchismaUp |   | accSagittal19SchismaUp | accSagittal19SchismaUp
accSagittal1MinaDown |   | accSagittal1MinaDown | accSagittal1MinaDown
accSagittal1MinaUp |   | accSagittal1MinaUp | accSagittal1MinaUp
accSagittal1TinaDown |   | accSagittal1TinaDown | accSagittal1TinaDown
accSagittal1TinaUp |   | accSagittal1TinaUp | accSagittal1TinaUp
accSagittal23CommaDown |   | accSagittal23CommaDown | accSagittal23CommaDown
accSagittal23CommaUp |   | accSagittal23CommaUp | accSagittal23CommaUp
accSagittal23SmallDiesisDown |   | accSagittal23SmallDiesisDown | accSagittal23SmallDiesisDown
accSagittal23SmallDiesisUp |   | accSagittal23SmallDiesisUp | accSagittal23SmallDiesisUp
accSagittal25SmallDiesisDown |   | accSagittal25SmallDiesisDown | accSagittal25SmallDiesisDown
accSagittal25SmallDiesisUp |   | accSagittal25SmallDiesisUp | accSagittal25SmallDiesisUp
accSagittal2MinasDown |   | accSagittal2MinasDown | accSagittal2MinasDown
accSagittal2MinasUp |   | accSagittal2MinasUp | accSagittal2MinasUp
accSagittal2TinasDown |   | accSagittal2TinasDown | accSagittal2TinasDown
accSagittal2TinasUp |   | accSagittal2TinasUp | accSagittal2TinasUp
accSagittal35LargeDiesisDown |   | accSagittal35LargeDiesisDown | accSagittal35LargeDiesisDown
accSagittal35LargeDiesisUp |   | accSagittal35LargeDiesisUp | accSagittal35LargeDiesisUp
accSagittal35MediumDiesisDown |   | accSagittal35MediumDiesisDown | accSagittal35MediumDiesisDown
accSagittal35MediumDiesisUp |   | accSagittal35MediumDiesisUp | accSagittal35MediumDiesisUp
accSagittal3TinasDown |   | accSagittal3TinasDown | accSagittal3TinasDown
accSagittal3TinasUp |   | accSagittal3TinasUp | accSagittal3TinasUp
accSagittal49LargeDiesisDown |   | accSagittal49LargeDiesisDown | accSagittal49LargeDiesisDown
accSagittal49LargeDiesisUp |   | accSagittal49LargeDiesisUp | accSagittal49LargeDiesisUp
accSagittal49MediumDiesisDown |   | accSagittal49MediumDiesisDown | accSagittal49MediumDiesisDown
accSagittal49MediumDiesisUp |   | accSagittal49MediumDiesisUp | accSagittal49MediumDiesisUp
accSagittal49SmallDiesisDown |   | accSagittal49SmallDiesisDown | accSagittal49SmallDiesisDown
accSagittal49SmallDiesisUp |   | accSagittal49SmallDiesisUp | accSagittal49SmallDiesisUp
accSagittal4TinasDown |   | accSagittal4TinasDown | accSagittal4TinasDown
accSagittal4TinasUp |   | accSagittal4TinasUp | accSagittal4TinasUp
accSagittal55CommaDown |   | accSagittal55CommaDown | accSagittal55CommaDown
accSagittal55CommaUp |   | accSagittal55CommaUp | accSagittal55CommaUp
accSagittal5CommaDown |   | accSagittal5CommaDown | accSagittal5CommaDown
accSagittal5CommaUp |   | accSagittal5CommaUp | accSagittal5CommaUp
accSagittal5TinasDown |   | accSagittal5TinasDown | accSagittal5TinasDown
accSagittal5TinasUp |   | accSagittal5TinasUp | accSagittal5TinasUp
accSagittal5v11SmallDiesisDown |   | accSagittal5v11SmallDiesisDown | accSagittal5v11SmallDiesisDown
accSagittal5v11SmallDiesisUp |   | accSagittal5v11SmallDiesisUp | accSagittal5v11SmallDiesisUp
accSagittal5v13LargeDiesisDown |   | accSagittal5v13LargeDiesisDown | accSagittal5v13LargeDiesisDown
accSagittal5v13LargeDiesisUp |   | accSagittal5v13LargeDiesisUp | accSagittal5v13LargeDiesisUp
accSagittal5v13MediumDiesisDown |   | accSagittal5v13MediumDiesisDown | accSagittal5v13MediumDiesisDown
accSagittal5v13MediumDiesisUp |   | accSagittal5v13MediumDiesisUp | accSagittal5v13MediumDiesisUp
accSagittal5v19CommaDown |   | accSagittal5v19CommaDown | accSagittal5v19CommaDown
accSagittal5v19CommaUp |   | accSagittal5v19CommaUp | accSagittal5v19CommaUp
accSagittal5v23SmallDiesisDown |   | accSagittal5v23SmallDiesisDown | accSagittal5v23SmallDiesisDown
accSagittal5v23SmallDiesisUp |   | accSagittal5v23SmallDiesisUp | accSagittal5v23SmallDiesisUp
accSagittal5v49MediumDiesisDown |   | accSagittal5v49MediumDiesisDown | accSagittal5v49MediumDiesisDown
accSagittal5v49MediumDiesisUp |   | accSagittal5v49MediumDiesisUp | accSagittal5v49MediumDiesisUp
accSagittal5v7KleismaDown |   | accSagittal5v7KleismaDown | accSagittal5v7KleismaDown
accSagittal5v7KleismaUp |   | accSagittal5v7KleismaUp | accSagittal5v7KleismaUp
accSagittal6TinasDown |   | accSagittal6TinasDown | accSagittal6TinasDown
accSagittal6TinasUp |   | accSagittal6TinasUp | accSagittal6TinasUp
accSagittal7CommaDown |   | accSagittal7CommaDown | accSagittal7CommaDown
accSagittal7CommaUp |   | accSagittal7CommaUp | accSagittal7CommaUp
accSagittal7TinasDown |   | accSagittal7TinasDown | accSagittal7TinasDown
accSagittal7TinasUp |   | accSagittal7TinasUp | accSagittal7TinasUp
accSagittal7v11CommaDown |   | accSagittal7v11CommaDown | accSagittal7v11CommaDown
accSagittal7v11CommaUp |   | accSagittal7v11CommaUp | accSagittal7v11CommaUp
accSagittal7v11KleismaDown |   | accSagittal7v11KleismaDown | accSagittal7v11KleismaDown
accSagittal7v11KleismaUp |   | accSagittal7v11KleismaUp | accSagittal7v11KleismaUp
accSagittal7v19CommaDown |   | accSagittal7v19CommaDown | accSagittal7v19CommaDown
accSagittal7v19CommaUp |   | accSagittal7v19CommaUp | accSagittal7v19CommaUp
accSagittal8TinasDown |   | accSagittal8TinasDown | accSagittal8TinasDown
accSagittal8TinasUp |   | accSagittal8TinasUp | accSagittal8TinasUp
accSagittal9TinasDown |   | accSagittal9TinasDown | accSagittal9TinasDown
accSagittal9TinasUp |   | accSagittal9TinasUp | accSagittal9TinasUp
accSagittalAcute |   | accSagittalAcute | accSagittalAcute
accSagittalDoubleFlat |   | accSagittalDoubleFlat | accSagittalDoubleFlat
accSagittalDoubleFlat11v49CUp |   | accSagittalDoubleFlat11v49CUp | accSagittalDoubleFlat11v49CUp
accSagittalDoubleFlat143CUp |   | accSagittalDoubleFlat143CUp | accSagittalDoubleFlat143CUp
accSagittalDoubleFlat17CUp |   | accSagittalDoubleFlat17CUp | accSagittalDoubleFlat17CUp
accSagittalDoubleFlat17kUp |   | accSagittalDoubleFlat17kUp | accSagittalDoubleFlat17kUp
accSagittalDoubleFlat19CUp |   | accSagittalDoubleFlat19CUp | accSagittalDoubleFlat19CUp
accSagittalDoubleFlat19sUp |   | accSagittalDoubleFlat19sUp | accSagittalDoubleFlat19sUp
accSagittalDoubleFlat23CUp |   | accSagittalDoubleFlat23CUp | accSagittalDoubleFlat23CUp
accSagittalDoubleFlat23SUp |   | accSagittalDoubleFlat23SUp | accSagittalDoubleFlat23SUp
accSagittalDoubleFlat25SUp |   | accSagittalDoubleFlat25SUp | accSagittalDoubleFlat25SUp
accSagittalDoubleFlat49SUp |   | accSagittalDoubleFlat49SUp | accSagittalDoubleFlat49SUp
accSagittalDoubleFlat55CUp |   | accSagittalDoubleFlat55CUp | accSagittalDoubleFlat55CUp
accSagittalDoubleFlat5CUp |   | accSagittalDoubleFlat5CUp | accSagittalDoubleFlat5CUp
accSagittalDoubleFlat5v11SUp |   | accSagittalDoubleFlat5v11SUp | accSagittalDoubleFlat5v11SUp
accSagittalDoubleFlat5v19CUp |   | accSagittalDoubleFlat5v19CUp | accSagittalDoubleFlat5v19CUp
accSagittalDoubleFlat5v23SUp |   | accSagittalDoubleFlat5v23SUp | accSagittalDoubleFlat5v23SUp
accSagittalDoubleFlat5v7kUp |   | accSagittalDoubleFlat5v7kUp | accSagittalDoubleFlat5v7kUp
accSagittalDoubleFlat7CUp |   | accSagittalDoubleFlat7CUp | accSagittalDoubleFlat7CUp
accSagittalDoubleFlat7v11CUp |   | accSagittalDoubleFlat7v11CUp | accSagittalDoubleFlat7v11CUp
accSagittalDoubleFlat7v11kUp |   | accSagittalDoubleFlat7v11kUp | accSagittalDoubleFlat7v11kUp
accSagittalDoubleFlat7v19CUp |   | accSagittalDoubleFlat7v19CUp | accSagittalDoubleFlat7v19CUp
accSagittalDoubleSharp |   | accSagittalDoubleSharp | accSagittalDoubleSharp
accSagittalDoubleSharp11v49CDown |   | accSagittalDoubleSharp11v49CDown | accSagittalDoubleSharp11v49CDown
accSagittalDoubleSharp143CDown |   | accSagittalDoubleSharp143CDown | accSagittalDoubleSharp143CDown
accSagittalDoubleSharp17CDown |   | accSagittalDoubleSharp17CDown | accSagittalDoubleSharp17CDown
accSagittalDoubleSharp17kDown |   | accSagittalDoubleSharp17kDown | accSagittalDoubleSharp17kDown
accSagittalDoubleSharp19CDown |   | accSagittalDoubleSharp19CDown | accSagittalDoubleSharp19CDown
accSagittalDoubleSharp19sDown |   | accSagittalDoubleSharp19sDown | accSagittalDoubleSharp19sDown
accSagittalDoubleSharp23CDown |   | accSagittalDoubleSharp23CDown | accSagittalDoubleSharp23CDown
accSagittalDoubleSharp23SDown |   | accSagittalDoubleSharp23SDown | accSagittalDoubleSharp23SDown
accSagittalDoubleSharp25SDown |   | accSagittalDoubleSharp25SDown | accSagittalDoubleSharp25SDown
accSagittalDoubleSharp49SDown |   | accSagittalDoubleSharp49SDown | accSagittalDoubleSharp49SDown
accSagittalDoubleSharp55CDown |   | accSagittalDoubleSharp55CDown | accSagittalDoubleSharp55CDown
accSagittalDoubleSharp5CDown |   | accSagittalDoubleSharp5CDown | accSagittalDoubleSharp5CDown
accSagittalDoubleSharp5v11SDown |   | accSagittalDoubleSharp5v11SDown | accSagittalDoubleSharp5v11SDown
accSagittalDoubleSharp5v19CDown |   | accSagittalDoubleSharp5v19CDown | accSagittalDoubleSharp5v19CDown
accSagittalDoubleSharp5v23SDown |   | accSagittalDoubleSharp5v23SDown | accSagittalDoubleSharp5v23SDown
accSagittalDoubleSharp5v7kDown |   | accSagittalDoubleSharp5v7kDown | accSagittalDoubleSharp5v7kDown
accSagittalDoubleSharp7CDown |   | accSagittalDoubleSharp7CDown | accSagittalDoubleSharp7CDown
accSagittalDoubleSharp7v11CDown |   | accSagittalDoubleSharp7v11CDown | accSagittalDoubleSharp7v11CDown
accSagittalDoubleSharp7v11kDown |   | accSagittalDoubleSharp7v11kDown | accSagittalDoubleSharp7v11kDown
accSagittalDoubleSharp7v19CDown |   | accSagittalDoubleSharp7v19CDown | accSagittalDoubleSharp7v19CDown
accSagittalFlat |   | accSagittalFlat | accSagittalFlat
accSagittalFlat11LDown |   | accSagittalFlat11LDown | accSagittalFlat11LDown
accSagittalFlat11MDown |   | accSagittalFlat11MDown | accSagittalFlat11MDown
accSagittalFlat11v19LDown |   | accSagittalFlat11v19LDown | accSagittalFlat11v19LDown
accSagittalFlat11v19MDown |   | accSagittalFlat11v19MDown | accSagittalFlat11v19MDown
accSagittalFlat11v49CDown |   | accSagittalFlat11v49CDown | accSagittalFlat11v49CDown
accSagittalFlat11v49CUp |   | accSagittalFlat11v49CUp | accSagittalFlat11v49CUp
accSagittalFlat143CDown |   | accSagittalFlat143CDown | accSagittalFlat143CDown
accSagittalFlat143CUp |   | accSagittalFlat143CUp | accSagittalFlat143CUp
accSagittalFlat17CDown |   | accSagittalFlat17CDown | accSagittalFlat17CDown
accSagittalFlat17CUp |   | accSagittalFlat17CUp | accSagittalFlat17CUp
accSagittalFlat17kDown |   | accSagittalFlat17kDown | accSagittalFlat17kDown
accSagittalFlat17kUp |   | accSagittalFlat17kUp | accSagittalFlat17kUp
accSagittalFlat19CDown |   | accSagittalFlat19CDown | accSagittalFlat19CDown
accSagittalFlat19CUp |   | accSagittalFlat19CUp | accSagittalFlat19CUp
accSagittalFlat19sDown |   | accSagittalFlat19sDown | accSagittalFlat19sDown
accSagittalFlat19sUp |   | accSagittalFlat19sUp | accSagittalFlat19sUp
accSagittalFlat23CDown |   | accSagittalFlat23CDown | accSagittalFlat23CDown
accSagittalFlat23CUp |   | accSagittalFlat23CUp | accSagittalFlat23CUp
accSagittalFlat23SDown |   | accSagittalFlat23SDown | accSagittalFlat23SDown
accSagittalFlat23SUp |   | accSagittalFlat23SUp | accSagittalFlat23SUp
accSagittalFlat25SDown |   | accSagittalFlat25SDown | accSagittalFlat25SDown
accSagittalFlat25SUp |   | accSagittalFlat25SUp | accSagittalFlat25SUp
accSagittalFlat35LDown |   | accSagittalFlat35LDown | accSagittalFlat35LDown
accSagittalFlat35MDown |   | accSagittalFlat35MDown | accSagittalFlat35MDown
accSagittalFlat49LDown |   | accSagittalFlat49LDown | accSagittalFlat49LDown
accSagittalFlat49MDown |   | accSagittalFlat49MDown | accSagittalFlat49MDown
accSagittalFlat49SDown |   | accSagittalFlat49SDown | accSagittalFlat49SDown
accSagittalFlat49SUp |   | accSagittalFlat49SUp | accSagittalFlat49SUp
accSagittalFlat55CDown |   | accSagittalFlat55CDown | accSagittalFlat55CDown
accSagittalFlat55CUp |   | accSagittalFlat55CUp | accSagittalFlat55CUp
accSagittalFlat5CDown |   | accSagittalFlat5CDown | accSagittalFlat5CDown
accSagittalFlat5CUp |   | accSagittalFlat5CUp | accSagittalFlat5CUp
accSagittalFlat5v11SDown |   | accSagittalFlat5v11SDown | accSagittalFlat5v11SDown
accSagittalFlat5v11SUp |   | accSagittalFlat5v11SUp | accSagittalFlat5v11SUp
accSagittalFlat5v13LDown |   | accSagittalFlat5v13LDown | accSagittalFlat5v13LDown
accSagittalFlat5v13MDown |   | accSagittalFlat5v13MDown | accSagittalFlat5v13MDown
accSagittalFlat5v19CDown |   | accSagittalFlat5v19CDown | accSagittalFlat5v19CDown
accSagittalFlat5v19CUp |   | accSagittalFlat5v19CUp | accSagittalFlat5v19CUp
accSagittalFlat5v23SDown |   | accSagittalFlat5v23SDown | accSagittalFlat5v23SDown
accSagittalFlat5v23SUp |   | accSagittalFlat5v23SUp | accSagittalFlat5v23SUp
accSagittalFlat5v49MDown |   | accSagittalFlat5v49MDown | accSagittalFlat5v49MDown
accSagittalFlat5v7kDown |   | accSagittalFlat5v7kDown | accSagittalFlat5v7kDown
accSagittalFlat5v7kUp |   | accSagittalFlat5v7kUp | accSagittalFlat5v7kUp
accSagittalFlat7CDown |   | accSagittalFlat7CDown | accSagittalFlat7CDown
accSagittalFlat7CUp |   | accSagittalFlat7CUp | accSagittalFlat7CUp
accSagittalFlat7v11CDown |   | accSagittalFlat7v11CDown | accSagittalFlat7v11CDown
accSagittalFlat7v11CUp |   | accSagittalFlat7v11CUp | accSagittalFlat7v11CUp
accSagittalFlat7v11kDown |   | accSagittalFlat7v11kDown | accSagittalFlat7v11kDown
accSagittalFlat7v11kUp |   | accSagittalFlat7v11kUp | accSagittalFlat7v11kUp
accSagittalFlat7v19CDown |   | accSagittalFlat7v19CDown | accSagittalFlat7v19CDown
accSagittalFlat7v19CUp |   | accSagittalFlat7v19CUp | accSagittalFlat7v19CUp
accSagittalFractionalTinaDown |   | accSagittalFractionalTinaDown | accSagittalFractionalTinaDown
accSagittalFractionalTinaUp |   | accSagittalFractionalTinaUp | accSagittalFractionalTinaUp
accSagittalGrave |   | accSagittalGrave | accSagittalGrave
accSagittalShaftDown |   | accSagittalShaftDown | accSagittalShaftDown
accSagittalShaftUp |   | accSagittalShaftUp | accSagittalShaftUp
accSagittalSharp |   | accSagittalSharp | accSagittalSharp
accSagittalSharp11LUp |   | accSagittalSharp11LUp | accSagittalSharp11LUp
accSagittalSharp11MUp |   | accSagittalSharp11MUp | accSagittalSharp11MUp
accSagittalSharp11v19LUp |   | accSagittalSharp11v19LUp | accSagittalSharp11v19LUp
accSagittalSharp11v19MUp |   | accSagittalSharp11v19MUp | accSagittalSharp11v19MUp
accSagittalSharp11v49CDown |   | accSagittalSharp11v49CDown | accSagittalSharp11v49CDown
accSagittalSharp11v49CUp |   | accSagittalSharp11v49CUp | accSagittalSharp11v49CUp
accSagittalSharp143CDown |   | accSagittalSharp143CDown | accSagittalSharp143CDown
accSagittalSharp143CUp |   | accSagittalSharp143CUp | accSagittalSharp143CUp
accSagittalSharp17CDown |   | accSagittalSharp17CDown | accSagittalSharp17CDown
accSagittalSharp17CUp |   | accSagittalSharp17CUp | accSagittalSharp17CUp
accSagittalSharp17kDown |   | accSagittalSharp17kDown | accSagittalSharp17kDown
accSagittalSharp17kUp |   | accSagittalSharp17kUp | accSagittalSharp17kUp
accSagittalSharp19CDown |   | accSagittalSharp19CDown | accSagittalSharp19CDown
accSagittalSharp19CUp |   | accSagittalSharp19CUp | accSagittalSharp19CUp
accSagittalSharp19sDown |   | accSagittalSharp19sDown | accSagittalSharp19sDown
accSagittalSharp19sUp |   | accSagittalSharp19sUp | accSagittalSharp19sUp
accSagittalSharp23CDown |   | accSagittalSharp23CDown | accSagittalSharp23CDown
accSagittalSharp23CUp |   | accSagittalSharp23CUp | accSagittalSharp23CUp
accSagittalSharp23SDown |   | accSagittalSharp23SDown | accSagittalSharp23SDown
accSagittalSharp23SUp |   | accSagittalSharp23SUp | accSagittalSharp23SUp
accSagittalSharp25SDown |   | accSagittalSharp25SDown | accSagittalSharp25SDown
accSagittalSharp25SUp |   | accSagittalSharp25SUp | accSagittalSharp25SUp
accSagittalSharp35LUp |   | accSagittalSharp35LUp | accSagittalSharp35LUp
accSagittalSharp35MUp |   | accSagittalSharp35MUp | accSagittalSharp35MUp
accSagittalSharp49LUp |   | accSagittalSharp49LUp | accSagittalSharp49LUp
accSagittalSharp49MUp |   | accSagittalSharp49MUp | accSagittalSharp49MUp
accSagittalSharp49SDown |   | accSagittalSharp49SDown | accSagittalSharp49SDown
accSagittalSharp49SUp |   | accSagittalSharp49SUp | accSagittalSharp49SUp
accSagittalSharp55CDown |   | accSagittalSharp55CDown | accSagittalSharp55CDown
accSagittalSharp55CUp |   | accSagittalSharp55CUp | accSagittalSharp55CUp
accSagittalSharp5CDown |   | accSagittalSharp5CDown | accSagittalSharp5CDown
accSagittalSharp5CUp |   | accSagittalSharp5CUp | accSagittalSharp5CUp
accSagittalSharp5v11SDown |   | accSagittalSharp5v11SDown | accSagittalSharp5v11SDown
accSagittalSharp5v11SUp |   | accSagittalSharp5v11SUp | accSagittalSharp5v11SUp
accSagittalSharp5v13LUp |   | accSagittalSharp5v13LUp | accSagittalSharp5v13LUp
accSagittalSharp5v13MUp |   | accSagittalSharp5v13MUp | accSagittalSharp5v13MUp
accSagittalSharp5v19CDown |   | accSagittalSharp5v19CDown | accSagittalSharp5v19CDown
accSagittalSharp5v19CUp |   | accSagittalSharp5v19CUp | accSagittalSharp5v19CUp
accSagittalSharp5v23SDown |   | accSagittalSharp5v23SDown | accSagittalSharp5v23SDown
accSagittalSharp5v23SUp |   | accSagittalSharp5v23SUp | accSagittalSharp5v23SUp
accSagittalSharp5v49MUp |   | accSagittalSharp5v49MUp | accSagittalSharp5v49MUp
accSagittalSharp5v7kDown |   | accSagittalSharp5v7kDown | accSagittalSharp5v7kDown
accSagittalSharp5v7kUp |   | accSagittalSharp5v7kUp | accSagittalSharp5v7kUp
accSagittalSharp7CDown |   | accSagittalSharp7CDown | accSagittalSharp7CDown
accSagittalSharp7CUp |   | accSagittalSharp7CUp | accSagittalSharp7CUp
accSagittalSharp7v11CDown |   | accSagittalSharp7v11CDown | accSagittalSharp7v11CDown
accSagittalSharp7v11CUp |   | accSagittalSharp7v11CUp | accSagittalSharp7v11CUp
accSagittalSharp7v11kDown |   | accSagittalSharp7v11kDown | accSagittalSharp7v11kDown
accSagittalSharp7v11kUp |   | accSagittalSharp7v11kUp | accSagittalSharp7v11kUp
accSagittalSharp7v19CDown |   | accSagittalSharp7v19CDown | accSagittalSharp7v19CDown
accSagittalSharp7v19CUp |   | accSagittalSharp7v19CUp | accSagittalSharp7v19CUp
arpeggiatoDown |   |   | arpeggiatoDown
arpeggiatoUp |   |   | arpeggiatoUp
  |   |   | arrowheadBlackDown
  |   |   | arrowheadBlackUp
  |   |   | barlineTick
brassBend |   |   | brassBend
brassDoitMedium |   |   | brassDoitMedium
brassFallLipShort |   |   | brassFallLipShort
brassFallRoughMedium |   |   | brassFallRoughMedium
brassFlip |   |   | brassFlip
brassJazzTurn |   |   | brassJazzTurn
brassLiftMedium |   |   | brassLiftMedium
brassMuteClosed |   |   |  
brassMuteOpen |   |   |  
brassScoop |   |   | brassScoop
brassSmear |   |   | brassSmear
  |   |   | breathMarkTick
  |   |   | breathMarkUpbow
csymAugmented |   |   |  
csymBracketLeftTall |   |   | csymBracketLeftTall
csymBracketRightTall |   |   | csymBracketRightTall
csymDiagonalArrangementSlash |   |   | csymDiagonalArrangementSlash
csymDiminished |   |   |  
csymHalfDiminished |   |   |  
csymMajorSeventh |   |   |  
csymMinor |   |   | csymMinor
csymParensLeftTall |   |   | csymParensLeftTall
csymParensLeftVeryTall |   |   | csymParensLeftVeryTall
csymParensRightTall |   |   | csymParensRightTall
csymParensRightVeryTall |   |   | csymParensRightVeryTall
noteheadParenthesis |   |   | noteheadParenthesis
noteheadParenthesisLeft |   |   |  
noteheadParenthesisRight |   |   |  
  |   |   | noteheadTriangleUpHalf
  |   |   | noteheadTriangleUpWhole
  |   |   | noteheadXHalf
  |   |   | noteheadXWhole
  |   |   | ornamentPrecompDoubleCadenceUpperPrefixTurn
  |   |   | pictChokeCymbal
  |   |   | pluckedLeftHandPizzicato
repeat1Bar |   |   |  
repeat2Bars |   |   |  
repeat4Bars |   |   |  
repeatBarSlash |   |   |  
  |   |   | timeSigMinus
  |   |   | timeSigParensLeft
  |   |   | timeSigParensLeftSmall
  |   |   | timeSigParensRight
  |   |   | timeSigParensRightSmall
  |   |   | timeSigPlusSmall
vexAccidentalMicrotonal1 | vexAccidentalMicrotonal1 | vexAccidentalMicrotonal1 | vexAccidentalMicrotonal1
vexAccidentalMicrotonal2 | vexAccidentalMicrotonal2 | vexAccidentalMicrotonal2 | vexAccidentalMicrotonal2
vexAccidentalMicrotonal3 | vexAccidentalMicrotonal3 | vexAccidentalMicrotonal3 | vexAccidentalMicrotonal3
vexAccidentalMicrotonal4 | vexAccidentalMicrotonal4 | vexAccidentalMicrotonal4 | vexAccidentalMicrotonal4
vexNoteHeadMutedBreve | vexNoteHeadMutedBreve | vexNoteHeadMutedBreve | vexNoteHeadMutedBreve
vexNoteHeadRectBlack | vexNoteHeadRectBlack | vexNoteHeadRectBlack | vexNoteHeadRectBlack
vexNoteHeadRectWhite | vexNoteHeadRectWhite | vexNoteHeadRectWhite | vexNoteHeadRectWhite
vexWiggleArpeggioUp | vexWiggleArpeggioUp | vexWiggleArpeggioUp | vexWiggleArpeggioUp

**Comment by ronyeh** [comment]
> ```js
> Leland: ['Petaluma', 'Bravura', 'Custom'],
> ```

Petaluma looks different than all of the other fonts. I don't think Petaluma should be a backup for Leland.

I think a reason someone would use a `vexflow-leland.js` would be for smaller library size. Maybe they don't need the missing glyphs? If we include Bravura in the vexflow-leland and vexflow-gonville and vexflow-petaluma, wouldn't that make the individual libraries much larger?

**Comment by AaronDavidNewman** [comment]
> `Leland: ['Petaluma', 'Bravura', 'Custom'],`

I'm sure Rodrigo meant: `['Leland', 'Bravura', 'Custom'];`  :)

> I think a reason someone would use a vexflow-leland.js would be for smaller library size. Maybe they don't need the missing glyphs? 

The main reason you would use any font, I think, is because you like the way it renders.  You get an exception if you reference a glyph that is not found, so any application would need to make sure that all fonts stacks contains any glyph the application supports, regardless of what glyphs the base font contains.  Or else handle the exception some other way.

Also, Leland is a new font and over time I would expect many of the missing glyphs to be added.  By defining the font stack, the Leland glyphs will replace the Bravura fonts when glyphs are generated from a new version.

**Comment by rvilarl** [comment]
> > `Leland: ['Petaluma', 'Bravura', 'Custom'],`
> 
> I'm sure Rodrigo meant: `['Leland', 'Bravura', 'Custom'];` :)

This is indeed what I meant.

> 
> > I think a reason someone would use a vexflow-leland.js would be for smaller library size. Maybe they don't need the missing glyphs?
> 
> The main reason you would use any font, I think, is because you like the way it renders. You get an exception if you reference a glyph that is not found, so any application would need to make sure that all fonts stacks contains any glyph the application supports, regardless of what glyphs the base font contains. Or else handle the exception some other way.
> 
> Also, Leland is a new font and over time I would expect many of the missing glyphs to be added. By defining the font stack, the Leland glyphs will replace the Bravura fonts when glyphs are generated from a new version.

Yes, these are the two options. I would vote for leaving Bravura as fall back rather than handling execptions. As an user I find it weird that you get exceptions when you use different variants.

**Comment by rvilarl** [comment]
Sizes without fall-back:
```
-rw-rw-r--. 1 rodrigo rodrigo  416431 may 29 22:05 vexflow-leland.js
```
Sizes with fall-back (Bravura included):
```
-rw-rw-r--. 1 rodrigo rodrigo  603943 may 29 22:12 vexflow-leland.js
```
Sizes with missing glyphs included (missing glyphs taken from Barbura):
```
-rw-rw-r--. 1 rodrigo rodrigo  437844 may 29 22:27 vexflow-leland.js
```

**Comment by rvilarl** [comment]
@ronyeh @AaronDavidNewman what is your preference?

**Comment by AaronDavidNewman** [comment]
@rvilarl I may not be a good target audience for the font-specific releases.  I would only use a monolith that included all the fonts I wanted to use.  And if there were 100 fonts available, I would probably use them all :)

If you are using all the fonts though, the font stack approach takes up less room in memory than the glyphs file with symbols duplicated from another font, doesn't it?

**Comment by ronyeh** [comment]
I feel like the full VexFlow.js can have all the fonts with the appropriate font stacks for each font name. 

The individual vexflow-{font_name}.js files should be slim and trim if possible. (I am personally okay with missing glyphs, as long as we log warnings to the console for any glyph that is used that is not available.) If we are not okay with having missing glyphs, we should just steal the missing glyphs from Bravura for the individual font libs. 

Maybe Simon and Michael have feedback on this? I think their libraries use Gonville. Are they okay with having the vexflow-gonville.js bundled with the full Bravura as a fallback font?

**Comment by rvilarl** [comment]
> @rvilarl I may not be a good target audience for the font-specific releases. I would only use a monolith that included all the fonts I wanted to use. And if there were 100 fonts available, I would probably use them all :)

Would you have interest in `Sebastian`, `Finale` and `Leipzig` font families?
See https://www.smufl.org/fonts/
 
> If you are using all the fonts though, the font stack approach takes up less room in memory than the glyphs file with symbols duplicated from another font, doesn't it?

This is right, they should only be used in individual vexflow-{font-name}.js files

**Comment by rvilarl** [comment]
> I feel like the full VexFlow.js can have all the fonts with the appropriate font stacks for each font name.

Agree

> The individual vexflow-{font_name}.js files should be slim and trim if possible. (I am personally okay with missing glyphs, as long as we log warnings to the console for any glyph that is used that is not available.) If we are not okay with having missing glyphs, we should just steal the missing glyphs from Bravura for the individual font libs.
> 
> Maybe Simon and Michael have feedback on this? I think their libraries use Gonville. Are they okay with having the vexflow-gonville.js bundled with the full Bravura as a fallback font?

@sschmidTU @mscuthbert what do you think?

**Comment by sschmidTU** [comment]
I like Gonville, still used in OSMD as it was the default font in vexflow 1.2.93 and I think it switched to Bravura in vexflow 3 (not sure).
Would be great if there was a mono build just with Gonville as well.
I believe Bravura behaves similarly to Gonville as far as the space used etc., so we might look at using that in future.

**Comment by rvilarl** [comment]
This one can be closed now
