### ISSUE TITLE
[Questions] Problems with drawing notes on default stave

### ISSUE THREAD

**Issue by TheLucifurry** [0xfe/vexflow#1403]
Hi all)
I have custom tablature staver renderer and i have a two major problems:
[Sandbox with the renderer](https://stackblitz.com/edit/vexflow-playing?file=index.ts)
1) **Modifiers affects on note symbols position** (see green on pic)
it's, possibly, correct, but i want to disable it

2) **Modifiers and all default Stave symbols are too big** (see red on pic) 
How can i to reduce their sizes?

![image](https://user-images.githubusercontent.com/47812547/172033494-2bfd24d0-8b43-43d2-9b93-43829657310f.png)

**Comment by TheLucifurry** [comment]
In sandbox, i have a few monkey patches, that fixex standart behaviour, maybe, some of them can be added directly to Vexflow source
Especially, `Stave.prototype.setTempo` patch

**Comment by rvilarl** [comment]
I am not an expert in the usage of tab but I am missing a formatter to align the staves.

**Comment by AaronDavidNewman** [comment]
@TheLucifurry I'm a little confused by what you are trying to do with the start behavior.  Do you have an example image of what the correct output would look like? 

The stave has a default start X relative to the key/time/clef markings, but you can override it if you want using setNoteStartX.  And the tempo X can be set using setXShift method of StaveTempo.  Unlike time signature and key signature, this won't affect the x position of the notes.

**Comment by TheLucifurry** [comment]
@rvilarl oh, sorry, i've discovered, that modifiers don't push out note symbols, when they have enough space)
![image](https://user-images.githubusercontent.com/47812547/172289951-4a86e69a-1a33-48d8-8508-23ae3c6816fd.png)

But sharp modifier (and, possible, others) are really huge, maybe it'd be better to make it smaller like in TuxGuitar
![image](https://user-images.githubusercontent.com/47812547/172291204-6241c0a0-b7d8-4804-9859-ec43dfeca573.png)

@AaronDavidNewman BTW, this picture has tempo caption, that places right above the clef. So I don't think, that there is a strict standart of how we need to display meta information of musical notation

**Comment by rvilarl** [comment]
> But sharp modifier (and, possible, others) are really huge, maybe it'd be better to make it smaller like in TuxGuitar 

It seems that TuxGuitar is making them small enough to place them in one column (still overlapping though). The size of the accidental is given by the smufl font and is in line with the scores found in a standard google search https://www.google.com/search?q=partiture+accidentals&source=lnms&tbm=isch
