### ISSUE TITLE
Whole/Half rests should have ledger lines?

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1404]
I expect a whole rest to have a 'hat' on it, or you can't tell whether it is half or whole rest.  

![image](https://user-images.githubusercontent.com/5438280/172073748-14d102a2-f6b5-42e2-98a6-be02599e72d8.png)

I couldn't find an example of this, but it seems like these types of rests should have ledger lines (unlike shorter rests that have flags.)

**Comment by mscuthbert** [comment]
yes, definitely.  (Breve rests get two ledger lines, one above, one below)

(Did we fix the related problem that the default position of a whole rest/semibreve rest on a one-line staff is one line below where it is on all other staves?)

**Comment by AaronDavidNewman** [comment]
I looked into this a little bit. Currently the logic is to never draw ledger lines on rests.  So first we get rid of that...I think just if the ticks is >= 8192...or possibly look at the glyph name would be better.

For the location of the ledger lines, it works correctly if the pitch that represents the rest location is on a line.  If it is on a space, there is a gap in the case of whole rest, or the rest appears incorrectly as whole rest in the case of a 1/2 rest.  Do we care?  I don't know why anyone would place a rest like this.

If we _do_ care, we would have to adjust the y position of the rest in order for it to be correct.  btw this is possibly related to the 1 line issue, Smoosic doesn't support 1-line staves yet so I couldn't test that.

The other question is about ledger lines above/below.  Gould wasn't clear - I think we show them, yes?  I don't know why you would put the rest multiple lines above/below the staff unless there was another note in the same tick context getting in the way, in which case you would want it.  It is the default behavior and is not incorrect, so...

line 1/2 rest:
![image](https://user-images.githubusercontent.com/5438280/173126431-6b2ca5da-869c-4e32-8b95-7c88c52b13eb.png)

space 1/2 rest:
![image](https://user-images.githubusercontent.com/5438280/173126499-177271e2-5b76-4558-8258-195f6d1ea7d4.png)


space whole rest:
![image](https://user-images.githubusercontent.com/5438280/173126745-3f843781-002d-4b22-95bd-c73c65b1d8ed.png)

Above the staff, there is a similar issue but the gap vs. incorrect note type are swtiched.

**Comment by mscuthbert** [comment]
Only the last ledger line is drawn, not the one separating it from the staff.  You don't need to be able to count the number of ledger lines that the rest is away from the staff, it's just there to visually distinguish whole, half, and breve rests.  It might be better to use a substitute glyph rather than using the ledger line code.  SMuFL has three code points with glyphs at the end of the rests range that include the ledger: https://www.smufl.org/version/1.2/range/rests/

Rests on spaces (in general not just outside the staff) are highly discouraged.  They move up or down by a line at a time.

**Comment by AaronDavidNewman** [comment]
Thanks @mscuthbert .  It sounds like replacing the glyph is the way to go.   I will look at the font file, I think we would need to regenerate the glyphs and replace restWhole with the decorated glyph.

**Comment by rvilarl** [comment]
I think that modifying the glyphs makes maintainance difficult. I am still considering to make a rotation to avoid the modified arpeggiato that we use on strokes.

**Comment by AaronDavidNewman** [comment]
@rvilarl  isn't it just a question of changing the codepoint in glyphnames.json and regenerating the font?

**Comment by rvilarl** [comment]
No, those rests with ledger lines are defined already in glyphnames.json (restWholeLegerLine, restHalfLegerLine).
We have to:
- include them in valid_code.js to regenerate.
- modify the application to select these glyphs if the rests are located in a leger.

**Comment by AaronDavidNewman** [comment]
@rvilarl right that's what I meant, I don't suggest changing the glyph in the font.  We could change which one we use.   Using the ledger glyph is preferable to drawing the line manually, since it's available.

We could add the glyph and use both, or if restWholeLegerLine etc. looks good on in the staff, then we can just always use that one.
