### ISSUE TITLE
Adding custom keySpecs for Turkish maqam music

### ISSUE THREAD

**Issue by muratcorlu** [0xfe/vexflow#141]
Hi there,

I want to use vexflow in my site to draw musical sheets of Turkish Classical Music songs. But Turkish Classical Music(a.k.a "maqam music") has some keyspecs that has several accidentals.

For example you can see a "maqam"s keyspec that named "Saba":

![donanim](https://f.cloud.github.com/assets/127687/1751387/3e30aa54-65e3-11e3-904b-f1c858d9e912.gif)

I tried to customize `Vex.Flow.keySignature.keySpecs` array and `Vex.Flow.keySignature` constructor function, but I couldn't success to define that kind of spec.

I tried something like that:

``` javascript
Vex.Flow.accidentalCodes.accidentals['b4'] = {
    code: "v57",
    width: 10,
    shift_right: 0,
    shift_down: 0
};
Vex.Flow.accidentalCodes.accidentals['b1'] = {
    code: "vb7",
    width: 10,
    shift_right: 0,
    shift_down: 0
};
Vex.Flow.keySignature.keySpecs["Saba"] = [{
  acc: "b4", line: 2
},{
  acc: "b1", line: 3
}];

var keySpecsBackup = JSON.parse(JSON.stringify(Vex.Flow.keySignature.keySpecs));

Vex.Flow.keySignature = function(spec) {
  var keySpec = Vex.Flow.keySignature.keySpecs[spec];

  if (!keySpec) {
    throw new Vex.RERR("BadKeySignature",
        "Bad key signature spec: '" + spec + "'");
  }

  // It it's not an array, make it array
  if( Object.prototype.toString.call( keySpec ) !== Object.prototype.toString.call( [] ) ) {
    keySpec = [keySpec];
  }

  var acc_list = [];

  for (var i = 0, count = keySpec.length; i < count; i++) {
    var currentKeySpec = keySpec[i];

    if (!currentKeySpec.acc) {
      continue;
    }

    var code = Vex.Flow.accidentalCodes.accidentals[currentKeySpec.acc].code;

    if (currentKeySpec.line) {
      acc_list.push({glyphCode: code, line: currentKeySpec.line});
    } else {
      var notes = Vex.Flow.keySignature.accidentalList(currentKeySpec.acc);

      for (var i = 0; i < keySpec.num; ++i) {
        var line = notes[i];
        acc_list.push({glyphCode: code, line: line});
      }
    }
  }

  return acc_list;
};

Vex.Flow.keySignature.keySpecs = keySpecsBackup;

Vex.Flow.keySignature.accidentalList = function(acc) {
  if (acc == "b") {
    return [2, 0.5, 2.5, 1, 3, 1.5, 3.5];
  }
  else if (acc == "#") {
    return [0, 1.5, -0.5, 1, 2.5, 0.5, 2]; }
};
```

I tried to override `Vex.Flow.keySignature` function to make enabled to set keySpecs as array and set line directly but I couldn't success. Can you suggest me a workaround?

In MusicXML 3.0, Turkish Maqam Music support added to MusicXML standart. So, if Vexflow support that kind of customizations, that will be great I think.

**Comment by alejandroiglesias** [comment]
@infojunkie any chance of making the pull request? Seems it would be useful for many of us to keep it on the main codebase.

**Comment by SalahAdDin** [comment]
:+1: 
I need this!!! Thank you!

**Comment by infojunkie** [comment]
Sorry guys, I deleted my fork because it was too hackish and the code had diverged too much. I hope to get back to this sometime this year :-)

**Comment by SalahAdDin** [comment]
But, if you deleted your fork, will be very hardly come back it :'(
