### ISSUE TITLE
Fix stems + noteheads

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1415]
https://github.com/0xfe/vexflow/pull/1401#issuecomment-1163651219

Recent PRs have caused some stems to be detached from the noteheads. We need to update the metrics files (esp for Leland) so that the stems and noteheads connect smoothly.

**Comment by ronyeh** [comment]
@rvilarl if you have time can you look into this? I noticed that in the new test cases from recent merges, some note heads don't connect well to their stems. I think we need to adjust the font metrics files (especially in Leland) to make the note heads match up again. For example, a couple of note heads in Gonville changed recently. I think that may have resulted in the note head not aligning with the stems anymore.

I think this issue should be resolved before the 4.1 release, since it is a regression, in some ways.

**Comment by rvilarl** [comment]
@ronyeh this is only adjustment of metric files, I think that it can be done after 4.1, I would not wait for that. My problem is that I doubt on how some noteheads should be connected to the stem. I will look into it. @AaronDavidNewman could you help here? 
@ronyeh by the way have you looked into the open PRs?

**Comment by rvilarl** [comment]
These are the results @ronyeh @AaronDavidNewman what are the must fix according to you?

**Leland**
**NoteHead Various_Heads**
![pptr-NoteHead Various_Heads Leland svg](https://user-images.githubusercontent.com/22865285/176285358-b4f19fb1-776c-4b89-8218-ef9e93fd2067.png)
**NoteHead Various_Heads_1**
![pptr-NoteHead Various_Note_Heads_1 Leland](https://user-images.githubusercontent.com/22865285/176285480-18b8330f-461d-4379-840d-8e035708df23.svg)
**NoteHead Various_Heads_2**
![pptr-NoteHead Various_Note_Heads_2 Leland](https://user-images.githubusercontent.com/22865285/176285545-d8a2dced-95e3-4cc6-99ef-ec3773860911.svg)

**Bravura**
**NoteHead Various_Heads**
![pptr-NoteHead Various_Heads Bravura svg](https://user-images.githubusercontent.com/22865285/176285362-e1caa711-26c7-4230-b3aa-b39b2bdce1d7.png)
**NoteHead Various_Heads_1**
![pptr-NoteHead Various_Note_Heads_1 Bravura](https://user-images.githubusercontent.com/22865285/176285484-64ec6d35-2851-41e9-9300-24eb59c820ed.svg)
**NoteHead Various_Heads_2**
![pptr-NoteHead Various_Note_Heads_2 Bravura](https://user-images.githubusercontent.com/22865285/176285547-2b17d0f4-109d-4640-a2c8-ef1f4b13d22e.svg)

**Gonville**
**NoteHead Various_Heads**
![pptr-NoteHead Various_Heads Gonville svg](https://user-images.githubusercontent.com/22865285/176285365-2a654143-7390-4883-ab9d-b91d503b3655.png)
**NoteHead Various_Heads_1**
![pptr-NoteHead Various_Note_Heads_1 Gonville](https://user-images.githubusercontent.com/22865285/176285485-eb093bae-db82-4d3c-8302-af11590e42d1.svg)
**NoteHead Various_Heads_2**
![pptr-NoteHead Various_Note_Heads_2 Gonville](https://user-images.githubusercontent.com/22865285/176285550-ef221539-6527-4c10-be9e-76d278425793.svg)

**Petaluma**
**NoteHead Various_Heads**
![pptr-NoteHead Various_Heads Petaluma svg](https://user-images.githubusercontent.com/22865285/176285369-2692f51d-76d0-44ce-8833-67dfebb09ce5.png)
**NoteHead Various_Heads_1**
![pptr-NoteHead Various_Note_Heads_1 Petaluma](https://user-images.githubusercontent.com/22865285/176285489-19518fc2-92ba-473c-9e44-855d8f4b952c.svg)
**NoteHead Various_Heads_2**
![pptr-NoteHead Various_Note_Heads_2 Petaluma](https://user-images.githubusercontent.com/22865285/176285551-0410e283-c6bf-4f9c-b17a-2b819325351f.svg)

**Comment by rvilarl** [comment]
> These are the results @ronyeh @AaronDavidNewman what are the must fix according to you?

I would say:
1) the stem up in Various Heads 2
2) the lack of space between Notes in Various Heads 1

**Comment by rvilarl** [comment]
@ronyeh this topic is not so easy to make it properly. I am trying to understand how to align the headnotes properly and the logic is distributed in several places: in the xxx_metrics.ts files in `noteHead` and `stem` and also in the tables.ts file in `glyphProps`. In tables we also still use `any` making it difficult to understand where the different values are used.
My plan is:
- remove the instances of `any` in tables.ts.
- remove the different values in the `noteHead` and `stem` in xxx_metrics.ts.
- try to use the metrics directly from the glyphs in order to minimise the values required in `noteHead` and `stem`.

**Comment by AaronDavidNewman** [comment]
Sorry, I'm just now catching up.  So this is kind of a long response :)

I don't have a priority preference but X notehead is pretty common in jazz, slash and triangle note head is pretty common for percussion.  So we could fix up the metrics for those symbols easy enough.

Also, I notice that we have don't have any slash note head cases in the note head test set (they are in the easy score set).

Finally, it would be nice if we could decouple the note head from the duration and key somehow.  This may be outside the scope of this issue, and it's a legacy problem.  For instance, currently there is a 'type' in the `NoteStruct`, a note type that comes from the duration string from 'Tables.getGlyphProps', and a note type in the key string from `StaveNote.calculateKeyProps`.   It's not clear what the precedence is.  You should be able to specific a note head and override any default that is assigned from key or duration.  StaveNote has 'custom' but there is no way to set that in the constructor.  This would be required for some of the Smufl note heads we don't support. 

btw I like the idea of renaming `this.glyph` in `StaveNote` and `NoteHead`  to `this.glyphProps`.  That is a good first step.

**Comment by rvilarl** [comment]
I have been looking into this topic and it seems that we are using the metrics to resolve another problem. The width of the custom noteheads are not calculated properly. I have added the following lines to notehead.draw:

```diff
      Glyph.renderGlyph(ctx, head_x, y, glyph_font_scale, this.glyph_code, {
        category: this.custom_glyph ? `noteHead.custom.${categorySuffix}` : `noteHead.standard.${categorySuffix}`,
      });
+      ctx.setFillStyle('#3a2');
+      ctx.fillRect(head_x, y, this.width, 2);
+      ctx.setFillStyle('black');
    }
```
and I get the following

This one is fine
![NoteHead Basic Bravura](https://user-images.githubusercontent.com/22865285/204111619-49c32530-6ecb-4cc7-ae40-e33051a776c6.png)
Here the Xs are wrong
![NoteHead Various_Heads Bravura](https://user-images.githubusercontent.com/22865285/204111623-3f651ad2-4149-41c4-9c72-b62fd6fa1580.png)
Here a lot of them are wrong
![NoteHead Various_Note_Heads_1 Bravura](https://user-images.githubusercontent.com/22865285/204111649-28a9b874-a8fb-48c4-ba56-968a1cb1ab69.png)

@AaronDavidNewman any idea?

**Comment by AaronDavidNewman** [comment]
Short answer, no.  I know there was a problem where the note was using the default notehead width for formatting, instead of the actually chosen one.  But I thought that was fixed.  

How come the green line doesn't start at the start of the glyph, X-wise?  The notehead glyphs should all start at x=0.

**Comment by rvilarl** [comment]
Thanks for the tip, that was exactly the problem.
