### ISSUE TITLE
How to add multiple Bars with EasyScore? 

### ISSUE THREAD

**Issue by nochmu** [0xfe/vexflow#1421]
The regular tutorial tells that I have to add a second stave.  https://github.com/0xfe/vexflow/wiki/Tutorial#step-7-barlines--run-
But when I try this with the EasyScroe sample, it seems that the second call has no effect. 
Is there a way? 

```var vf = new Vex.Flow.Factory({renderer: {elementId: 'output'}});
var score = vf.EasyScore();
var system = vf.System();

var stave = system.addStave({
  voices: [
         score.voice(score.notes('A4/q, B4, C5, D5'))
	 ]
}); 
stave.addClef('treble').addTimeSignature('4/4');

system.addStave({
  voices: [
         score.voice(score.notes('A4/q, B4, C5, D5'))
	 ]
}); 

vf.draw();
```

**Comment by AaronDavidNewman** [comment]
You are adding staves to the same system, so they will appear on top of each other like this:

https://jsfiddle.net/0m3xa0f0/

If you want staves in a new system, you need to create a new system and adjust its x value.  Look at the function `appendSystem` in bach_tests.ts.

``` typescript
  function appendSystem(width: number) {
    const system = f.System({ x, y, width, spaceBetweenStaves: 10 });
    x += width;
    return system;
  }
```
