### ISSUE TITLE
Extending barlines 

### ISSUE THREAD

**Issue by CodersExpo** [0xfe/vexflow#1436]
Maybe I'm doing this wrong...but, I did read this:
(Step 7: Barlines ): https://github.com/0xfe/vexflow/wiki/Tutorial#step-7-barlines

Seems to me this could be overcome by passing in a collection of Note to Voice. ie:
`system
    .addStave({
        voices: [
            score.voice(score.notes('C#5/q, B4, A4, G#4'), { stem: 'up' }) // **<<== and an array of class Note. **
            //**Url: (https://rvilarl.github.io/vexflow/api/classes/Note.html)**
        ],
    })
    .addClef('treble')
    .addTimeSignature('4/4');
`
...I don't know exactly the solution to this, but limiting a stave to 1 measure is... well ...limiting. The solution above is more of a hack IMHO. There should be a way to allow the addition of barlines (measures) per stave. Thoughts??

**Comment by AaronDavidNewman** [comment]
You are not doing it wrong.  The scope of vexflow is to be an engraving library.  It handles formatting of music within a measure, and vertically across staves.

Most of us who contribute to vexflow use it in our own applications that expand on this in different ways.

If you want an application that does multiple measures, I'd recommend [Smoosic](https://aarondavidnewman.github.io/Smoosic/) :)  It uses vexflow as an engraving engine and handles and tries to be a general-purpose music notation program.

**Comment by CodersExpo** [comment]
Thank you for your reply, clarification and suggestion Aaron much appreciated! Really very nice project here and I thank you so much for your time and effort! I will check out Snoosic for sure!
