### ISSUE TITLE
Issue with TextNote alignment over notes

### ISSUE THREAD

**Issue by nitzanrh** [0xfe/vexflow#1437]
Hey guys,

I'm trying to use TextNote to align short text over some notes, however I can't make the TextNote align exactly over the notes.
Here is a fiddle:

https://jsfiddle.net/mhyj20g3/

Basically I created array of notes, then array of texts and drew them both using FormatAndDraw.

Cheers,
Nitzan

**Comment by AaronDavidNewman** [comment]
ii think ‘Annotation’ would work better here than TextNote. Check out the annotation test cases.

**Comment by nitzanrh** [comment]
Hi Aaron,

Thanks for your reply.

I now see your edit :) Yes I did try to use annotations and they did alight horizontally better with the notes, however there is significantly less flexibility with the vertical alignment. I need my text be be aligned regardless whether there are other modifiers, different pitches etc.

Is there any documentation you could lead me to that demonstrates the use of Voice with TextNote?

Cheers,
Nitzan

**Comment by rvilarl** [comment]
@nitzanrh the recommended interface is factory. I have put a jsfiddle for you, hope it helps

https://jsfiddle.net/rg8qw5no/

**Comment by nitzanrh** [comment]
> @nitzanrh the recommended interface is factory. I have put a jsfiddle for you, hope it helps
> 
> https://jsfiddle.net/rg8qw5no/

Hi rvilarl,

Thanks for your reply.

Your JSFiddle makes a lot of sense. It also handles Grace notes with TextNotes, something which I haven't managed to get done correctly.
Also, since EasyScore is an extension of Vexflow I would assume the same is possible with using 'low-level' Vexflow, correct?
I'm asking this because I have already written quite a substantial amount of code without using EasyScore(aka factory) and I would like to implement your logic with 'low-level' vexflow

Cheers,
Nitzan

**Comment by rvilarl** [comment]
Factory is not EasyScore. EasyScore is a helper class to make some common tasks easier and it does not aim to be complete, however, Factory does. Look at #775. If you want to use low level looking into the implementation details of the Factory methods should help.

**Comment by rvilarl** [comment]
@nitzanrh can we close this now or do you need additional support?

**Comment by nitzanrh** [comment]
Yes this can be closed, thanks for pointing the difference between EasyScore and Factory. 

For future readers, in order to align the TextNote with the notes, one needs to have separate voices for each and then use joinVoices.

Cheers!
