### ISSUE TITLE
svg grouping

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1458]
All the prototype that I have done to get #1457 ready have highlighted some issues / questions:
- There are still elements with more than 3 digits precission. Should we make the rounding directly in SVGContext rather that in Glyph to make sure that all the elements get rounded? I think we should.
- Does it make sense to have a group that always contains only one SVGElement? I think that it would make more sense to get rid of the group and assign an ID to the element (path / rect / ...)
- Do we want make new classes for the elements that we want to color independently in order to be able to access them as an SVGElement (dynamic coloring)? For example ledger lines or lines on the staves as requested in #1433 I would go for the ledger lines with staff lines I am unsure.
- Are the elements rightly grouped? i.e.: Should StaveModifiers, Clef, and/or Time/KeySignature be grouped under Stave? I am unsure, this would for example make all this elements grey taking the default of the Stave.

@AaronDavidNewman @mscuthbert @sschmidTU what is your oppinion?

**Comment by AaronDavidNewman** [comment]
> Should StaveModifiers, Clef, and/or Time/KeySignature be grouped under Stave? 

It is preferred.  For SVG at least, there is a performance benefit if the modifiers are under the parent element.  You can remove and replace a stave by just removing the stave group, for instance.

It looks they are that way already.  Tempo is an outlier, in that it is not part of a group in svg, even though it is rendered under the stave.  

It would be good to have tempo as part of a group, because you can remove/replace tempo element without having to redraw anything else (change time signature, for instance, usually requires re-rendering the notes).

**Comment by rvilarl** [comment]
> > Should StaveModifiers, Clef, and/or Time/KeySignature be grouped under Stave?
> 
> It is preferred. For SVG at least, there is a performance benefit if the modifiers are under the parent element. You can remove and replace a stave by just removing the stave group, for instance.
> 
> It looks they are that way already. Tempo is an outlier, in that it is not part of a group in svg, even though it is rendered under the stave.
> 
> It would be good to have tempo as part of a group, because you can remove/replace tempo element without having to redraw anything else (change time signature, for instance, usually requires re-rendering the notes).

I agree that it makes more sense. However if we group the StaveModifiers under Stave the Modifiers also get the defaults from this group and the StaveBarlines end up grey, which I personally prefer, but also the clef and key/timemeassures, wich I doubt.

![CrossBeam Mixed_clef_voice_middle Bravura](https://user-images.githubusercontent.com/22865285/196054238-f6b2c947-a8da-47cd-a1db-8de86b8429ad.png)

![CrossBeam Mixed_clef_voice_middle Bravura](https://user-images.githubusercontent.com/22865285/196054303-188e92f4-5dc7-46a3-a9d0-74c204d640f5.png)
