### ISSUE TITLE
Can't install package on Macbook M1 (puppeteer/chromium)

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1463]
ARM silicone macbook.  npm install of latest vexflow gives the following error.  Apparently there is no chromium for the M1.  Is it possible to install without the chromium option?

I've read various workarounds, they all sound complicated and not really clear how to get it to work with this project.  Wondering if anyone has solved this before I go down the rabbit hole.

```
ANEWMAN-202207:vexflow anewman$ npm install
npm ERR! code 1
npm ERR! path /Users/anewman/src/github/vexflow/node_modules/grunt-contrib-qunit/node_modules/puppeteer
npm ERR! command failed
npm ERR! command sh -c -- node install.js
npm ERR! The chromium binary is not available for arm64: 
npm ERR! If you are on Ubuntu, you can install with: 
npm ERR! 
npm ERR!  apt-get install chromium-browser
npm ERR! 
npm ERR! /Users/anewman/src/github/vexflow/node_modules/grunt-contrib-qunit/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112
npm ERR!             throw new Error();
npm ERR!             ^
npm ERR! 
npm ERR! Error
npm ERR!     at /Users/anewman/src/github/vexflow/node_modules/grunt-contrib-qunit/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js:112:19
npm ERR!     at FSReqCallback.oncomplete (node:fs:202:21)

```

**Comment by rvilarl** [comment]
@ronyeh can you look into that?

**Comment by ronyeh** [comment]
Oh, interesting. Unfortunately I have an Intel Macbook.

There should be an option in puppeteer to use the local installation of Chrome, right? Can you figure out how to set puppeteer to point to the Chrome in your /Applications/ folder? Then maybe we can do a PR where we add that flag on M1/M2 Macs (and any computer where npm install of Chromium fails).

**Comment by ronyeh** [comment]
`LaunchOptions.executablePath` property

Path to a browser executable to use instead of the bundled Chromium. Note that Puppeteer is only guaranteed to work with the bundled Chromium, so use this setting at your own risk.

**Comment by ronyeh** [comment]
Some comments that might be relevant:

https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-749069120

https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-792259876

This last one has some useful steps to try. 

https://github.com/puppeteer/puppeteer/issues/6622#issuecomment-788199984

Some of the steps include:
* export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true. This will allow puppeteer to install.
* npm install puppeteer. It will skip trying to download chromium and install correctly.
* At this point, trying to run puppeteer (for me, using the command npm run test) gives the following error: `Error: Failed to launch the browser process! spawn /usr/bin/chromium-browser ENOENT`
* `brew install chromium` then run `which chromium` to make sure it installed properly, it should output the path to the new Chromium executable.
* ....

**Comment by write2aj** [comment]
You could try installing chromium using brew. 
For my Mac M1 with `macOS 12.6` it got installed using the below brew install.
`brew install chromium --no-quarantine` which installs it at - `/opt/homebrew/bin/chromium` and has the Chromium app in Applications folder as well.

**Note** - without the `--no-quarantine` MacOS's Gatekeeper prevents the app from running.

Hope this help!
