### ISSUE TITLE
CanvasRenderingContext2D vs ConvasContext causes breaking change (upgrading to 4.0.1)

### ISSUE THREAD

**Issue by andiejs** [0xfe/vexflow#1467]
Hi, I'm trying to upgrade from 3.0.9 to 4.0.1. I read the "breaking changes" doc here https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.0 and I seem to be encountering a breaking change not mentionned.

I'm running this vexflow code and getting differently typed results under the two versions:

var renderer = new Vex.Flow.Renderer(cnv, Vex.Flow.Renderer.Backends.CANVAS);
this.ctx = renderer.getContext();

3.0.9 result:
CanvasRenderingContext2D {vexFlowCanvasContext: CanvasRenderingContext2D,  clear: ƒ, setFont: ƒ, setRawFont: ƒ, setFillStyle: ƒ, …}

4.0.1 result:
CanvasContext {textHeight: 0, context2D: CanvasRenderingContext2D, canvas: canvas}

My code is breaking because it's trying to call this.ctx.setTransform, which doesn't exist in 4.0.1

I'm trying to figure out how to update my code: what the types are and how to call the functions setTransform, translate, clearRect, etc. Is there any doc on this anywhere or can anyone give me a hint?

Thanks!

**Comment by AaronDavidNewman** [comment]
I'm not a canvas guy, but you should be able to go:

`this.ctx.canvas2d.setTransform(...)`

**Comment by andiejs** [comment]
Thanks. That doesn't get me that far though. 
All the types are wrong everywhere in my code, and it's not clear which need to remain CanvasRenderingContext2D and which should be CanvasContext. I can't just set this.ctx to this.ctx.canvas2D, because some functions are now through ctx.canvas2D (e.g. ctx.canvas2D.setTransform), while others are on ctx (e.g. ctx.openGroup). 

I should be able to hack my way through this so I'm not really asking for help here, unless someone can point to doc or a discussion that already exists -- and I would like to suggest that it deserves a mention under "breaking changes"!

**Comment by AaronDavidNewman** [comment]
3.0.9 was a javascript release, wasn't it?  And 4.x and up have been Typescript.  So I don't understand the 'types are wrong' part. 

`vexFlowCanvasContext` was renamed to `canvas2D`.  I think that is the only change to the interface in canvasContext.  vexflow API works the same in SVG and canvas, so any canvas-specific things you do would be outside the library.  And you can always find the canvas element because it will be inside the first argument to `VF.Renderer`.  You don't need the vexflow API for that.

**Comment by sschmidTU** [comment]
@andiejs I think you have to use vexflow's built-in types from the release now. Maybe you've been using types from DefinitelyTyped, they're obsolete in Vexflow >=4.
