### ISSUE TITLE
Wrong Placement of Annotation

### ISSUE THREAD

**Issue by StevenSchuerstedt** [0xfe/vexflow#1469]
Hello,
I'm working on a note editor using vexflow and one of its features is to analyze the music and display the name of the chords above the notes. I'm using annotations for this, but there is a weird error when the notes in the chord are spaced apart (like an ocvate) and the stems are pointing down. 
<img width="233" alt="image" src="https://user-images.githubusercontent.com/50596774/200810922-042f5701-8ac2-41b2-8bd5-90a2592f79cf.png">

I want the "Cmaj" annotation to be placed above the notes, therefore I'm using addModifier and setVerticalJustification(...TOP). This works fine for all other cases except this one. 

Here is a minimal example on jsfiddle: https://jsfiddle.net/0ov5316w/52/

Is this a bug or am I doing something wrong? Any help is appreciated! 
~Steven

**Comment by AaronDavidNewman** [comment]
I just saw this now...this looks like a bug having to do with the multiple notes in the chord and the stem direction.  If I change the middle chord so there is only the c5, it looks fine.

If you want chord symbols, you could try ChordSymbol module:

https://jsfiddle.net/AaronDavidNewman/yo2zmcug/

Meanwhile I'll have a look at this bug in annotation, maybe we need a test case for this.

**Comment by StevenSchuerstedt** [comment]
Hey, thanks for your input!
In the meantime I tried the ChordSymbol module and it works fine for this example, but if the notes are very high the error persists. (see https://jsfiddle.net/yLrotqpn/51/) 

I have the impression that in this configuration of low note / high note in a chord and the stem direction, the chord symbol is added to the lower note in the chord, and positions itself according to this. 

I tried to use setIndex() to add the modifier to the higher note, but with no effect. (I also tried setVertical(Top))
There is this function setNote() to attach the modifier to a specific note, but in this configuration the StaveNote is actually multiple notes? Is there a way to attach the modifier to one specific note in the StaveNote? I think this could solve the issue. If I remove the low note everything renders correctly.

**Comment by StevenSchuerstedt** [comment]
I also tried it with your smoosic editor, but with the same result. 

<img width="242" alt="image" src="https://user-images.githubusercontent.com/50596774/201888110-9a4d0996-ad47-40a1-8203-5c1526113fa2.png">

**Comment by StevenSchuerstedt** [comment]
so I looked at the source code of vexflow, at https://github.com/0xfe/vexflow/blob/master/src/chordsymbol.ts and changing 

`y = Math.min(stave.getYForTopText(this.text_line), note.getYs()[0] - 10);`
to
`y = Math.min(stave.getYForTopText(this.text_line), Math.min(...note.getYs()) - 10);`
solved the issue for me. I guess it makes sense to not use the first index of the y values exclusivly, but to check for the smallest, or use `this.index` for that.

**Comment by AaronDavidNewman** [comment]
You're hired!  I guess I never tried the obvious test case of high-note, stem down.  I must have copied the bug from annotation when I added ChordSymbol.  (the pitches in Note are sorted, so the final value should be the highest note/lowest Y).

I'll add that to the fix for this issue.  Thanks for digging in.

**Comment by StevenSchuerstedt** [comment]
great :) thanks for the quick fix and Im happy to help :))
