### ISSUE TITLE
FontFace not defined with generate:reference

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1474]
@ronyeh I hope you can help me in this one. I am going further with the Font Face API and I have found this problem

if you add the following line in `textfonts.ts`
```diff
export function loadTextFonts() {
+  Font.loadWebFonts();
  // Sans-serif fallback font, very close to Arial
  {
```

you get the following error when running `node run reference` and `node run test:reference` while generating the png files

```
            const fontFace = new FontFace(fontName, woffURLs);
                             ^

ReferenceError: FontFace is not defined
```

**Comment by ronyeh** [comment]
Does that line build fine if you just run grunt?

What is different when you run grunt reference?

It is possible that FontFace is not declared or supported in all environments yet. For example, I remember some versions of TypeScript didn't include FontFace in the type declarations.

**Comment by ronyeh** [comment]
For example, here I commented that some typescript versions might not know about fontface. 

https://github.com/0xfe/vexflow/blob/bcf0f48bc287651fe56e3fd0594732d5940a056a/src/font.ts#L332


The function was designed to be called at runtime in the browser environment, where FontFace is available. 

What is your goal? Why do you need to call loadwebfonts there?

**Comment by rvilarl** [comment]
> Does that line build fine if you just run grunt?

yes

> What is different when you run grunt reference?

nothing this one also runs fine. The problem is the genartion of the files to find out the diffs. The call to grunt generate:current

> For example, here I commented that some typescript versions might not know about fontface.
> 
> https://github.com/0xfe/vexflow/blob/bcf0f48bc287651fe56e3fd0594732d5940a056a/src/font.ts#L332
> 
> The function was designed to be called at runtime in the browser environment, where FontFace is available.
> 
> What is your goal? Why do you need to call loadwebfonts there?

Just to show the error. I has made already a lot of changes to use font directly and I wanted to make a minoe change shiwub th issue

**Comment by AaronDavidNewman** [comment]
This is probably happening because the image generation runs in a node context, not a browser context.  So if it's possible to check, we should skip the tests that use FontFace in that case.  Sorry if that's just stating the obvious.

**Comment by ronyeh** [comment]
Might be relevant.

https://github.com/jsdom/jsdom/issues/2698

That issue also references two other issues related to loading web fonts.

Our test generation scripts use things like jsdom or node canvas, so it's
possible that FontFace API isn't supported there, as Aaron points out. You
can probably make a minimal reproduction in jsdom to verify this.

**Comment by rvilarl** [comment]
@ronyeh @AaronDavidNewman thanks for your help, I will try to find a way to get it running.
