### ISSUE TITLE
Gootville SMuFL

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1475]
_gootville The [Gonville](http://www.chiark.greenend.org.uk/~sgtatham/gonville/) fonts for score musical symbols. This font is modified and maintained by the MuseScore project._

I propose to replace Gonville by Gootville in order to make all the fonts SMuFL compliant. 

This will allow to use the OTF font file directly. Gonville symbols are not in the SMuFL unicodes. 

Gootville is licensed under the SIL Open Font License.

**Comment by sschmidTU** [comment]
Does Gootville look the same as Gonville? Otherwise if replaced this will be a breaking change for Gonville users who will have to change the look of their scores.

**Comment by rvilarl** [comment]
I would say very similar, I like Gootville flags better. The only big difference that I have seen is in TAB. Some examples below (first Gootville)
**Flags**
![Accidental Accidental_Arrangement_Special_Cases Gonville_current](https://user-images.githubusercontent.com/22865285/204018978-10bb8176-ffd3-4af2-8f13-416df417c866.png)
![Accidental Accidental_Arrangement_Special_Cases Gonville_reference](https://user-images.githubusercontent.com/22865285/204018982-6c7d9d22-7902-4ad6-9043-26f8c599fffc.png)
**Articulations**
![Articulation Articulation___Accent_Tenuto Gonville_current](https://user-images.githubusercontent.com/22865285/204019792-abcc7a7c-5fb3-44e2-88f2-f6a16d31eed8.png)
![Articulation Articulation___Accent_Tenuto Gonville_reference](https://user-images.githubusercontent.com/22865285/204019795-c5506768-f343-4982-8640-91b9371d227f.png)
**TAB**
![Annotation Simple_Annotation Gonville_current](https://user-images.githubusercontent.com/22865285/204020087-ce9e32b8-193c-4f17-95e0-acb6d3d92e32.png)
![Annotation Simple_Annotation Gonville_reference](https://user-images.githubusercontent.com/22865285/204020089-f617de16-b684-47f9-a152-8c520cdb0a24.png)

**Comment by AaronDavidNewman** [comment]
Can you link to the Gootville font repository and license?   I did some googling but got a few different versions that didn't seem complete.

**Comment by rvilarl** [comment]
https://github.com/musescore/MuseScore/tree/master/fonts/gootville

**Comment by acidjunk** [comment]
The gootville font seems a bit less crispy (noticed it -> especially in the 16th flag)

Could be my eyes.

**Comment by AaronDavidNewman** [comment]
There are OTF versions of Gonville.  Would those work?  Or would we need to re-map the codes to make it SMUFL to read the OTF directly?

I think people will always be sentimental about Gonville as a Lilypad link.  Although personally I like Gootville better - the original is a little light for my taste for some of the modifiers.  

I like that it has its own text font - it would mean all the major engraving fonts have a text font to pair with by default.

**Comment by rvilarl** [comment]
> There are OTF versions of Gonville. Would those work? Or would we need to re-map the codes to make it SMUFL to read the OTF directly?

The problem is that the Glyphs are not mapped to unicode as per SMuFL spec, this is why we have `fontgen_gonville_custom.js` and the `valid_codes.js` mapping.

**Comment by rvilarl** [comment]
> The gootville font seems a bit less crispy (noticed it -> especially in the 16th flag)
> 
> Could be my eyes.

More examples on flags (Gootville above)

![StaveNote Flag_and_Dot_Placement___Stem_Up Gonville_current](https://user-images.githubusercontent.com/22865285/204025577-522eb93f-7352-429d-aa6a-800c713864de.png)
![StaveNote Flag_and_Dot_Placement___Stem_Up Gonville_reference](https://user-images.githubusercontent.com/22865285/204025579-683f4cec-9f90-4c76-af22-b24164f2a07e.png)

**Comment by rvilarl** [comment]
**Bravura**
![StaveNote Flag_and_Dot_Placement___Stem_Up Bravura](https://user-images.githubusercontent.com/22865285/204026177-86ce55f7-e961-4e9e-b2b3-3127e02541ec.png)
**Gootville**
![StaveNote Flag_and_Dot_Placement___Stem_Up Gonville](https://user-images.githubusercontent.com/22865285/204026180-48c981f7-a233-4604-9b54-1fec589a047a.png)
**Petaluma**
![StaveNote Flag_and_Dot_Placement___Stem_Up Petaluma](https://user-images.githubusercontent.com/22865285/204026182-178705e0-5b60-4e16-bfe8-314dc055c373.png)
**Leland**
![pptr-StaveNote Flag_and_Dot_Placement___Stem_Up Leland](https://user-images.githubusercontent.com/22865285/204026184-df2b38ca-7f2e-4fc8-ae5b-bea3b13073a5.svg)

**Comment by acidjunk** [comment]
I like the font.

**Comment by sschmidTU** [comment]
The flags are quite a bit thicker than Gonville as well. It looks good, but it may not always be desired.

**Comment by ronyeh** [comment]
Now that we have Gonville as SMuFL, do we still need Gootville since it is very similar?

<img width="950" alt="S 2022-12-16 at 13 02 26 " src="https://user-images.githubusercontent.com/239113/208188528-4800b340-95ae-4a88-9228-3749214394bd.png">

I downloaded MuseScore 4 today, and the font page lists Gonville and GonvilleText. Is it actually Gonville that they use, or is it secretly Gootville but they call it Gonville??

**Comment by ronyeh** [comment]
https://github.com/musescore/MuseScore/blob/cf7e523f726d580ba6c381936c023babd996406d/src/engraving/engravingmodule.cpp#L100-L107

The code shows that they actually use Gootville but just call it Gonville.

In our case, since we have a SMuFL-ized version of Gonville, I don't think we need Gootville since it is redundant (and MuseScore considers it "Gonville" anyways).

**Comment by rvilarl** [comment]
> I downloaded MuseScore 4 today, and the font page lists Gonville and GonvilleText. Is it actually Gonville that they use, or is it secretly Gootville but they call it Gonville??

yes,  we do the same now with GonvilleSmufl
___
De: Tantacrul <info.tantacrul@gmail.com>
Date: mié, 7 dic 2022 a las 12:08
Subject: Re: Gonville
To: Rodrigo Vilar <rvilarl@gmail.com>


Hi there,

Yes, I'm referring to Gootville (although that's just its filename - we call it Gonville in MuseScore because it pretty much is). I'm unsure how much it was altered when moved over to MuseScore. However, since we've put a good bit of effort into making sure it aligns to the SMuFL spec - and have tested it a lot, it might be a nice reference for you.

What I'd advise is just taking that work we've done (including the JSON) and replacing whatever symbols you don't like. It'd be much faster than making the whole thing (and testing it) from scratch. But it's completely up to you!

I've asked our engraving expert to put Gootville up on GitHub so you can grab it.

Thanks!
Martin

On Tue, 6 Dec 2022 at 22:11, Rodrigo Vilar <[rvilarl@gmail.com](mailto:rvilarl@gmail.com)> wrote:
Hi Martin,

Do you refer to Gootville? I proposed to use that in VexFlow as Gonville replacement but there were concerns related to some different Glyphs.
If there is a Gonville could you point me to the location of the files? Thanks!

Regards,
Rodrigo
___

**Comment by rvilarl** [comment]
Regarding Gootville, the flags and other glyphs are quite nice. I would vote to support it.

**Comment by rvilarl** [comment]
Gootville already supported in vexflow5 branch
