### ISSUE TITLE
Some duplicated images when running grunt test:reference

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1483]
Currently, the `Gruntfile.js` runs `generate_images.js` without specifying the `--backends` option.

This means that we generate images with both JSDOM and Puppeteer.

This results in some duplicate work. For example, in the `build/images/current/` folder, we have:

```
Rests.Dotted.Gonville.png
pptr-canvas_Rests.Dotted.Bravura.png
pptr-Rests.Dotted.Bravura.svg
pptr-Rests.Dotted.Bravura.svg.png
pptr-Rests.Dotted.Gonville.svg
pptr-Rests.Dotted.Gonville.svg.png
pptr-Rests.Dotted.Leland.svg
pptr-Rests.Dotted.Leland.svg.png
pptr-Rests.Dotted.Petaluma.svg
pptr-Rests.Dotted.Petaluma.svg.png
Rests.Dotted.Bravura.png
Rests.Dotted.Petaluma.png
```

`pptr-Rests.Dotted.Petaluma.svg.png` and `Rests.Dotted.Petaluma.png` are nearly visually identical, which is a good thing. :-)

But perhaps this means we can turn off jsdom when generating these test images, and use pptr exclusively. That might speed up the testing process a bit.

**Comment by rvilarl** [comment]
I agree, it would be better one default method and not three, when no method is selected.
