### ISSUE TITLE
4.2.0 bugs

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1496]
I have gone through the tests and I found some errors, some of them already present on previous versions.

**Comment by rvilarl** [comment]
**Lower Pizzicato orientation** 
**Gonville - WRONG**
![Articulation Articulation___Snap_Pizzicato_Fermata Gonville](https://user-images.githubusercontent.com/22865285/208477471-87c1b470-6a60-41da-ac7c-93602e70bd4b.png)
**Bravura - RIGHT**
![Articulation Articulation___Snap_Pizzicato_Fermata Bravura](https://user-images.githubusercontent.com/22865285/208477473-67a99887-10b0-40c4-9222-ac478cdd7997.png)

**Comment by rvilarl** [comment]
**Arrow alignment**
**Gonville - WRONG**
![StaveNote Center_Aligned_Note_with_Multiple_Modifiers Gonville](https://user-images.githubusercontent.com/22865285/208479490-cb8b4a01-f623-4d5b-bf2c-958d9211a6d9.png)
**Bravura - RIGHT**
![StaveNote Center_Aligned_Note_with_Multiple_Modifiers Bravura](https://user-images.githubusercontent.com/22865285/208479494-0d4ef200-12ff-4a21-8590-4e12fa0c6caf.png)

**Comment by ronyeh** [comment]
Thanks!

I just published 4.2.0 beta by the way. Let's include these bug fixes in the 4.2.0 release. I think we can continue to fix bugs in the 4.2.x and 4.x releases, and continue our bigger features (Gootville, FontFace, etc.) in the 5.0 branch (maybe we'll call the 5.x branch `main`).

**Comment by rvilarl** [comment]
**Very short fermata (#1495)**
**Gonville - WRONG**
![GlyphArticulation GlyphArticulation___Vertical_Placement Gonville](https://user-images.githubusercontent.com/22865285/208291710-3dcad9c2-be7d-4546-b54f-1885dc125069.png)

**Bravura - RIGHT**
![GlyphArticulation GlyphArticulation___Vertical_Placement Bravura](https://user-images.githubusercontent.com/22865285/208291711-6a9c7d4b-9638-43e4-ae1c-186a20706980.png)
