### ISSUE TITLE
Softmax Default

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#1502]
Hello -- we've had a lot of discussions about more substantial refactors to the formatting/softmax algorithms, and these should continue etc.  But one thing keeps getting lost: everyone seems to be in agreement that the current default softmax of 100 is really not good.  

Discussions of where to put that default have ranged from 5 to 15 (#1352 ) -- before looking at the discussions, I found for music21j a sweet spot at 10.  definitely 1 and 2 are too low, and 100 is way too high.  I don't really care where it ends up between 5 and 15, but if we're all in agreement to switch to something like 10, update the visual tests, and then work on the bigger problem later, this would be really great.  Thanks!

**Comment by AaronDavidNewman** [comment]
I use 2 as default in the vexflow fork I use for Smoosic (which is probably why I lost track of it for the main branch).  I don't know that 2 is too low...intuitively, it always seemed like the ideal would be somewhere between 1 and 2.  But it seems like we require it to be an integer - maybe `pow()` works better with integers?   I should know things like this, but I don't.

But yes, 100 is too high.  No objections here for changing it.  Most formatting tests specify the softmax so those won't change.  And many of our other unit tests don't use formatting at all.  There will be minor changes for tests like bach, easyscore etc.

**Comment by sschmidTU** [comment]
Definitely seconding a reduction of default Softmax value.
With my testing of mid-2020, 15 seemed like the sweet spot, though that was with Vexflow 3.

From my code comments:
```ts
  // 15 seems like the sweet spot. Vexflow default is 100.
  // if too high, score gets too big, especially half notes. with half note quarter quarter, the quarters get squeezed.
  // if too low, smaller notes aren't positioned correctly.
```

I do remember that a too low softmax (e.g. 2) leads to other issues ("smaller notes aren't positioned correctly").

In any case, I'd have to do some new testing with the current vexflow to make sure of anything concrete.

**Comment by mscuthbert** [comment]
> intuitively, it always seemed like the ideal would be somewhere between 1 and 2. 

That's what I would have thought also, but experimentally, 2 gave too little distinction between half notes and eighth notes, etc.

(I was going to mention another issue that happens if like me you make measures be individual Stave objects and run formatter on a measure stack is that the spacing should attempt to be consistent within a system not just within a measure, but I don't want to side track).

We now have votes for 2, 5, 10, 15 -- arithmetic mean would be 8; geometric is 6.

Note that any change to the default will not affect any of us who do our own tweaking; it'll just affect people who don't know about softmax configuration and get them something that is vaguely plausible.  -- I'll make a PR for 8 and we can tweak in future versions?
