### ISSUE TITLE
Too much space after percussion clef

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#1504]
In the default font set on Vexflow 4.1, there is much too much space after the percussion clef and before the key/time signature compared to 1.2.9, looking a bit like something is meant to go there and is missing:

<img width="185" alt="Screenshot 2022-12-27 at 14 17 09" src="https://user-images.githubusercontent.com/3521479/209738848-cc8540df-f10b-4de8-8e97-aedfe04733fe.png">

Just doing a lot of visual regression testing -- 95% are improvements or at least a matter of taste.  Will be flagging the things that I think are a step backwards.

**Comment by mscuthbert** [comment]
The problem seems to be in the Clef constructor in clef.ts:

```
  constructor(type: string, size?: string, annotation?: string) {
    super();

    this.setPosition(StaveModifierPosition.BEGIN);
    this.setType(type, size, annotation);
    this.setWidth(Tables.currentMusicFont().lookupMetric(`clef_${this.size}.width`));
    L('Creating clef:', type);
  }
```

The width for the clef is defined only by the clef size, not the actual clef.  When multiple clefs are used simultaneously on different staves, then it makes sense to take the size from the largest clef, but when only a percussion clef is used, that max width is too much.

**Comment by rvilarl** [comment]
@mscuthbert what font are you using? could you add the associated test?

**Comment by mscuthbert** [comment]
I'm still learning how to make the images with the new generation system.  :-)  I'll follow up soon.  It's whatever the default font loaded w/ Vexflow 4.1 is (Gonville SMuFL?)

**Comment by rvilarl** [comment]
@mscuthbert are the tests in `Clef Keys´ a real use case. Does it make sense to have different keys one after another in the same measure?

**Comment by mscuthbert** [comment]
> @mscuthbert are the tests in `Clef Keys´ a real use case. Does it make sense to have different keys one after another in the same measure?

It doesn't make sense in an actual musical piece, but it makes a lot of sense for some of the other major purposes of Vexflow, for instance didactic training to see a bunch of key signatures and have students label their key underneath.  I think that having a separate test where there's a whole note, barline, keychange, another whole note, barline, etc. would be a little more realistic (but again, still not something you'd normally see in music).
