### ISSUE TITLE
Unison noteheads too aggressive

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#1507]
(Vexflow 4 regression)

VF4 (3?) allows for StaveNotes in different voices to be formatted so that they can share noteheads in certain cases in the great #1263 PR.  I've noticed however that the algorithm is somewhat too aggressive.  I've just been looking at the two-voice code so far.

It checks for stemmed vs unstemmed, notes vs rests, white noteheads vs black, number of dots, but there are a number of things that are not yet working that I think needs a partial rewrite (started in "fix_unison_noteheads" branch).

(1) start with a conservative approach: assume notes with any overlap cannot be at the same xShift unless proven innocent.  :-)  That's the biggest change that seems to be the major change here.

(2) the method of counting number of Dot modifiers on each note and seeing if they are equal is not robust enough.  Here a two-note chord (F-C) with one dot on each note is merged with a single double-dotted C.

![Screenshot 2022-12-28 at 16 29 50](https://user-images.githubusercontent.com/3521479/209895444-69691b48-f4e8-4fee-8d46-966c9c1f8913.png)

(3) different notehead glyphs except for white vs. black noteheads are not taken into account.  Harmonics must be shifted from regular notes, etc.  (whole notes and breves seem to work great except that the shorter note should be the one shifted right):

![Screenshot 2022-12-28 at 16 47 27](https://user-images.githubusercontent.com/3521479/209896706-9cd02265-6994-4ddc-b61c-0e59f7dfc5b7.png)

(4) noteheads with different styles (colors, etc.) should not share the same notehead.

(5) (very important): notes with different accidentals should never share a notehead unless either both accidentals are displayed and the notes are the exact same duration/lyrics/instrument/etc. (so it doesn't matter which accidental goes with which note).

Gould 55-60 shows how many cases are ambiguous.  Thus one of the most important things we can do is have a system where these formatter rules can be turned on and off (on a per note and system-wide setting).  Probably my first PR will just be to add a way of disabling the unison notehead setting.

When it's done right, sharing a notehead is very cool, so super thankful for OSMD and @rvilarl for implementing; but it's never absolutely necessary, so I wonder if we can walk back a little bit on this until bugs are worked out a bit more.

(note that rules for notehead sharing are very different for keyboard/harp music; there noteheads are shared more aggressively.  See Gould 307-8; but this is given as an exception not the general rule)

Thanks!

**Comment by sschmidTU** [comment]
2-5 seem like they aren't that difficult to implement, so it should be possible to resolve this issue with that rather straightforwardly, right? All of these seem like very rare cases, and of course we should also fix those, though it seems to me it's better to have a very useful improvement for most cases, then fix it for the very rare and specific cases.

**Comment by mscuthbert** [comment]
I'm not sure they're that rare, especially in online UX where color, size, etc. helps to make it obvious to the user what is being edited, etc.  We're a long way from Vexflow being the best system for pure notation presentation like a book; it is, however, the best (open source) system for creating interfaces.

The difference between starting with a conservative set of notes that can be merged versus assuming they can and they counting differences is that it is always acceptable to write separately two notes which could share a notehead.  Whereas making a mistake and merging notes that cannot share a notehead makes the passage either unplayable or very difficult to read. Over time we're going to keep coming up with more cases where they cannot share a notehead (my wife just came up with cue-sized notes vs. full-sized notes).

**Comment by rvilarl** [comment]
I would suggest to make it configurable (enabled/disabled) and to increase the test cases to cover and fix the unsupported scenarios.

**Comment by sschmidTU** [comment]
> I'm not sure they're that rare

Ok, I'll specify: 2-3 and 5 seem very rare to me, in the context of what most users see.

I would also in case of doubt make it configurable (enabled/disabled, or maybe safe/unsafe).
For OSMD, the benefit already outweighs the rare issues.

**Comment by rvilarl** [comment]
> (3) different notehead glyphs except for white vs. black noteheads are not taken into account. Harmonics must be shifted from regular notes, etc. (whole notes and breves seem to work great except that the shorter note should be the one shifted right):

@mscuthbert the rule "the shorter note should be the one shifted right" is not followed in many examples in BB. Can you look into that and confirm if the rule is right?

**Comment by mscuthbert** [comment]
> @mscuthbert the rule "the shorter note should be the one shifted right" is not followed in many examples in BB. Can you look into that and confirm if the rule is right?

I can't remember where I found that and couldn't find it looking in BB quickly -- it's mostly about the breve and whole note which is pretty rare admittedly.  With the stems (and especially with beams) it's easy to see which part goes which which so it matters much less (and stem placement rules override), but without stems (breves and wholes) it shows that the player reading the note on the right is most ready to take over the next note that's encountered.

It's not a big deal compared with the other options (or just a universal "turn off" mode)

**Comment by rvilarl** [comment]
@mscuthbert all the other cases and the turn off are already in #1545, have you seen it? I would also like to get your feedback there on the unison with different accidentals
