### ISSUE TITLE
StaveNote not defined?

### ISSUE THREAD

**Issue by zgaus11** [0xfe/vexflow#1518]
I even copied and pasted the example from the VexFlow tutorial and the staff shows up but the notes do not. I get "StaveNote is not defined" in the console.

I am using vscode and the p5.js library if that matters.

I imported the library from the URL in the HTML not npm install.

Is it a problem with the draw loop and the setup loop in p5.js?

I am new to programming and would appreciate any help!

**Comment by rvilarl** [comment]
Hi, it would help if you share the example/code that you use. The best would a jsfiddle.

**Comment by rvilarl** [comment]
@zgaus11 I am closing the issue, please re open with further details if you want us to look into it
