### ISSUE TITLE
Possible to play as audio?

### ISSUE THREAD

**Issue by Jerydeak** [0xfe/vexflow#1543]
Is it possible to play the notes as audio via VexFlow? (e.g. MIDI)

**Comment by rvilarl** [comment]
> Is it possible to play the notes as audio via VexFlow? (e.g. MIDI)

No VexFlow does not provide a play feature. Look into
https://github.com/AaronDavidNewman/Smoosic
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay (version for sponsors)
https://github.com/rvilarl/pianoplay
