### ISSUE TITLE
Custom glyphs: microtonals

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1558]
It seems that vexAccidentalMicrotonal1, vexAccidentalMicrotonal3, vexAccidentalMicrotonal4 are not supported by SMUFL. I would suggest to drop the support.

See https://github.com/w3c/smufl/issues/272

@mscuthbert @AaronDavidNewman @sschmidTU @ronyeh @0xfe what do you think?

**Comment by sschmidTU** [comment]
They aren't used in OSMD (so far).
In general I would prefer features, options and customizations not to be dropped just to conform to SMUFL, but these symbols in particular are probably not going to be used.

**Comment by rvilarl** [comment]
Not needed in 4.0
