### ISSUE TITLE
Custom glyphs: noteheads

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#1559]
The custom glyphs define:
- vexNoteHeadRectBlack & White which are very similar to the standard SMUFL noteheadSquareBlack & White, and 
- noteheadSquareBlack & White which differ significantly from the standard (to make them square)

The SMUFL glyphs (ie Bravura) define:
- noteheadSquareBlack & White which are more like a rectangle.
- noteheadSquareBlackLarge & WhiteBlack which are squares but significantly better.

Custom Glyphs
![image](https://user-images.githubusercontent.com/22865285/231724544-2d8227fb-a130-4445-bd9c-a0ee9df9729f.png)

SMUFL Glyphs (Bravura)
![image](https://user-images.githubusercontent.com/22865285/232288064-d1ce4aca-34be-4c52-9f0e-26aeffcc02bb.png)

**Comment by rvilarl** [comment]
I vote to use the standard ones although the ones which are square, are much bigger, but at least, they make a difference

SMUFL Glyphs
![pptr-canvas_NoteHead Drum_Chord_Heads Bravura_current](https://user-images.githubusercontent.com/22865285/232288181-4c526449-7dfa-4459-963d-ab76403013c2.png)
Custom Glyphs
![pptr-canvas_NoteHead Drum_Chord_Heads Bravura_reference](https://user-images.githubusercontent.com/22865285/232288182-3357eda7-d613-4920-89b2-777a67bc3654.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman @sschmidTU @ronyeh @mscuthbert @0xfe what do you think?

**Comment by sschmidTU** [comment]
I don't know, doesn't make sense to me that they are so big. They are bigger than any other notehead glyph, and I don't see a reason for that. Other rare notehead glyphs are also small, so it's not for readability.
I would prefer keeping the small size.

**Comment by ronyeh** [comment]
Does anyone use these custom glyphs? If we cannot find a suitable SMuFL replacement, and they are required for some reason, can we programmatically draw the custom noteheads? The ones in question are just rectangles.
