### ISSUE TITLE
Indices vs Indexes

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1568]
Both are used in the vexflow codebase. We should standardize. "Indices" is used more often in our codebase.... but both are technically correct.

https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/i/index-indexes-indices

I would personally prefer "indexes" because if I do a code base search for "index" I would also prefer that lines containing "indexes" also show up. Currently, it doesn't match "indices" so I'd have to do a second search to find lines with "indices".

**Comment by rvilarl** [comment]
I would also go for indexes.

**Comment by sschmidTU** [comment]
+1 for indexes, it's more clear for non-native speakers as well. (plus the search argument)
(even as someone who likes Latin, indices being the Latin plural, I prefer pragmatism, and both plurals are valid for a reason)

**Comment by mscuthbert** [comment]
My general preference is for indices (except for things like multiple tables of contents which I've been told are properly called indexes from someone in the know) but the "find" functionality argument outweighs this preference (and non-native speakers), so go with indexes!

**Comment by rvilarl** [comment]
Done in https://github.com/vexflow/vexflow/tree/vexflow5

**Comment by rvilarl** [comment]
Considered in https://github.com/vexflow/vexflow
