### ISSUE TITLE
Flow.html dropdown does not show all unit test modules.

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1570]
There is some nice new styling for qunit, but the modules dropdown now I can't access many test cases from the 'module' dropdown. I tried it in both Chrome and Firefox on windows 11.

This is changeset from master https://github.com/0xfe/vexflow/commit/fff37a0e55cd980c41c0d4c5d82a64c747bf0599 dated 5/21.

![image](https://github.com/0xfe/vexflow/assets/5438280/b23a24a0-27c3-45cc-be4a-f0e920e930d0)

**Comment by ronyeh** [comment]
Thanks for the report. @rvilarl can you look into this? This is related to your PR https://github.com/0xfe/vexflow/pull/1562

I have verified this bug on my own build. For example, there is no easy way to filter by the Voice module.

**Comment by ronyeh** [comment]
For a temporary workaround, @AaronDavidNewman 

You can add a module query param to the flow.html webpage:

`flow.html?module=voice`

**Comment by ronyeh** [comment]
@rvilarl For an example of what it used to look like, see:

https://unpkg.com/vexflow@4.1.0/tests/flow.html

I notice that flow.html now points directly to the qunit files in `node_modules/`.

This works fine for local testing, but it breaks the ability to have the tests running on unpkg.com (as seen above). We will need to figure out a way to package up & release the qunit files for the NPM release of 4.2. I'll open up a bug for this.

**Comment by ronyeh** [comment]
https://github.com/0xfe/vexflow/pull/1562/commits/68a1e90f219ff5bc9e0078122eaaa22576da14f6#diff-e2e19576662ee6740f166cf6679fe835507a68b592654b613ab64dc7d401cf5cR150-R154

This is what I mean. Referring to the qunit files inside node_modules/ is fine for local testing but may break some things (like our NPM release). Will have to figure this out.

**Comment by rvilarl** [comment]
There is another related to the scroll of the unit tests. The tests can be selected eriting on the text box. But I agree that the lack of scroll bars is no good.

**Comment by ronyeh** [comment]
I examined the dom with chrome inspector and it looks like the other
modules don't even have check boxes. Is there a limit to the number of
modules that will be shown? Maybe the qunit upgrade needs another line of
code to tell it to show all modules.

**Comment by ronyeh** [comment]
I've assigned the two most recently discovered issues to me and you (@rvilarl).

Let's clean up the small issues so we can get 4.2 shipped.
