### ISSUE TITLE
VexFlow 4.2

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#1576]
@rvilarl @mscuthbert I haven't seen any recent new bug reports.... So I propose going ahead with the release of 4.2  later this week. 

If anything comes up, we can always patch in 4.2.1. I think there are some bugs with the flow.html test page that we can fix in 4.2.1.

@rvilarl it would also be nice to have a wiki page summarizing the biggest changes from 4.1 to 4.2. Since you were the lead developer for 4.2, can you write up a short wiki page? You can also link to related closed PRs, or include GIFs to illustrate the changes, since some of the bigger ones are visual changes. 

After this release.... 4.x will go into long term maintenance mode. We will go ahead with 5.x but will patch any important bugs that come up on the 4.x branch.

**Comment by rvilarl** [comment]
@ronyeh thanks a lot! I will do. I am also looking forward to moving to 5.x. And no thought 4.x has to be maintained.

**Comment by mscuthbert** [comment]
Sounds good to me. 

I'm off all my various open source projects for a bit so tag me if you ever need my review.

**Comment by ronyeh** [comment]
Hi everyone.

Released!

Thanks @rvilarl for much of the hard work pushing VexFlow forward!

Test it out with:

```
npm install vexflow
```

I had a small hiccup so it has been released as **version 4.2.1**:

I detailed the steps I took here: https://github.com/0xfe/vexflow/wiki/Release-4.2

If you have a chance, please check it out and give us any feedback (and bug reports).

🤞 If there are any regressions since 4.1, we will try our best to fix them. 🤞


Tagging:
@0xfe @mscuthbert 
@AaronDavidNewman @sschmidTU

**Comment by 0xfe** [comment]
Yay! Great job Rodrigo and everyone! 🎉

**Comment by rvilarl** [comment]
> @rvilarl it would also be nice to have a wiki page summarizing the biggest changes from 4.1 to 4.2. Since you were the lead developer for 4.2, can you write up a short wiki page? You can also link to related closed PRs, or include GIFs to illustrate the changes, since some of the bigger ones are visual changes.

@ronyeh see https://github.com/0xfe/vexflow/wiki/Changelog-ver-4.2
