### ISSUE TITLE
Spacing of 2nds with accidentals

### ISSUE THREAD

**Issue by gristow** [0xfe/vexflow#1578]
A chord of a 2nd, with an accidental on either or both notes, takes extra unnecessary x space when the notes are in the top half of the staff. See [this fiddle](https://jsfiddle.net/gristow/wzr9y1u0/9/).

<img width="189" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/ef9afd7f-efe8-42ca-84a8-8952718c12cf">
<img width="202" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/c0679e67-31e5-45f4-ac3c-78eda2a12fd2">

Compared to:
<img width="165" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/cc7e77a2-25fb-4fea-bdc3-151f10a30015">
<img width="168" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/cd50964d-a17b-4352-988e-6c8ab6fa34d3">

I'm swamped right now, and won't have time to look into this for a while. But if anyone has quick ideas about where the issue might be coming from in the codebase, I can do some tracking!

**Comment by mscuthbert** [comment]
Almost certainly related to stemming code -- did you happen to see if the same thing happens with half notes/quarters/etc. or is it something specific to whole notes?

**Comment by gristow** [comment]
It also happens with half notes/quarters:
<img width="155" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/07dede13-f705-4e65-b237-8916ed3b5768">
<img width="189" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/0e870651-1c86-4426-8118-a05c602d63b9">

**Comment by gristow** [comment]
And interestingly it doesn't happen with intervals other than a 2nd:
<img width="175" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/ed4f48e2-6396-4851-b0a6-a7fec23725ed">
<img width="175" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/c6fd10bf-782f-45ed-bbf3-1c6363e0d2b6">

I've got a spare hour, and now I'm intrigued, so I'm going to go ahead and dive into debugging this.

**Comment by mscuthbert** [comment]
Is it the same if the lower note has the accidental?

What if it's a three note cluster? 

It definitely has something to do with the code where the stem is moved right and one note head is flipped to the opposite side. 

Another thing to check is to have a second staff (or voice if it's far enough away vertically to not interfere) and see if the alignment of the two staves gets messed up (in other words, does Formatter know where the note actually is, or is that information wrong)

**Comment by gristow** [comment]
Progress report:
I tracked the problem down to faulty code in `accidental.ts`, relating to double counting the extra left pixels needed when a notehead is shifted left on a down stemmed note. I've fixed that.

Once fixed, visual regression tests for `StringNumber` started failing. This caused me to assume I'd made an error in my fix. After much hair pulling, I realized that, in fact, fixing `accidental` revealed a bug in `StringNumber` that was not caught by the existing visual tests. When added to a down-stemmed 2nd chord, `StringNumber` correctly updates modifier state to provide itself enough left x space, however, it doesn't update it's own starting x to take advantage of that.

See [fiddle](https://jsfiddle.net/gristow/wzr9y1u0/).

<img width="253" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/623fe546-1e85-441b-a0c0-7a05d161e976">

*Because of the accidental bug, everything is too far to the right. But this creates space for the string number.*


<img width="237" alt="image" src="https://github.com/0xfe/vexflow/assets/8905340/eca8cb42-2cdf-45bc-8ce2-e85752649c94">

*When no accidentals are present, we see that there is also a bug in string number.*

I should be able to get a fix for that at the same time.

**Comment by gristow** [comment]
Ok, PR coming shortly. Here are the changes in the visual regression tests:

New:
![pptr-canvas_Three_Voice_Rests Three_Voices____3 Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/8a7d1a81-6b55-4478-8232-4cfcf55b6461)
Reference:
![pptr-canvas_Three_Voice_Rests Three_Voices____3 Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/7d77ab0d-d09a-440b-a24b-fad8eb4e7d67)

New:
![pptr-canvas_Three_Voice_Rests Three_Voices____2_Complex Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/dea0ead6-54f8-4531-af12-b3199520ab71)
Reference:
![pptr-canvas_Three_Voice_Rests Three_Voices____2_Complex Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/5f517a6c-213d-41f4-aa26-d35c78cbff2f)

New:
![pptr-canvas_Three_Voice_Rests Three_Voices____1 Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/98d82d48-9fff-46ee-95a1-4dbb8421c4d5)
Reference:
![pptr-canvas_Three_Voice_Rests Three_Voices____1 Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/8a21c85d-5d80-4c71-bd2d-24540c8655c6)

New:
![pptr-canvas_StringNumber String_Number_In_Notation___no_circle Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/2872bcc3-f667-450b-abdd-d4e513b161a5)
Reference:
![pptr-canvas_StringNumber String_Number_In_Notation___no_circle Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/8a34373d-e563-4ca8-859b-2b2ec2e3e886)

New:
![pptr-canvas_StringNumber String_Number_In_Notation Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/f2ab32d1-aa88-48d8-993e-2ee3b48ab794)
Reference:
![pptr-canvas_StringNumber String_Number_In_Notation Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/8be560c5-8405-4ad5-bd40-6e2764559877)

New:
![pptr-canvas_StringNumber Fret_Hand_Finger_In_Notation Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/824c2669-abbe-44c1-85cb-61744bd82eb8)
Reference:
![pptr-canvas_StringNumber Fret_Hand_Finger_In_Notation Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/f2fdd302-f51d-4980-b46c-af5a5bcddf3a)

New:
![pptr-canvas_StringNumber Complex_Measure_With_String___Finger_Numbers Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/88a9214c-c7df-4353-b26d-8a0b00a42323)
Reference:
![pptr-canvas_StringNumber Complex_Measure_With_String___Finger_Numbers Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/299c6d1a-be3f-4d78-be25-6f7770bd6719)

New:
![pptr-canvas_StaveNote Center_Aligned_Note_with_Multiple_Modifiers Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/293d0d53-e751-4759-9533-23e824b120bc)
Reference:
![pptr-canvas_StaveNote Center_Aligned_Note_with_Multiple_Modifiers Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/a0485f9f-3bb4-495e-9957-313e51bacbca)

New:
![pptr-canvas_EasyScore Draw_Parenthesised Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/c84cffe8-e634-4f96-a0e9-2069551f570f)
Reference:
![pptr-canvas_EasyScore Draw_Parenthesised Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/2cbca6b0-bec5-4b80-999a-f0432d2b9a18)

New:
![pptr-canvas_Accidental Stem_Down Bravura_current](https://github.com/0xfe/vexflow/assets/8905340/308bb667-434f-4483-a0ba-a9b630727c0d)
Reference:
![pptr-canvas_Accidental Stem_Down Bravura_reference](https://github.com/0xfe/vexflow/assets/8905340/ff36d497-9ac1-40f1-ae96-05952980cd0a)
