### ISSUE TITLE
Create accidentals programmatically in vex flow

### ISSUE THREAD

**Issue by radams52** [0xfe/vexflow#1584]
I have an array of notes.   #1)  let  notes = ['c/4', 'e/4', 'g#/4', 'a#/4']    
The standard code for entering notes is:    #2)    [new StaveNote({ keys: array, duration: "w" })]
However, to have an accidental show up on the chord render requires a modifier: 
                    #3)       [new StaveNote({ keys: array, duration: "w" }).addModifier(new Accidental(#), 2]
I want to take an array of notes and programmatically add the modifier for any accidentals that occur.   I can get to what appears to be the exact same code as number 3 above by iterating through the array to determine which notes/indexes require a modifier, and then joining the modifier fragment to the original code.  Even though the result looks the same as #3, an error message always occurs upon running:          
                   #4)    Formatter.FormatAndDraw         The error message is:      #5)   TypeError: t.shouldIgnoreTicks is not a function. (In 't.shouldIgnoreTicks()', 't.shouldIgnoreTicks' is undefined)
My question is about avoiding the error message.  I need to be able to have accidentals recognized and entered automatically with code.  EasyScore recognizes accidentals without a program change, but I'm using vex flow because of formatting issues with EasyScore.  Is there a way to turn off the 'tick' requirements causing this error message, or a different way to enter accidentals?
Any thoughts or suggestions will be appreciated.  

Code: 
const array = ['c/4', 'e/4', 'g#/4', 'a#/4'];
const neededCode = [new StaveNote({ keys: array, duration: "w" }).addModifier(newAccidental(#),2];  //this code works
const stringCode = 'new StaveNote({ keys: array, duration: "w" })'            //starting string without modifier     
const modFragments = [];
const finalCode = []

for (let i = 0; i < array.length; i++) {
  if (array[i].includes('#')) {
    modFragments.push(`.addModifier(new Accidental("#"), ${i})`);
  }
}
const newString = ('[' + stringCode + fragments[0] + fragments[1] + ']');      //should result in same code as #3 above
final.push(newString);      //   console.log(final) results in    new StaveNote({ keys: array, duration: "w" }).addModifier(newAccidental(#),2       which is the same as output for the working needed Code.  

Formatter.FormatAndDraw(context, measure, final);     // #5 error message above is received.  'measure' represents placement.

**Comment by AaronDavidNewman** [comment]
If you look in the test files in the vex repository, there are lots of examples of adding accidentals to chords and they don't receive any error.  accidental_tests.ts is a good place to start.  Your use of 'includes' does not seem correct here - it is an array method not a string method.  And I don't see why there is ${i}, i is a number so why not just i?  I'm not sure if these are the cause of your problem.

If you still see issues after looking at the unit test cases, please create a jsfiddle exhibiting the problem so we can look at it.

**Comment by radams52** [comment]
Thank you very much for your suggestions and quick response.  Looking at the tests you suggested provided me some direction about automatic accidentals.  I was able to find a solution from another post.          
 Example can be found here. (https://jsfiddle.net/wp7k9yrL/)
