### ISSUE TITLE
Is it possible to draw tuplet number closer to group beamings?

### ISSUE THREAD

**Issue by fablau** [0xfe/vexflow#1594]
Hello everyone.

I am using the [OSMD system](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay), which is based on Vexflow, and I have a problem that looks like it is related to Vexflow.

Look at the screenshot below, it is taken from a simple MusicXML file (attached in the .zip file below) and displayed via the OSMD demo located here:

https://opensheetmusicdisplay.org/demos/public-typescript-demo/

![VexflowSample](https://github.com/0xfe/vexflow/assets/10005316/bece332b-46e2-4232-b3de-7d3be30dbf10)

If you look at the 2nd, 3rd and 4th tuplet numbers are positioned far away from the beaming of their related group (I have marked those numbers with a red arrow).

Is there a way to fix that problem in Vexflow? Or is that something that has already been fixed in its latest version? As far as I know OSMD isn't using the last version of Vexflow, so that could even just be the case.

Any thoughts are very welcome.

Thanks in advance!

[tripletsTestOSMDT.musicxml.zip](https://github.com/0xfe/vexflow/files/12444072/tripletsTestOSMDT.musicxml.zip)

**Comment by rvilarl** [comment]
Hello @fablau OSMD is maintinig its own copy of VexFlow. This is based on an old release no longer maintained.

**Comment by fablau** [comment]
Thank you for your reply @rvilarl.

Are you saying that the newest versions of Vexflow no longer cause that issue?

Thanks again!

**Comment by AaronDavidNewman** [comment]
I think what you have displayed here is the same behavior as current vexflow.  I'd imagine that's the correct behavior, also, for a bottom tuplet.  Otherwise you'd have the tuplets in the staff, and that's no good.

In the later versions 1) bracket is supported, and 2) you can choose top or bottom for the number.  I'm not sure about the version you are using (and I don't know anything about OSMD).

**Comment by fablau** [comment]
Thank you @AaronDavidNewman for chiming in. I agree with you, better not to have numbers on the staff, but what about this solution, which is the correct compromise:

![sibEx](https://github.com/0xfe/vexflow/assets/10005316/f9fa4b49-ab7a-4bbb-aae5-9e4b474a252b)

Numbers are still off the staff, but the note lines and beamings are longer, so tho be closer to the number. The above example is from Sibelius notational program.

Your thoughts?

Thanks again.

**Comment by AaronDavidNewman** [comment]
I see, you're talking about the position of the beams.  This must be a bug that's been fixed in the meantime, this is how it looks in Smoosic (which uses ~4.2.2 build):

![image](https://github.com/0xfe/vexflow/assets/5438280/ee724ebb-f18c-444b-bf2c-ac7109331369)

**Comment by fablau** [comment]
That's fantastic! Thank you @AaronDavidNewman ! I'll see if the nice folks at OSMD can implement a newer version of Vexflow in some way... otherwise, I'll try to help to accomplish that ;)

Thanks again!

**Comment by AaronDavidNewman** [comment]
Closing as complete
