### ISSUE TITLE
Presentation of StaveNote keys in chords

### ISSUE THREAD

**Issue by newlandsvalley** [0xfe/vexflow#1597]
Does Vexflow require the keys in a chord to be presented in order - lowest pitch to highest?  This is perhaps what the Accidental tests seem to suggest. I am finding that if I present them in another order (say highest to lowest) then accidentals become attached to the wrong keys.

**Comment by rvilarl** [comment]
@newlandsvalley could you provide a jsfiddle with the error?

**Comment by newlandsvalley** [comment]
I think it is identical to this issue - https://github.com/0xfe/vexflow/issues/104.  From what I can make out from the comments, the keys do indeed need to be sorted lowest to highest.  Is this still true?  Is this behaviour documented anywhere?

**Comment by rvilarl** [comment]
This is no longer needed. StaveNote sorts the keys internally.  See sortedKeyProps in StaveNote. I am not sure though what is the index used in addModifier (sorted or unsorted)

**Comment by newlandsvalley** [comment]
Many thanks, @rvilarl. I think it only makes sense from the user's point of view if the index is to the original unsorted keys.  I'll try to investigate the very latest release and provide a jsfiddle as you suggest if I can still reproduce it.

**Comment by newlandsvalley** [comment]
OK - my application had been using Vexflow 4.0.2 where this behaviour happens, but it's fixed in v 4.2.3.  I'll close this issue.
