### ISSUE TITLE
stave.addKeySignature for bass clef without visible bass symbol

### ISSUE THREAD

**Issue by sfox-developer** [0xfe/vexflow#1603]
Hey there, first of all awesome work here, love it!

Issue/ Question
Is there a way to display the key signature properly positioned as bass key signature without displaying a bass clef symbol?

Description
I have a full row with multiple bars by adding multiple staves beneath eachother as per documentation. Within i want to change the key signature but i don't want to set the bass clef which is displaying a bass symbol again.

JSFiddle
Here is a jsfiddle
https://jsfiddle.net/vxdnb0pw/2/

Checkout line 28 to comment in or out.

Looking forward to an answer / idea.

-----

Update:

For StaveNote there is an option to pass the clef to change the note position. Any change to do the same for KeySignature?
`new StaveNote({ clef: "bass", keys: ["a/2"], duration: "1" }),`

It is also possible to add notes in treble notiation (clef: treble) and add them to a bass stave.
Same fiddle but extened on bottom:
https://jsfiddle.net/vxdnb0pw/3/

**Comment by AaronDavidNewman** [comment]
Wow, I can't believe we've never noticed this.  If the clef is not displayed, the key signature is not displayed correctly, even though the notes and accidentals are.

Looking at it, it should be work to add a `setClefLines` method to `Stave`, where `stave.clef` is set correctly but the stave modifier is not added. 

Thanks for finding this!

**Comment by AaronDavidNewman** [comment]
Added pull request.

**Comment by sfox-developer** [comment]
Awesome @AaronDavidNewman , thanks a lot 🎉.

**Comment by RyoSusami** [comment]
@AaronDavidNewman I had just encountered the same problem. Thank you!
