### ISSUE TITLE
TabNotes can be rests

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#1620]
In a non-tab stave, setting staveNote duration '4r' will create a quarter rest.  For a tabNote though, this doesn't affect the note.  How do you create a rest on a tab stave (other than by rendering the glyph manually,)?

**Comment by sschmidTU** [comment]
I thought you never display rest notes in tabs (the x-placement of notes should indicate when to play them), but apparently it's possible:
https://www.guitar.ch/en-us/guitar/theory/theory-rhythmic-tablature.html

Here a guitar tab player encounters a rest note and doesn't know what it means:
https://www.reddit.com/r/guitarlessons/comments/134veo6/unfamiliar_notation_on_guitar_tabs/

**Comment by AaronDavidNewman** [comment]
I found you can just insert a StaveNote onto a TabStave.  So I think I can close this.  

I've seen it this way in cases when the standard notation stave is above the tab stave.  I haven't seen the 'x', but I'm not a guitar player so who knows.

> Here a guitar tab player encounters a rest note and doesn't know what it means

lol, yeah that happens :)  In the US, a lot of guitar players didn't have much/any music in school, since it's not an official band/orchestra instrument.
