### ISSUE TITLE
Bass Clef - Incorrect Notes???

### ISSUE THREAD

**Issue by skuhn002** [0xfe/vexflow#1625]
### Discussed in https://github.com/0xfe/vexflow/discussions/1624

<div type='discussions-op-text'>

<sup>Originally posted by **skuhn002** June 25, 2024</sup>
I have been building a simple web application to practice sight-reading ([link](https://github.com/skuhn002/sight-read.git)), but I am getting incorrect notes on the bass cleff. Is anyone else having that issue?</div>

For example:

<img width="317" alt="image" src="https://github.com/0xfe/vexflow/assets/45501912/732ff740-74b5-48ae-85f5-2d532697dd3a">

This note is being rendered on the bass clef by passing the note "f/5", but the note shown is actually an "A" on the bass clef.

It seems the code is rendering the note as if it were still on the Treble clef, but I've hard coded the clef as "bass".

**Comment by the-drunk-coder** [comment]
I'm observing the same, the notes always seem to refer to the treble clef ...

**Comment by AaronDavidNewman** [comment]
What version are you using?  This was fixed recently.

**Comment by the-drunk-coder** [comment]
I'm on 4.2.4 ... seems like I can't get 4.2.5 through npm ?

**Comment by AaronDavidNewman** [comment]
@mscuthbert  @ronyeh  and @rvilarl , is there a vexflow 4.2.5 in the works?

I create my own npm package so I don't have to follow the released branches, if you want to use that.  It is https://www.npmjs.com/package/vexflow_smoosic.  It should be identical to 0xfe/vexflow latest.

**Comment by rvilarl** [comment]
@mscuthbert please provide a fiddle.
@AaronDavidNewman I am not working on a 4.2.5

**Comment by mscuthbert** [comment]
@rvilarl -- I think you've tagged the wrong person.

**Comment by AaronDavidNewman** [comment]
I will take a look at this over the next couple of days.  It looks like @ronyeh  created the release in github, and we just need to commit it to npm.

**Comment by ronyeh** [comment]
Oh, I can manually push it to npm for now. I’ll do it later today.

I have changed the release script to automatically release to the npm
project called vexflow4 from now on. Notice the extra 4 at the end.

https://www.npmjs.com/package/vexflow4

So if you update your projects to depend on vexflow4 you’ll get 4.2.5 with
the latest PRs.

Eventually we will release v5 to the vexflow project and we won’t be able
to make v4 patch releases to the same project anymore.

That’s why I created a vexflow4 npm project, so folks who need to stay on
v4 and need the newest fixes can just add the 4 to their package.json
dependency section.

**Comment by ronyeh** [comment]
I have manually released 4.2.5 on npm / vexflow:

https://www.npmjs.com/package/vexflow

@the-drunk-coder let me know if it works.

Going forward, new version 4.x releases will go to the npm project called `vexflow4`: https://www.npmjs.com/package/vexflow4

We'll need to update this repo's readme to reflect that.

Once we update the regular npm `vexflow` project to version 5.x, we won't be able to issue patches to `vexflow` anymore. But we'll continue fixing bugs and making releases on the `vexflow4` project as long as people need to stay on v4. We will port these patches over to v5 as well.

**Comment by AaronDavidNewman** [comment]
Thanks Ron

**Comment by the-drunk-coder** [comment]
Hmm maybe I'm doing something wrong, but neither the vexflow nor the vexflow4 package make any difference to me, the notes are displayed on the same line no matter which clef I set (the clef itself is displayed correctly)

**Comment by rvilarl** [comment]
@the-drunk-coder please share your code.

**Comment by AaronDavidNewman** [comment]
@the-drunk-coder please look at the test files.  keysignature_tests.ts and the test called clefKeySignature.

Notes have clefs and staves also have clefs (because clefs can change mid-measure).  The note needs to have the correct clef to be displayed on the correct line.  They don't inherit from the stave.

If there is no clef displayed on the stave, setClefLines makes all of the clef/stave line routines act correctly for that stave.  It always worked if there was a clef displayed.  I think it worked for the note line, also, but the issue was with key signatures.  The key signatures don't have a clef, so they get their line from the stave.

``` typescript
  const stave = f.Stave({ x: 10, y: 10, width: 800 }).addClef('bass').addTimeSignature('C|').setClefLines('bass');
  f.StaveNote({ keys: ['c/4'], duration: '4', clef: 'bass' }),
```

**Comment by the-drunk-coder** [comment]
@AaronDavidNewman ooh yes that's it, I wasn't aware of that ... now it works, thanks for the hint :)

**Comment by AaronDavidNewman** [comment]
Cool.  Closing as resolved.

**Comment by merges** [comment]
I'm experiencing the same issue with EasyScore in Vexflow 5.
