### ISSUE TITLE
Is there a helper method to divide a list of notes into notes for the measures?

### ISSUE THREAD

**Issue by the-drunk-coder** [0xfe/vexflow#1628]
Hi,

I'm trying to generate multiple bars from a list of notes.

Is there a helper method that automatically splits notes and adds a tie if they don't fit into a bar?

Example: 

I have a list of four notes, the first three are quarter notes, plus a half note.

I want them to split into two lists, one that contains four quarters, and a second one that contains one quarter and a dotted half-note rest, so that it fits into two 4/4 measures.

Just wondering whether someone has already written something like this, otherwise I can probably do it myself ...

Best,
n

**Comment by rvilarl** [comment]
I am not aware of such a helper in the lib.

**Comment by the-drunk-coder** [comment]
Ok, that's what I feared ... I wrote something that does the job for the moment, but it's not super flexible and doesn't handle triplets so far ... 

If anyone's interested: https://github.com/the-drunk-coder/scoreviz/blob/9eeb194775399b41a65c0254f8b4d9af0d558ada/web/index.js#L157
