### ISSUE TITLE
EasyScore Time Option Doesn't Work

### ISSUE THREAD

**Issue by epihel** [0xfe/vexflow#1631]
Using Vexflow 4.2.5, passing a time signature to EasyScore doesn't override the default 4/4 time signature:
```
const factory = new Vex.Flow.Factory();
const vexScore = factory.EasyScore({ time: '3/4' });

EasyScore.defaults.time === '4/4'
EasyScore.options.time === '3/4'

```
Bug: Vexflow evaluates the score as 4/4 time.

This works:

```
const vexScore = factory.EasyScore();
vexScore.defaults.time = '3/4';

EasyScore.defaults.time === '3/4'
EasyScore.options.time === null
```

Vexflow evaluates the score as 3/4 time.

**Comment by epihel** [comment]
Note that this also works:
`vexScore.set({ time: '3/4'});`

**Comment by rvilarl** [comment]
@epihel this is not a bug, the `factory` and `constructor` accept a `EasyScoreOptions` and `set` accepts a `EasyScoreDefaults`. `time` is a member of `EasyScoreDefaults`

**Comment by epihel** [comment]
@rvilarl Ah, okay; I misunderstood the API. Feel free to close.
