### ISSUE TITLE
Notes tie issues

### ISSUE THREAD

**Issue by Skinz3** [0xfe/vexflow#1638]
<img width="1371" alt="Capture d’écran 2024-10-16 à 19 00 51" src="https://github.com/user-attachments/assets/678ce7fd-705e-4b0e-95b8-cdcf51814250">

Hello, i have an issue while generating my sheet.

Im specifying the (x,y) position for my staves, and when im connecting notes, while doing a line break in the sheet, i got the following notation error on the tie. 

What can i do ?

**Comment by AaronDavidNewman** [comment]
You need to make 2 ties - one with no endpoint on the first note, and one with no start point on the second note.

**Comment by Skinz3** [comment]
Thanks !
