### ISSUE TITLE
how to use vexflow generate electirc guitar like pic

### ISSUE THREAD

**Issue by cxykhaos** [0xfe/vexflow#1642]
i only know use normal and bend(like   tabnote.addModify(new Bend())

like pic:  how to generate 
![image](https://github.com/user-attachments/assets/a00c9dfd-9669-4f97-940d-da2e756785c8)
![image](https://github.com/user-attachments/assets/a45e8063-cc14-4313-af3a-c1495fb66746)

can docs have some example?

**Comment by AaronDavidNewman** [comment]
Can you circle the thing you're talking about?  I'm not a guitar guy :)

**Comment by cxykhaos** [comment]
<img width="91" alt="image" src="https://github.com/user-attachments/assets/d1a3d8e5-64a5-4882-9a6a-f3ecda1b7bf9">   just like this  and this 
<img width="68" alt="image" src="https://github.com/user-attachments/assets/ee41b7b7-4267-43ff-8758-3d283dce7606">


> Can you circle the thing you're talking about? I'm not a guitar guy :)
