### ISSUE TITLE
applyAccidentals() ignores BarNotes ?

### ISSUE THREAD

**Issue by iforce2d** [0xfe/vexflow#1646]
I'm using Accidental.applyAccidentals() to automatically set the correct accidentals based on key signature. It does not seem to care that a BarNote should reset the calculation. Is this the expected behavior?

With all notes Bb in key of C:

      var notes = [
        new VF.StaveNote({ keys: ["bb/4"], duration: "q" }),
        new VF.StaveNote({ keys: ["bb/4"], duration: "q" }),        
        new VF.BarNote(),        
        new VF.StaveNote({ keys: ["bb/4"], duration: "q" }),
        new VF.StaveNote({ keys: ["bb/4"], duration: "q" }),
      ];
      ...
      Vex.Flow.Accidental.applyAccidentals([voice], `C`);
![Selection_353](https://github.com/user-attachments/assets/7e71d58a-c711-4fbc-bf85-cd06fb034efd)

With all notes B in key of F:

      var notes = [
        new VF.StaveNote({ keys: ["b/4"], duration: "q" }),
        new VF.StaveNote({ keys: ["b/4"], duration: "q" }),        
        new VF.BarNote(),        
        new VF.StaveNote({ keys: ["b/4"], duration: "q" }),
        new VF.StaveNote({ keys: ["b/4"], duration: "q" }),
      ];
      ...
      Vex.Flow.Accidental.applyAccidentals([voice], `F`);
![Selection_354](https://github.com/user-attachments/assets/23e21971-a93b-4b01-98f1-22417d46d2cd)

https://jsfiddle.net/r5ykuw41/1/

**Comment by rvilarl** [comment]
You are right this is not correct. I also do not understand why we have the Barnote. I have always used new Stave. @AaronDavidNewman @mscuthbert can you help?

**Comment by mscuthbert** [comment]
This is correct I think -- a BarNote is, I believe, a "Note" (staff object) that _**LOOKS**_ like a barline.  Vexflow uses BarNotes to draw barlines at the end of measures.   It does not **_function_** as a barline. To do that, you need to place multiple staves adjacent to each other as different measures.

**Comment by rvilarl** [comment]
Would it make sense to remove the BarNote then?

**Comment by AaronDavidNewman** [comment]
No, because it is useful for things like alternating time signatures and parts that don't align.  For occasions like that, you'd have to compute the accidentals manually anyway, but it's nice to have the measures line up because the music can still be formatted proportionally.

**Comment by rvilarl** [comment]
OK then this is right applyAccidentals ignores BarNotes.
