### ISSUE TITLE
VexFlow should be able to "plug-in" alternate fonts.

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#181]
A good start would be the lilypond font or [SMUFL](http://smufl.org).

This means:

1) Factoring out direct references to Gonville font indexes (e.g., "v51", "v7b", etc.) and putting them in a separate table (e.g., "closed_head": "v51", "16th_rest": "v8a", etc.).

2) The table must include all parameters related to the glyphs, e.g., scale, grace_note_scale, x_shift, y_shift, etc, bounding_box, etc.

3) The Glyph renderer should be able to render different JSON font formats.

**Comment by jmahmud** [comment]
Hi all

I realise this thread is quite old now (almost a year to the date!) but I was wondering whether Bravura or general SMuFL has been incorporated within Vexflow main branch?  I have a fork of the source at the moment but would like to incorporate SMuFL as an option for rendering glyphs.  Could you let me know@

* if available in VF, how can it be selected OR
* how I might incorporate the changes made by Silverwolf90 into my branch.

Any information would be greatly appreciated!

Cheers
Josh

**Comment by SalahAdDin** [comment]
What's about this?

i want to do a music sheet editor and i want to do a tool bar with the common music symbols, i don't know how implements the VexFlow glyph fonts for do it. :/

**Comment by SalahAdDin** [comment]
The SMuFL font used here is Bravura, right?

**Comment by Silverwolf90** [comment]
@SalahAdDin yes this is Bravura

SMuFL is not in the main branch of VexFlow. And the work done so far is definitely not ready to move into the main branch. It goes without saying that trying to support SMuFL is particularly intrusive, as changes are required throughout the entire codebase. And it's perhaps one that it's not ready for (went through a lot of pain to get it to the point that it's at).

As far as how fonts are stored, you can see the data here: https://github.com/0xfe/vexflow/blob/master/src/fonts/vexflow_font.js

It just stores a serialized version of the glyph outlines (with some other data as well). If you want to add new glyphs, you could probably use something like [opentype.js](https://nodebox.github.io/opentype.js/) to parse a font file and serialize the outlines of the glyphs you want into a similar structure.

**Comment by SalahAdDin** [comment]
I didn't know that this is so hard.

**Comment by jmahmud** [comment]
Hi Cyril

Is this something which you're willing to allow others to contribute to or
are you wanting to continue work on it before making it more public?

Thanks
Josh



On Mon, Apr 4, 2016 at 11:52 PM, Yusuf (Josè) Luis <notifications@github.com

**Comment by Silverwolf90** [comment]
My work is already available here:

https://github.com/Silverwolf90/vexflow/tree/remove-hardcoded-head-width

But it's quite old.

**Comment by SalahAdDin** [comment]
@Silverwolf90 Make a pull request please.

**Comment by Silverwolf90** [comment]
I'm not sure I understand. What is the advantage of opening up a PR? Couldn't you just fork my repo?

**Comment by ronyeh** [comment]
I love reading historical discussions like this to learn about design decisions. :-) Someday maybe we can create a "best-of" list of PR discussions and stick them in our wiki somewhere, hehe.

But I think this issue is now **solved** since we now have good SMuFL support in VexFlow. (We also have support for web fonts, too!)
