### ISSUE TITLE
Create Builder API

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#195]
The VexFlow low-level API is now in a good enough state for the existence of a high-level one. There needs to be a simple API for users that just want to create quick snippets of music, which can be fine tuned with the low level API.

The VexTab `Artist` class is a good example of a builder API, but not an ideal one.

Strawman example:

```javascript
var artist = new VexFlow.Builder(context);

var stave = artist.addStave({width: 400, name: "piano"}).addClef("treble");
artist.addNotes(stave, ":q C4 D4 E4 F#4");
artist.addNotes(stave, ":8 C5").addAnnotation({type: "fermata", position: "top"});

// Automatic beaming
artist.beamNotes(stave.getNotes());

var bass_stave = artist.addStave({width: 400, name: "piano"}).addClef("bass");
artist.addNotes(stave, ":q C4 D4 E4 F#4");

// Align notes in bass and treble staves
artist.connectStaves({staves: [stave, bass_stave], connector: "curly"});
artist.draw(x, y);
```

This is only an example.

**Comment by 0xfe** [comment]
Hi mscuthbert@, What is the state of the JS API? How easy is it to create scores with it?

**Comment by mscuthbert** [comment]
It's not fully polished but it's in pretty good shape and can do everything the example above needs except adding staff names (that'd be an easy fix); it might not be as close to the Vexflow API as you would like for an "official" builder, but removing/changing notes and redrawing the staves is quite easy and there are a number of widgets such as a score follower that plays pitches while following the score that may be useful, along with basic note changer widgets.  

Docs are built at: http://web.mit.edu/music21/music21j/doc/index.html  

The big missing part is a Javascript MusicXML or MIDI parser -- I've relied on music21p's Python parsers and the automatic conversion to music21j functionality.  I have some time in December to work more on it.

There's a sandbox in the TestHTML folder for playing with it.

**Comment by aaronmars** [comment]
What's the state of this? I definitely feel that the current API is not the easiest thing to use for higher-level applications. In addition to the "quick snippets", this builder should be able to be used for more complex snippets (entire standalone scores) as well as full-on applications.

**Comment by mturley** [comment]
I just found this, and realized it's exactly what I need for an application I want to build.  Has anyone started work on this that I can get involved with?

**Comment by 0xfe** [comment]
With the new `EasyScore`, `Factory`, and `System` classes, we have some pretty good alternatives.

**Comment by SalahAdDin** [comment]
Are Theses classes documented?
