### ISSUE TITLE
Using repeat bar as modifier

### ISSUE THREAD

**Issue by amitgur** [0xfe/vexflow#244]
When a repeat bar is in  the first measure it must be treated like keySigniture, Clef and timeSigniture. if not it will collapse with those elements or with the first note.
To achive that I added "addModifier" method in stavebarline and added a new glyph which is a repeat sign. I'll be happy to share a pullRequest of those (0xfe?)

example: look at the last line here:
https://bandpad.co/score/LatinHappyBirthday?lang=en
change instruments (to tuba) and watch the repeat bar moving by the keySigniture width.

OK, the latin version of this song is a joke for my birthday, this is the students version:
https://bandpad.co/score/HappyBirthday1?lang=en

**Comment by 0xfe** [comment]
Obsolete.
