### ISSUE TITLE
Exception in Raphael when rendering slashed grace note

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#256]
The following stack trace is produced when attempting to render a grace note that has `slash: true` set.

I am using Raphael 2.1.1

`Error: Invalid value for <path> attribute d="L53.484700000000004,58.57142857142857L66.4847,49.57142857142857Z" raphael.js:5801
$ raphael.js:5801
setFillAndStroke raphael.js:6144
R._engine.path raphael.js:6449
paperproto.path raphael.js:3748
Vex.Flow.RaphaelContext.RaphaelContext.stroke vexflow-debug.js:10524
Vex.Flow.GraceNote.Vex.Inherit.draw vexflow-debug.js:14382
(anonymous function) vexflow-debug.js:14546
Vex.Flow.GraceNoteGroup.Vex.Inherit.draw vexflow-debug.js:14545
Vex.Flow.StaveNote.Vex.Inherit.drawModifiers vexflow-debug.js:4716
Vex.Flow.StaveNote.Vex.Inherit.draw vexflow-debug.js:4806
Vex.Flow.Voice.Voice.draw vexflow-debug.js:6462`
.....

**Comment by gristow** [comment]
Recommend we close -- #281 resolved this.

**Comment by 0xfe** [comment]
Thanks. Closing.
