### ISSUE TITLE
Align stave modifiers

### ISSUE THREAD

**Issue by aerhard** [0xfe/vexflow#257]
When there are multiple staves, time and key signatures get misaligned when their preceding modifiers don't have equal width. 
There's a parameter in the time signature constructor allowing to specify custom padding, so users are able to align time signatures manually.  
Should the key signature class get that parameter, too / should there even be a Formatter function aligning stave modifiers? Alignment of all modifiers should also fix the offset between the repeat bar lines and the first stave connector in the following test:
![modifier-offsets](https://cloud.githubusercontent.com/assets/5211195/4035280/d2b5a24e-2c8d-11e4-88ff-707ed0792435.JPG)
.

**Comment by 0xfe** [comment]
This is asking for a new context type.

I think the Formatter should be aware of all these elements and decide what to do with them. It might not be so hard -- we need something like a `StaveModifierContext` that works in the same way as `TickContext` and `ModifierContext`. Each of the contexts are responsible for aligning their contained elements, and the Formatter will x-justify them on the stave based on their alignment points.

**Comment by 0xfe** [comment]
This was fixed in a recent PR via the new `ClefNote` class.
