### ISSUE TITLE
Create SVGContext?

### ISSUE THREAD

**Issue by gristow** [0xfe/vexflow#277]
We're not gaining a huge advantage by using Raphael over native SVG support -- except for IE <= 8 support.  I'm doing a lot of other SVG programming these days, and would be happy to make an SVGContext for us, if others think it worthwhile.

(I know we've tried to keep canvas & Raphael contexts as similar as possible.  One advantage that creating a native SVG context could have would be the potential to register the rendered SVG object with its Vex.Flow object -- so that if someone wanted to, they could reach into the SVG and apply styles directly to objects without re-rendering the entire context.  I'm thinking, in particular, about the potential of animation effects -- a note gradually glowing on a mouseover, etc...  Though, short of using the non-standard Function.caller this would probably require code changes throughout all draw() methods.)

**Comment by laurensramandt** [comment]
+1 as the possibility for the aforementioned UI effects would mean a huge gain in user friendliness

**Comment by gristow** [comment]
I'm making good progress on this -- may have something working as early as tomorrow.

I've come across some discrepancies between RaphaelContext and CanvasContext. Can anyone confirm that clearRect() is meant to erase pixels from a drawing?  (Currently, in Raphael, it draws a white--or specified color--rectangle instead of clearing pixels.  In CanvasContext it clears pixels.)

For now, I'm implementing this to match CanvasContext -- using SVG masking, and if that's what it's meant to do, I'll fix RaphaelContext to also do that.

**Comment by 0xfe** [comment]
Thanks for the update Gregory.

clearRect() on SVG draws a rectangle with the fill set to a pre-specified
background color. (I think this behavior was because I couldn't figure out
a way to actually clear the display with Raphael.)

On Thu, Jan 8, 2015 at 10:29 PM, Gregory Ristow <notifications@github.com>
wrote:

> I'm making good progress on this -- may have something working as early as
> tomorrow.
>
> I've come across some discrepancies between RaphaelContext and
> CanvasContext. Can anyone confirm that clearRect() is meant to erase pixels
> from a drawing? (Currently, in Raphael, it draws a white--or specified
> color--rectangle instead of clearing pixels. In CanvasContext it clears
> pixels.)
>
> For now, I'm implementing this to match CanvasContext -- using SVG
> masking, and if that's what it's meant to do, I'll fix RaphaelContext to
> also do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/277#issuecomment-69288678>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by 0xfe** [comment]
To be clear, yes the intent is to erase pixels from a drawing.

On Fri, Jan 9, 2015 at 8:05 AM, Mohit Muthanna Cheppudira <
mohit@muthanna.com> wrote:

> Thanks for the update Gregory.
>
> clearRect() on SVG draws a rectangle with the fill set to a pre-specified
> background color. (I think this behavior was because I couldn't figure out
> a way to actually clear the display with Raphael.)
>
> On Thu, Jan 8, 2015 at 10:29 PM, Gregory Ristow <notifications@github.com>
> wrote:
>
>> I'm making good progress on this -- may have something working as early
>> as tomorrow.
>>
>> I've come across some discrepancies between RaphaelContext and
>> CanvasContext. Can anyone confirm that clearRect() is meant to erase pixels
>> from a drawing? (Currently, in Raphael, it draws a white--or specified
>> color--rectangle instead of clearing pixels. In CanvasContext it clears
>> pixels.)
>>
>> For now, I'm implementing this to match CanvasContext -- using SVG
>> masking, and if that's what it's meant to do, I'll fix RaphaelContext to
>> also do that.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/0xfe/vexflow/issues/277#issuecomment-69288678>.
>>
>
>
>
> --
> Mohit Muthanna [mohit (at) muthanna (uhuh) com]
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by gristow** [comment]
Ok -- I've got SVGContext working and passing all tests.  Right now implementation of clearRect() matches that of RaphaelContext.  It's on my to-do list to fix this -- but it involves dynamically creating clipping paths covering everything except the area inside the rectangle and applying these to all previous children of the SVG, and things get a bit complex at that point.

You can [see the tests here](http://www.gregoryristow.com/vex/tests/flow.html). everything that says "Raphael" is actually SVGContext.  I just hacked the test helpers so I didn't have to reprogram all of the tests.

And you can [see the new SVGContext here](http://www.gregoryristow.com/vex/src/svgcontext.js)

I'm happy to put in a PR for this -- though I'm not sure how we want to handle the tests on this.  (It seems like it might get a bit out-of-control to be running tests on three backends.)

**Comment by 0xfe** [comment]
Wow, great work. Also, it seems like this has drastically cut the total
test runtime -- do you see the same?

Anyhow, I think we should deprecate the Raphael backend for this one. So,
perhaps for now you can update `test/vexflow_test_helpers.js` to use
`SVGContext` instead of `RaphaelContext` by default, and have a flag (maybe
Vex.Flow.Test.NO_RAPHAEL default true) which can be used to enable Raphael
tests.

On Fri, Jan 9, 2015 at 3:55 PM, Gregory Ristow <notifications@github.com>
wrote:

> Ok -- I've got SVGContext working and passing all tests. Right now
> implementation of clearRect() matches that of RaphaelContext. It's on my
> to-do list to fix this -- but it involves dynamically creating clipping
> paths covering everything except the area inside the rectangle and applying
> these to all previous children of the SVG, and things get a bit complex at
> that point.
>
> You can see the tests here
> <http://www.gregoryristow.com/vex/tests/flow.html>. everything that says
> "Raphael" is actually SVGContext. I just hacked the test helpers so I
> didn't have to reprogram all of the tests.
>
> And you can see the new SVGContext here
> <http://www.gregoryristow.com/vex/src/svgcontext.js>
>
> I'm happy to put in a PR for this -- though I'm not sure how we want to
> handle the tests on this. (It seems like it might get a bit out-of-control
> to be running tests on three backends.)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/277#issuecomment-69397500>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by mscuthbert** [comment]
This is really incredible! I can definitely see rewriting all canvas routines to use SVG instead after the speed increase from this change.  It'll be a huge advantage to the system.  Thank you!

**Comment by gristow** [comment]
Thanks... it was surprisingly easy to write this, took half the time I'd budgeted.

Speaking of half the time, yep, I'm also seeing speed increases: total test runtimes of 2733ms for SVG, and 6727ms for Raphael, so more than twice as fast, with the unchanged HTML canvas tests included in that.

Mohit, instead of just NO_RAPHAEL why don't I create a boolean for testing of each backend:
Vex.Flow.Test.RUN_CANVAS_TESTS, default true
Vex.Flow.Test.RUN_SVG_TESTS, default true
Vex.Flow.Test.RUN_CANVAS_TESTS, default false

I'll replace all of the calls to runTest() and runRaphaelTest() with a call to runTests(), which will farm it out to the individual backend helpers depending on the options.  This will also solve a worry I've had that there are some tests we only run using canvasContext.

If all goes well, I'll have all this done tonight!

**Comment by 0xfe** [comment]
On Sat, Jan 10, 2015 at 4:08 PM, Gregory Ristow <notifications@github.com>
wrote:

> Thanks... it was surprisingly easy to write this, took half the time I'd
> budgeted.
>
> Speaking of half the time, yep, I'm also seeing speed increases: total
> test runtimes of 2733ms for SVG, and 6727ms for Raphael, so more than twice
> as fast, with the unchanged HTML canvas tests included in that.
>
Very nice!

> Mohit, instead of just NO_RAPHAEL why don't I create a boolean for testing
> of each backend:
> Vex.Flow.Test.RUN_CANVAS_TESTS, default true
> Vex.Flow.Test.RUN_SVG_TESTS, default true
> Vex.Flow.Test.RUN_CANVAS_TESTS, default false
>
> I'll replace all of the calls to runTest() and runRaphaelTest() with a
> call to runTests(), which will farm it out to the individual backend
> helpers depending on the options. This will also solve a worry I've had
> that there are some tests we only run using canvasContext.
>
Yes sure, that sounds good to me.


> If all goes well, I'll have all this done tonight!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/277#issuecomment-69472024>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]
