### ISSUE TITLE
tabnote.js stem rendering

### ISSUE THREAD

**Issue by gristow** [0xfe/vexflow#279]
getPartialStemLines() is returning an extra empty set of bounds (the last value for upward pointing stems, the first for downward).  As a result, lines 297 - 303 call context.moveTo() & context.lineTo() with undefined values, throwing a console error in SVG mode.  (Canvas seems to, more forgivingly, assume the most recent pen Y position used.)

We could fix by testing for empty bounds and continuing if this is the desired behavior for getPartialStemLines().

Replicate by running just the tabnote tests in SVG mode.

tabnote.js, lines 297 - 303:
```javascript
        stem_lines.forEach(function(bounds) {
          ctx.beginPath();
          ctx.moveTo(stem_x, bounds[0]);
          ctx.lineTo(stem_x, bounds[bounds.length - 1]);
          ctx.stroke();
          ctx.closePath();
        });
```

**Comment by 0xfe** [comment]
Finally got around to this. Thanks for narrowing this down.
