### ISSUE TITLE
StaveNote test

### ISSUE THREAD

**Issue by slcott** [0xfe/vexflow#282]
I think there's an error somewhere in here:

>Vex.Flow.Test.StaveNote.autoStem = function() {
  var note = new Vex.Flow.StaveNote(
      { keys: ["c/5", "e/5", "g/5"], duration: "8", auto_stem: true});
  equal(note.getStemDirection(), Vex.Flow.StaveNote.STEM_DOWN,
      "Stem must be down");

>  note = new Vex.Flow.StaveNote(
      { keys: ["c/5", "e/4", "g/4"], duration: "8", auto_stem: true});
  equal(note.getStemDirection(), Vex.Flow.StaveNote.STEM_UP,
      "Stem must be up");

 > note = new Vex.Flow.StaveNote(
      { keys: ["c/5"], duration: "8", auto_stem: true});
  equal(note.getStemDirection(), Vex.Flow.StaveNote.STEM_DOWN,
      "Stem must be up");

 > note = new Vex.Flow.StaveNote(
      { keys: ["a/4", "e/5", "g/5"], duration: "8", auto_stem: true});
  equal(note.getStemDirection(), Vex.Flow.StaveNote.STEM_DOWN,
      "Stem must be down");

 > note = new Vex.Flow.StaveNote(
      { keys: ["b/4"], duration: "8", auto_stem: true});
  equal(note.getStemDirection(), Vex.Flow.StaveNote.STEM_DOWN,
      "Stem must be up");

}

**Comment by slcott** [comment]
specifically look at:
> STEM_DOWN,
"Stem must be up

This looks contradictory.

**Comment by 0xfe** [comment]
That looks like a bad copy-paste. Thanks for reporting.

On Sun, Feb 22, 2015 at 12:13 PM, Scott Riccardelli <
notifications@github.com> wrote:

> specifically look at:
>
> STEM_DOWN,
> "Stem must be up
>
> This looks contradictory.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/282#issuecomment-75445640>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]
