### ISSUE TITLE
Single voice on grand staff

### ISSUE THREAD

**Issue by anastasiyaShahova** [0xfe/vexflow#286]
How do I draw single voice on grand staff? In tutorial draw only multiple voices on staves. How do I implement this?
![screenshot from 2015-03-25 13 45 27](https://cloud.githubusercontent.com/assets/9428676/6823167/c03ccc90-d2f6-11e4-8a24-6e52fd3f2579.png)

**Comment by gristow** [comment]
Use two different voices (voices have to be assigned one stave).  Where you want empty space on each staff, use a ghostNote instead of a staveNote.

**Comment by 0xfe** [comment]
Closing this. @anastasiyaShahova, please use the VexFlow mailing list if you need more help.

**Comment by Silverwolf90** [comment]
I'll just add on a quick point here @gristow, VexFlow does support drawing a single voice across multiple staffs. But this is not possible directly through the `Voice` object. You must call `staveNote.setStaff(otherStaff)` on the notes in a voice you want to appear on a different staff.

Note that if you provide the `stave` parameter in `Voice.draw(ctx, stave)`, each note in the voice will be assigned that `stave`. Effectively, the `Voice` object is just a convenient wrapper around a collection of notes.

**Comment by gristow** [comment]
Thanks @Silverwolf90, glad to know there's an easier way to do this!

**Comment by timaschew** [comment]
@Silverwolf90 
it's `staveNote.setStave(otherStaff)` ;)
But I still can't get it working, here is a fiddle: http://jsfiddle.net/51b0j8bp/2/
