### ISSUE TITLE
Dots move further away from some stavenotes (the ones on lines) every time they are formatted

### ISSUE THREAD

**Issue by firedrake93** [0xfe/vexflow#288]
In Vex.Flow.Dot.format, you need to change

dot.dot_shiftY += (-half_shiftY);

to 

dot.dot_shiftY = (-half_shiftY);

**Comment by 0xfe** [comment]
I can't seem to reproduce this bug. Do you have an example?

**Comment by firedrake93** [comment]
Step 1. Make a dotted stave note on a line (not a space). 
Step 2. Format and draw. 
Step 3. Format and draw again. 
Each time you format and draw, the dot will move higher up the page. This is because, like I said, in your Dot.format function, you are incrementing dot_shiftY each time the function is called, instead of setting it. Just change the += to =.

**Comment by 0xfe** [comment]
Ah, I see it. Thanks for reporting (and tracking down the issue.)
