### ISSUE TITLE
Typescript Declarations

### ISSUE THREAD

**Issue by ssoRL** [0xfe/vexflow#290]
I recently got vexflow to work with my typescript project and as such have created a functional vexflow.d.ts file. If this is something that anyone else would find useful perhaps I could add it to the repository.

**Comment by rquiring** [comment]
I'd certainly be interested in that! However I can't find it in your vexflow fork, did you publish it anywhere else yet?

**Comment by zhangxia85** [comment]
That will be very helpful, especially when one needs to customerize it. What more interesting is making a typescript version fork. At least what good to do so is that javascript contributors can still contribute pure javascript code as long as they have a typescript compiler aside. Partially typed code is still better than untyped.

**Comment by 0xfe** [comment]
Hi @ssoRL,

That sounds great -- I'm a fan of TypeScript and I'm curious to see it. Can you put it in a contrib/typescript directory and send me a pull request?

Thanks.

**Comment by ssoRL** [comment]
OK, pull request sent.

**Comment by 0xfe** [comment]
Thanks. It turns out that maintaining Typescript declarations is more effort than I'm comfortable with, and there already are third party typescript wrappers for VexFlow. Closing.
