### ISSUE TITLE
Barline on grand stave

### ISSUE THREAD

**Issue by AnastasiyaShakhova** [0xfe/vexflow#294]
How I can draw barline on grand stave? StaveConnector draw line only at the beginning stave or at the end of the stave. But I don't know, how I can draw line at any position grand stave.
![12](https://cloud.githubusercontent.com/assets/9428676/7859511/66b12870-054a-11e5-8066-21f3e975a298.png)
I need the following:
![23](https://cloud.githubusercontent.com/assets/9428676/7859513/6c3681b4-054a-11e5-9fd2-1d803ba5f3c1.png)

**Comment by dfcreative** [comment]
+1

**Comment by sschmidTU** [comment]
something like this:
```js
        var connector = new Vex.Flow.StaveConnector(top.getVFStave(), stave);
        connector.setType(Vex.Flow.StaveConnector.type.BOLD_DOUBLE_RIGHT);
        connector.setContext(ctx).draw();
```
