### ISSUE TITLE
Drum notations are not supported

### ISSUE THREAD

**Issue by Gefn** [0xfe/vexflow#298]
The current version does not allow to write drums tab. The glyphs are not implemented and there is no way to describe a note by an instrument directly. Maybe a fork ? VexDrums ?

**Comment by ckosmowski** [comment]
I would also love to have drum notations or developer docs as an introduction to the code so i can implement it myseld.

**Comment by 0xfe** [comment]
There is support for various percussion instruments (including drums) in VexFlow. Can you expand on what exactly is missing?

**Comment by ckosmowski** [comment]
Okay. If there is support for drums i couldn't find how to use this feature. Do i have to write them down as normal notes ? How to use an "x" as the stem for the hi hat or an "x" in a circle for an open hi hat.

**Comment by 0xfe** [comment]
See `tests/percussion_tests.js` for examples on how to do this.

![screen shot 2015-10-09 at 10 46 32 am](https://cloud.githubusercontent.com/assets/241299/10396928/0dd6f260-6e73-11e5-9b35-36e46e566987.png)
![screen shot 2015-10-09 at 10 46 26 am](https://cloud.githubusercontent.com/assets/241299/10396929/0dd9f73a-6e73-11e5-9843-79dc32bb08b0.png)
![screen shot 2015-10-09 at 10 46 09 am](https://cloud.githubusercontent.com/assets/241299/10396930/0ddd3b20-6e73-11e5-8d7b-bddadbf2a069.png)

**Comment by ckosmowski** [comment]
Awesome! Thanks.
