### ISSUE TITLE
Bug in calculation of partial beams with secondary breaks

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#302]
This can be reproduced in Vex.Flow.Test.Beam.breakSecondaryBeams() if the first voice is changed to:

```javascript
var notes = [
  newNote({ keys: ["f/5"], stem_direction: 1, duration: "16", dots: 1 }),
  newNote({ keys: ["f/5"], stem_direction: 1, duration: "32"}),
  newNote({ keys: ["c/5"], stem_direction: 1, duration: "16", dots: 1 }),
  newNote({ keys: ["d/5"], stem_direction: 1, duration: "32"}),
  newNote({ keys: ["c/5"], stem_direction: 1, duration: "16", dots: 1 }),
  newNote({ keys: ["d/5"], stem_direction: 1, duration: "32"}),

  newNote({ keys: ["f/5"], stem_direction: 1, duration: "16"}),
  newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
  newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
  newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
  newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
  newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"})
];
notes.forEach(function(note) {
  if ('dots' in note && note.dots >= 1) {
    note.addDotToAll();
  }
});
```
You then get:
![partial_beam_bug](https://cloud.githubusercontent.com/assets/847926/9919829/2617f62c-5c84-11e5-90e3-b60788eba9a5.png)
...those first two partial beams at the 32nd level should be pointing left.

I have a fix for this, but it requires a re-write of `Beam.getBeamLines()`.  I'll send a PR for review once it's tested a bit more.

**Comment by 0xfe** [comment]
Thanks Aaron. Good catch, I'll wait for your fix.

On Wed, Sep 16, 2015 at 6:10 PM, Aaron <notifications@github.com> wrote:

> This can be reproduced in Vex.Flow.Test.Beam.breakSecondaryBeams() if the
> first voice is changed to:
>
> var notes = [
>   newNote({ keys: ["f/5"], stem_direction: 1, duration: "16", dots: 1 }),
>   newNote({ keys: ["f/5"], stem_direction: 1, duration: "32"}),
>   newNote({ keys: ["c/5"], stem_direction: 1, duration: "16", dots: 1 }),
>   newNote({ keys: ["d/5"], stem_direction: 1, duration: "32"}),
>   newNote({ keys: ["c/5"], stem_direction: 1, duration: "16", dots: 1 }),
>   newNote({ keys: ["d/5"], stem_direction: 1, duration: "32"}),
>
>   newNote({ keys: ["f/5"], stem_direction: 1, duration: "16"}),
>   newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
>   newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
>   newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
>   newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"}),
>   newNote({ keys: ["e/5"], stem_direction: 1, duration: "16"})
> ];
> notes.forEach(function(note) {
>   if ('dots' in note && note.dots >= 1) {
>     note.addDotToAll();
>   }
> });
>
> You then get:
> [image: partial_beam_bug]
> <https://cloud.githubusercontent.com/assets/847926/9919829/2617f62c-5c84-11e5-90e3-b60788eba9a5.png>
> ...those first two partial beams at the 32nd level should be pointing left.
>
> I have a fix for this, but it requires a re-write of Beam.getBeamLines().
> I'll send a PR for review once it's tested a bit more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/302>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by aaronmars** [comment]
Sent: https://github.com/0xfe/vexflow/pull/303

**Comment by 0xfe** [comment]
Thanks for working on this! Merged.
