### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by arxpoetica** [0xfe/vexflow#304]
What is the status of this project. It seemed to be cranking along for a good while, and ground to a halt a little under a year ago.

Is anyone still working on this? If not, why?

**Comment by 0xfe** [comment]
Yep, it's active. I'm severely backlogged on my merging, thanks to various
other commitments in my life. :-/

I've given myself a strict deadline to get the backlog cleared by the end
of the month.

On Wed, Oct 7, 2015 at 11:10 AM, Robert Hall <notifications@github.com>
wrote:

> What is the status of this project. It seemed to be cranking along for a
> good while, and ground to a halt a little under a year ago.
>
> Is anyone still working on this? If not, why?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/304>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by arxpoetica** [comment]
Cool, thx for the info.
