### ISSUE TITLE
Displaced head should take away from modifier width

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#305]
In stave chords with both displaced heads and modifiers on the same side of the note, the displaced head extent can sometimes overlap the modifiers.

![screen shot 2015-10-10 at 5 40 19 pm](https://cloud.githubusercontent.com/assets/241299/10413440/b282274a-6f76-11e5-8a70-859969ebdb9a.png)

The left chord above has this problem, the right doesn't. In the left chord, the total width is larger than it should be.

Possible fixes:
1) the extra modifier width should be decreased appropriately to accommodate for the overlap, or,
2) width calculations used by the formatter should account for the overlap.

**Comment by Silverwolf90** [comment]
Ugh. Figured this would be easy to fix. Now have spent a couple hours on this. There are definitely some major issues in `StaveNote#getMetrics`. And also probably in the `ModiferContext` too

Diffs below. Notice that the note metrics are not correct. Although some get some fixed.

My hunch is that different pieces of code that use `StaveNote#getWidth` do not have a consistent expectation of what that number represents. I'm guessing that some expect it to include the displaced noteheads and others don't. I'll have to look into this further.

![accidental multi_voice_blessed](https://cloud.githubusercontent.com/assets/1631625/21742643/03789f28-d4eb-11e6-9cf4-5e640ddc95d5.png)
![accidental multi_voice_current](https://cloud.githubusercontent.com/assets/1631625/21742644/037a10ce-d4eb-11e6-8ef8-dcc41387536c.png)
![accidental multi_voice](https://cloud.githubusercontent.com/assets/1631625/21742645/037d9f78-d4eb-11e6-8715-c90f8fcd64e7.png)
![accidental stem_down_blessed](https://cloud.githubusercontent.com/assets/1631625/21742646/03803918-d4eb-11e6-95cc-92730cc8cccb.png)
![accidental stem_down_current](https://cloud.githubusercontent.com/assets/1631625/21742647/038709be-d4eb-11e6-93f9-69278f43aaab.png)
![accidental stem_down](https://cloud.githubusercontent.com/assets/1631625/21742648/0387702a-d4eb-11e6-82e4-dae099deb1fc.png)
![dot basic_blessed](https://cloud.githubusercontent.com/assets/1631625/21742649/038b7850-d4eb-11e6-98b3-04bd8269ccde.png)
![dot basic_current](https://cloud.githubusercontent.com/assets/1631625/21742650/038ea502-d4eb-11e6-9f73-7c8567d4eed4.png)
![dot basic](https://cloud.githubusercontent.com/assets/1631625/21742651/0391660c-d4eb-11e6-8bff-eb30a097d40e.png)
![dot multi_voice_blessed](https://cloud.githubusercontent.com/assets/1631625/21742652/0394a1a0-d4eb-11e6-96f6-d9c132c0018e.png)
![dot multi_voice_current](https://cloud.githubusercontent.com/assets/1631625/21742653/039a77f6-d4eb-11e6-9f5a-a7a04ca8d59b.png)
![dot multi_voice](https://cloud.githubusercontent.com/assets/1631625/21742654/039c1c46-d4eb-11e6-9f6d-bdd9cdc342fc.png)
![easyscore draw_basic_blessed](https://cloud.githubusercontent.com/assets/1631625/21742655/039fd1b0-d4eb-11e6-9b63-208f9605db7a.png)
![easyscore draw_basic_current](https://cloud.githubusercontent.com/assets/1631625/21742656/03a21d12-d4eb-11e6-802f-118e9bec6a5a.png)
![easyscore draw_basic](https://cloud.githubusercontent.com/assets/1631625/21742657/03a50e1e-d4eb-11e6-8f5a-5b855d546602.png)
![formatter stavenote_justification_blessed](https://cloud.githubusercontent.com/assets/1631625/21742658/03a7c49c-d4eb-11e6-9c2b-44a5a3b4bf28.png)
![formatter stavenote_justification_current](https://cloud.githubusercontent.com/assets/1631625/21742659/03adc93c-d4eb-11e6-98a5-3b9e1dc152e9.png)
![formatter stavenote_justification](https://cloud.githubusercontent.com/assets/1631625/21742660/03b04e96-d4eb-11e6-94c9-5161bcf87f0b.png)
![grace_notes grace_note_basic_blessed](https://cloud.githubusercontent.com/assets/1631625/21742661/03b35898-d4eb-11e6-9273-bf0c3dbb217f.png)
![grace_notes grace_note_basic_current](https://cloud.githubusercontent.com/assets/1631625/21742662/03b6a354-d4eb-11e6-9134-4da3d1b6a4fc.png)
![grace_notes grace_note_basic_with_slurs_blessed](https://cloud.githubusercontent.com/assets/1631625/21742663/03b99640-d4eb-11e6-8c4d-bd361c6a8fe6.png)
![grace_notes grace_note_basic_with_slurs_current](https://cloud.githubusercontent.com/assets/1631625/21742664/03bbfe30-d4eb-11e6-8e98-7aa6c73bc33b.png)
![grace_notes grace_note_basic_with_slurs](https://cloud.githubusercontent.com/assets/1631625/21742665/03c00ea8-d4eb-11e6-87b5-4cc698889fe1.png)
![grace_notes grace_note_basic](https://cloud.githubusercontent.com/assets/1631625/21742666/03c2e9e8-d4eb-11e6-8c2b-068eaa87e3f5.png)
![notehead basic_blessed](https://cloud.githubusercontent.com/assets/1631625/21742667/03c62fa4-d4eb-11e6-8e1a-3873ae063994.png)
![notehead basic_current](https://cloud.githubusercontent.com/assets/1631625/21742668/03c9cee8-d4eb-11e6-8123-4b5ac1bfa001.png)
![notehead basic](https://cloud.githubusercontent.com/assets/1631625/21742669/03ccc0ee-d4eb-11e6-92d8-c857a711a508.png)
![notehead bounding_boxes_blessed](https://cloud.githubusercontent.com/assets/1631625/21742670/03d8a882-d4eb-11e6-9ad3-4349063d13de.png)
![notehead bounding_boxes_current](https://cloud.githubusercontent.com/assets/1631625/21742671/03d8ee1e-d4eb-11e6-85c4-bd71f7870026.png)
![notehead bounding_boxes](https://cloud.githubusercontent.com/assets/1631625/21742672/03dd0c7e-d4eb-11e6-9b71-735c6b6a549c.png)
[results.txt](https://github.com/0xfe/vexflow/files/691540/results.txt)
![stringnumber complex_measure_with_string___finger_numbers_blessed](https://cloud.githubusercontent.com/assets/1631625/21742673/03e43db4-d4eb-11e6-9ed0-d1f7403110c5.png)
![stringnumber complex_measure_with_string___finger_numbers_current](https://cloud.githubusercontent.com/assets/1631625/21742674/03f2df9a-d4eb-11e6-90f5-fcaa0ac71d05.png)
![stringnumber complex_measure_with_string___finger_numbers](https://cloud.githubusercontent.com/assets/1631625/21742675/03f6ddb6-d4eb-11e6-9f86-10b719f527b5.png)
![stringnumber fret_hand_finger_in_notation_blessed](https://cloud.githubusercontent.com/assets/1631625/21742676/03f8d99a-d4eb-11e6-9129-c660984cf470.png)
![stringnumber fret_hand_finger_in_notation_current](https://cloud.githubusercontent.com/assets/1631625/21742677/03fbbc32-d4eb-11e6-8203-a89aa6c76876.png)
![stringnumber fret_hand_finger_in_notation](https://cloud.githubusercontent.com/assets/1631625/21742678/03ff38c6-d4eb-11e6-8181-f529e19f9248.png)
![stringnumber string_number_in_notation_blessed](https://cloud.githubusercontent.com/assets/1631625/21742679/040154da-d4eb-11e6-9a04-3e8fb480d9c1.png)
![stringnumber string_number_in_notation_current](https://cloud.githubusercontent.com/assets/1631625/21742680/0404ea14-d4eb-11e6-9249-0268b945d923.png)
![stringnumber string_number_in_notation](https://cloud.githubusercontent.com/assets/1631625/21742681/04197330-d4eb-11e6-9c1d-13fdd0328ec6.png)
![strokes strokes___notation_and_tab_blessed](https://cloud.githubusercontent.com/assets/1631625/21742682/041b4ef8-d4eb-11e6-8278-02ffbc7e84c9.png)
![strokes strokes___notation_and_tab_current](https://cloud.githubusercontent.com/assets/1631625/21742683/041e98a6-d4eb-11e6-80a6-44f3c628ecac.png)
![strokes strokes___notation_and_tab](https://cloud.githubusercontent.com/assets/1631625/21742684/0420dc60-d4eb-11e6-83e7-dc9336132358.png)
![textnote textnote_formatting_blessed](https://cloud.githubusercontent.com/assets/1631625/21742685/042350e4-d4eb-11e6-83a1-08980e350eb9.png)
![textnote textnote_formatting_current](https://cloud.githubusercontent.com/assets/1631625/21742686/042ab172-d4eb-11e6-9441-80edb3cf2890.png)
![textnote textnote_formatting_with_glyphs_0_blessed](https://cloud.githubusercontent.com/assets/1631625/21742687/042eaaca-d4eb-11e6-9902-70443b445bb1.png)
![textnote textnote_formatting_with_glyphs_0_current](https://cloud.githubusercontent.com/assets/1631625/21742688/042f9f2a-d4eb-11e6-81bc-2de70403cfef.png)
![textnote textnote_formatting_with_glyphs_0](https://cloud.githubusercontent.com/assets/1631625/21742689/04326ba6-d4eb-11e6-9bcb-75385f398376.png)
![textnote textnote_formatting](https://cloud.githubusercontent.com/assets/1631625/21742690/04347a2c-d4eb-11e6-9f83-dde93e845bd2.png)

**Comment by 0xfe** [comment]
This is fixed.
