### ISSUE TITLE
Rationalize StaveNote.getStemExtents with Stem.getExtents

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#306]
Looks like there are two functions that are used for retrieving stem lengths -- both slightly different, and both used in a lot of places. Figure out what's different about them and refactor (or rename) for clarification and readability.

**Comment by Silverwolf90** [comment]
Cool, this was completed in https://github.com/0xfe/vexflow/pull/398.

 `.getStemExtents` now delegates to `stem.getExtents`
