### ISSUE TITLE
player problems on firefox?

### ISSUE THREAD

**Issue by AlmogCohen** [0xfe/vexflow#307]
Hi,
Just trying to use the player option with vexflow but it seems that for some reason only the first two notes are played well and rest sound weird.

The problem can be seen anywhere there is a player. For example here:
http://0xfe.blogspot.ca/2013/01/hear-your-music.html

**Comment by 0xfe** [comment]
Closing because this issue belongs in the VexTab repo. (Feel free to reopen it there.) Thanks. :-)

**Comment by AlmogCohen** [comment]
NP
