### ISSUE TITLE
Bug in beam calculation with breaks

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#308]
The logic for calculating beams with secondary breaks has a bug in a specific case.  If the notes in the `AutoBeamFormatting.secondaryBreaks` test include the following for a quarter note-duration:
```javascript
newNote({ keys: ["f/5"], duration: "32"}),
newNote({ keys: ["f/5"], duration: "32"}),
newNote({ keys: ["f/5"], duration: "32"}),
newNote({ keys: ["f/5"], duration: "32"}),
newNote({ keys: ["f/5"], duration: "16", dots: 1}),
newNote({ keys: ["f/5"], duration: "32"}),
```
... the output is:
![screen shot 2015-10-14 at 10 08 44](https://cloud.githubusercontent.com/assets/847926/10491455/96506aea-725b-11e5-87c1-a4dbb1b99896.png)
(^ those first 4 notes are supposed to be 32nds)

I have a fix ready for this case, but I'm now a bit scared of other scenarios where the beaming/beam breaking logic fails.  Shall I submit this fix?

**Comment by 0xfe** [comment]
Yes, please submit -- I'll give it a look. Also, please add beam tests for these corner cases, and verify that the existing beam tests work correctly. I'm working on a framework for visual regression testing, so hopefully we won't have to rely on eyeballing the huge number of tests before submitting.
