### ISSUE TITLE
Uncaught RuntimeError: Invalid selector for renderer.

### ISSUE THREAD

**Issue by MusStudent** [0xfe/vexflow#311]
Hello. I tried to use vexflow-min.js on local server, but I got some errors like this
>Uncaught RuntimeError: Invalid selector for renderer.

I got the same errors in any other scripts like renderer,js, vexflow-master/src/fonts/vexflow_font.js and others. I use jQuery 1.11.3 and tried to use jQuery 2.1.4 from your package - vecflow not working.

**Comment by 0xfe** [comment]
Please ask questions on the VexFlow forum. Also, please paste your full code -- it is very difficult to help without more information. Thanks.
