### ISSUE TITLE
Howto highlight single notes

### ISSUE THREAD

**Issue by ckosmowski** [0xfe/vexflow#313]
I have a metronome software and i am trying to use vexflow for visualising the metronome while its playing. Is it posibble to highlight one note in a stave and redraw that note ? I tried with setStyle and the draw() methods but it seems like the new note is always drawn ontop of the old one and this mixes up the old and the new color.

Do i have to redraw the whole stave each time ? And if so what would be the fastest way ? Is there a method that does an "update" or something?

**Comment by gristow** [comment]
This sort of question is best asked on the VexFlow forum: https://groups.google.com/forum/#!forum/vexflow

But, in short, yes -- you have to redraw the whole image. I typically keep an array of all my VexFlow objects in the order they need to be drawn, clear the canvas, and redraw each. Even on SVG you can get a pretty good frame rate if you need it. And Canvas is designed for exactly this sort of fast repainting.

**Comment by 0xfe** [comment]
Agree with @gristow that these questions should go to the forum. (Also closing.)

The cleanest way to do this is to use the new SVG support for interactivity. Take a look at the "Interactive Mouseover Stavenote" test in `tests/stavenote_tests.js` for an example of how to do this.

```
var item = staveNote.getElem();
Vex.forEach($(item).find("*"), function(child) {
              child.setAttribute("fill", "green");
              child.setAttribute("stroke", "green");
            });
```

Children of the element have class names like "stem", "flag", "modifiers", etc. incase you want to selectively modify their attributes.

_Note_: Interactivity support is new, and only supported by `StaveNote`, however it is easy to add it to other elements using the `openGroup` and `closeGroup` hooks.
