### ISSUE TITLE
renderHairpin (Stavehairpin.js) arbitrary distances

### ISSUE THREAD

**Issue by jmahmud** [0xfe/vexflow#314]
Hi Mohit

I have a question in how the distance and the position works in stavehairpin...

I can see in renderHairpin you have some logic of setting the y value of the hairpin depending on whether it is above or below the stave.  What I am slightly confused about is you have some hardcoded values which are added on (+20 is below the stave, +30 if above the stave).  Are these just hardcoded margins that set the position away from the stave?  How do these work if you were rendering larger / smaller than normal? 

I have some specific positioning for the y value (i.e. has come from musicXML) and I'm wondering if I have to offset the +20 and +30 accordingly as my values are true offsets from the top of the stave...

Any advice would be great!

Cheers!
Josh

PS I've also made a pull request with a couple of suggestions for changes - all relatively minor but hopefully useful.

**Comment by 0xfe** [comment]
Yeah, that class is poorly implemented -- we certainly shouldn't have those
hardcoded values there (in the least they should be tweakable constants.) I
welcome any changes to improve the class.

On Sun, Nov 15, 2015 at 6:22 AM, Joshan Mahmud <notifications@github.com>
wrote:

> Hi Mohit
>
> I have a question in how the distance and the position works in
> stavehairpin...
>
> I can see in renderHairpin you have some logic of setting the y value of
> the hairpin depending on whether it is above or below the stave. What I am
> slightly confused about is you have some hardcoded values which are added
> on (+20 is below the stave, +30 if above the stave). Are these just
> hardcoded margins that set the position away from the stave? How do these
> work if you were rendering larger / smaller than normal?
>
> I have some specific positioning for the y value (i.e. has come from
> musicXML) and I'm wondering if I have to offset the +20 and +30 accordingly
> as my values are true offsets from the top of the stave...
>
> Any advice would be great!
>
> Cheers!
> Josh
>
> PS I've also made a pull request with a couple of suggestions for changes
> - all relatively minor but hopefully useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/314>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]
