### ISSUE TITLE
Second call to staveNote.draw cause the stem position be set incorrectly

### ISSUE THREAD

**Issue by mmis1000** [0xfe/vexflow#316]
I am currenly make a program with vexflow.
And i am implementing some animate with the note color.
The first time it draws fine, everything work correctly.

But then I modify the color of the note.
Clear the canvas, and draw the note again.
I found all stems with beam are missing.

Then I further tracks it.

I found the `setStave` method in` staveNote`;
called the `setYBounds` method of `Stem` with wrong value.
And corrupt the stem position of the note.
Hence cause the stem not render properly.

Is this a intended behavior?
If it is, is there a way to change the color and redraw the sheet without recalculate all the layout?

**Comment by 0xfe** [comment]
You can do this with SVG by attaching an event to the note (or stem) and updating the color. Take a look at the interactive test example in `tests/stavenote_tests.js`.
