### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by SalahAdDin** [0xfe/vexflow#317]
Hi man, how are you?

I like this library so much, but, i think that we need more documentation for develop.

For example, i want know all possibles  variables for duration: w for what? q for what?

I think that will be very useful have a most completly documentation.

**Comment by 0xfe** [comment]
Documentation, unfortunately, will always lag. The best place to learn about the VexFlow API is from the tests in the `tests/` directory.

To answer your specific question, `src/tables.js` has the various values for constants, durations, articulations, etc.
