### ISSUE TITLE
Add annotation to a GhostNote or how to make a blank StaveNote?

### ISSUE THREAD

**Issue by baronar** [0xfe/vexflow#319]
I need to add some text in a space. Maybe there is a better way for me to do it?

I tried...

        staveChrord = new Vex.Flow.GhostNote(
          duration: "#{options.notesPerBar}"
        ).addAnnotation 0, newAnnotation(noteName)

but there is no addAnnotation in GhostNote. I tried this because hunting around on the web to see how to make a blank note said to use GhostNote.

**Comment by 0xfe** [comment]
Hi, I replied to your question on the mailing list. Closing this -- let's keep the discussion there.
