### ISSUE TITLE
Incorrect positioning of annotation below whole note

### ISSUE THREAD

**Issue by relativeflux** [0xfe/vexflow#321]
Hi Mohit,

As noted by myself [on the forum](https://groups.google.com/forum/#!topic/vexflow/9pIlvUhclpU), there seems to be an issue with positioning of annotations below stemless notes (using `VerticalJustify.BOTTOM`). The following code illustrates the correct behaviour, with a stemmed note (quarter note):

```
var canvas = $("div.sandbox div.sandbox canvas")[0];
var renderer = new Vex.Flow.Renderer(canvas, Vex.Flow.Renderer.Backends.CANVAS);
var ctx = renderer.getContext();

var stave = new Vex.Flow.Stave(10, 10, 300).addClef("treble").setContext(ctx).draw();

var notes = [
  new Vex.Flow.StaveNote({ keys: ["a/3"], duration: "4" })
    .addModifier(0, new Vex.Flow.Annotation("ppp")
    .setFont('gonville', 16, 'italic')
    .setVerticalJustification(Vex.Flow.Annotation.VerticalJustify.BOTTOM))
]

Vex.Flow.Formatter.FormatAndDraw(ctx, stave, notes);
```

If we subtitute a whole note, however, the annotation seems to always stick to the bottom of the stave, rather than being rendered below the note:

```
var canvas = $("div.sandbox div.sandbox canvas")[0];
var renderer = new Vex.Flow.Renderer(canvas, Vex.Flow.Renderer.Backends.CANVAS);
var ctx = renderer.getContext();

var stave = new Vex.Flow.Stave(10, 10, 300).addClef("treble").setContext(ctx).draw();

var notes = [
  new Vex.Flow.StaveNote({ keys: ["a/3"], duration: "1" })
    .addModifier(0, new Vex.Flow.Annotation("ppp")
    .setFont('gonville', 16, 'italic')
    .setVerticalJustification(Vex.Flow.Annotation.VerticalJustify.BOTTOM))
]

Vex.Flow.Formatter.FormatAndDraw(ctx, stave, notes);
```

Using `addAnnotation` instead of `addModifier` has no affect.

(BTW I use annotations rather than `TextNote` objects as I don't want to pollute my internal note array with 'non-music' notes, or have to add an extra `Voice` to hold them).

Here are two screenshots showing the result of the above code (taken from the [VexFlow Sandbox](http://www.vexflow.com/docs/sandbox.html)). The first shows the correctly positioned annotation with a quarter note, the second the incorrect positioning with a whole note:

![vf_annotation_correct](https://cloud.githubusercontent.com/assets/17030640/12762632/12c43adc-c9e8-11e5-954b-8fdbe3d7b1c7.png)
![vf_annotation_incorrect](https://cloud.githubusercontent.com/assets/17030640/12762638/1ba33838-c9e8-11e5-87d4-ae64516e581b.png)

Hopefully you'll be able to look into this.

Thanks!

**Comment by SalahAdDin** [comment]
:+1:

**Comment by relativeflux** [comment]
Hi Mohit, just wondering if there was any progress on this issue?

Many thanks

**Comment by 0xfe** [comment]
Hi, sorry, haven't had a chance to dig in as yet.

**Comment by relativeflux** [comment]
Just a quick update to say that if I remove the test for whether or not the note has a stem in the relevant code (annotation.js, lines 144-49) the annotation seems to be positioned correctly:

```
if (this.vert_justification == Annotation.VerticalJustify.BOTTOM) {
        y = stave.getYForBottomText(this.text_line);
        //if (has_stem) {
          var stem_base = (this.note.getStemDirection() === 1 ? stem_ext.baseY : stem_ext.topY);
          y = Math.max(y, stem_base + (spacing * (this.text_line + 2)));
       // }
      }
```

**Comment by 0xfe** [comment]
One thing you could try is running the visual regression tests with this
code commented out and see if it breaks anything. Wanna do it?

On Mon, Feb 29, 2016 at 10:00 AM, relativeflux <notifications@github.com>
wrote:

> Just a quick update to say that if I remove the test for whether or not
> the note has a stem in the relevant code (annotation.js, lines 144-49) the
> annotation seems to be positioned correctly:
>
> if (this.vert_justification == Annotation.VerticalJustify.BOTTOM) {
>         y = stave.getYForBottomText(this.text_line);
>         //if (has_stem) {
>           var stem_base = (this.note.getStemDirection() === 1 ? stem_ext.baseY : stem_ext.topY);
>           y = Math.max(y, stem_base + (spacing * (this.text_line + 2)));
>        // }
>       }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/321#issuecomment-190247841>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by relativeflux** [comment]
Sure, I'll have a go. So I've installed the dependencies, built VexFlow and run tools/generate_svg_images.js. I guess I just need to make that edit and run tools/visual_regression.sh?

**Comment by 0xfe** [comment]
On Mon, Feb 29, 2016 at 2:54 PM, relativeflux <notifications@github.com>
wrote:

> Sure, I'll have a go. So I've installed the dependencies, built VexFlow
> and run tools/generate_svg_images.js. I guess I just need to make that edit
> and run tools/visual_regression.sh?
>

The blessed images are already in the repo. After you make the edit, your
run tools/generate_svg_images.js, which will build new images from your
changes. Then run tools/visual_regression.sh which will actually diff them
and show you what's changed.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/0xfe/vexflow/issues/321#issuecomment-190354991>.
>



-- 
Mohit Muthanna [mohit (at) muthanna (uhuh) com]

**Comment by adamauckland** [comment]
@relativeflux Did you ever get this working? I have exactly the same problem. Attach an annotation on a whole note at C and the annotation is rendered directly over the notehead.
