### ISSUE TITLE
Update meteor package

### ISSUE THREAD

**Issue by SalahAdDin** [0xfe/vexflow#325]
Ok, i'm testing meteor and i want to do a music sheet web page. So, i installed VexFlow and i have one error with meteor and i see that the package was outdated:
![seleccion_025](https://cloud.githubusercontent.com/assets/5034215/13589179/e421a6fc-e4a3-11e5-8058-f6f546a559f4.png)
![mrt vexflow package atmosphere - mozilla firefox_026](https://cloud.githubusercontent.com/assets/5034215/13589183/e981b89e-e4a3-11e5-8492-deae30ca83e9.png)

Thank you very much.

**Comment by SalahAdDin** [comment]
@0xfe If you want i can create the meteor package and upload it, and mantain intead you, what's you say?

**Comment by 0xfe** [comment]
Hi, I don't actually own the meteor package (I didn't even know what meteor was until this bug).

So you're welcome to maintain it. :-)

**Comment by SalahAdDin** [comment]
Ok, i did it using the fork and i haven't any problems with it:
![seleccion_036](https://cloud.githubusercontent.com/assets/5034215/13688181/0d39d6d0-e6ee-11e5-9830-f46cbcc2dc89.png)
So, i'll put in meteor community.
