### ISSUE TITLE
How to: correctly aligned accidentals and voices in grand piano staff at the same time

### ISSUE THREAD

**Issue by cfreeze202** [0xfe/vexflow#332]
Hi, 
I would like to share something that took me time to figure out.

Accidentals get aligned correctly and do not collide when the FormatAndDraw() method is used, but if you have a grand piano staff, notes in different staves can not be aligned with the same x position using FormatAndDraw().
The solution to align the notes is to not use FormatAndDraw(), but do it manually by creating voices for treble and bass staves, formatting them with a formatter like shown in step 2 of the VexFlow tutorial and draw the voices. The important part is to **not join the voices.**
If you do it that way, the notes are now correctly aligned, but the accidentals are colliding with each other.
That is because within the joinVoices() method, something gets called that aligns the accidentals. 
Workaround:
**You have to call the joinVoices() method for each voice individually, not to join voices, but to align accidentals.
Then format treble and bass voices together to the stave, but do not join them together.**

```javascript
//create a voice for treble stave and one for bass stave
var voiceTreble = new Vex.Flow.Voice({num_beats:timeSignatureNumerator, beat_value: timeSignatureDenominator, resolution:Vex.Flow.RESOLUTION});
var voiceBass   = new Vex.Flow.Voice({num_beats:timeSignatureNumerator, beat_value: timeSignatureDenominator, resolution:Vex.Flow.RESOLUTION});

//add tickables (you pass the notes (staveNotes) that you have created before
voiceTreble.addTickables(yourStaveNotesForTrebleStave);
voiceBass.addTickables(yourStaveNotesForBassStave);

//do this if you want to get beams (manually)
var beamsTreble = Vex.Flow.Beam.applyAndGetBeams(voiceTreble);
var beamsBass = Vex.Flow.Beam.applyAndGetBeams(voiceBass);

var formatter = new Vex.Flow.Formatter();   //create a formatter

//joinVoices is the method which invokes something that renders the accidentals in the right way without colliding, but enter only one voice at a time for aligning the accidentals. You don't want to really join the voices
formatter.joinVoices([voiceTreble]);   
formatter.joinVoices([voiceBass]); 

//now align the voices to fit the grand piano staff. They are put in the array all together, but they are not joined together. In the second argument, you enter only the treble stave as stave here, assuming the bass stave and the treble stave have the same width as they are a grand piano staff
formatter.formatToStave([voiceTreble, voiceBass],yourTrebleStave, {align_rests: true});

var max_x = Math.max(yourTrebleStave.getNoteStartX(), yourBassStave.getNoteStartX());
yourTrebleStave.setNoteStartX(max_x);
yourBassStave.setNoteStartX(max_x);
    
//draw voices and beams, ctx is the context you got from your CANVAS / SVG
voiceTreble.draw(ctx, yourTrebleStave);
voiceBass.draw(ctx, yourBassStave);

if (beamsTreble != null) {
  for (var i=0; i<beamsTreble.length; ++i) {
    beamsTreble[i].setContext(ctxMain).draw();
  }
}
if (beamsBass != null) {
  for (var i=0; i<beamsBass.length; ++i) {
    beamsBass[i].setContext(ctxMain).draw();
  }
}
```

@Mohit: maybe this fits into the tutorial or FAQ section where the grand piano staff was explained

**Comment by 0xfe** [comment]
Yes, this is described in the "Formatting" section of the [FAQ](https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ).

**Comment by cfreeze202** [comment]
Hi,

it was not clear to me after reading that „Formatting“ section of the FAQ, that I have to call joinVoices even with only a single voice to avoid colliding of accidentals.
That is the part I was missing there, because in this section, multiple voices are described. I thought that section would only cover multiple voices. Maybe a little sentence could be added there to call joinVoices on a single voice to avoid accidental colliding.

Thanks,
Chris

**Comment by Silverwolf90** [comment]
I do agree it is misleading! Particularly because `joinVoices` is pluralized and it's not particularly intuitive that it would impact the formatting of modifiers for a single voice. I added a quick question + answer to the FAQ.

**Comment by Silverwolf90** [comment]
@0xfe I made a couple edits to the FAQ for clarity

**Comment by 0xfe** [comment]
I see, got it. Thanks for updating the FAQ, @Silverwolf90.

**Comment by cfreeze202** [comment]
Thanks for updating the FAQ and for your work.
