### ISSUE TITLE
How to: CANVAS, SVG and RAPHAEL

### ISSUE THREAD

**Issue by cfreeze202** [0xfe/vexflow#333]
Hi, 
I didn't really find how to use SVG without Raphael. Here is an overview of the three options CANVAS, RAPHAEL and SVG.

**1. CANVAS:**

- In your html code of the website, create a `<canvas>` element with width and height and give it an id like id="myCanvas".

- In your javascript vexflow code do `var renderer = new Vex.Flow.Renderer(yourCanvasElement_ID, Vex.Flow.Renderer.Backends.CANVAS);`

**2. RAPHAEL**

- Raphael is deprecated, use SVG instead

- In your html code of the website, create a `<div>` element with width and height and give it an id like id="myRaphaelCanvas".

- In your javascript vexflow code do `var renderer = new Vex.Flow.Renderer(yourRaphaelCanvasElement_ID, Vex.Flow.Renderer.Backends.RAPHAEL);` 

- download and include the raphael-min.js javascript library to be loaded in your source code like you do with vexflow-min.js

**3. SVG**
- In your html code of the website, create a `<svg>` element with width and height and give it an id like id="mySVGCanvas".

- within the <svg> element, specify the argument `viewbox = "0 0 width height"`and set it to the same width and height as specified in your `<svg>` element. I had to familiarize with how SVG coordinate systems work, with viewbox, viewport and preserveAspectRatio properties to see the output.

- In your javascript vexflow code do `var renderer = new Vex.Flow.Renderer(yourSVGElement_ID, Vex.Flow.Renderer.Backends.SVG);`

- no additional libraries required.

For SVG savvy people this may be boring stuff, but maybe a bunch of other non-experts like me would like to see a summary of options like this. @Mohit: Maybe it fits into the VexFlow tutorial.

**Comment by 0xfe** [comment]
Thanks @cfreeze202. Would you be interested in putting this into a wiki page over here? (Maybe titled "Using HTML5 Canvas or SVG with VexFlow")

**Comment by cfreeze202** [comment]
Sure, but I don’t know where and how to edit the wiki pages (never did one, but assuming some kind of markup language…)

—
Chris

**Comment by 0xfe** [comment]
Thanks, it's actually quite simple. Click the "wiki" tab above. Click "New page", and type away. Syntax is Markdown which is very straightforward (and there's help right on the page.)

(BTW, totally optional -- if you're not comfortable, I'm happy to do it instead.)

**Comment by cfreeze202** [comment]
Ah, damn, wasn’t logged in, so I didn’t see the new page button, ha!
Perfect, I’ll do it tomorrow, as we have night time already here.
I’ll send you a mail when it’s ready then you can make changes as you like.

Best,
Chris

**Comment by cfreeze202** [comment]
Hi, 

I added the site to the wiki.

Todo for me:
- check if the code is OK or has misspelling / incorrect syntax.
- optimize headings and layout a bit.

Please send me your comments about what to change.

Regards,
Chris

**Comment by 0xfe** [comment]
Great, thanks. Looks like the site is still in edit mode, so I can't make changes. Whenever you're done I'll go over it and fix up as necessary.

**Comment by cfreeze202** [comment]
Thanks. Seems like you can edit the page. I don’t know how to disable „edit mode“. I just clicked on save page.
I looked up my code and I don’t have the px units for pixels, but I have the closing html tags </canvas> and </svg>, so I changed it that way.
If not appropriate, you can rechange it anyway.
Thank you.

**Comment by 0xfe** [comment]
This is done.

**Comment by SalahAdDin** [comment]
Was Rapahel deprecated?
