### ISSUE TITLE
strokeStyle property isn't working inside setKeyStyle

### ISSUE THREAD

**Issue by Fluxionsdx** [0xfe/vexflow#339]
My code: note.setKeyStyle(k, {fillStyle: aScoreNotesColors[k], strokeStyle: aScoreNotesColors[k] });

The note head is being colored correctly via the fillStyle property, but the note stem is being colored the default black. They should be the same color. The strokeStyle property was coloring the note stem correctly when I was using note.setStyle({style}) method. Also, the VexFlow FAQ uses a property "stemStyle" in the example. I think that was a typo, as I do not see that property listed, and it's name suggests that it has the same function as strokeStyle.

**Comment by andreujuanc** [comment]
Hello!,
Any words on this?

**Comment by SalahAdDin** [comment]
@0xfe 👍

**Comment by gristow** [comment]
FYI: This was fixed via #567
