### ISSUE TITLE
How do I dynamically position voices based on key signature width?

### ISSUE THREAD

**Issue by dannyid** [0xfe/vexflow#340]
I'm working on a web app that will dynamically update a vexflow generated score based on user input. 

My approach so far is to destroy all the vexflow created SVGs and redraw the whole canvas from scratch at every change. 

An issue I'm running into is that based on what key signature I've chosen to display, I have to re-calculate 

-The total width of the staves
-The width for the voice formatter
-The `noteStartX` values for my voices

Is there a best approach for this? The way I'm currently doing it is by 

-Drawing a staff with a key signature
-Measuring its `start_x`
-Subtracting `79.4353` that value from value, which is the value of `start_x` for C Major
-Destroying the dummy staff and then
-Using the newly calculated offset to push the aforementioned three values to the right that far on a new staff

It feels a little gross. A segment of my code below. 

```javascript
    this.topStaff = new Vex.Flow.Stave(20, 0, this.staveWidth)
      .addClef("treble")
      .addTimeSignature(this.props.timeSig)
      .addKeySignature(this.props.keySig)
      .setContext(this.ctx)
      .draw();

    // The staff is drawn above, then the offset width is gotten below.
    // 79.4353 is the default width for C Major so that's what the
    // start_x is with no keySig selected
    this.offsetX = this.topStaff.start_x - 79.4353;

    // Then the dummy staff is cleared to make room for the real staves
    this.clearCanvas();

    // Now put real staves in with offset included in staff width
    this.topStaff = new Vex.Flow.Stave(20, 0, this.staveWidth + this.offsetX)
      .addClef("treble")
      .addTimeSignature(this.props.timeSig)
      .addKeySignature(this.props.keySig)
      .setContext(this.ctx)
      .draw();
```
later...
```javascript
    // adding voices
    this.topVoice.addTickables(this.props.topNotes);
    this.bottomVoice.addTickables(this.props.bottomNotes);

    const formatter = new Vex.Flow.Formatter();
    formatter.joinVoices([this.topVoice])
    formatter.joinVoices([this.bottomVoice])
    formatter.format([this.topVoice, this.bottomVoice], this.staveWidth + this.offsetX);

    const maxX = Math.max(this.topStaff.getNoteStartX(), this.bottomStaff.getNoteStartX());
    this.topStaff.setNoteStartX(maxX + 24);
    this.bottomStaff.setNoteStartX(maxX + 24);

    this.topVoice.draw(this.ctx, this.topStaff);
    this.bottomVoice.draw(this.ctx, this.bottomStaff);
```
Update: The notes do seem to themselves account for time signature presence, but not key signature as far as I can tell.

**Comment by 0xfe** [comment]
@dannyid You can use the new `System` class that handles alignment across staves for you. (See examples in `easyscore_tests.js`.) If you want to do this yourself, take a loot at `System.format()` which demonstrates how to align staves with different `StaveModifier` (e.g., clef, keysig, timesig, etc.) widths.

**Comment by SalahAdDin** [comment]
Please @0xfe, update documentation please.

**Comment by dannyid** [comment]
Thanks for the help @0xfe, I'll give it a try.

**Comment by 0xfe** [comment]
FYI, docs here: https://github.com/0xfe/vexflow/wiki/Using-EasyScore
