### ISSUE TITLE
Sign in from iPad with Chrome or Safari

### ISSUE THREAD

**Issue by tomasorti** [0xfe/vexflow#341]
Hi.
I am not able to Login from iPad.
When I click on "Sign in" I get a drop-down list (Login, Register, Demo Article, Home).
But I am not able to click on them.
Is VexFlow ready to run on iPad?
Currently using iOS 8.3, Chrome 47.0.2526.107.
User agent: Mozilla/5.0 (iPad; CPU OS 8_3 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12F69 Safari/600.1.4

Regards.

**Comment by Silverwolf90** [comment]
I think you are having issues with [my.vexflow.com](my.vexflow.com) while this issues list concerns the JavaScript library. See the bottom of the page for the appropriate places to direct questions:

> Questions? Comments? Criticism? You can find me at [0xFE](http://0xfe.muthanna.com/) or [@11111110b](https://twitter.com/11111110b).

**Comment by SalahAdDin** [comment]
![problemavexflow](https://cloud.githubusercontent.com/assets/5034215/17839149/492990bc-67a5-11e6-943f-4085a1cc686e.png)

Problem with my.vexflow.com.
