### ISSUE TITLE
Numeric duration should not generate error but instead warning

### ISSUE THREAD

**Issue by dz902** [0xfe/vexflow#342]
If numeric duration is supplied `4` instead of a string `"4"` then a deep error will happen. Error message is not clear enough too.

I suggest either generate a warning instead of throwing an error, or make the error message more descriptive.

**Comment by 0xfe** [comment]
Thanks. I think maybe we should just convert it into a string instead of throwing an error.

**Comment by rvilarl** [comment]
I believe that now tha we use TypeScript, we could this on. @0xfe what do you think?

**Comment by sschmidTU** [comment]
@ronyeh i wouldn't necessarily classify JS projects as old school though, many JS developers, even with React, still use JS. JS is still by far the most popular language on Github.
https://madnight.github.io/githut/#/pull_requests/2021/3
(unfortunately i couldn't find a statistic on the percentage of React projects using TS, which would be really interesting)
JS is also a beginner language that a lot of coders will use who submit issues like this one.
No doubt that I much prefer TS though :)

**Comment by ronyeh** [comment]
Sorry! I didn't mean to disparage JS by saying "old school" :-) I was trying to refer to older/legacy VexFlow projects that were less strict with the typing.

If we plan to support these older projects, we could be slightly more robust with type checking. In this case, if someone supplies a number but we expected a string, we could just convert that number to a string representation of the number. That seems like the easiest approach. 

Even though our project is built with TypeScript, I imagine some people might continue to use VexFlow via script tag, as specified here: https://github.com/0xfe/vexflow/#using-the-html-script-tag

In that case, the JS bundle is pre-built, and does no compile-time type checking.

**Comment by rvilarl** [comment]
I will close this issue for now. `vf.StaveNote({ keys: ['e/4'], duration: 1 as any })` produces no error.
