### ISSUE TITLE
Noteheads & Stems

### ISSUE THREAD

**Issue by gristow** [0xfe/vexflow#345]
Working on a project, in which some of the images are rendered at a large scale, I noticed noteheads are not actually meeting the stems properly:
![image](https://cloud.githubusercontent.com/assets/8905340/15811545/dd88db9c-2b77-11e6-951e-20d064182b10.png)

And notes are not actually centering correctly on lines or within spaces. (I've added white guides to make it easier to spot how low this note is, compared to its proper placement.)
![image](https://cloud.githubusercontent.com/assets/8905340/15811632/eb74b810-2b78-11e6-82b1-228d83d3fec3.png)

I'm working on a fix for these -- and the ability to set the thickness of staff lines (which look very odd when scaled up 20 times or so from 2px) -- and should have a PR for this in the next day or two.

**Comment by SalahAdDin** [comment]
Is this a current glyph fonts? Can it solved using other fonts?

**Comment by gristow** [comment]
It's not an issue with the font, but one of how what we draw manually (in this case stave lines and stem lines) do or don't line up with our positioning of the glyphs from the font (in this case, the note head). Changing a font wouldn't help, we just need to fine-tune how the manually drawn elements & glyph elements are positioned so they work together.

**Comment by mscuthbert** [comment]
This is a general problem that affects a lot of rendering engines and music font/line intersections.  One possible solution would be to use a font that has SMuFL anchor points defined on it and develop a parser to read them.

**Comment by gristow** [comment]
@mscuthbert, that does sound like a better long-range solution, though I think I probably lack the understanding of font metrics necessary to pull it off.

I've got a working branch now that fixes these obvious notehead intersection issues, but it's not elegant. (Basically adding the necessary fractional number offsets to stems in each direction & noteheads on stavelines to make this work...) Wondering if I should submit a PR for it as a temporary solution, or if going the SMuFL route seems like a better plan even though it might not happen immediately.

Thoughts?

**Comment by mscuthbert** [comment]
My sense -- submit the PR for how it is set up now -- presumably if we ever go the SMuFL route the software would still need 90% of your code to take the JSON data and interpret it properly.

**Comment by 0xfe** [comment]
@gristow Wow, that looks pretty bad. I don't think I've ever zoomed in that deep.

I'm happy to review whatever fix you have now. If you think it's inelegant, maybe we can figure out a way to clean it up.

**Comment by Silverwolf90** [comment]
The notehead is perfectly centered now that https://github.com/0xfe/vexflow/pull/407 has been merged in. Until we support SMuFL (which has stem anchors on the notehead glyphs) we won't have a perfect connection between the stem and the notehead -- although I think it has improved since the original post.

**Comment by SalahAdDin** [comment]
Please please please support SMuFL :D

**Comment by 0xfe** [comment]
These should be all fixed now. We also have a `fontname_metrics.js` file to fine tune any joints that are off.
