### ISSUE TITLE
Code quality: Mix of underscores + camelCase

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#348]
I've been looking through the codebase lately and I forgot how much of a mix there is between naming styles. This should be made consistent one way or the other. I'd propose that since all API methods are in camelCase that it makes the most sense to have the entire codebase in camelCase.

The only place off the top of my head where I think this could cause a breaking change is for options objects, eg: `Vex.Flow.StaveNote.render_options`. I'd prefer to deprecate those and add camelCase versions. But they could also not be included in these changes.

**Comment by 0xfe** [comment]
Yes agreed. The camel case started coming in after I started to learn more about modern JS style. There's actually been a bunch of code that's been refactored to camel case, but it's these breaking ones that I'm not entirely sure what to do about. Deprecating them sounds like the right approach.

**Comment by rvilarl** [comment]
@0xfe this one can be closed, already captured in #1166
