### ISSUE TITLE
Proposed steps to prepare for SMuFL support

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#349]
I wanted to get this discussion going again, as I've been giving a bit of thought to VexFlow lately. I don't have much time these days, but I figured I could lay down my thoughts on how we could get to SMuFL support and maybe we could agree on a plan.

I previously worked on a branch to support SMuFL ([branch](https://github.com/Silverwolf90/vexflow/tree/remove-hardcoded-head-width) related to https://github.com/0xfe/vexflow/issues/181), and while I got it into a working state it was quite a mess. Such a drastic change permeates through the entire codebase, and I'm not sure the current codebase is good enough to support such a large change in a clean manner. Although, the new testing infrastructure should also help significantly.

The first things that need to be done is to improve font infrastructure without doing anything SMuFL specific:
- **Rely _only_ on glyph metrics provided by automatic font processing**
  - Get accurate bounding box information for each glyph
    - In the font files, the height (eg: `Vex.Flow.Font.glyphs['v0'].ha`) values seem to be completely off. Take a look at the following image, but ignore horizontal/vertical alignment of the box on the glyph, it should be obvious that the height of some of the boxes clearly don't fit the glyphs.
      ![image](https://cloud.githubusercontent.com/assets/1631625/15986828/fdce9166-300a-11e6-916a-a4a8a0fecc47.png)
  - Bounding box data is generally not available on a per-glyph basis in most font encodings. But there are tools to extract the bounding box from an SVG path (I've not used them though):
    - https://github.com/icons8/svg-path-bounding-box
    - https://www.npmjs.com/package/svg-bounding-box
- **Implement horizontal/vertical origin alignment on the `Glyph` class**
  - Some kind of api like: `glyph.setAlignH('center')` `glyph.setAlignV('baseline')`
  - This removes need for low-level fine-tuning in high-level classes, ie: the `Ornament` class shouldn't need to worry about pixel amounts to center the `Glyph` at a point
  - I implemented this functionality in that old branch, probably a lot of that code can be re-used
- **Use appropriate glyphs for articulations that are `above`/`below`** 
  - VexFlow articulations only use the glyph meant for placement above a note, even if it placed below. But Gonville has specific glyphs with origin points meant for articulations placed below a note
  - Articulations should not need to rely on these awkward `shift_up` and `shift_down` properties in `Vex.Flow.articulationCodes.articulations`
- **!!! Remove all hardcoded numbers around glyph positioning !!!**
  - This is the most important thing to make SMuFL support as easy to implement as possible, all previous tasks in this issue are here to support this
  - This includes both magic numbers in the code and any hard coded glyph metrics or numbers for fine-tuning, there are a ton in `tables.js`
  - The exceptions are anything that can't be computed from the width/height, like `stem_extensions` for different durations with flags
  - This should not be done all at once, but a few at a time. Some hardcoded numbers, like notehead widths, might cause more changes than others.
- **Font sizes for relatively scaled objects, eg: `GraceNote`, should use a percentage scale rather than a hardcoded fontsize**
- **All glyph rendering should use the same API.**
  - Currently there is a mix between calling `new Glyph(...)`, `Glyph.renderGlyph(...)` `Glyph.renderOutline(...)`

At this point we should be in a pretty decent place to start thinking about supporting SMuFL compliant fonts.

**Comment by Silverwolf90** [comment]
Currently experimenting a bit... deriving accurate bounding boxes from the `Vex.Flow.Font` outlines is trivial.

![image](https://cloud.githubusercontent.com/assets/1631625/15992458/f9b3280c-30c4-11e6-8eee-eeeb6bec936f.png)

**Comment by mscuthbert** [comment]
For `!!! Remove all hardcoded numbers around glyph positioning !!!` -- is there a place where we can start collecting the magic number bare-ints immediately, so they at least become searchable.  I.e., replace `pos.x += 11` with `pos.x += glyph.defaults.noteheadWidth` until we figure out how to make this font specific?

**Comment by 0xfe** [comment]
Two options:

- In each file, add a `CONSTANTS` struct with all the hardcoded values locally.
- Have a separate `constants.js` which has separate constant structs for each class.

I think I'd prefer the former so constants are localized.

**Comment by 0xfe** [comment]
Cyril, Does SMUFL have a standardized serialization format for JavaScript? E.g., can I get a JSON font and some rendering code? Or do I have to convert the fonts myself (similar to Gonville)?

**Comment by Silverwolf90** [comment]
If you don't want to use a raw font file, then you'll have to do
preprocessing to store outlines in JSON (like we've been doing with
gonville).  There is a metadata file for SMuFL fonts which provide data for
the bounding box, anchors,and alternates.

**Comment by Silverwolf90** [comment]
Also, using opentype.js we could easily write whatever we need around font
preprocessing in JS.

On 2 Aug 2016 22:29, "Cyril Silverman" <silverwolf90@gmail.com> wrote:

If you don't want to use a raw font file, then you'll have to do
preprocessing to store outlines in JSON (like we've been doing with
gonville).  There is a metadata file for SMuFL fonts which provide data for
the bounding box, anchors,and alternates.

**Comment by Silverwolf90** [comment]
Getting closer!

**Comment by 0xfe** [comment]
I wish I dug through some of your work earlier @Silverwolf90! Would have saved me a ton of time :-)
