### ISSUE TITLE
Make visual regression tests work on Windows

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#354]
The current visual regression tests work on Linux and OSX, but not on Windows.

Figure out the gaps, and find a way to make it work.

**Comment by 0xfe** [comment]
@Silverwolf90 have you tried using cygwin?

**Comment by Silverwolf90** [comment]
I have not, I'll give that a shot tonight as I wrap up https://github.com/0xfe/vexflow/pull/353
