### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#361]
As we start to move over to ES6, I wanted to propose using ESLint over JSHint.

Reasons:

* More flexible, powerful
  * Larger set of more configurable rules
  * Supports custom rules, we could create our own `vexflow` specific set of eslint rules that suggest best practices, or warn of improper usage.
* Some errors can be automatically fixed with a CLI flag: `eslint --fix`
* It's currently winning the linter wars
  * JSCS team decided to make 3.0 the last major version and join the ESLint team

I personally use the [airbnb](https://github.com/airbnb/javascript) style guide's [`eslint-config`](https://www.npmjs.com/package/eslint-config-airbnb), with some tweaks. For the most part it's a great starting place, but I find it overly strict in some cases. But in general, VexFlow would benefit significantly from having stricter linting rules.

**Comment by Silverwolf90** [comment]
My ideal `.eslintrc` would look something like this:
```json
{
  "extends": "airbnb",
  "rules": {
    "max-len": [2, 80],
    "no-param-reassign": [0],
    "no-shadow": [0],
    "no-use-before-define": [0],
    "strict": [2, "global"],
    "no-else-return": [0],
    "space-before-function-paren": [2, "never"],
    "no-case-declarations": [0],
    "func-names": [0],
    "prefer-template": [0],
    "no-confusing-arrow": [0],
    "no-multi-spaces": [0],
    "new-cap": [0],
  }
}
```

**Comment by aaronmars** [comment]
Yes! I support this 100%.

**Comment by mscuthbert** [comment]
I like this a lot too (and thanks for the great link to the airbnb code).  One thing that the new class system proposal would run afoul of is the `export class Thing ...` paradigm -- I think I like the airbnb idea of imports at the top of the file and exports at the bottom of the file.

**Comment by Silverwolf90** [comment]
WIth the above config:

[Here's the result of running `eslint --fix`](https://github.com/Silverwolf90/vexflow/commit/67618d41b16107994e557b50e83fc4fa8f511279)

[Here's an example of a `annotation.js` after manually editing remaining lint errors](https://github.com/Silverwolf90/vexflow/commit/f24967dacf98f9baf9c3116ed18c4e22e2f75ea3)

**Comment by 0xfe** [comment]
Looks great. I like the final `annotation.js` too.

I don't know what all the options mean, but I'm happy to look through them in detail. (E.g., I used to care about 80-char line lengths, but it's a bit of an uphill battle, and I'm not sure if there's any value in it anymore.)

**Comment by Silverwolf90** [comment]
Initial PR with four files here: https://github.com/0xfe/vexflow/pull/369

[Wiki page which outline basic steps to convert a file](https://github.com/0xfe/vexflow/wiki/Migrating-to-ESLint)

**Comment by Silverwolf90** [comment]
I think it's probably worth doing all the automatic steps at once. [Here's a branch (continuing off of the previous PR) which shows the codebase after running every file through `lebab` w/ only safe transforms and `eslint --fix`.](https://github.com/Silverwolf90/vexflow/tree/eslint-all)

After the automatic steps, we're at 892 problems. Then I disabled the `quote-props` rule and the problems lower to 540. Compared to the initial 8k problems, this is starting to seem reasonable!

**Comment by mscuthbert** [comment]
540 problems sounds great to deal with!  Should we mark pull requests to go into that branch instead for now?

I'd also be in favor of dropping 80 characters or at least moving to something more like 100 or 130.  I prefer not to split quoted strings/error messages, even if it goes over the limit, so that they can be found in a search on the error message. (I.e.,  L('Massive Error in the ' +  
'beaming routine') which won't be found in a search for "Massive Error in the beaming routine");

**Comment by Silverwolf90** [comment]
@mscuthbert Agreed. My earlier comment about the config is out of date. Following @0xfe's comment I bumped it up to 100. And I disabled a couple not-so-important rules to make the migration easier.

Also, those split strings are usually great candidates for conversion to ES6 template strings.

On the branch I just posted, the config file looks like this:

```json
{
  "extends": "airbnb-base",
  "root": true,
  "rules": {
    "max-len": [2, 100],
    "camelcase": [0],
    "no-case-declarations": [2],
    "no-confusing-arrow": [0],
    "new-cap": [0],
    "no-else-return": [0],
    "no-multi-spaces": [0],
    "no-param-reassign": [0],
    "no-shadow": [0],
    "no-use-before-define": [0],
    "quote-props": [0],
    "prefer-template": [0],
    "space-before-function-paren": [2, "never"],
    "strict": [2, "global"]
  }
}
```

I'm happy to accept PRs to that branch. @0xfe do you have a preference on how we go about this?

**Comment by Silverwolf90** [comment]
Also, worth noting that I've been reformatting them to look like this:

```javascript
// If it fits on one line...

if (!this.accidental) {
  throw new Vex.RERR('ArgumentError', `Unknown accidental type: ${type}`);
}

// If its a little too long...

if (!this.accidental) {
  throw new Vex.RERR(
    'ArgumentError', `Unknown accidental type: ${type}. Extra stuff here to make the line longer.`
  );
}

// if it's way too long

if (!this.accidental) {
  throw new Vex.RERR(
    'ArgumentError',
    `Unknown accidental type: ${type}. Extra stuff here to make the line longer. And even longer!`
  );
}
```

**Comment by Silverwolf90** [comment]
[Updated the wiki.](https://github.com/0xfe/vexflow/wiki/Migrating-to-ESLint) Added a TODO list of all files, checking off those which are complete.

**Comment by mscuthbert** [comment]
Super basic question, but how to we get the list of errors for each file? Simply run grunt? or...

**Comment by Silverwolf90** [comment]
Ah, of course I forgot the basic bits. You have two options:

Running `grunt eslint` will run eslint on all the  [`ESLINT_SOURCES`](https://github.com/Silverwolf90/vexflow/blob/eslint-all/Gruntfile.js#L23)  expected to pass in the Gruntfile. You could just add a failing file to that array.

Or you can run eslint independently of grunt:

`cd <vexflow root>`
`npm install`
`eslint <path>`

**Comment by 0xfe** [comment]
Sending PRs to Silverwolf's branch sounds good. Cyril can you send me PRs every time you have a few files ready. It's easier to review in smaller batches (and also to debug if things go wrong.)

**Comment by Silverwolf90** [comment]
Yep that sounds good!

**Comment by Silverwolf90** [comment]
Although I would suggest we do all the safe automatic transforms at once across the codebase in one PR. And from there go a few files at a time.

**Comment by aaronmars** [comment]
So, am I reading this right that I can do this?
- Claim a few files
- Checkout from Silverwolf's `eslint-all` branch
- Fix eslint errors
- Send a PR to the branch above

**Comment by 0xfe** [comment]
Yes! 👍 

I guess this issue is the best place to claim your files. First come first serve. :-)

**Comment by Silverwolf90** [comment]
Just FYI that I've completed these already:

accidental.js
clef.js
formatter.js
frethandfinger.js
modifiercontext.js
stave.js
staveconnector.js
stavenote.js
stringnumber.js
tremolo.js
tuning.js
vex.js
vibrato.js
voice.js

**Comment by aaronmars** [comment]
I'll have a go at the following (if this causes too much insanity with merges, please let me know):

annotation.js
articulation.js
barnote.js
beam.js
bend.js

**Comment by Silverwolf90** [comment]
Note that in https://github.com/0xfe/vexflow/pull/374 I've removed the restriction on `ForInStatement` as it appears in VexFlow quite a bit.

**Comment by Silverwolf90** [comment]
Just completed strokes.js

**Comment by Silverwolf90** [comment]
I've just taken care of:

frethandfinger.js
music.js
stemmablenote.js

303 problems left!

**Comment by Silverwolf90** [comment]
Finished!

**Comment by 0xfe** [comment]
\o/ You're a superstar, Cyril!

Just merged everything! You deserve the honors of closing this issue. :-p

**Comment by Silverwolf90** [comment]
Awesome! And thank you! Closing.

**Comment by mscuthbert** [comment]
Whooooooo! Hoooooooo!  :-)

**Comment by gristow** [comment]
Wow -- bravo!
