### ISSUE TITLE
Secondary beam breaks doesn't work with tuplets

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#372]
If auto-beaming is configured to work with secondary breaks, tuplets are not counted correctly.
Fo example, if I have a 16th note triplet, and auto breaks are to be on 8th note boundaries, the tuplet notes' fractional values are not considered.

Here's an example of the bug:
<img width="529" alt="screen shot 2016-06-29 at 09 11 25" src="https://cloud.githubusercontent.com/assets/847926/16459989/10eb0914-3dda-11e6-90b3-5ea2ced780e3.png">

This is generated with `Beam.generateBeams(notes, { secondary_breaks: '8' });`
The 16ths in the tuplet are being treated like full-value 16ths rather than all three of them adding up to the space of a single 8th note.

**Comment by aaronmars** [comment]
OK.  I got the secondary beam issue worked out, but there's still an issue with tuplet bracketing and placement (see image).  I'll work that out and include it in the fix.

<img width="535" alt="screen shot 2016-07-03 at 06 39 11" src="https://cloud.githubusercontent.com/assets/847926/16545743/2daa3a40-40e9-11e6-8b9f-0b1bb784de88.png">

This is just called with
```javascript
const beams = Vex.Flow.Beam.generateBeams(notes, { secondary_breaks: 8 });
```

**Comment by aaronmars** [comment]
Well, this snowballed a bit.  Here are the things I'd like to clean up here.

- That initial issue where secondary beams are not broken correctly when tuplets are involved.
- Issue where a tuplet will have a bracket if it does not include the first note of the beam group.
- Issue where the tuplet numbers and brackets are mis-aligned
- Issue I found while rendering a quarter note triplet that has 8th notes in it (new screenshot below).  I believe the ratio is wrong in this case.  Shouldn't it just be '3' rather than '4:2'? (I'm pretty sure it should be bracketed too)

<img width="532" alt="screen shot 2016-07-07 at 08 04 42" src="https://cloud.githubusercontent.com/assets/847926/16658007/8647fe66-4419-11e6-97bd-3216a3d5c3cc.png">

**Comment by 0xfe** [comment]
Thanks for investigating Aaron. Do you have tentative changes to fix some of the issues?

**Comment by gristow** [comment]
I think I know what's going on with the final tuplet. When you create that last tuplet, are you passing `num_notes` and `notes_occupied` in the options object? If not, `tuplet.js` assumes `num_notes` to be the number of notes provided, and `notes_occupied` to be 2. (In this case, you'd get 4:2, even though what you want is a basic tuplet.)

Having said that -- these four notes should all be bracketed automatically (by default, any tuplet group where not every note is beamed is bracketed), so I'm not sure why that isn't happening...

**Comment by aaronmars** [comment]
OK cool.  I got the bracket thing sorted out.  For now, I'll leave that ratio thing alone since it works with the manual setting of the ratio options (thanks, @gristow ).

I think I've got the rest sorted out.  One big issue was that the beaming logic was only considering the very first note of a beam group when looking for tuplets.
@0xfe , I'll post my branch with the fixes as soon as I can.

**Comment by aaronmars** [comment]
Here's what I have so far:
https://github.com/aaronmars/vexflow/tree/tuplet_beam_breaks

The beam breaks are fixed in beam.js by using `note.ticks.value()` to tally up the ticks used by the tuplets (instead of intrinsic ticks, which is still used to determine if a note needs a beam).

The tuplet location/bracketing weirdness is fixed by the refactor that inspects every note in a beam group, rather than just the first note.

I added the `adjustTuplets()` function to attempt to fix the tuplet `y_offset` in case the beams are causing them to overlap.  I'm not sure about the best way to do this (I'm not 100% familiar with the VexFlow metrics that would affect this).  I'm also wondering if these various tuplet loops can be combined, but it might not be possible since the first one is happening in the "smart" `generateBeams()`, and the other is happening just from the normal beam drawing logic.

**Comment by aaronmars** [comment]
Brought in the refactor from @Silverwolf90 and things cleaned up quite a bit.  The change I'll be submitting here just addresses the tuplet inspection in beam.js:

**Before:**
<img width="566" alt="screen shot 2016-07-31 at 08 03 21" src="https://cloud.githubusercontent.com/assets/847926/17277364/0b29ff32-56f6-11e6-8af8-b5b1b274915a.png">
**After:**
<img width="557" alt="screen shot 2016-07-31 at 08 04 50" src="https://cloud.githubusercontent.com/assets/847926/17277369/19ae0e90-56f6-11e6-95c2-c43cd3f3af0c.png">
