### ISSUE TITLE
Editorconfig

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#376]
I really like the idea of .editorconfig (http://editorconfig.org).  It allows a project to define some basics (like indentation, newlines, etc.).  This way, editor applications can conform to these settings per-project.

I am a perfect use case as I prefer 4-space indentation, and I'd like my editor to default to that.  VexFlow uses 2 spaces, so if it has an .editorconfig, I don't have to constantly change the settings in my editors/IDEs.

The best thing is this just helps catch eventual linter errors before they happen, and it helps maintain code style.  It's totally opt-in since it requires a compatible editor.

Is this an OK thing to add?

**Comment by mscuthbert** [comment]
Please, please! I haven't done too many pushes to the Vexflow codebase, but when I have it's always needed an extra roundtrip (before Lint was added) because I used 4 spaces instead of 2.  :-)

**Comment by 0xfe** [comment]
Yes, lets try it out. (I've never used it before.)

**Comment by peterankelein** [comment]
I realize this is an older discussion but since it was never done, hope you don't mind I took it on as a first contribution.

**Comment by rvilarl** [comment]
@0xfe this one can be closed.
