### ISSUE TITLE
Lots of duplicate assertions

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#382]
The codebase is littered with duplicate assertions like the following:

``` javascript
if (!this.context) {
  throw new Vex.RERR('NoCanvasContext', "Can't draw without a canvas context.");
}
```

This block of code exists in nearly every class which renders to the canvas (and often many times per file). We should extract these out into generic assertions which can be reused.

**Comment by rvilarl** [comment]
@0xfe this is already done with `checkContext` and `check<T>`. I believe it can be closed.
