### ISSUE TITLE
Migrate Tutorial to Wiki

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#396]
The tutorial is old and stale and built before awesome tools like jsfiddle, and is a huge pain to update.

We should put everything in the Wiki, and use [jsfiddle examples like this](https://jsfiddle.net/nL0cn3vL/2/) which people can play with.

**Comment by mscuthbert** [comment]
yes, yes! Should the fiddle migration wait until https://trello.com/b/LakLkQBW/jsfiddle-roadmap "Sync Fiddles with GitHub" is complete?

**Comment by 0xfe** [comment]
Thanks for the pointer. Not sure how long that would take to actually get deployed.

**Comment by 0xfe** [comment]
Okay, done. Moved everything to https://github.com/0xfe/vexflow/wiki/The-VexFlow-Tutorial and changed the link in README.md.

Also, updated all the examples to the current API, added JSFiddle links, and new screenshots. (We'll leave the screenshots in until we find a good way to embed the fiddles in the wiki.)

Feel free to update/fix the new doc.
