### ISSUE TITLE
Support for drum's notation?

### ISSUE THREAD

**Issue by ichionid** [0xfe/vexflow#405]
Hey,
I am really happy to find out a library that supports html renderning of notation. I am looking forward to creating a machine learning app with React. Would you support drum's notation? Do you believe that this is doable with your js lib by extending it, i feel like trying it :-)

**Comment by Silverwolf90** [comment]
VexFlow does have support for percussion noteheads.

http://public.vexflow.com/tests/ -- search for "Percussion" to see some examples

**Comment by Silverwolf90** [comment]
The code for these tests are in this file https://github.com/0xfe/vexflow/blob/master/tests/percussion_tests.js
