### ISSUE TITLE
Is it possible for us to hide the "Rest Note" in multiple voices conditions?

### ISSUE THREAD

**Issue by PatrickCSFan** [0xfe/vexflow#406]
Thanks for the great work of the new version of vexflow!
We are trying to use vexflow in a multiple voices condition - I am not sure if we have missed anything in the document. May I know if there is any quick way to automatically hide the "rest note" in the following condition? (The first and third notes)

https://jsfiddle.net/3hk4fha5/

![image](https://cloud.githubusercontent.com/assets/10361578/17270673/386c08e2-569b-11e6-988e-393579c41d74.png)

**Comment by Silverwolf90** [comment]
You can use the `GhostNote` class for "hidden" rests.

**Comment by PatrickCSFan** [comment]
Oh Cool! Thanks @Silverwolf90!
