### ISSUE TITLE
Dots should be aligned on chords with displaced noteheads 

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#410]
See Behind Bars, page 57, "chords with adjacent notes" 

> Align dots vertically for each part, independently of other chords

Currently the dots are not aligned:

![image](https://cloud.githubusercontent.com/assets/1631625/17461483/8e8994e8-5c85-11e6-9196-15c963a649d3.png)

**Comment by sug1no** [comment]
fixed with #665.
