### ISSUE TITLE
Vertical formatting results in lots of collisions when mixing elements and changing sizes

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#411]
This relates to a lot of things I've been bringing up lately (positioning, boudingboxes, units, hardcoded values, etc). So I figured I should showcase the current state of vertical formatting:

![image](https://cloud.githubusercontent.com/assets/1631625/17462011/57e1096a-5c96-11e6-839a-3983db1bee12.png)

https://jsfiddle.net/vrd5757s/1/

Fundamentally, the mixing of elements should not be a complex case to handle: advance the position of the next element by some value derived from the previous element. There are implementation details around this, but the basic mechanism is the same. The current formatting lifecycle, specifically the `ModifierContext` (see https://github.com/0xfe/vexflow/issues/409) and the `.format()` methods make this much more convoluted then it needs to be, while also enforcing an inflexible ordering of `Modifiers` which is problematically opinionated.

**Comment by rvilarl** [comment]
@AaronDavidNewman the test is there in #1238 

![image](https://user-images.githubusercontent.com/22865285/142896887-be15dc4e-089c-4182-84d8-26108c9fd86f.png)

**Comment by AaronDavidNewman** [comment]
I should have a chance to look at this in the next week or so

**Comment by rvilarl** [comment]
@AaronDavidNewman is this one now closed?

**Comment by AaronDavidNewman** [comment]
yes this can be closed, thought it was

**Comment by rvilarl** [comment]
@Silverwolf90 @0xfe @ronyeh please close.
