### ISSUE TITLE
Riffing off the Builder strawman - going higher-level

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#415]
My main thought is that it's too low level. The tests don't really feel any cleaner to me. Simply saving a couple calls to `setStave` and `setContext`  doesn't seem to warrant the added cognitive load of a new API.

In the following example I go with a more declarative/config-based API, while exposing hooks to apply transformations to the objects.

```javascript
// A more succinct way to prepare StaveNotes
const topNotes = ['f/5', 'e/5', 'd/5', 'c/5', 'c/5', 'd/5', 'e/5', 'f/5']
  .map(wrapKeys) // converts  'f/5' to { keys: ['f/5'] }
  .map(setStem(VF.Stem.UP))
  .map(setDuration('8'))
  .map(newNote);

// Typical and verbose way of declaring`StaveNotes` in tests
const bottomNotes = [
  newNote({ keys: ['f/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['e/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['d/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['c/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['c/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['d/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['e/4'], stem_direction: -1, duration: '8' }),
  newNote({ keys: ['f/4'], stem_direction: -1, duration: '8' }),
];

const someBuilderConfig = {
  domNodeSelector: canvasSelector,
  contextBuilder,
  width: 450,
  height: 500,
  staveSpace: 10
};

new Builder(someBuilderConfig)
  .addStave({
    x: 10,
    y: 10,
    transform: (stave) => stave.addClef('treble').addTimeSignature('4/4'),
  })
  .addStave({
    x: 10,
    y: 150,
    transform: (stave) => stave.addClef('bass').addTimeSignature('4/4'),
  })
  .addVoice({
    staveIndex: 0,
    notes: topNotes,
    beams: [[0, 4], [4, 8]], // beams and tuplets are so common, maybe basic usage should get shortcuts?
  })
  .addVoice({
    staveIndex: 1,
    notes: bottomNotes,
    beams: [[0, 4], [4, 8]],
  })
  .add(  // can add any generic element
    new VF.TextBracket({
      start: bottomNotes[0],
      stop: bottomNotes[bottomNotes.length - 1],
      text: '8',
      superscript: 'vb',
      position: VF.TextBracket.Positions.BOTTOM
    })
  )
  .format()
  .draw();
```

That code builds:

![image](https://cloud.githubusercontent.com/assets/1631625/17643043/928c4494-6155-11e6-9f27-97acc5efa894.png)

Worth noting that neither implementation support multiple measures, and most use-cases (and a significant amount of tests) require multi-measure layout. But this enters formatting territory that VexFlow has not yet tackled.

**Comment by 0xfe** [comment]
I should actually call the strawman a Factory instead of a builder, because the main purpose of the API is to return preconfigured VF elements. I would expect a proper builder API (like yours) to use the factory underneath, so we can switch out implementations, styles, etc. simply by changing the factory.

BTW, #195 is another proposal for a builder, but think yours is nicer and more idiomatic JS.

**Comment by Silverwolf90** [comment]
Ah, ok! That makes sense for a factory. But it's doing a lot of other stuff in addition to constructing objects. It's creating the rendering context, formatting the staves to the context width, and drawing the elements it created. That feels like too much.

Tricky case: How would one set-up a voice that traverses 2 staves?

**Comment by 0xfe** [comment]
A few comments about your builder proposal. I think we should try to avoid indexing as much as we can, and see if we can offer a more natural nested interface. In your example, you connect the voice to the stave via an index, which can get messy if they added a new stave in between, and everything gets reindexed.

If you need to refer to some element, you assign it a value during creation.

Also, the `x` and `y` values, clefs, time and key signatures, etc. should be part of current builder state and need not be specified unless overridden.

So:

```javascript
someBuilderConfig = { ..., position: {x: 10, y: 10}, ... }
let builder = new Builder(someBuilderConfig)

builder
  .setKey('G').setTimeSignature('4/4')
  .newSystem()
    .newStave({transform: (stave) => stave.addClef('treble')})
       .newVoice().addNotes(notes1)
       .newVoice().addNotes(notes2)
    .newStave({transform: (stave) => addClef('bass')})
       .newVoice().addNotes(notes3)
       .newVoice().addNotes(notes4)
  .newSystem()
    .newStave(...).setKey("C")
       .newVoice(...)
  .draw()
```

This has a few advantages: 1) you can easily write a parser for a document format (like MusicXML), 2) even if you use it by hand, it's easy to edit, insert, remove elements without readjusting values everywhere, 3) you have some clearly defined semantics for `new`, `set`, `add`, and they can behave predictably.

Thoughts?

**Comment by 0xfe** [comment]
Re: your comment extra stuff, it's partly personal preference, but I think that's okay for a factory to do. It's a tradeoff between too much design and practicality. My goal for this factory is to be a helper that reduces plumbing effort and duplication.

Hopefully it can become an interface for builders, but still need to think it through a bit.

**Comment by Silverwolf90** [comment]
It's tough for me to see how that might really work given the contrived example, it would need to be fleshed out significantly. I'm not convinced that an API like can handle non-trivial complexity.  I've found that music notation does not naturally nest. What about cross-staff voices, cross-staff chords,  cross-measure beams, cross-measure tuplets, spanning elements, (ie: brackets, slurs)? All these objects transcend a nested structure.

**Comment by 0xfe** [comment]
Yes, definitely need to flesh it out, and also agree that not everything can be nested, but I think it's the right place to start, because it's simpler (for the user) to work with.

I think we can devise multiple ways to handle the cross-element notation, and ideally we can do it within this framework. E.g., if we assign ID's to elements, then we can refer to them in the middle of the documents, say, if we want to reassign a note to a different voice. 

Here's a strawman with a voice that spans staves, and a slur:

```javascript
let builder = new Builder(someBuilderConfig)

builder
  .setKey('G').setTimeSignature('4/4')
  .newSystem()
    .newStave({id: 'topStave', transform: (stave) => stave.addClef('treble')})
       .newVoice().addNotes(notes1)
       .newVoice().addNotes(notes2)
    .newStave({transform: (stave) => addClef('bass')})
       .newVoice()
          .addNotes([
            {key: 'a/4'},
            {key: 'b/4'},
            {key: 'c/5', stave: 'topStave'},
            {key: 'd/5', stave: 'topStave'},
            {key: 'e/5'},
            {key: 'f/5', id: 'slurStart'},
            {key: 'g/5', id: 'slurEnd'},
          ])
     .newVoice().addNotes(notes6)
  .newSystem()
    .newStave(...).setKey("C")
       .newVoice(...);

builder.createSlur({from: 'slurStart', to: 'slurEnd'});
builder.draw();
```

Or alternatively by updating the stave of a note later:

```javascript
let builder = new Builder(someBuilderConfig)

builder
  .setKey('G').setTimeSignature('4/4')
  .newSystem()
    .newStave({id: 'topStave', transform: (stave) => stave.addClef('treble')})
       .newVoice().addNotes(notes1)
       .newVoice().addNotes(notes2)
    .newStave({transform: (stave) => addClef('bass')})
       .newVoice()
          .addNotes([
            {key: 'a/4', id: 'lowA'},
            {key: 'b/4'},
            {key: 'c/5'},
          ])
     .newVoice().addNotes(notes6)
  .newSystem()
    .newStave(...).setKey("C")
       .newVoice(...);

builder.updateElement('highC', {stave: 'topStave'})
builder.draw();
```

There's lots of ways to skin this cat, but I think we can totally make this nested structure work as a base, with the right provisions for the non-nested elements. It would be great if we could identify the different classes of non-nested notation, and have general ways to work with them.

**Comment by Silverwolf90** [comment]
But now we are back to indexing (via ids -- which could definitely be used above as well). This only manages to avoid indexing staves **sometimes**,  so again I'm not sure this is worth the nested structure. Flat seems *a lot* more flexible at a very slight cost. It's very elegant, and probably makes it easier to write stuff out by hand, but is this the common use case in production? There are many other solutions much more suited for that kind of use-case.

It's worth noting that the requirements for something like this are **much** higher. Before this could be implemented we would need some sort of System and Stave formatter. I'd argue that something this high-level is out-of-scope for VexFlow and should be in a separate project. I think a case could be made to separate *all* formatting code from rendering code, but that's another matter.

**Comment by 0xfe** [comment]
Yeah, I think it's out of scope too, and probably a separate project. I also think the purpose of this builder is to generate scores, which may be different from your intended purpose for a builder.

Re: formatters for systems, I'd love to have something inside VexFlow. I don't think that's too far out of scope from stave formatters.

**Comment by SalahAdDin** [comment]
Eh, i don't understand this.

**Comment by Silverwolf90** [comment]
Can you elaborate?
