### ISSUE TITLE
Rationalize `getExtraPx` and `getMetrics`

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#418]
We have `getMetrics` which seems to return all of the same information as `getExtraPx`, and is used well across the codebase.

There are currently 4 references to `getExtraPx`.

Your mission, if you choose to accept it, is to replace these references with `getMetrics`, and kill `getExtraPx` once and for all.

**Comment by rvilarl** [comment]
@0xfe you can close this one. There is no `getExtraPx` in the code.
