### ISSUE TITLE
Incorrect notehead displacement when `.setStemDirection` is called after construction

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#436]
~~Take a look at the `EasyScore - Draw Basic` test. The chord's noteheads are incorrectly displaced.~~

Take a look at what happens if you call `setStemDirection(Stem.DOWN)` after the construction of a stem-up chord with displaced noteheads.

![image](https://cloud.githubusercontent.com/assets/1631625/18035893/e85b740a-6d56-11e6-8918-1d76fff7394d.png)

My guess is that the noteheads only get built on construction, and so changing the stem after construction does not change placement. That being said, the displacement of noteheads is certainly a kind of "formatting" and not something to be done on construction. However, that's a larger change, and in the meantime we should rebuild when `setStemDirection()` is called.

**Comment by 0xfe** [comment]
`EasyScore - Draw Basic` seems to render correctly for me. Your branch broken?

<img width="587" alt="screen shot 2016-08-28 at 5 06 03 pm" src="https://cloud.githubusercontent.com/assets/241299/18036760/be336a30-6d41-11e6-874f-6666367f3bff.png">

**Comment by Silverwolf90** [comment]
You're right the blessed test isn't, I must have changed the chord's notes for some reason. Although the case of setting `setStemDirection` to `DOWN` after construction on a displaced chord is indeed broken.

**Comment by Silverwolf90** [comment]
Edited original post.

**Comment by 0xfe** [comment]
Looks like this bug is breaking your PR. I think you could move `buildNoteHeads()` and `buildStem()` out of the constructor, and have them called on `setStemDirection()`.

**Comment by Silverwolf90** [comment]
I fixed the test in the PR -- I'll move that logic and create a related test in a separate PR.

**Comment by 0xfe** [comment]
NM, it was a straightforward fix. I'll commit it with the merge.

**Comment by 0xfe** [comment]
This is fixed.
