### ISSUE TITLE
Unable to build vexflow

### ISSUE THREAD

**Issue by Huji** [0xfe/vexflow#443]
The `npm install` command fails with the attached log.
[npm-log.txt](https://github.com/0xfe/vexflow/files/443144/npm-log.txt)

**Comment by 0xfe** [comment]
@Huji What machine are you doing this on? I have VexFlow building on Mac, Windows, and Linux. Also the current `master` branch builds fine on [Travis CI](https://travis-ci.org/0xfe/vexflow/builds/155767288).

**Comment by Huji** [comment]
It is a linux machine (Ubuntu 16.04)

**Comment by Silverwolf90** [comment]
Looks like installation is failing on SlimerJS. Could you try installing that dependency manually?

`npm install slimerjs`

**Comment by 0xfe** [comment]
On Ubuntu, the symlinks to `node` are broken (it uses `nodejs` instead of `node`). The following command fixes the links.

```javascript
sudo apt-get install nodejs-legacy
```

Also, BTW, you're using a very old version of Node (4.2.6). I'd recommend upgrading to at least 6.x.

**Comment by Huji** [comment]
@0xfe that fixed it.
