### ISSUE TITLE
Append new bars on next line?

### ISSUE THREAD

**Issue by VolvoOlympian** [0xfe/vexflow#448]
Is it possible to append new bars to the next row?

**Comment by Silverwolf90** [comment]
Hi VolvoOlympian,

Currently VexFlow doesn't support automatic placement of multiple systems -- you'll have to manage that in your own code.

**Comment by mscuthbert** [comment]
VexFlow doesn't care, however, if two tied notes are on the same Vex.Flow.Stave or not and will draw the ties between them properly.  So just create a new Vex.Flow.Stave for the next system
