### ISSUE TITLE
Babel 6.14 removes need for loose mode...

### ISSUE THREAD

**Issue by mscuthbert** [0xfe/vexflow#449]
`__proto__` broken in IE9/10 (#404) has been fixed as of 8/24 in Babel, so the es2015-loose mode is no longer necessary if we bump the min babel version:

https://github.com/babel/babel.github.io/blob/master/_posts/2016-08-24-6.14.0.md

(and I thank everyone here for all the training and learning on ES6/babel, etc. -- finally applying what I've learned here to music21j -- so cross-compatibility may be much easier soon!)

**Comment by 0xfe** [comment]
Thanks for notifying. So, no need for legacy builds?
