### ISSUE TITLE
`Factory` method conventions

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#457]
So far, the `Factory` methods seem bring a bit more consistency to object construction. Now that we've implemented a variety of objects, it might be worth defining some conventions. I think there's a bit of inconsistency that could be ironed out.

Two forms of Factory method arguments exist so far:
1. An object with all config properties at the top level
   - The object is passed straight into the respective constructor
   - eg: `StaveNote(noteStruct)`, `GraceNote(noteStruct)`
2. An object with properties and a nested `options` object
   - The object is picked apart and the values passed appropriately -- this could be to a constructor or to subsequent method calls.
   - eg: `Beam(params)`, `Stave(params)`, `Annotation(params)`

For the latter, it's not really clear to me how the `options` object is intended to be used. Take the defaults for `Annotation` :

``` javascript
{
  text: 'p',
  vJustify: 'below',
  hJustify: 'center',
  fontFamily: 'Times',
  fontSize: 14,
  fontWeight: 'bold italic',
  options: {},
}
```

Since the font/justification properties are at the "top level", what goes in the `options` object? Not that they shouldn't be "top level" properties, but the distinction between the two tiers is not clear to me.

**Comment by 0xfe** [comment]
I agree this is a good time to raise and rethink this. The inconsistency in `StaveNote` has bothered me too, but I'm not entirely sure how to rationalize, because I think it's pretty reasonable.

I think it's important to note that the `Factory` API is not set in stone and we can iterate on it. My intended pattern for factory methods was something like:

```javascript
Factory.Element(params, factoryOptions)
```

Above `params` should look like this:

```javascript
{
  param1: ...,
  param2: ...,
  options: { ... }
}
```

The `paramX` fields are **required** and `options` include everything optional. So for `Annotation`, ideally we'd do this:

```javascript
{
  text: 'p',
  options: {
    vJustify: 'below',
    hJustify: 'center',
    fontFamily: 'Times',
    fontSize: 14,
    fontWeight: 'bold italic',
  }
}
```

It's not like that now, but perhaps we should settle on it?

**Comment by 0xfe** [comment]
Looking at `factory.js` now, it looks like most of the methods are sane. Only `Annotation` is inconsistent. (Ignoring `StaveNote` and `GraceNote` for now.)

**Comment by 0xfe** [comment]
And thinking about `StaveNote` and `GraceNote`, perhaps we should:

```javascript
{
  keys: [...],
  duration: ...,
  options: {
    type: ...,
    dots: ...,
    ...
  }
```

Maybe?

**Comment by Silverwolf90** [comment]
When you say **required**, do you mean, required to be passed to the constructor of the object? Or, required as part of the `params` object passed to the `Factory` method?

**Comment by 0xfe** [comment]
I mean required for the construction of a valid object. You can't have a `StaveNote` without `keys` or `duration` so they're required. You can, OTOH, construct a valid `StaveNote` without providing `type` or `dots` because you can have reasonable defaults.

**Comment by Silverwolf90** [comment]
Cool that makes sense to me!

**Comment by rvilarl** [comment]
@0xfe I think you can close this one.
