### ISSUE TITLE
removing elements from the score

### ISSUE THREAD

**Issue by wilkerlucio** [0xfe/vexflow#466]
Hey, is there a way to remove specific items from the score after drawn? I'm trying to write a React wrapper for Vexflow, so would be nice to remove elements from the score after they get removed at the react render tree. I saw in issue #371 that in the SVG drawings I could access the rendered element, which is great! The problem I faced is that sometimes a note adds more than just itself, for example, https://jsfiddle.net/8eckj32x/13/

In that JSFiddle, if you add in the end this code:

``` javascript
voice.tickables[0].attrs.el.remove()
```

You will notice that the note is removed, but the extra line draw at the end isn't, making this way of deleting inconsistent.

Is there another way to remove specific items from the score after drawn?

**Comment by Silverwolf90** [comment]
In this specific case, I probably would expect the ledger lines to be included in the SVG group for the note. But, generically, removing individual elements is not a supported VexFlow behavior. I think you'll have to clear all and redraw everything for expected result. Basically partial updating of rendered notation is not supported (as this would have to be supported in both SVG and Canvas). Using the method you described (ie: the native DOM methods) you might be able to get pretty far with manually manipulating the SVG, but it won't always work consistently (as you've discovered).
