### ISSUE TITLE
Beam.generateBeams algorithm gives wrong results on dotted rhythms

### ISSUE THREAD

**Issue by andiejs** [0xfe/vexflow#467]
The code below should automatically beam the notes in groups of 1/4 notes (i.e. as in 4/4 time); instead it beams like: (dotted-quarter) (eighth, eighth) (eighth, eighth) (eighth).

Looks like the algorithm is wrong in that it groups the dotted-quarter as one group (since it can't break it) and then starts a new group at the next eighth. Probably would be better to keep track of the fact that 1/8 of the next group was already used up.

Thanks!
Andie

```javascript
VF = Vex.Flow;

// Create an SVG renderer and attach it to the DIV element named "boo".
var div = document.getElementById("boo")
var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);

// Configure the rendering context.
renderer.resize(500, 500);
var context = renderer.getContext();
context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

// Create a stave of width 400 at position 10, 40 on the canvas.
var stave = new VF.Stave(10, 40, 400);

// Add a clef and time signature.
stave.addClef("treble").addTimeSignature("4/4");

var notes = [
  new VF.StaveNote({ keys: ["a/4"], duration: "4d" }).addDotToAll(),
  new VF.StaveNote({ keys: ["b/4"], duration: "8" }).
    addAccidental(0, new VF.Accidental("b")),
  new VF.StaveNote({ keys: ["c/4"], duration: "8" }),
  new VF.StaveNote({ keys: ["d/4"], duration: "8" }),
  new VF.StaveNote({ keys: ["e/4"], duration: "8" }).
      addAccidental(0, new VF.Accidental("b")),
  new VF.StaveNote({ keys: ["d/4"], duration: "8" })
  ];

var beams = VF.Beam.generateBeams(notes, {groups : [ new Vex.Flow.Fraction(1,4) ]});
Vex.Flow.Formatter.FormatAndDraw(context, stave, notes);
beams.forEach(function(b) {b.setContext(context).draw()})
// Connect it to the rendering context and draw!
stave.setContext(context).draw();
```

**Comment by Silverwolf90** [comment]
Yup, looks like a bug.

Screenshot of case:

<img width="431" alt="screen shot 2016-11-18 at 4 44 37 pm" src="https://cloud.githubusercontent.com/assets/1631625/20451481/b4428c60-adae-11e6-94f1-7fabaff2d661.png">

**Comment by gristow** [comment]
In case someone wants to make a start on this -- I have an auto-beaming routine I wrote for a project that addresses metric beaming within meters. I'm unfortunately swamped right now and haven't had the time to move this upstream into the VexFlow code... but the algorithm seems to be pretty solid. (To implement this in VexFlow, we also need an option to be able to force partial beams to point right or left.)

In any case... here's my metric beaming routine, using Vex's `Fraction` class and relying on a fractional value for any meter to indicate how much of a meter can be beamed together. It's not the cleanest code, but the algorithm is fairly solid and tested at this point:

```javascript
// Metric Beaming:
// takes a measure of notes & rests, and breaks them into beam groups
// to be beamed by vexFlow.
//
// This works according to the meter -- unlike VexFlow's more primitive
// autobeaming routines. GCR TODO: Long term, convert this directly to
// VexFlow and push upstream.

import Fraction from './fraction';

const autoBeam = (measure, timeSignature) => {
  let activeGroup = [];
  const beamGroups = [];

  // Determine the default beaming fraction:
  const beamingFraction = timeSignature.beatDuration.getFraction();

  // Divide into measure parts following beaming fraction:
  // noteHolder is roughly the same thing as VexFlow's StaveNote with some helper routines added.
  // a Measure is a collection of NoteHolders
  const noteHolders = measure.getNoteHolders();
  const pointerFraction = new Fraction(0, 1);
  let groupPointerFraction = new Fraction(0, 1);
  let holderPointerIndex = 0;
  let currentGroup = [];
  const measureParts = [];

  const debug = false;
  const log = (s) => { if (debug) console.log(s); };

  // Helper functions:
  const calculateSingletonDirections = (group) => {
    // For each note:
    for (let i = 0; i < group.length; i++) {
      const priorNote = group[i - 1];
      const note = group[i];
      const nextNote = group[i + 1];

      // Is it a singleton (aka partialBeam in vex terminology)?
      const singleton = (
          // It has more than the previous note's beams:
          priorNote && nextNote &&
          priorNote.holder.rhythm.numberOfBeams() <
          note.holder.rhythm.numberOfBeams() &&
          // And it has more than the next note's beams:
          nextNote.holder.rhythm.numberOfBeams() <
          note.holder.rhythm.numberOfBeams()
      );

      if (singleton) {
      // Should it's flag point right?
        // Does its startPointer modulo its parent rhythm (twice as long)
        // equal zero? If so -- it's at the start of its subdivisional unit
        // and should point to the right. Otherwise, it should point to the
        // left.
        log(`${note.pointerFraction
          } % (${
            note.holder.rhythm.getFraction()
            } * 2) = ${
            note.pointerFraction.clone()
            .modulo(note.holder.rhythm.getFraction().multiply(2))
            .equals(0)}`
        );
        if (
          note.pointerFraction.clone()
            .modulo(note.holder.rhythm.getFraction().multiply(2))
            .equals(0) ) {
          log('Forcing partial right: ');
          log(note);
          note.partialDirection = 'right';
        } else {
          log('Forcing partial left: ');
          log(note);
          note.partialDirection = 'left';
        }
        if ( note.holder.forcePartialDirection ) {
          note.partialDirection = note.holder.forcePartialDirection;
          log(`Manual direction override: ${note.holder.forcePartialDirection}`);
        }
      }
    }
  };

  const newGroup = () => {
    log('new group');
    // If there are more than two notes, save it as a beam group:
    if (activeGroup.length >= 2) {
      calculateSingletonDirections(activeGroup);
      beamGroups.push(activeGroup);
    }

    // Start a new active group:
    activeGroup = [];
  };


  while (holderPointerIndex < noteHolders.length) {
    const rhythmFraction = noteHolders[holderPointerIndex].rhythm.getFraction();

    const newGroupNeeded =
        // The current group has one note already and:
        ( currentGroup.length > 0 &&
        // We're at the beginning of a new beam group:
        // (aka our pointer mod beamingFraction = 0),
        ( pointerFraction.modulo(beamingFraction).equals(0) ||
        // Or adding the next note would make the current group bigger
        // than a beaming fraction,
        groupPointerFraction.clone().add(rhythmFraction)
        .greaterThan(beamingFraction) ||
        // Or adding the next note would cross a beaming point:
        Math.floor( pointerFraction.clone() // Last beam point after addition
                    .add(rhythmFraction)
                    .divide(beamingFraction)
                  ) -
        Math.floor( pointerFraction.clone() // Last beam point
                    .divide(beamingFraction)
                  ) > 1
        )
    );

    if (newGroupNeeded) {
    // then terminate the current group and begin a new one:
      measureParts.push(currentGroup);
      currentGroup = [];
      groupPointerFraction = new Fraction(0, 1);
    }
    // Add the current note to the current group & update the pointer:
    currentGroup.push({
      holder: noteHolders[holderPointerIndex],
      pointerFraction: pointerFraction.clone(),
    });
    pointerFraction.add(rhythmFraction);
    groupPointerFraction.add(rhythmFraction);
    holderPointerIndex++;
  }

  // Add the last group:
  measureParts.push(currentGroup);

  log('measureParts');
  log(measureParts);

  // For each measurePart
  for (let i = 0; i < measureParts.length; i++) {
    const part = measureParts[i];
    // Can't have a beam if only one beamable...
    // eslint-disable-next-line no-continue
    if (part.length < 2) continue;
    // Loop through notes within each beaming Fraction
    for (let j = 0; j < part.length; j++) {
      const priorNote = part[j - 1];
      const note = part[j];
      const nextNote = part[j + 1];

      // Is it beamable?
      if (
        // 8th note or smaller
        note.holder.isBeamable() &&
        // Followed or preceeded by beamable note within
        // the same group?
        ( ( nextNote && nextNote.holder.isBeamable() ) ||
          ( priorNote && priorNote.holder.isBeamable() ) )
      ) {
        log('adding to the group...');
        // Add it to the beamGroup!
        activeGroup.push(note);
      } else {
        log('new group: ' );
        log(activeGroup);
        // Otherwise, start a new beam group:
        newGroup();
      }
      if (!nextNote) newGroup();
    }
  }

  return beamGroups;
};

export default autoBeam;
```

**Comment by andiejs** [comment]
Here's my easy fix to the createGroups() function in beam.js. I added tickrunningtotal. My changes are signed below.

      function createGroups() {
	  let nextGroup = [];
	  let tickrunningtotal = new Fraction(0, 1);//ANDIE
	  unprocessedNotes.forEach(unprocessedNote => {
              nextGroup    = [];
              if (unprocessedNote.shouldIgnoreTicks()) {
		noteGroups.push(currentGroup);
		  currentGroup = nextGroup;
		  return; // Ignore untickables (like bar notes)
              }
              currentGroup.push(unprocessedNote);
              const ticksPerGroup = tickGroups[currentTickGroup].clone();
              const totalTicks = getTotalTicks(currentGroup).add(tickrunningtotal); //ANDIE
	      
              // Double the amount of ticks in a group, if it's an unbeamable tuplet
              const unbeamable = Flow.durationToNumber(unprocessedNote.duration) < 8;
              if (unbeamable && unprocessedNote.tuplet) {
		ticksPerGroup.numerator *= 2;
              }
	      
              // If the note that was just added overflows the group tick total
              if (totalTicks.greaterThan(ticksPerGroup)) {
		  // If the overflow note can be beamed, start the next group
		  // with it. Unbeamable notes leave the group overflowed.
		if (!unbeamable) {
		    nextGroup.push(currentGroup.pop());
		}
		  noteGroups.push(currentGroup);
		  
		  tickrunningtotal = totalTicks.subtract(ticksPerGroup); //ANDIE
		  while (tickrunningtotal.greaterThanEquals(ticksPerGroup)) {
		      tickrunningtotal = tickrunningtotal.subtract(ticksPerGroup);
		  } //ANDIE
		  currentGroup = nextGroup;
		  nextTickGroup();
              } else if (totalTicks.equals(ticksPerGroup)) {
		  noteGroups.push(currentGroup);
		  tickrunningtotal = new Fraction(0, 1); //ANDIE
		  currentGroup = nextGroup;
		  nextTickGroup();
              }
	  });
	  
	  // Adds any remainder notes
	beam  if (currentGroup.length > 0) {
              noteGroups.push(currentGroup);
	  }
      }

**Comment by mscuthbert** [comment]
if it's at all helpful, the beaming algorithm from music21j is available at https://github.com/cuthbertLab/music21j/blob/master/src/music21/beam.js (called from meter.js and stream.js -- makeBeams() )  -- obviously the objects are different, but the logic of all the things that need to be taken into consideration (offsets for pickup measures, etc.) could be used to help the Vexflow algorithms.  In music21j the Beams object represents the amount of beaming on a single note, so it's not the same as the Vexflow Beam object, which is the beaming structure on a group of notes.

Some of the things that the current Beam object doesn't seem able to represent are "tertiary beam breaks" (and further) for breaking 16th note beams at the 32nd note level, and setting the direction of partial beams (for instance, in 6/8, in the pattern 8 16 8 16, the first 16th note can have the partial go left or right depending on whether the composer intends a sub grouping of 1/8 or 3/16).

Tertiary beam breaks are rare enough, I'll defer doing it till later, but I'll try to get in an interface for setting partial beam direction in soon.
