### ISSUE TITLE
Notes don't adjust to clef change

### ISSUE THREAD

**Issue by PCrompton** [0xfe/vexflow#469]
When I change the clef from "treble" to "bass" in my score, the notes remain on the same line and spaces and are therefore not accurate in the new clef.

**Comment by PCrompton** [comment]
Ok, so after googling around I figured out that I need to add the clef key to StaveNote initialization, but it would be nice have that in the documentation somewhere.

**Comment by Silverwolf90** [comment]
This is correct, including `Clef` elements does not impact the `StaveNotes` in the voice. You must manually provide the `StaveNote` with the expected `clef` on construction.

So to make a note in bass clef:

```javascript
const noteInBassClef = new Vex.Flow.StaveNote({ keys: ['c/4'], clef: 'bass', duration: '4' });
```

**Comment by mix3d** [comment]
That's really too bad, it would be AWESOME if the notes were universal, and the staff's clef defined how notes were drawn; ESPECIALLY if you could change the clef dynamically (which you cant, bleh), and the notes updated automatically.
