### ISSUE TITLE
Measures within EasyScore 

### ISSUE THREAD

**Issue by ergodaveh** [0xfe/vexflow#471]
Many thanks for providing this project.  I have recently begun using  this project, firstly by trying out the EasyScore API.  I have read the example article found [here ](https://github.com/0xfe/vexflow/wiki/Using-EasyScore) and looked through the easyscore.js.  The example shows a single measure with notes.  But the API does not appear to have any methods to add additional measures to a stave.  Is this a feature of the EasyScore API?  Ifso,  how can I add measures or a barline to a Stave.  

**addtional comment**

Recently viewed the easyscore.js which show these lines referring to the voice and options:
```javascript
voice(notes, voiceOptions) {
  voiceOptions = Object.assign({ time: this.defaults.time }, voiceOptions);
  return this.factory.Voice(voiceOptions).addTickables(notes);
}
```
Does/will the Options have a property for the number of beats(num_beats)  similar to this
```javascript
Vex.Flow.TIME4_4 = {
  num_beats: 8,   //results: shows two measure 
  beat_value: 4,
  resolution: Vex.Flow.RESOLUTION
};
```
which is passed to the `VF.Voice(Vex.Flow.TIME4_4).addTickables(notes);`

Does easyScore have such a feature?  ifso, does anyone have demonstrative example.

**Comment by Silverwolf90** [comment]
Take a look at the example here: https://github.com/0xfe/vexflow/blob/master/tests/bach_tests.js

It builds up a score with easy score that looks like this:

![Bach Minuet in G](https://camo.githubusercontent.com/8b7356acc32db4764828e5c34012ae701f15805a/687474703a2f2f696d6775722e636f6d2f596646766a44442e706e67)

**Comment by Silverwolf90** [comment]
Concerning your second question, you can indeed pass the following to `voiceOptions.time`

Either
* A string, eg: `'5/4'`
* A an object, eg:  `{ num_beats: 8, beat_value: 4,  resolution: Vex.Flow.RESOLUTION }`

So:

`vf.Voice(fiveQuarterNotes, { time: '5/4' })`

**Comment by Silverwolf90** [comment]
I'm closing this for now, if these answer weren't helpful or didn't work feel free to reopen.

**Comment by bgrandjean** [comment]
Hello @Silverwolf90 

Your link is unfortunately dead:

https://github.com/0xfe/vexflow/blob/master/tests/bach_tests.js

How is it possible to juxtapose several measures with the EasyScore API?
Do you have another example pls?

Thanks a lot
Bruno

**Comment by sschmidTU** [comment]
@bgrandjean this link works:
https://github.com/0xfe/vexflow/blob/3.0.9/tests/bach_tests.js
Though the code might need to be updated for Vexflow 5, not sure.

**Comment by SausageDogger** [comment]
@sschmidTU Thanks! I cant believe that there is not exist a useful tutorial for EasyScore.And your job of OSMD is amazing XD
