### ISSUE TITLE
Order of StaveNote.keys does not match StaveNote.note_heads or setKeyStyle index param

### ISSUE THREAD

**Issue by LearningNerd** [0xfe/vexflow#472]
**Here's a CodePen demonstrating the problem: http://codepen.io/anon/pen/YpWNML?editors=0010** based on [the FAQ page here](https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#can-i-color-notes-individually).

If I create a new StaveNote with the keys in a _particular order_ (notice how G/4 is a higher pitch than C/4 but I'm listing the notes out of order here):
`var chord = new Vex.Flow.StaveNote({ keys: ['G/4', 'E/4', 'C/4'], duration: '8'});`

I would like to be able to programmatically style my C/4 note, currently at `chord.keys[2]`, to be a different color than all other notes -- let's say that I generate the StaveNote programmatically and I know that the last key has a special meaning, and all other keys in the chord are listed in the order in which they're pressed down by the user on a MIDI input device, not in order of their pitch.

So now if I try to do this, expected it to make my C/4 note red:
`chord.setKeyStyle(2, {fillStyle: "red"});`

When I render the note, G/4 note is colored red instead. I expected index 2 to match C/4 because that's how I listed the keys when I created the StaveNote. This is unintuitive and makes it harder for me to control the styling of my notes programmatically.

Thanks for your help on this! By the way, this is my first time opening an issue in an open source project (I'm still pretty newbish at programming), and just wanted to say I love this project and really appreciate all the hard work you all put into making VexFlow!!

**Comment by gristow** [comment]
It's a bit unintuitive but here's what's happening: the array you pass into the constructor is sorted so that it's in order from lowest note to highest note before the `StaveNote.note_heads` are created. This makes it possible, for instance, to determine which side of the stem notes should go on if they're only a 2nd apart, etc...

 So, in the example you give, the notes from lowest to highest would be ['C/4', 'E/4', 'G/4'], which is why `setKeyStyle(2, {})` is coloring the G/4.

**Comment by 0xfe** [comment]
Thanks Greg. 

FYI, there is a warning on the console when note are added in the wrong order.

**Comment by LearningNerd** [comment]
Yup, that's exactly what I see happening -- thanks @gristow! And thanks @0xfe, I had completely missed that! I still think this could be clarified in the docs better at least, or certainly mentioned in https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#can-i-color-notes-individually

And perhaps it would be more intuitive and consistent if `StaveNote.keys` were _also_ reordered so that its order matches that of `note_heads` ?

**Comment by 0xfe** [comment]
Yes, the docs need work.

Re: reordering, we can't do that because it makes the indexes inconsistent and will break a lot of users.

**Comment by gristow** [comment]
By the way, @LearningNerd, contributing to the docs is a great way to start getting involved in open source projects. As you find 'gotchas' that those of us who are deep in the code take for granted, consider writing them up to help other newcomers to VexFlow!

**Comment by LearningNerd** [comment]
@0xfe - You're right, that _would_ be bad. Hmm. OK, my last suggestion then, which is @lsegal's idea: what about a little helper function like `StaveNote.indexOf('C/4')` that would give me the index of wherever VexFlow put the note after sorting them?

@gristow - ah, yes! I will! :)

**Comment by 0xfe** [comment]
Yes, `indexOf` sounds like a useful helper, and would be straightforward to add. If you file a feature request, it will (eventually) get done. Thanks :-)

**Comment by Silverwolf90** [comment]
Popping in to add some edge cases to the mix :)

A chord can have multiple notes with the same pitch. On a single staff this typically doesn't exceed 2 identical notes:

![image](https://cloud.githubusercontent.com/assets/1631625/20446761/2258d34a-ad90-11e6-859f-da4b0c09c3f6.png)

And I do believe VexFlow already handles this case. The noteheads should displace correctly.

But to complicate matters further, let's talk about cross-staff chords! Technically a chord can cross any number of staves and thus could have any number of duplicate pitches. I realize that VexFlow doesn't support cross-staff chords (yet!) but it occurs often enough in printed music that it's worth considering how it's impacted by new functionality.

To me it seems to me that an `indexOf` function doesn't cover these cases well, since the first occurrence is not necessarily what you're looking for. Maybe an `indexesOf` which returns an array of all indexes for that pitch?

**Comment by 0xfe** [comment]
These are good corner cases, Cyril. For `indexesOf` to return an array, the sort needs to be stable (and I'm not sure if it is.)

**Comment by Silverwolf90** [comment]
Good point, if it's using the native `Array#sort` then it's not guaranteed to be stable (ie: depends on the browser).

**Comment by stephaneeybert** [comment]
Any work around to add a dot or an accidental to the correct key then ?

I'm [trying](https://stackoverflow.com/q/60801367/958373) to tell Vexflow add a dot to my key.

**Comment by sschmidTU** [comment]
@stephaneeybert I replied on your Stackflow question. You need to have your notes sorted by frequency in Vexflow, the rest is not a Vexflow problem.

**Comment by stephaneeybert** [comment]
Following your suggestion I could create the methods to sort the notes before adding them as keys in the stave:
```
  private getNoteFrequency(note: Note): number {
    return Tone.Frequency(note.renderAbc()).toFrequency();
  }

  private sortNotesByPitch(notes: Array<Note>): Array<Note> {
    return notes.sort((noteA: Note, noteB: Note) => {
      return this.getNoteFrequency(noteA) - this.getNoteFrequency(noteB);
    });
  }
```

**Comment by sschmidTU** [comment]
i believe this question was resolved [on stackoverflow](https://stackoverflow.com/q/60801367/958373) and can be closed.

**Comment by stephaneeybert** [comment]
As explained above I could avoid the warning message about the sorting of the keys, by sorting them by frequency in advance.

The sorting method that I used for this was:
```
private sortNotesByFrequency(notes: Array<Note>): Array<Note> {
  return notes.sort((noteA: Note, noteB: Note) => {
    return this.getNoteFrequency(noteA) - this.getNoteFrequency(noteB);
  });
}
```
Doing this I could see the keys are sorted like this: [ "C/5",  "E/5",  "A/5" ]

But the displayed notes on the stave look wrong, as if it's a reversed chord, with some space between them. See here
![screen](https://user-images.githubusercontent.com/240058/106028098-d13d1180-60cb-11eb-8526-e0877aad93c2.jpg)
 for the example.

But I would like to display the notes for the following chord: [ "A/5",  "C/5",  "E/5" ] 
These notes should not have a space between them.

So I tried to feed the following notes: [ "A/5",  "C/5",  "E/5" ] using the method:
```
private renderNotesSortedByIndex(notes: Array<Note>): Array<string> {
  const vexflowNotes: Array<string> = new Array<string>();
  this.notationService.sortNotesByIndex(notes)
    .forEach((note: Note) => {
      vexflowNotes.push(this.renderNote(note));
    });
  return vexflowNotes;
}
```
But then I get again the same dreaded warning message.

So how to render the [ "A/5",  "C/5",  "E/5" ] chord ?

**Comment by sschmidTU** [comment]
@stephaneeybert 
That chord that Vexflow displays **is** exactly C5, E5, A5.
It's just a different order of A5, C5, E5 you seem to desire, which is actually out of order because it goes highest, lowest, middle.
Maybe you wanted A5, C6, E6?

**Comment by stephaneeybert** [comment]
Thanks @sschmidTU I just talked to my end user, showing him your image and the explanation for it.

Here are the chords I want to display:
    // 'G', 'A', 'B', 'C', 'D', 'E', 'F'
    // 'E', 'F', 'G', 'A', 'B', 'C', 'D'
    // 'C', 'D', 'E', 'F', 'G', 'A', 'B'
They are to be read from bottom to top as tuples.
For example, one is A C E

Now, what if I wanted to display three consecutive (no space in between) notes for the A C E chord on the octave 5 ? Is this possible ?

**Comment by gristow** [comment]
@stephaneeybert, it sounds like your confusion might be over how the notes are named using letters and octave numbers. Octave numbers start from C. Middle C is C4. So, the C Major scale starting on middle C is:

C/4 D/4 E/4 F/4 G/4 A/4 B/4 C/5

You can render any combination of notes as long as you label them as such.

See [here](http://newt.phys.unsw.edu.au/jw/notes.html) for information on note naming.

**Comment by sschmidTU** [comment]
@stephaneeybert yes, the chord A C E (from bottom to top) is technically not on the same octave, since new octave numbers start at C. So, you have to increase the octave every time you go over the C from bottom to top.

**Comment by stephaneeybert** [comment]
Thanks guys ! You shed the saving light !

**Comment by stephaneeybert** [comment]
Sorting the notes by pitch was not the way to go for me, since my notes are already sorted as such with them being added from lowest to highest for a chord. Each chord having 3 notes, the lowest note is added first, followed by two higher notes.
So I check if the octave of a higher note needs to be incremented.

```
  private createNotesAndPlacedChord(octave: number, chordDuration: number, velocity: number, tonality: Tonality, placedChordIndex: number, chromas: Array<string>): PlacedChord {
    let noteIndex: number = 0;
    let previousChroma: string = '';
    const nextUpperOctave: number = octave + 1;
    const notes: Array<Note> = new Array();
    for (let i = 0; i < chromas.length; i++) {
      const chroma: string = chromas[i];
      if (noteIndex > 0 && this.chordChromaBelongsToNextUpperOctave(previousChroma, chroma, tonality)) {
        octave = nextUpperOctave;
      }
      console.log(octave);
      console.log(' ');
      const note: Note = this.notationService.createNote(noteIndex, chroma, octave);
      noteIndex++;
      previousChroma = chroma;
      notes.push(note);
    }
    return this.notationService.createPlacedChord(placedChordIndex, chordDuration, TempoUnit.NOTE, velocity, tonality, notes);
  }

  // If a current chord chroma is lower than the previous chord chroma
  // then the current chroma belong to the next upper octave
  private chordChromaBelongsToNextUpperOctave(previousChroma: string, currentChroma: string, tonality: Tonality): boolean {
    const tonalityChromas: Array<string> = this.getTonalityChromas(tonality.range, tonality.firstChroma);
    console.log(tonalityChromas);
    console.log(previousChroma + ' ' + currentChroma);
    console.log(tonalityChromas.indexOf(currentChroma) < tonalityChromas.indexOf(previousChroma));
    return tonalityChromas.indexOf(currentChroma) < tonalityChromas.indexOf(previousChroma);
  }

```
It seems to work fine for the tonality: 'C', 'D', 'E', 'F', 'G', 'A', 'B'

But I'm doing modulation, and when on the tonality: "G", "A", "B", "C", "D", "E", "F#" the chord 'G', 'B', 'D' on octave 5 does not display as expected as there is a gap between two of these notes. Using console logging I ensured the octave of each and every of these 3 notes remains 5.

![image](https://user-images.githubusercontent.com/240058/107283640-f2ebb080-6a5c-11eb-9066-f2239a247d20.png)

Is it that I need to first tell Vexflow which tonality the chord is on ?

**Comment by gristow** [comment]
The key doesn't matter. This MIDI naming system comes from the keyboard. Each octave spans C-B, even if we were in F# major! And whenever we reach the next C, we use the number for the following octave. So, if you right a G, A or B triad, you'll have some notes that are in the next octave, compared to the root of the chord. For your example, a G Major triad on G4, it would be G4-B4-D5.

![MIDI Number Chart](https://www.mobilefish.com/images/services/midi_maker_grand_staff_octave.gif)

(Je vais aussi traduire en français, car votre nom est très français est c'est possible que je peux plus facilement expliquer: la tonalité n'a aucune importance. Ce système MIDI de nommer les notes vient du clavier. Chaque octave contient Do à Si, même si on est en Fa# majeure!, et chaque fois qu'on arrive à un nouveau Do, on commence avec le numero de l'octave suivante. Donc, si on écrit un accord de trois sons sur Sol, sur La ou sur Si, on aura forcement une ou deux notes qui sont dans l'octave suivante celle de la fondamentale. En cas de l'accord de Sol, sur G4, c'est G4-B4-D5.)

**Comment by stephaneeybert** [comment]
All right ! Merci ! Indeed I'm a frenchie from Provence. Your french is very good !

So I understand the ruler is always the C major tonality with the following notes 'C', 'D', 'E', 'F', 'G', 'A', 'B'.

Then the chord with the chromas F, A, C starting on octave 4 is understood as chromas/octave: F/4, A/4, C/5 then.

But what about a chord with the first two chromas on octave 4 that ends with a B# instead of a B ? Say like ..., ..., B# ? Is the B# on octave 4 or is it on octave 5?

**Comment by gristow** [comment]
In all cases, we ignore the accidental. So, B#4 is the same note on the piano as C5. And a G#4 major triad is spelled G#4-B#4-D#5.

**Comment by stephaneeybert** [comment]
So, ignoring the accidentals, only the first letter of the chroma, the alphabetical one, is considered.

Here is my updated function:

```
private chordChromaBelongsToNextUpperOctave(previousChroma: string, currentChroma: string): boolean {
  const tonalityChromas: Array<string> = this.getTonalityChromas(DEFAULT_TONALITY_C_MAJOR.range, DEFAULT_TONALITY_C_MAJOR.firstChroma);
  const previousAlphaChroma: string = previousChroma.substr(0, 1);
  const currentAlphaChroma: string = currentChroma.substr(0, 1);
  return tonalityChromas.indexOf(currentAlphaChroma) < tonalityChromas.indexOf(previousAlphaChroma);
}

```
