### ISSUE TITLE
Beams breaking when moving from A to B inside of the Treble Clef

### ISSUE THREAD

**Issue by Latke89** [0xfe/vexflow#475]
Hi, I'm having an issue with beams breaking whenever I'm going moving between A and B inside the treble clef, and while I do know about the beam positioning, I'm not in a great position to use it. I'm generating a random scale on my backend, giving it to teoria to build the scale, then handing it to vexflow for templating purposes, so I won't know until runtime if I'm going to need to position the beams up or down.

Here is the bit of code where I'm templating:

```javascript
                system.addStave({voices:[
                    score.voice(
                        score.beam(
                            score.notes(first))
                                .concat(score.beam(score.notes(second)))
                                .concat(score.beam(score.notes(third)))
                                .concat(score.beam(score.notes(fourth)))
                        )
                    ]
                }).addClef('treble').addTimeSignature('4/4');
```

And here is what I'm getting when I break that specific octave:

![scalesnippet](https://cloud.githubusercontent.com/assets/17570063/20528689/34ff6de8-b09b-11e6-83a9-31456c6ee72e.png)

Any help would be greatly appreciated, thanks!

**Comment by Silverwolf90** [comment]
Hi @Latke89,

Either you need to set the stem direction explicitly in `score.notes`:

```javascript
score.notes('b4[stem="up"]');
```

or you can use the `autoStem` option on `score.beam`:

```javascript
score.beam(someNotes, { autoStem: true });
```
