### ISSUE TITLE
[EasyScore] More than one bar in a stave not working

### ISSUE THREAD

**Issue by graciano** [0xfe/vexflow#477]
I'm trying to create a score from a string, for example: `notesString = "F#6/4, G#5/4, E6/4, G#5/4 | D6/4, G#5/4, C#6/4, G#5/4"` and the second bar is not being rendered. I can't see any error in the string there. Is this because I understood something wrong in the documentation or is really a bug?
I'm using a code like this:
```javascript
var score = vf.EasyScore()
var system = vf.System()
system.addStave({
      voices: [
        score.voice(score.notes(notesString))
      ]
    }).addClef('treble').addTimeSignature('4/4')
```
And the result is:
![image](https://cloud.githubusercontent.com/assets/3246681/20871084/935b5a3c-ba78-11e6-8d70-4605c09e4a8e.png)

**Comment by Silverwolf90** [comment]
You can't create multiple bars with the EasyScore syntax. `|` is not valid syntax.

Are you not getting some kind of error?

**Comment by graciano** [comment]
I'm trying to find where I read something that might have hinted to me that `|` would be a bar divider, but I couldn't find it.

Vexflow gave me no error, it seems that it just ignores everything after the non-valid character. If I remove the `|` character, it gives the same result. It only gives me an error if I don't provide enough notes in the string:
`[RuntimeError] IncompleteVoice:Voice does not have enough notes.`
So, to get an music sheet with two bars per line I should render another stave side by side? What do you think would be my best option?

I think I can live with one bar per line in the earlier stages of development of my project. But some day I might have to change that.

**Comment by 0xfe** [comment]
Yeah, `|` is not EasyScore syntax -- it's VexTab, which is where you probably remember it from.

Take a look at `tests/bach_tests.js` for an example of how to render multiple staves.

**Comment by graciano** [comment]
That's right. Thank you :)

**Comment by adminkov7** [comment]
Hello. How to use Vex.Flow.MultiMeasureRest() in code:
var score = vf.EasyScore();
function makeSystem(width) {
    var system = vf.System({ x: x, y: y, width: width, spaceBetweenStaves: 10 });
    x += width;
    return system;
  }
let system = makeSystem(notes.length * 60);
system.addStave({
  voices: [score.voice(score.notes(arrVexFlow[j][1])).setStrict(false)]
});

**Comment by adminkov7** [comment]
Hello. How to use  Vex.Flow.**MultiMeasureRest**() in code:
var score = vf.EasyScore();
function makeSystem(width) {
var system = vf.System({ x: x, y: y, width: width, spaceBetweenStaves: 10 });
x += width;
return system;
}
for(let j=0; j < arrVexFlow.length; j++){
  let system = makeSystem(notes.length * 60);
  system.addStave({
  voices: [score.voice(score.notes(notes_string).setStrict(false)] // ???
  });
}
**Thanks for the answer**
