### ISSUE TITLE
Manually set the x position of stavenotes

### ISSUE THREAD

**Issue by lpeppe** [0xfe/vexflow#478]
Hi,
as the title says I'm searching for a way to manually set the x position of a note on the stave. I found a method called "setXShift" in the tickable prototype but I can't figure out how to make it work properly. Any ideas?

**Comment by 0xfe** [comment]
If the note already has a `TickContext`, then call `note.getTickContext().setX( ... )`.

Else, you'll need to create a `TickContext` and associate it with the note, then do the above.

**Comment by 0xfe** [comment]
Example from `src/formatter.js`:

```javascript
  static SimpleFormat(notes, x = 0, { paddingBetween = 10 } = {}) {
    notes.reduce((x, note) => {
      note.addToModifierContext(new ModifierContext());
      const tick = new TickContext().addTickable(note).preFormat();
      const extra = tick.getExtraPx();
      tick.setX(x + extra.left);

      return x + tick.getWidth() + extra.right + paddingBetween;
    }, x);
  }
```

**Comment by lpeppe** [comment]
thanks a lot man!
