### ISSUE TITLE
If I put Db on a D major key signature the note is placed at D

### ISSUE THREAD

**Issue by cedvdb** [0xfe/vexflow#479]
When I'm in a time signature and try to create a note that is a flat, for instance Db on a D major scale, the note figures at D instead of C. I assume this is a bug. 

So at the moment what I have to do is check if the note, for example "Db" has a "b" in it, if so decrease it by a semitone so I can give C to Vex Flow.

So yeah I've to give the **wrong** note to VF to have the correct one drawn.

**Comment by 0xfe** [comment]
I'm sorry, can you please provide a code snippet to clarify?

- what does it mean to be in a time signature? Do you mean key signature?
- why would Db render as a C? Did you want a C# instead?

Can you also attach a screenshot of what you're seeing?

**Comment by cedvdb** [comment]
Sorry, I meant key signature indeed. Does that make sens now ? 

Here is a picture  http://imgur.com/a/jkKrk

The first note of the right hand is actually Gb.

I add the key signature to the staff like this:

```
        topStaff.addModifier(new Vex.Flow.KeySignature(this.keySignature));
```

That indeed draws the correct key signature. However, from what I understand the code is often decoupled with logic on one side and rendering on the other. So I'm assuming this is for rendering and not for the logic. If there is another method for the logic of translating the notes to their real position I don't know it and it's hard to find in tests since all I've seen is what I wrote or addKeySignature(), which doesn't work either.

**Comment by 0xfe** [comment]
Yes, this library is purely rendering and only includes the minimum amount of semantic logic so as to cover the majority of music-notation scenarios. Music notation is hugely complex, and filled with exceptions, so tying them into the renderer severely limits flexibility.

There are higher-level libraries (such as VexTab) that encode a lot of the western notation rules, so if you simply want to display a few measures of music -- that would be much easier to use.

That said, for what you want, the logic is encoded in `src/keymanager.js` in the `VF.KeyManager` class. It can cover simple diatonic scales, and help select key positions for you, and keep track of accidentals in a voice when they're overridden. (VexTab uses `KeyManager` to manage notes in major or minor keys.)

**Comment by Silverwolf90** [comment]
Closing. If you have any further questions about this feel free to reopen.
