### ISSUE TITLE
Do you feel it would be nice to have real-time discusstions regarding github issues?

### ISSUE THREAD

**Issue by shytikov** [0xfe/vexflow#481]
I'm leading to Gitter or Slack channel for `WexFlow`.  

I believe it would be nice to have real-time Q&A between `WexFlow` users. 

What do you think?

**Comment by Silverwolf90** [comment]
I like this idea. I'd be in favor Gitter.

**Comment by rvilarl** [comment]
@0xfe @mscuthbert are you planning to set this up?

**Comment by rvilarl** [comment]
@0xfe if not we should close it

**Comment by rvilarl** [comment]
And there is a google group by the way:

https://groups.google.com/g/vexflow
