### ISSUE TITLE
EasyScore: rest in middle of measure not working (possible bug)

### ISSUE THREAD

**Issue by graciano** [0xfe/vexflow#482]
So, I'm messing with some strings with easyScore and when a rest is in the middle of a measure, it returns an error.

This string: `A4/8, B4/8, A4/8, B4/8, B4/8, A4/r8`(with a rest at the end) generates this ([fiddle here](https://jsfiddle.net/0b6hcc69/45/)) :

![image](http://i.imgur.com/UeeZImA.png)

--

But this string `A4/8, B4/8, A4/8, B4/r8, B4/8, A4/r8` (with a rest in the middle) generates an error ( [fiddle here](https://jsfiddle.net/0b6hcc69/44/)) :
```javascript
formatter.js:84 Uncaught RuntimeErrorcode: "IncompleteVoice"
message: "Voice does not have enough notes."

__proto__: Object
(anonymous) @ formatter.js:84
createContexts @ formatter.js:76
createModifierContexts @ formatter.js:404
joinVoices @ formatter.js:659
(anonymous) @ system.js:92
format @ system.js:89
(anonymous) @ factory.js:329
draw @ factory.js:329
(anonymous) @ embedded:18
transform.run @ VM161 babel.js:3192
exec @ VM161 babel.js:3247
runScripts @ VM161 babel.js:3284
```

**AND** this string `A4/8, B4/8, A4/8, B4/8, A4/8, B4/r8, A4/8, A4/8`, that should return an error because it's too many notes in the same voice, renders just fine with the rest at the end, and ignoring notes after that. Seems to me that this is the reason I mentioned in #477 when it ignored a *too many notes* error.  [fiddle here](https://jsfiddle.net/0b6hcc69/46/)

I tried looking into the files [easyscore.js](https://github.com/0xfe/vexflow/blob/d27e7b027b15c1bf583da9d583ccaede548c6b1a/src/easyscore.js) and [note.js](https://github.com/0xfe/vexflow/blob/5654fa3c492bde48a8189f9d13932b81818801e3/src/note.js) and couldn't find anything wrong.

**Comment by Silverwolf90** [comment]
Thank you for the thorough report (and especially the fiddles)!

This does appear to be a bug. I haven't looked at the code yet, but discovered that if you let the duration carry over instead of setting it every time)([fiddle](https://jsfiddle.net/0b6hcc69/47/)) that it behaves as expected.

**Comment by Silverwolf90** [comment]
Ah yes of course, this is in fact not a bug, but invalid syntax. [Here's a fiddle with the corrected syntax.](https://jsfiddle.net/0b6hcc69/48/)

You correct syntax for a rest is `B4/4/r`

**Comment by Silverwolf90** [comment]
Also worth mentioning that you can find the EasyScore tests here:

https://github.com/0xfe/vexflow/blob/master/tests/easyscore_tests.js

**Comment by graciano** [comment]
Invalid syntax again. Sorry for my lack of attention and thanks.
This project is really good. I think I'll write about it when I learn more :)
