### ISSUE TITLE
Question: is vexflow suitable for real-time music notation?

### ISSUE THREAD

**Issue by shimpe** [0xfe/vexflow#484]
For an experiment I'm doing I don't want to generate a complete score first and display that. Instead I'd like to update/display the score while it is being generated (a kind of real-time music score display server). Does vexflow provide a suitable basis to dynamically extend the displayed score?

**Comment by Silverwolf90** [comment]
Not really, VexFlow objects are not designed to be mutated after being formatted. I would suggest that you design your own data model which is then transformed into VexFlow objects.

**Comment by Silverwolf90** [comment]
I updated my original answer to be a bit more clear what I meant.

**Comment by shimpe** [comment]
Thanks, I had correctly understood your suggestion. My concern is that as the score grows, it needs to rerender everything from scratch all the time and so probably things will start to slow down. (Unless there's a way to render line by line... I need to think a bit about it)

**Comment by 0xfe** [comment]
Yes, ideally, you only want to render just the parts that change (and are visible on the display.) Stave-by-stave is usually a good approach (with the caveat that there can be edits which might affect all following staves.)

**Comment by lpeppe** [comment]
I had your exact same doubt and I also had to rerender everything from scratch every time something changes. So far I have no slow down at all, even for quite big staves!
