### ISSUE TITLE
StaveModifiers placed at the end of the Stave collide with StaveTies without end notes.

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#489]
See the collision at the end of the stave in this example:

![image](https://cloud.githubusercontent.com/assets/1631625/21296197/2c0abc56-c55e-11e6-80f7-bd9eba3aa891.png)

StaveModifiers placed at the beginning do *not* exhibit this issue (although the spacing leaves something to be desired):

![image](https://cloud.githubusercontent.com/assets/1631625/21296204/4f1d9b96-c55e-11e6-935a-00750fd3aaa4.png)

**Comment by 0xfe** [comment]
This is because `Stave.setTieEndX()` does not accommodate for modifiers.

From `src/stave.js`:

```javascript
  getTieStartX() { return this.start_x; }
  getTieEndX() { return this.x + this.width; }
```

So while `getTieStartX()` is based on `Stave.start_x` which changes as modifiers are added, `getTieEndX()` is just the last horizontal pixel on the stave.

**Comment by Silverwolf90** [comment]
Cool, simple fix then.
