### ISSUE TITLE
Experimental idea for EasyScore

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#493]
Currently EasyScore has one potential point of extension called `commitHooks` (introduced in https://github.com/0xfe/vexflow/pull/426).

This is:
* perfect for stuff like attributes
  * eg `c#4/4[id="note1",class="red"]`
* constraining but acceptable for simple modifier cases
  * eg: `c#4/4[articulations="staccato.above,marcato.below"]`
* not useful for anything complex
* executed inline with parsing, so we can't expose anything ahead of the current position

With tagged template literals we could mix JavaScript expressions within the EasyScore language. 

Total Strawman:

```javascript
easyScore`
  (a4 e5 f5)/16
    ${modify({
      0: vf.Fingering({ number: '1', position: 'left' }),
      2: vf.Fingering({ number: '4', position: 'above' }),
    })}
  e5, e5 ${link(vf.Tie)} e5, e5/8, e5, e5/2
`;
```

In this example `modify` and `link` are higher order functions that return a function which will be passed something like: `(prevNote, nextNote, allNotes)`. In order to expose all parsed notes, these transformations would be run after all entire line has been parsed.

Thoughts?

**Comment by 0xfe** [comment]
Interesting. I like the idea of `modify` and `link`, but it's hard to get past the potential mess embedded javascript can create if unchecked. Wouldn't the `id` property allow you to do much of this out of band just as easily (albeit slightly more verbose)?

**Comment by Silverwolf90** [comment]
Yeah this definitely has potential to be used in an abusive manner. "With great power comes great responsibility" or something ¯\\\_(ツ)\_/¯

**Comment by rvilarl** [comment]
@0xfe I think you can close this one
