### ISSUE TITLE
No file extensions on import statements

### ISSUE THREAD

**Issue by aaronmars** [0xfe/vexflow#509]
When modules are a proper, browser-supported thing, a statement like:
`import { Stave } from './stave';`
...will likely 404 since ./stave isn't a file.

I think it would be best (read: future-proof) if these imports pointed to actual files?

**Comment by Silverwolf90** [comment]
I'm not sure it would make sense to future-proof [until TC39 and Node.js have an approved way forward around a module loader API](https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e#.x60etmce6).

**Comment by Silverwolf90** [comment]
In `eslint-plugin-import` it looks like there's also a rule to enforce this too: [`import/extensions`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/extensions.md)

**Comment by rvilarl** [comment]
@0xfe I think you can close this one.
