### ISSUE TITLE
API documentation doesn't work

### ISSUE THREAD

**Issue by p-himik** [0xfe/vexflow#510]
The link on the wiki just leads to a file listing that doesn't contain any trace of API documentation.

**Comment by rvilarl** [comment]
@0xfe I think you can close this one.

**Comment by p-himik** [comment]
@rvilarl Why? It's still the case to this day.
![image](https://user-images.githubusercontent.com/4410314/125350491-77719080-e367-11eb-9920-186b3d8d57ed.png)

There _is_ a table of contents. But it's partially obscured when expanded, is hidden by default, is reactive only to mouse movement (tabbing will not show it), and is lacking any sort of description of the sections. If I hadn't accidentally moved my mouse pointer in just the right spot, I would've never even seen it.

**Comment by rvilarl** [comment]
Because docco was discarded the api is now being documented with typedoc. You can clone the repository and use `grunt typedoc` after `npm install` to see how it looks.
@0xfe perhaps you could release a `4.0.0a` version :)

**Comment by p-himik** [comment]
I see. But an issue should be closed only after it's been dealt with, one way or another.
In this case, the wiki still has that link pointing to the old doc, so it's still an issue - regardless of the fact that one can build up-to-date documentation locally.

**Comment by rvilarl** [comment]
@ronyeh this belongs to 4.0.0, please label.
