### ISSUE TITLE
VexFlow needs an API reference - JSDoc comments

### ISSUE THREAD

**Issue by Silverwolf90** [0xfe/vexflow#513]
The current documentation is really lacking. The linear style really doesn't work for VexFlow. Without a proper API reference, a project of VexFlow's complexity is very difficult to use in an in-depth manner. While [JSDoc comments](http://usejsdoc.org/about-getting-started.html) are cumbersome, I think the benefits outweigh the costs. 

* The generated docs will be of much higher quality (ie: hyperlinked symbols)
* Tooling can take advantage of the data
* We can more explicitly declare what is private/public, and generate public-only docs
* ESLint has a [`valid-jsdoc`](http://eslint.org/docs/rules/valid-jsdoc) rule to enforce a basic level of quality.

[documentation.js looks interesting](https://github.com/documentationjs/documentation)

**Comment by PCrompton** [comment]
I concur. VexFlow seems to be a very powerful tool but I've been somewhat overwhelmed trying to figure out how to get it to do what I want it to do. For instance, I had some difficulty a while back with clef configuration. I would change the clef symbol but the notes were still on the lines and spaces of the treble clef. After some digging I figured out I had to set the clef in multiple places to get it to render properly.

**Comment by gristow** [comment]
Absolutely, JSDoc comments would be great for readability & tooling support. Plus, this would enforce a shared style of documentation which we were never really able to accomplish with Docco's markdown-like comment filtering.

In addition to ESLint's `valid-jsdoc` we might consider turning on [`require-jsdoc`](http://eslint.org/docs/rules/require-jsdoc), at least at a warning level.

**Comment by rvilarl** [comment]
Now that we have typescript, we are using typedoc, which is simpler than jsdoc, WIP.
@0xfe I think you can close this one
