### ISSUE TITLE
Problem saving vexflow data

### ISSUE THREAD

**Issue by lpeppe** [0xfe/vexflow#524]
Hi guys, I'm working on an editor powered by vexflow. I need to save the data of the editor (preferably in JSON) but I'm encountering many problems. Is there a correct way to save the notes (and ties) and restore them properly? 

This is the repository of the editor, if you want to check it out:
https://github.com/lpeppe/vexflow_editor

EDIT:
My problem is that whenever I try to convert vexflow data to JSON (a StaveNote for example) I get a circular reference error

**Comment by Silverwolf90** [comment]
Hi @lpeppe, currently there's no built-in way to serialize/deserialize VexFlow objects. You'll have to build that functionality yourself.

**Comment by 0xfe** [comment]
Also, ideally, you'd serialize/deserialize your musical model, not the VexFlow objects themselves. The internals of VexFlow can change anytime.

**Comment by lpeppe** [comment]
yeah, I think you are right. I managed anyway to create a data structure containing only primitive types, and then recreate vexflow objects with it.
