### ISSUE TITLE
Center note on staff

### ISSUE THREAD

**Issue by PCrompton** [0xfe/vexflow#526]
I'm writing a flashcard app and was wondering if someone could point me to any documentation that would explain how to center the note horizontally on the staff? Here's a screen shot of how it's rendering in my app right now: 
![simulator screen shot jan 12 2017 11 33 12 am](https://cloud.githubusercontent.com/assets/2374809/21898749/da040eb4-d8bb-11e6-826d-b552ca843c83.png)

I'd ideally like the whole note to be centered horizontally.

Thanks

-Paul

**Comment by Silverwolf90** [comment]
Pass `align_center: true` on `StaveNote` construction. There's an example in this test: https://github.com/0xfe/vexflow/blob/master/tests/stavenote_tests.js#L761

**Comment by 0xfe** [comment]
I think this is one of those cases where the attribute belongs in the formatter, not the `StaveNote`. It would be trivial to support centered justification in `Formatter`.

**Comment by PCrompton** [comment]
It's not working quite as smoothly as I'd hoped. I'm having to adjust other parameters to get it in the center.

**Comment by Silverwolf90** [comment]
@0xfe The attribute is necessary on the note because voices with measure rests (which are centered) can be formatted amongst voices with notes. But the logic to calculate the center it does indeed happen in the formatter.

@PCrompton Do you have a screenshot of the default position when you pass it that property?

**Comment by 0xfe** [comment]
@Silverwolf90 In that case, wouldn't the voice be a more appropriate place for the attribute?

**Comment by Silverwolf90** [comment]
What would be the expected behavior if there are multiple notes in the voice?

**Comment by PCrompton** [comment]
It works when I rotate to landscape but not in portrait. 
![simulator screen shot jan 13 2017 10 43 50 am](https://cloud.githubusercontent.com/assets/2374809/21935951/714da336-d97d-11e6-8689-20208324bd0d.png)
![simulator screen shot jan 13 2017 10 43 47 am](https://cloud.githubusercontent.com/assets/2374809/21935952/7157b0a6-d97d-11e6-9bbc-f2fe2940974d.png)

Here's the function I'm calling to draw it:

```
function drawStaffWithPitch(pitch, clef, width, height) {
    VF = Vex.Flow;
    var div = document.getElementById("note")
    var renderer = new VF.Renderer(document.getElementById("note"), VF.Renderer.Backends.SVG);
    renderer.resize(width, height);
    document.getElementById("note").setAttribute("width", width)
    document.getElementById("note").setAttribute("height", height)
    var context = renderer.getContext();
    context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");
    
    var stave = new VF.Stave(width*0.1, height/5, width*0.75);
    stave.addClef(clef);
    stave.setContext(context).draw();
    
    if (pitch != null) {
        var letter = pitch.charAt(0);
        var octave = pitch.charAt(pitch.length-1);
        var accidental;
        if (pitch.length == 3) {
            accidental = pitch.charAt(1);
        } else {
            accidental = null;
        }
        var note = new VF.StaveNote({clef: clef, keys: [letter+"/"+octave], duration: "w", align_center: true});
        if (accidental != null) {
            note = note.addAccidental(0, new VF.Accidental(accidental))
        }
        var notes = [note];
        var voice = new VF.Voice({num_beats: 4,  beat_value: 4});
        voice.addTickables(notes);
        var formatter = new VF.Formatter().joinVoices([voice]).format([voice], 400);
        
        voice.draw(context, stave);
    }
}
```

**Comment by Silverwolf90** [comment]
@PCrompton You are not changing the width based on orientation, but always formatting it to 400px:

```
new VF.Formatter().joinVoices([voice]).format([voice], 400);
```

**Comment by 0xfe** [comment]
@Silverwolf90 I think that's the point. Centering only makes sense on an entire voice, because you would center-justify the entire thing (like centering a line in a word-processor.) If there's multiple notes, then centering a single one doesn't make sense (just as centering a single word in a wordprocessor doesn't make sense.)

**Comment by SalahAdDin** [comment]
Interesting.
