### ISSUE TITLE
Fretboard diagrams

### ISSUE THREAD

**Issue by infojunkie** [0xfe/vexflow#529]
I am submitting a feature request for fretboard diagrams :-) 

Rationale (if you need one) : As a guitarist, fretboard diagrams are useful to specify not only the chord being played, but also the *voicing* of the chord, and it allows the notator / arranger to suggest a suitable hand position. Specifying all this info with regular notation alone is not ideal, and using tab notation is too restrictive for passages that are better notated with actual music (for example, melodies in a lead sheet).

Ideally the fretboard diagram API would allow the notator to specify an unambiguous voicing and to have some control over the parameters of rendering. This means: 

- fret / string positions of the notes
- number of frets to show (default is usually 4)
- label in front of specific fret(s) (usually numbers in Arabic or Latin numerals)
- number of strings to show
- tuning of each string
- diagram scaling factor
- diagram location offset

**Comment by 0xfe** [comment]
Have you seen https://github.com/0xfe/fretboard?

**Comment by infojunkie** [comment]
Nice! Would be great to explore linking to VexFlow.

**Comment by infojunkie** [comment]
I've also been exploring "in-place" fretboard diagrams, such as this: https://musescore.com/infojunkie/retab - as a way to optimize space utilization on the sheet.

**Comment by SalahAdDin** [comment]
@0xfe man, you have all tools :D 👍
