### ISSUE TITLE
Playback drums - Any ideas? (React-Native)

### ISSUE THREAD

**Issue by davidfloegel** [0xfe/vexflow#532]
Hello there!

I'm so happy vexflow now works with react-native! Amazing work!

I'm about to release an app using vexflow to render drum notations and I was wondering if anyone has an idea how I could implement a playback feature?

Thanks

David

**Comment by 0xfe** [comment]
VexFlow does not do playback -- it's something you'll have to implement yourself. (It's straightforward to integrate a JS audio library such as MIDI.js to Vexflow.)

**Comment by francowanseele** [comment]
Hey! I am spending so much days trying to make vexflow works in my react native application. 

Do you have an example of how to use it? Just show a basic music sheet.

Any example or help would be amazing! Thanks :)
