### ISSUE TITLE
SVG display with EasyScore

### ISSUE THREAD

**Issue by HollyJHuber** [0xfe/vexflow#533]
The Wiki on [Using HTML5 Canvas or SVG with VexFlow](https://github.com/0xfe/vexflow/wiki/Using-HTML5-Canvas-or-SVG-with-VexFlow) is helpful but I'm wondering if anyone could provide some more specifics or examples. The article says you can "tweak your SVG display using the properties" but provides no details as how to implement those tweaks.

I have tried to implement this SVG renderer in my EasyScore but any attempt to target an SVG tag by id results in that tag being replaced. Is the EasyScore VF.Factory compatible with this renderer code?

`var renderer = new Vex.Flow.Renderer(document.getElementById("mySVGCanvas"),
                                     Vex.Flow.Renderer.Backends.SVG);`

Specifically how does one insert a viewbox into the SVG tag generated by EasyScore?

Any assistance is greatly appreciated. Thanks!

**Comment by gristow** [comment]
Easiest way to access the SVG viewbox is programmatically:

`renderer.ctx.setViewBox(x, y, width, height);`

But you can also access the SVG element itself directly if you want to do more direct manipulations:

`const svgElement = renderer.ctx.svg;'

**Comment by HollyJHuber** [comment]
Thank you, but this code does not work with EasyScore. As I mentioned, the renderer generates an svg tag that is ignored by EasyScore, perhaps due to an incompatibility with VF.Factory? 

I was able to insert a viewbox in the SVG tag generated by EasyScore using javascript before the vf.draw(): 

` var svgEls = document.getElementsByTagName("svg");
    if (svgEls[0] !== undefined){
        svgViewbox = "-40 0 " + (vfwidth + 40) + " " + vfheight;
        svgEls[0].removeAttribute("height");
        svgEls[0].removeAttribute("width");
        svgEls[0].setAttribute("viewBox", svgViewbox);        
    }`

**Comment by gristow** [comment]
Sorry, @HollyJHuber, I read too quickly and missed the EasyScore part. To get the SVG programmatically with EasyScore you'll have to reach into your `Factory` object to get its context:
```
const vf = new Vex.Flow.Factory({renderer: {selector: 'boo'}});
const context = vf.getContext();
context.setViewBox(x, y, width, height);
// or context.setViewBox("-40 0 90 180"); as "x y w h"

const svg = context.svg; // the SVG DOM element
```

Your code will do the same thing -- but may break if there's ever another SVG above the one you want on your page.

**Comment by HollyJHuber** [comment]
Thank you @gristow, very helpful! And you're right about the flaw in my code.

**Comment by SalahAdDin** [comment]
Good work 👍
