### ISSUE TITLE
No way to disable strict mode in EasyScore

### ISSUE THREAD

**Issue by darajava** [0xfe/vexflow#534]
Or at least I can't find a documented way to disable it. Is there such an option?

**Comment by 0xfe** [comment]
Not sure what you mean by strict mode.

**Comment by darajava** [comment]
Excuse me, here is what I'm referring to: https://groups.google.com/d/msg/vexflow/2kLDAZWDk2Q/MC4tsJc-30wJ

I want to generate an arbitrary amount of notes which is agnostic of any time signature, but it's throwing "too many/few ticks" unless there are 4 beats in the bar, even though I'm not setting a time signature. Maybe there is another way to do this, but I have not found any in any tutorials so far.

**Comment by 0xfe** [comment]
Oh, you mean strict voices. It doesn't do that sorry -- the typical strategy is to fill the rest of the voice with rests or ghost notes.

**Comment by darajava** [comment]
Thank you, I've started a thread on the Google discussion as this is more of a question than an issue:

https://groups.google.com/forum/#!topic/vexflow/2eIdj18k4RE

Thanks for your help - Vexflow is really amazing!! :smile:
