### ISSUE TITLE
Vexflow/EasyScore fails for basic beam rendering on eighth notes

### ISSUE THREAD

**Issue by darajava** [0xfe/vexflow#535]
```
    var vf = new Vex.Flow.Factory({
      renderer: {selector: 'notation', width: 520, height: 200}
    });
  
    var score = vf.EasyScore();
    var system = vf.System();

    var noteString = "G4,A4,B4,C5"

    system.addStave({
      voices: [score.voice(score.beam(score.notes(noteString)).concat(score.beam(score.notes(noteString))))]
    }).addClef('treble').addKeySignature(this.props.startingKey.ucFirst());

    vf.draw();
```

Renders as:

![image](https://cloud.githubusercontent.com/assets/5908229/23036600/59966944-f47b-11e6-812d-59268e22568a.png)

I've seen the tests for Vexflow and they seem extremely robust so I feel like I'm missing something here. Is there a problem with my code or is this a bug with any workaround?

**Comment by 0xfe** [comment]
You need to set consistent stem directions when beaming with EasyScore. The tutorial has examples for this.

**Comment by darajava** [comment]
Thanks! It does render as expected when I include the stem directions, but I thought that was optional and that Vexflow would choose the nicer looking stem orientation if omitted as seen here: https://jsfiddle.net/ywa7xt7k/1/

**Comment by gristow** [comment]
Late to the game on this, but there is a simpler way. In your `.beam()` calls, pass an object with `options.autoStem = true`. So:

``` JavaScript
const beamParams = { options: { autoStem: true } };
system.addStave({
  voices: [
    score.voice(score.beam(score.notes(noteString), beamParams)
    .concat( score.beam(score.notes(noteString), beamParams) ))
  ]
}).addClef('treble').addKeySignature(this.props.startingKey.ucFirst());
```

**Comment by zfan40** [comment]
@gristow I believe you had a little error in your demo script.
the beamParams should be `{ autoStem: true }` instead of `{ options: { autoStem: true } }`
Not 100% sure about that
