### ISSUE TITLE
how to use this make a music notation Kara OK

### ISSUE THREAD

**Issue by chubbyerror** [0xfe/vexflow#537]
i try set color, but it well make whole music notation change color.
i try use tow VexTab, but it is hard to make VexTab one on top of another.

**Comment by chubbyerror** [comment]
> What?

as lyric mod or LRC or Kara OK , at right time make "the playing notes" change clolr.

have u every c that ??

**Comment by gristow** [comment]
You can color notes (see "Can I color notes" in the [FAQ](https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ)). Redraw with the right notes colored whenever you want to color a note.

But there's no built in support for the timing of that for Karaoke. All of that would need to be programmed from scratch.
