### ISSUE TITLE
Removing the link under the canvas

### ISSUE THREAD

**Issue by sodbileg** [0xfe/vexflow#540]
Is there any option to remove the link (www.vexflow.com) under the canvas while using VexTab?

**Comment by eliot-akira** [comment]
The repository for VexTab is [here](https://github.com/0xfe/vextab). You may have better luck raising an issue there. If the link is hardcoded, you may need to edit and create a custom build.

**Comment by sodbileg** [comment]
Thanks for your reply. The setting was `VexTabDiv.Artist.NOLOGO = true;`
