### ISSUE TITLE
Webpack dependency is incompatible with current config object

### ISSUE THREAD

**Issue by eliot-akira** [0xfe/vexflow#541]
In `package.json`, the Webpack dependency is specified as `"*"`. It installs version 2.x, with breaking changes in the config object - so the VexFlow build is interrupted with an error.

**Changing the Webpack dependency to `"1.*"`** got the build to complete.

Perhaps this can be included in PR #525? Updating the config object to Webpack 2.x might take some effort.

**Comment by mmathys** [comment]
@0xfe did you abandon this project? :(
