### ISSUE TITLE
Draw notes one beat at a time?

### ISSUE THREAD

**Issue by MegaMech** [0xfe/vexflow#544]
Is it possible to draw measures one beat at a time? I tried voice.setStrict(false) either used it wrong, or it doesn't do what I think it does. Also, does the audio player only work with vextab? Can the audio player play as my program is generating the notes?

Something along the lines of:

```
`notes = [];
 for (i=1; i<notedata.length; i++) { //Loops 4 times before a new stave is created
      notes.push(new vf.StaveNote({clef: "treble", keys: [notedata[i]], duration: "q" })); //Adds a note to notes array
    
    var voice = new vf.Voice({ //Creates a voice whatever that may be... In my professional lingo, a voice means for example: Alto, Tenor, Bass, Soprano. Usually a voice is a separate melody. I don't think you would call piano style chords different voices. But music notation programming wouldn't need to distinguish the two anyway. In theory, I would only want to call this once per bar, but I have to call it in order to draw.
    num_beats: 4,  
    beat_value: 4,
    resolution: vf.RESOLUTION
  });
voice.addTickables(notes);
    var beams = vf.Beam.generateBeams(notes); //drawing
    vf.Formatter.FormatAndDraw(context, stave, notes);
    beams.forEach(function(b) {b.setContext(context).draw()});
    voice.draw(context, stave);
}`
```

Webpage running my current code:
http://alexwindsor.me/#musgen
pastebin:
https://pastebin.com/HvAWnatV

**Comment by stevenkaspar** [comment]
This isn't an issue, but you can do something like this. I am not sure on the music theory pureness of this approach though

```
// notes: StaveNotes[]

var voice = new vf.Voice({
  num_beats: notes.length,  
  beat_value: 4
});

voice.addTickables( notes );

```

**Comment by MegaMech** [comment]
Sorry... It could be an issue though.
The problem with using notes.length is that notes.length needs to be reset at the end of every for loop.
Otherwise when you have two items in the array it adds two notes, and than adds three notes, and than adds four notes. I used i+1 which cycles through 1-4. I've also already tried this, but got a better result this time. As soon as I add a timeout function I get "TypeError: a is undefined". I want to slowly create 1 note at a time. And I think it doesn't apply the notes to the bar until the bar is full, but can't be sure because it updates at probably 60fps.

Right now it's just putting all the notes on beat 1. I did have it putting the notes on each beat once, but as soon as I add timeout I get errors.

```
  for (i=0; i<notedata.length; i++) {
    setTimeout(function(){
      notes.push(new vf.StaveNote({clef: "treble", keys: [notedata[i]], duration: "q" }));
    var voice = new vf.Voice({
    num_beats: i+1,
    beat_value: 4
  });
    voice.addTickables(notes);
      var beams = vf.Beam.generateBeams(notes); //Should some of this stuff be outside of the for loop?
    vf.Formatter.FormatAndDraw(context, stave, notes);
    beams.forEach(function(b) {b.setContext(context).draw()});
    voice.draw(context, stave);
    notes = [];
   }, 300);
}
```

**Comment by MegaMech** [comment]
This seems to be the closest I can get to making it work. As soon as I add timeout the bottom 5 lines will be out of scope, and making voice global doesn't seem to work.
```
notes = [];
  for (i=0; i<notedata.length; i++) {
   
      notes.push(new vf.StaveNote({clef: "treble", keys: [notedata[i]], duration: "q" }));
    var voice = new vf.Voice({
    num_beats: i+1,
    beat_value: 4
  });
    console.log(i+1);
    voice.addTickables(notes);
    

  }
        var beams = vf.Beam.generateBeams(notes);
    vf.Formatter.FormatAndDraw(context, stave, notes);
    beams.forEach(function(b) {b.setContext(context).draw()});
    voice.draw(context, stave);
notes = [];
```

**Comment by stevenkaspar** [comment]
Yea, you will have to abstract the note a little more like you are saying

Here is a [fiddle](https://jsfiddle.net/stevenkaspar/8gLbetyy/) that I posted on another question

I just added the _add note_ button. You can see it doing its thing

**Comment by MegaMech** [comment]
So basically I would have to draw all the notes on beat one. Make the ones I don't want to be seen transparent and than manually move the notes to beat 2, 3, and 4. Which could cause formatting issues than make the notes appear after a bit of time?

Wouldn't it be possible to set voice.setStrict(false);, or something where it wouldn't care about how many beats go into the bar but would draw whatever notes it's been given?

**Comment by 0xfe** [comment]
Another option is to use `GhostNote`s to fill in the remaining beats, and incrementally replace them with real notes.

**Comment by MegaMech** [comment]
How would I replace beat 2, 3, and 4. I understand how I could have ghost notes.

**Comment by SalahAdDin** [comment]
Good work!

**Comment by gristow** [comment]
@MegaMech I'm going to close this issue out -- but the short version of this is:
- If you've used GhostNotes, you should just re-render the full measure each time you need to draw a beat
- While you /could/ draw a note at a time, the next beat might change how you want to render a beat you've already drawn. (For instance, they might be beamed together.) Because of this, I almost always chose to re-render the full score (or at least measure) when adding notes bit by bit.

For instance, [on this page I use for testing uTheory](https://tests.utheory.com/music-string.html) you can explore typing in notes in the format that's there and see how they're rendered in real time. (It's not perfect... there are still spacing issues I'm working on... but it's just an example of what re-rendering each beat looks like.)
