### ISSUE TITLE
Guitar Pro Support

### ISSUE THREAD

**Issue by mmathys** [0xfe/vexflow#545]
Let's say one has a tab in a Guitar Pro file. What's the best way to display the tab in vexflow?

Does one has to convert the Guitar Pro file into EasyScore?

**Comment by SalahAdDin** [comment]
:+1:

**Comment by gristow** [comment]
There is not currently a way to automatically display GuitarPro tab files using VexFlow -- though I believe GuitarPro can export to MusicXML and there's been some work done on importing MusicXML to VexFlow (though, I don't know if any of the repositories include support for tablature.)

In any case, check out the answers in Issue #550 for info on VexFlow/MusicXML.

(There had at one point been prior [discussion on this in the forum](https://groups.google.com/forum/#!topic/vexflow/wMS2OJvvcCQ).)
