### ISSUE TITLE
stave end clef overlaps stave end repeat barline dot

### ISSUE THREAD

**Issue by sug1no** [0xfe/vexflow#547]
https://jsfiddle.net/vpem4cjs/

![image](https://cloud.githubusercontent.com/assets/3293067/25927671/8cbe8452-3632-11e7-92e4-1576a41131ca.png)

is this a spec or bug?

**Comment by sug1no** [comment]
one more test:

https://jsfiddle.net/0ogxdft3/

![image](https://cloud.githubusercontent.com/assets/3293067/25930456/3d3c4a4a-3641-11e7-95a2-e66e6bc4551c.png)

stave end barline horizontal position (with stave end key sig) is depend on stave end barline type?

**Comment by SalahAdDin** [comment]
@0xfe please

**Comment by sug1no** [comment]
StaveModifier.x is resolved as follows:
https://github.com/0xfe/vexflow/blob/b7e6e300dfafad3c9a45c6635e18b0e345b397b9/src/stave.js#L477
```js
    for (let i = 0; i < endModifiers.length; i++) {
      modifier = endModifiers[i];
      x -= modifier.getPadding(i);
      if (i !== 0) {
        x -= modifier.getWidth();
      }

      modifier.setX(x);

      if (i === 0) {
        x -= modifier.getWidth();
      }
    }
```

In the case of <https://jsfiddle.net/0ogxdft3/> endModifiers is as follows:
![image](https://user-images.githubusercontent.com/3293067/47981287-9b886880-e10e-11e8-80c3-d4d5e8873f1c.png)

Baline.{width, padding} is defined as follows:
https://github.com/0xfe/vexflow/blob/b7e6e300dfafad3c9a45c6635e18b0e345b397b9/src/stavebarline.js#L42

```js
...
this.widths[TYPE.REPEAT_END] = 5;
...
this.paddings[TYPE.REPEAT_END] = 15;  // is this a left padding?
```
StaveModifier.getPadding ignores the this.padding by index:
https://github.com/0xfe/vexflow/blob/b7e6e300dfafad3c9a45c6635e18b0e345b397b9/src/stavemodifier.js#L53

```js
  getPadding(index) {
    return (index !== undefined && index < 2 ? 0 : this.padding);
  }
```

At least need to resolve left-padding of REPEAT_END Barline.

**Comment by SalahAdDin** [comment]
can you make a PR?

**Comment by sug1no** [comment]
@SalahAdDin 
I think this problem is complicated, so we need more investigation...
