### ISSUE TITLE
can i use two dots in a note?

### ISSUE THREAD

**Issue by bomben** [0xfe/vexflow#549]
i need to draw in my stave two dots on a single note.  is it possible?

**Comment by gristow** [comment]
Yes: call `addDotToAll()` on a StaveNote as many times as you need:
``` ES2015
  staveNote.addDotToAll().addNote(); // adds two dots.
```

or call `addDot()` on a TabNote:

``` ES2015
  tabNote.addDot().addDot(); // ads two dots
```
