### ISSUE TITLE
Does Vexflow support musicxml?

### ISSUE THREAD

**Issue by dinukadesilva** [0xfe/vexflow#550]

**Comment by bneumann** [comment]
No, not out of the box. There are however ways to accomplish it:
https://github.com/bneumann/vexflow-musicxml 
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay

First one is my own which is currently under development, see README for details. The second is a already pretty far done. There is also a [npm package](https://www.npmjs.com/package/opensheetmusicdisplay)

**Comment by infojunkie** [comment]
Also, LeadsheetJS https://github.com/SonyCSL-Paris/LeadsheetJS includes a MusicXML importer to their own internal format which is then rendered using VexFlow.

**Comment by gristow** [comment]
@bneumann, it seems like this question comes up quite often, and your answer is good. Would you consider adding it to the VexFlow Wiki or FAQ page?

**Comment by dinukadesilva** [comment]
That would be great. And i would like to contribute too......

**Comment by bneumann** [comment]
Sorry @gristow I just saw your post now. Yes I will put it in the Wiki for you.

**Comment by rvilarl** [comment]
@0xfe this one can be closed, it is already documented in the WIKI.
