### ISSUE TITLE
Chords with superscript & slashed bass notation

### ISSUE THREAD

**Issue by Bigsby** [0xfe/vexflow#551]
The example in the test doesn't seem right:
newTextNote({text: "D" + VF.unicode["sharp"] +"/F",  duration: "4d", superscript: "sus2"})
It writes the superscript (sus2) after the bass, it should be D#sus2/F (with sus2 in superscript)

**Comment by gristow** [comment]
You're right that this chord should be notated D# sus2/F, not D#/F sus2. `TextNote` does not give a way to do this, placing all superscript at the end of the text.

Would anyone like to way in on adding something like `textNote.text_struct.slash_bass` that would create the slash & bass at the end of everything? It seems like this would be an easy solution that catches most use cases.

**Comment by Bigsby** [comment]
Maybe this should be formalized and instead of just text, I mean as in accepting chords: key, bass key and maybe alterations.

**Comment by AaronDavidNewman** [comment]
@Bigsby @0xfe  can this be closed now that we have [chord symbol](https://github.com/0xfe/vexflow/wiki/Chord-Symbols-and-Chord-Changes) feature?

**Comment by Bigsby** [comment]
Sure. Chord symbols look amazing.
