### ISSUE TITLE
Feedback not working on http://my.vexflow.com

### ISSUE THREAD

**Issue by SamuelMiller** [0xfe/vexflow#553]
Hello,

I get the following error when I click on the Feedback tab, located on the right of screen, even though I am already logged in.

To post or comment, please Sign In
Error loading login options

Thanks for Vexflow!
Sam Miller

**Comment by SalahAdDin** [comment]
:+1:

**Comment by 0xfe** [comment]
Hi Samuel, My Vexflow is not really supported anymore -- it's just kinda running, and I'm not sure how long it'll keep itself going.

**Comment by SamuelMiller** [comment]
Hello,
Vexflow seems to be the best html/javascript-based solution out there for
generating scores and fretboard diagrams. Is there a way to run Vexflow
locally on my computer so I can generate scores and fretboard diagrams like
on myvexflow.com?
Also if you stop developing vexflow, are there any other open-source
alternatives out there?

Thanks,
Sam

**Comment by 0xfe** [comment]
Vexflow will continue to be developed, and so will Vextab. You can always use the [Vextab Google Docs plugin](https://chrome.google.com/webstore/detail/vextab-music-notation/pjggkphnejbllmmkmmgibonkbbhfjnkk?hl=en) for generating scores.

**Comment by SamuelMiller** [comment]
I mainly use vexflow, Vex Fretboard, for generating fretboard diagrams. Is
that available in the Google Docs plugin? Thanks.

**Comment by SamuelMiller** [comment]
Hi, are you able to help me out? Thanks, Sam


---------- Forwarded message ----------
From: Sam Miller <sam@islandroots.ca>
Date: Tue, Nov 7, 2017 at 12:30 PM
Subject: Fwd: Simple HTML example of Fretboard?
To: thatpaulschofield@gmail.com


Hello Paul,
I was wondering if you could help me out. It appears by your comment
that you were able to get Fretboard to work
(https://github.com/0xfe/fretboard/issues/15).  I have tried multiple
times to contact Mohit, the author of the script, for some assistance,
but he appears to be MIA. Are you able to give me a little guidance in
how to set up Fretboard (see comment below) in html? As I mentioned
below, Mohit's instructions are too minimal for my understanding.

Thanks,
Sam

---------- Forwarded message ----------
From: Sam Miller <sam@islandroots.ca>
Date: Tue, Oct 31, 2017 at 3:58 PM
Subject: Simple HTML example of Fretboard?
To: mohit@muthanna.com


Hello Mohit,

The usage description for Fretboard is minimal, at least for a novice like me.
(https://github.com/0xfe/fretboard). I don't understand the following:
"Simply instantiate a Vex.Fretboard.Div passing in the selector of a
div element as the first parameter. Call build(code) on the instance
to draw. If code is specified, it must be in the syntax described
below. If code is not specified, the contents of the div element are
parsed."

If it is not too much of a bother, could you email me a simple html
example of how to implement Fretboard. I do already have a basic
understanding of html.

Thanks,
Sam
