### ISSUE TITLE
StaveNote.setStyle doesn't color flags

### ISSUE THREAD

**Issue by nunoh** [0xfe/vexflow#557]
<img width="56" alt="screen shot 2017-07-17 at 11 23 34" src="https://user-images.githubusercontent.com/1161423/28262181-727a18c4-6ae2-11e7-8c27-768c592cd149.png">

Is this by design or possibly a bug? 

Any way of getting around it besides selecting the svg and coloring it manually? 

Trying to set `strokeStyle` doesn't seem to have an effect too.

https://jsfiddle.net/7290eukt/

**Comment by gristow** [comment]
I'm not sure what you mean by supplemental lines -- are you trying to color the [ledger line](https://en.wikipedia.org/wiki/Ledger_line) or the [flag](https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Parts_of_a_note.svg/189px-Parts_of_a_note.svg.png)?

Regardless I'm labeling as a bug because:
- `StaveNote.setStyle` should also style the note's flag (and there's currently no other way to do that other than reaching into the SVG)
- `StaveNote.setStyle` should return `this` to match `StaveNote.setKeyStyle`'s api.

**Comment by mscuthbert** [comment]
I don't think that StaveNote.setStyle should affect the ledger line, btw.

**Comment by gristow** [comment]
Yes -- @mscuthbert -- totally agree. `StaveNote.setStyle` shouldn't affect the ledger line, just the notehead, stem & flag. (I'll also add a `StaveNote.setFlagStyle` method for independent styling of the flag.)

The ledger lines should, however, respect `Stave.options.fill_style`, which they don't right now.

**Comment by nunoh** [comment]
I meant the ledger line yes. That was purely a bad translation on my part (not a 1st language speaker and didn't know the proper name until now).

**Comment by gristow** [comment]
Ok -- so the only way to color ledger line(s) individually would be by reaching into the SVG. (You can grab the note group element on the SVG via `staveNote.attr.el`, from there you'll have to do some query-selecting to get the `<rect>` elements that make up the ledger lines themselves.

By the way -- I notice in your fiddle you call `stave.draw(ctx)` after drawing everything else.  This has the effect of making the stave lines appear in front of the notes. It might look better if you go ahead and call `stave.draw()` before drawing everything else.

**Comment by nunoh** [comment]
Thanks for the tips. There's probably a good reason for it, but I don't see why the library shouldn't support an easy way to highlight a single note, ledger line included. Just my 2 cents though.

**Comment by gristow** [comment]
I'm not _against_ having a way to style ledger lines. It seems like for a lot of the educational apps that people are using VexFlow for it might be handy. Perhaps adding a `StaveNote.setLedgerStyle()` method would make sense. As I'm working on the flag-styling part of this, I'll look at doing that, too.

**Comment by nunoh** [comment]
Cool. Fyi, that is exactly my use case.

**Comment by gristow** [comment]
Working on this one now, and it seems now that we have `element` it would make sense to move most `setStyle`, `getStyle`, and `applyStyle` functions from different elements onto this. Should have this done in the next few days -- I'm finding a few little bugs having to do with `ctx.save` and `ctx.restore` behavior differing in `SVGContext` and `CanvasContext`.

**Comment by gristow** [comment]
FYI: this is fixed in the latest commit -- though because `NoteHead` draws another ledger line on top of the final ledger line drawn by StaveNote, one ledger line still won't be colored.

This will resolve itself as soon as I get to #566.

**Comment by nunoh** [comment]
Wow, that's great news. Thanks :)
