### ISSUE TITLE
"Beam is not defined" issue

### ISSUE THREAD

**Issue by thipages** [0xfe/vexflow#562]
Hi,
I am new and discover little by little this API which seems rather interesting.

I am trying to resolve beams for one stave using _generateBeams_ and _automatic Beaming_
**I have an issue about Beam Class being not recognized**. Find here a [simple FIDDLE](https://jsfiddle.net/thipages/a561gm8L/1/),  see the console message for the error message "Reference Error : Beam is not defined"

Thank you for the help.

**Comment by gristow** [comment]
You should be using the `EasyScore` method to draw beams -- not the full VexFlow api method:

``` JavaScript
const VF = Vex.Flow;

// Create an SVG renderer and attach it to the DIV element named "boo".
var vf = new VF.Factory({renderer: {selector: 'boo'}});
var score = vf.EasyScore();
var system = vf.System();
score.set({ time: '3/8' });;
notes='C#5/8, B4, G#4';

var beam = score.beam(score.notes(notes), {autoStem: true});

system.addStave({
  voices: [score.voice(beam)]
}).addClef('treble').addTimeSignature('3/8');

vf.draw();
```

**Comment by thipages** [comment]
Thank you. It. Works fine. I have seen some strange behaviours. I will compile them exhaustively  later
