### ISSUE TITLE
Windows build is failing

### ISSUE THREAD

**Issue by AaronDNewman** [0xfe/vexflow#571]
Hi, I've been lurking here for years.  I love the project and I am ready to start contributing in some way.  Years ago I created one of the 'ABC' variants (mine was iabc) but I think this is a much better approach.

I was able to build after Gregory Ristow's fix of webpack dependency a couple of weeks ago, but now webpack does not build for a different reason.  On both Windows 7 and Windows 10 I get:

> Running "eslint:target" (eslint) task
> 
> Running "webpack:build" (webpack) task
>  95% emit

The build will hang for hours and not progress.  I did some googling and it said this happens if there is a 'windows reserved character' in the output path, but there were no fixes that worked for me and it's not clear to me how to change it (I'm a bit of a grunt/npm noob). Also I know we are using an old version of webpack - I am able to build the latest version by itself.

Another build issue, but I don't think Windows-related:
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha512-yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvH
SUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== integrity checksum failed when using sha512: wanted sha512-yJHVQEhyqPLUTgt9B83PXu6W
rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA== but got sha1-UWbihkV/AzBgZL5Ul+jbsMPTIIM=. (11423 bytes)

I got around this by doing using --production option, but again got stuck on the webpack issue.

Thanks for this, keep up the good work.
Aaron

**Comment by 0xfe** [comment]
I don't have access to a Windows machine, but was able to upgrade Webpack to the latest version, and build everything without modification. Would that work?

Also, do you know which character in the output path is a windows reserved character?

**Comment by AaronDNewman** [comment]
>Upgrade Webpack to the latest version,...Would that work?

If you have this on a branch I will give it a try.  I originally tried to change webpack latest version in vexflow package.json,  but then got in over my head with other dependency issues.

> which character in the output path is a windows reserved character

I don't know how to tell what the output path is when the error occurs.  MS documents say reserved in file names are:
<>:"/\|?* 

but / and \ are legal in _path_ names, so it's not clear why wepback should be choking on these.  It's possible that a ':' character is causing the path to be interpreted as a windows volumne.  There is a thread here:
[https://github.com/angular/angular-cli/issues/3019](url)
and here:
[https://github.com/webpack/webpack/issues/2908](url)

**Comment by gristow** [comment]
I can very easily bump the project up to Webpack 3.41 (current latest). I've recently migrated two other sizable projects and our build is decidedly simpler by comparison, to see if that works?

@AaronDNewman, I'll fork & create a Webpack 3 branch and let you know when it's ready if you want to give that a try.

**Comment by 0xfe** [comment]
FYI @gristow, Here's the `Gruntfile` diff to make it work with the new Webpack -- 4 lines changed:

```javascript
diff --git a/Gruntfile.js b/Gruntfile.js
index 83c5f2a..c52989a 100644
--- a/Gruntfile.js
+++ b/Gruntfile.js
@@ -10,10 +10,11 @@ module.exports = (grunt) => {
     ' */',
   ].join('\n');
   const BASE_DIR = __dirname;
+  const RELATIVE_BUILD_DIR = "./build";
   const BUILD_DIR = path.join(BASE_DIR, 'build');
   const RELEASE_DIR = path.join(BASE_DIR, 'releases');
   const MODULE_ENTRY = path.join(BASE_DIR, 'src/index.js');
-  const TARGET_RAW = path.join(BUILD_DIR, 'vexflow-debug.js');
+  const TARGET_RAW = path.join(RELATIVE_BUILD_DIR, 'vexflow-debug.js');
   const TARGET_MIN = path.join(BUILD_DIR, 'vexflow-min.js');
   const TARGET_TESTS = path.join(BUILD_DIR, 'vexflow-tests.js');
 
@@ -30,7 +31,6 @@ module.exports = (grunt) => {
     return {
       entry: MODULE_ENTRY,
       output: {
-        path: '/',
         filename: target,
         library: 'Vex',
         libraryTarget: 'umd',
@@ -41,7 +41,7 @@ module.exports = (grunt) => {
           {
             test: /\.js?$/,
             exclude: /(node_modules|bower_components)/,
-            loader: 'babel',
+            loader: 'babel-loader',
             query: {
               presets: [preset],
               'plugins': ['add-module-exports', 'transform-object-assign'],
@@ -55,7 +55,7 @@ module.exports = (grunt) => {
   const webpackCommon = webpackConfig(TARGET_RAW, 'es2015');
 
   // Unsupported build for IE versions <11
-  const TARGET_LEGACY_RAW = path.join(BUILD_DIR, 'vexflow-legacy-debug.js');
+  const TARGET_LEGACY_RAW = path.join(RELATIVE_BUILD_DIR, 'vexflow-legacy-debug.js');
   const TARGET_LEGACY_MIN = path.join(BUILD_DIR, 'vexflow-legacy-min.js');
   const webpackLegacy = webpackConfig(TARGET_LEGACY_RAW, 'es2015-loose');
```

**Comment by gristow** [comment]
Thanks, @0xfe, super time saver!

**Comment by gristow** [comment]
@AaronDNewman, here's a fork updated to Webpack 3. Could you give this a try and see if it works? (If so, I'll PR it into here.)

https://github.com/gristow/vexflow/tree/webpack-3

**Comment by AaronDNewman** [comment]
Hi Gregory, the only issue I had is that I had to npm install with –no-optional, because fsevents is not defined for Windows (and probably Linux).  I don't know if there's a way to specify platform-specific dependencies.  If not we can just make a mention of it in the build instructions.

But the grunt build completed without incident, and I get the combined .js code and all the tests as output.  Thanks for getting me past that, now on to the fun stuff!

**Comment by gristow** [comment]
Ok... could you run `npm list fsevents` and paste the output? I'm trying to figure out what's requiring it...

**Comment by AaronDNewman** [comment]
C:\src\vex\vex_wp3\vexflow>npm list fsevents
vexflow@1.2.84 C:\src\vex\vex_wp3\vexflow
`-- webpack-dev-server@2.6.1
  `-- chokidar@1.7.0
    `-- UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0

**Comment by 0xfe** [comment]
This is a dev dependency -- only useful if you want hot-reloading during development.

**Comment by 0xfe** [comment]
(To be clear, this is an optional dependency, and you can leave it as-is.)
