### ISSUE TITLE
EasyScore Fiddle seems broken

### ISSUE THREAD

**Issue by thipages** [0xfe/vexflow#574]
Check [HERE](https://jsfiddle.net/0b6hcc69/5/)
it is the first  link from[ EasyScore Wiki](https://github.com/0xfe/vexflow/wiki/Using-EasyScore)

**Comment by 0xfe** [comment]
Looks like the API got changed and `selector` is now `elementId`.

**Comment by 0xfe** [comment]
And I called this out in #512. :-)

@thipages See this fiddle for now: https://jsfiddle.net/0b6hcc69/83/

**Comment by 0xfe** [comment]
Updated the Wiki with fixed examples.

**Comment by thipages** [comment]
Ok, thanks
Can you explained why it was still working a couple days ago? (newbie question)

**Comment by 0xfe** [comment]
It's probably because I pushed out a new NPM package two days ago (and hadn't pushed one in a long time.)

**Comment by thipages** [comment]
lol. Thank you!
