### ISSUE TITLE
IncompleteVoice with a 3/4 signature and a dotted half

### ISSUE THREAD

**Issue by Arnotjevleesch** [0xfe/vexflow#576]
Hi,

I thought this kind of voice was complete even in strict mode.

[Code here](https://jsfiddle.net/arnotjevleesch/pt64gkoL/2/)

Please comment the soft mode l.29 to reproduce

I have the same issue with 3/4 signature and two dotted quarters

Thx !

**Comment by gristow** [comment]
`addDotToAll` just instructs VexFlow to render a dot, it does not change the duration of the notes. Instead, when you create a note, you should add a "d" for "dot" to the duration. So, in your case, line 21 should read:
``` javascript
  new VF.StaveNote({ keys: ["a/4"], duration: "hd" }).addDot(0)
```
