### ISSUE TITLE
which files to host in CDN?

### ISSUE THREAD

**Issue by qwe19272375** [0xfe/vexflow#582]
Hi @0xfe ,
I am a member of cdnjs and trying to host this library.

[cdnjs](https://github.com/cdnjs/cdnjs) is one of the most famous free and public web front-end CDN services.

What the files should need to be added in cdnjs?
I found that `vexflow-min.js` may be the main file, and `vexflow-tests.js` seem not necessary for users?
Can these files work on web front-end that CDNJS should host them?

If you have any suggestions, please let me know.

Thank you.

cdnjs/cdnjs#11821

**Comment by 0xfe** [comment]
Hi Brian, Yes, `vexflow-min.js` should be sufficient -- you don't need `vexflow-tests.js`.

Thanks.

**Comment by 0xfe** [comment]
Ideally, we'd have the following files served out of CDN:

```
releases/vexflow-min.js
releases/vexflow-min.js.map
releases/vexflow-debug.js
releases/vexflow-debug.js.map
```
