### ISSUE TITLE
Using vexflow in other Github pages

### ISSUE THREAD

**Issue by Alonso-del-Arte** [0xfe/vexflow#586]
What is the proper protocol and etiquette for using vexflow on my own Github pages?

For this page https://alonso-del-arte.github.io/quiz-skeleton/Brucknerquiz.html I would like to use vexflow for question 14 to show four musical examples. But GitHub is blocking the scrips from vexflow.com, cloudflare.com and jquery.com.

I suppose I could include those in my own repository, but it would be misleading because I have not actually written any of those.

What would be the proper thing for me to do here?

Al

**Comment by gristow** [comment]
Wouldn't it be easier to just use image files (jpg, etc...) for those examples instead?

But, in any case, there's no problem including VexFlow in your repository; it's MIT licensed, so you're free to host it however you want as long as you keep the copyright notice in the source code in tact.

**Comment by Alonso-del-Arte** [comment]
Yes, that would be much easier in this particular case, but I also wanted to have this as a test case that I can refer to if I decide to deploy vexflow for a lot more than four or five musical examples.

So I did copy the files to the gh-pages branch of the repository, and now it displays.

Thank you very much for your help and advice.

**Comment by gristow** [comment]
No problem -- by the way I'm in the midst of prepping & conducting the E minor mass right now here at Oberlin. I had fun taking your quiz!

**Comment by Alonso-del-Arte** [comment]
The one on December 3? Cool. I might have to make a little trip to Ohio.
