### ISSUE TITLE
How to remove the time signature from a stave ? 

### ISSUE THREAD

**Issue by Prim3val** [0xfe/vexflow#591]
Say I used the `addTimeSignature()` method, is there any way I can remove the time signature from the stave ? I mean the glyph. I'm doing an editor, and I'd need to remove the time signature before re-rendering.

**Comment by Prim3val** [comment]
I forgot to add, what I do right now is looping over modifiers of the stave, and if one of them is a Time Signature, I remove it. No idea if it's the right way to do it though

**Comment by 0xfe** [comment]
The right way to do this would be to create a new set of elements (including the stave) upon every edit.
