### ISSUE TITLE
bad slash position(y) for Grace note chords

### ISSUE THREAD

**Issue by sug1no** [0xfe/vexflow#592]
please try:
https://jsfiddle.net/po0hr0jz/

![image](https://user-images.githubusercontent.com/3293067/32929821-1808c440-cb9e-11e7-8cc6-c9dea9ba8d30.png)

**Comment by gristow** [comment]
The issue is Line 54 of `gracenote.js`:
https://github.com/0xfe/vexflow/blob/04d15d1ab16e5b8c6b88f8f36a91bd65dc7f984d/src/gracenote.js#L54

Where the slash position is calculated as a fraction of the stem height. With grace note chords the stem will be longer, hence the odd positioning. Should be calculated as a fraction of the space-between-stave-lines from the outer Y of a stem.

I'll get to this when I can -- but it should be a pretty easy fix if someone else would like to tackle it.

**Comment by sug1no** [comment]
FYI: 'Behind Bars' Page 126:

> The diagonal line should intersect the tail of beam without colliding with the notehead:

> Ensure that a grace note on ledger lines has a sufficiently long stem for the diagonal stroke not to obscure a ledger line:

>PLACING DIAGONAL LINES ON GRACE-NOTE GROUPS
Place the line at the beginning of a group, and diagonally to the beam:

> With double-stemmed beams(stems extending in both directions from a beam), the stem direction of the first note determines the position of the diagonal line. The direction of the diagonal is the same as for the single grace note of the same stem direction:

**Comment by sug1no** [comment]
![image](https://user-images.githubusercontent.com/3293067/44447137-1ff44080-a622-11e8-954d-9af79d2054af.png)
![image](https://user-images.githubusercontent.com/3293067/44447366-c17b9200-a622-11e8-8fda-15c7fd5882fe.png)

more finale25 examples.
* for default stem length, slash y position is same for all duration.
* slash y position may resolve relative to the default(8th) logical stem end (flag side). (?)

**Comment by sug1no** [comment]
![image](https://user-images.githubusercontent.com/3293067/45987960-3709d080-c0af-11e8-92d5-a0e932a7d349.png)

more finale25 examples.

- The slash is scaled by the size of the grace note.

**Comment by sug1no** [comment]
https://github.com/0xfe/vexflow/blob/04d15d1ab16e5b8c6b88f8f36a91bd65dc7f984d/src/gracenote.js#L44

since slash line width is not specified slash line width is depend on the previous ctx.setLineWidth operation.

* default slash line width(thickness) value?

**Comment by sug1no** [comment]
https://forum.makemusic.com/default.aspx?f=6&m=380412
![image](https://user-images.githubusercontent.com/3293067/46506834-9ebed900-c870-11e8-9f08-e3b72d50a3bc.png)

https://ccrma.stanford.edu/software/cmn/cmn/cmn.html#grace-note
![image](https://user-images.githubusercontent.com/3293067/46506855-b4340300-c870-11e8-855e-a4daa1bfcf98.png)

**Comment by sug1no** [comment]
fixed by #661 (with some FIXMEs).
