### ISSUE TITLE
Glyphs should take spacing_between_lines_px value into account

### ISSUE THREAD

**Issue by Prim3val** [0xfe/vexflow#594]
If I create a stave with a space of, say 20 pixels between lines, the time signature glyph, the clef and the notes should have a corresponding size

**Comment by 0xfe** [comment]
Yeah, unfortunately this won't be possible without making some major changes to the rest of the library. If you're trying to resize the elements, it's simpler to just scale up the canvas. (Apologies, if this isn't helpful.)
