### ISSUE TITLE
Vexflow build uses "debug" as deault

### ISSUE THREAD

**Issue by bneumann** [0xfe/vexflow#606]
Hi,

I was just fiddeling with my bundle size when I saw that the release version of vexflow is the vexflow-debug package which is ~800kb. The minified version is only ~450kb.
Is this intentional?

Thanks

**Comment by 0xfe** [comment]
Hi -- yes, this is intentional, however I can't recall why. If @mscuthbert or @gristow have thoughts on this, I'm open to changing it. (It's just a change in the `main` field of `package.json`.

**Comment by bneumann** [comment]
Hehe, OK. I mean it doesn't matter if you import it in another project and let some tool (wepback, uglified) mangle it. After compilation it has about the same size, roughly 400kb, in my project. 
But if somebody plainly uses it, it would be twice the needed size

**Comment by gristow** [comment]
Yes, I think the thought was that this would make debugging easier for people by default. Though, with source mapping that’s less of an issue. And, yes, anyone including VexFlow through a build process hopefully has minification in place for production builds!

**Comment by bneumann** [comment]
If you don't mind I close this one. Thanks @gristow
