### ISSUE TITLE
cdnjs hosting

### ISSUE THREAD

**Issue by sashberd** [0xfe/vexflow#611]
Hi
We would like to host your lib on cdnjs, but we have an [issue](https://github.com/cdnjs/cdnjs/pull/11821#pullrequestreview-67287789) about some file. Could you please help us to resolve this question?
Thanks

**Comment by 0xfe** [comment]
Hi -- I responded to the question [here](https://github.com/0xfe/vexflow/issues/582). Not sure if there were more questions?

**Comment by sashberd** [comment]
Thanks
