### ISSUE TITLE
Styles cannot be applied to TabNotes

### ISSUE THREAD

**Issue by henrypenny** [0xfe/vexflow#620]
It appears that styles aren't applied to TabNotes:

```
let note = new VF.TabNote({ ... });
note.setStyle({fillStyle: 'blue', strokeStyle: 'blue'});
```
Should this work?

**Comment by henrypenny** [comment]
This seems to work:

`note.applyStyle(context, {fillStyle: 'blue', strokeStyle: 'blue'});`

**Comment by sug1no** [comment]
related? #602
