### ISSUE TITLE
Feature: add id or class to each SVG element.

### ISSUE THREAD

**Issue by henrypenny** [0xfe/vexflow#621]
It would be really helpful to be able to add an id or class to each SVG element.
This would allow targeting individual items or arbitrary groups of items with css or javascript.

```
new VF.StaveNote({ keys: ['b/4'], duration: '8', stem_direction: -1, id:'xyz', class: 'abc' });
```

**Comment by rjmill** [comment]
This is something I'd like to see more support for in vexflow as well.

@henrypenny The good news is that there is already some support for what you're wanting, and then there's workarounds possible for what isn't officially supported.

I'm still getting my feet wet with vexflow, but I'll share what I've found so far. I might be missing important details, so take it all with a grain of salt.

## Workarounds
### Setting ids

You can use `Element`'s `setAttribute` method to add an id to anything extending `Element` (including `StaveNote`.)

For instance:
```javascript
let myStaveNote = new VF.StaveNote({ keys: ['b/4'], duration: '8', stem_direction: -1 });
myStaveNote.setAttribute('id', 'xyz');
```
Be aware that any IDs set using this method will be prefixed with `Vex.Prefix.prefix`, which is `"vf-"` by default. (You can change it if you want, but it will change the prefex for *all* vexflow ids and class names.)

### Setting classes and ids
There might be a clean way to do this in vexflow, but I haven't discovered it yet. Depending on your needs, different approaches might make sense for you.

#### Using `context.openGroup` and `context.closeGroup`
you can wrap the entire element in a `<g>` using `context.openGroup()` before drawing your elements and `context.closeGroup()` afterwards. `context.openGroup()` returns a reference to the DOM node for the `<g>` element, so you can manipulate that just as you would any other HTML element.

This is probably the cleanest way to do it if you don't need super granular control.

#### Using `element.attrs.el`
Once a vexflow element is rendered, you can reference the DOM node directly through the vexflow element's `attrs.el` property. The potential problem here is that you might not have access to all the elements you want. For instance, the ledger lines aren't children of the stavenote element, so if you want to translate a note to the right, using `element.attrs.el` to do it will end up leaving the ledger lines behind.

## Inheritance mumbo jumbo
It can be a big pain to jump in and wrap each element in a group every time you call draw and add the proper classes, but that's where inheritance comes in. If you're using ES6+ with something like Babel (or if you don't care about supporting old browsers), extending the vexflow classes can make your life much easier.

For example:

```javascript
import Vex from 'vexflow';

const VF = Vex.Flow;

class MyStaveNote extends VF.StaveNote {
  // extend the constructor to add our props for id and classList
  constructor(props) {
    super(...arguments); // pass all arguments through to superclass constructor
    let {
      myId,
      myClassList=[],
    } = props;
    // NOTE: I'm prefixing everything with "my*" to make it clear that these props are
    //       not native to vexflow. In practice, you'd probably want to use a prefix
    //       specific to your project instead of "my". It's not technically necessary,
    //       but it's a good practice, IMO
    this.myId = myId;
    this.myClassList = myClassList;
  }

  draw() {
    super.draw(...arguments);

    let el = this.attrs.el;
    // attrs.el is a normal DOM node object, so you can manipulate it like any other DOM node
    el.setAttribute('id', this.myId);
    el.classList.add(...this.myClassList);

    // NOTE: at time of writing, draw doesn't return anything, but if it did, we'd want to preserve that behavior
  }
}
```

If you're not using ES6 in your project, it's still possible to do all this, but it's a bit more work.

## Ideas for vexflow features
Passing an id and classList in through the constructor makes a lot sense for SVG contexts, but not so much for canvas contexts.

Instead, what if we could pass lifecycle hooks in through the element's constructor. In my opinion, that would give users much tighter control over vexflow without requiring them to hack it in with OO/inheritance shenanigans.

If people are interested, I'd be happy to submit a pull request :slightly_smiling_face: The main lifecycle hooks I see are `beforeDraw` and `afterDraw`. I'm sure there are others that'd make sense though.

**Comment by 0xfe** [comment]
Closing old issue.
