### ISSUE TITLE
Unable to build project

### ISSUE THREAD

**Issue by henrypenny** [0xfe/vexflow#622]
When running Grunt on the master branch:

```
Warning: Uglification failed.
SyntaxError: Unexpected token: punc ()). 
Line 89 in build/vexflow-debug.js
 Use --force to continue.

Aborted due to warnings.
```

I've tried a number of solution on StackOverflow regarding enabling an ES6 compatible version of UglifyJs, all to no avail.

**Comment by 0xfe** [comment]
Sorry, I can't reproduce this error. Did you follow the full build instructions?
