### ISSUE TITLE
Is there a way to autobeam music that was entered with easyscore?

### ISSUE THREAD

**Issue by acidjunk** [0xfe/vexflow#625]
I found a page in the wiki about autobeaming and some docs on it (last edited in 2014). But it does not seem to work with music entered with easy score.

Is there a way to enable autobeaming for notes entered via easy score? (I just need simple autobeam, e.g. two eights -> beam, e.g. beam each quarter)

**Comment by eric-chong** [comment]
I am trying to find out how to accomplish this as well.

**Comment by eric-chong** [comment]
Found a test that has an example of using easyscore and auto beam generation.

https://github.com/0xfe/vexflow/blob/master/tests/auto_beam_formatting_tests.js#L44

Basically, just call `VF.Beam.applyAndGetBeams` passing in the voice you created for easyscore.  Then draw the beams after `vf.draw`

**Comment by acidjunk** [comment]
Ahm after `vf.draw()` did the job :)

```
var voice = score.voice(score.notes(
    'f5/8, e5, d5, c5/16, c5, d5/8, e5, f5, f5/32, f5, f5, f5'
), { time: '4/4' });
var beams = VF.Beam.applyAndGetBeams(voice);
vf.draw()
beams.forEach(function(beam) {
    return beam.setContext(vf.getContext()).draw();
});
```

**Comment by zfan40** [comment]
seems issue #535 shows a simpler demo
