### ISSUE TITLE
How to get the optimal height of the renderer to display all the stave's note

### ISSUE THREAD

**Issue by allan-simon** [0xfe/vexflow#629]
Currently when choosing the height of the rendered I'm putting an arbitrary number which does not feel right, so I would like to know if there was a way to get the minimun height of a given stave (with all its notes, beam etc etc. already added) so that I could resize a renderer to be able to display all notes ?

**Comment by gristow** [comment]
Hmmm.... only way I can think of is to call getBoundingBox on each drawn item and keep track of the min and max values.

**Comment by 0xfe** [comment]
I think you can get the bounding boxes of the voices too.

**Comment by allan-simon** [comment]
yes using the bouding boxes of the voice works, especially by looking at the source code I realized that the FormatAndDraw method actually create a voice and return it's bouding box so i just have to do 

`var voiceBoundingBox = VF.Formatter.FormatAndDraw(`

**Comment by bneumann** [comment]
Is it only the formatanddraw method or does the format alone also return the boxes (currently no PC to check)

**Comment by sschmidTU** [comment]
@bneumann Voice has a getBoundingBox() method, which FormatAndDraw() returns.
