### ISSUE TITLE
Calculate notes left to fill the voice

### ISSUE THREAD

**Issue by Gimly** [0xfe/vexflow#631]
Hopefully this is the right place to ask "newb" questions.

I'd like to be able to add notes to a voice interactively while still keeping the correct number of notes to fill the voice. What I have done now is creating a method that calculates the number of notes "left" to add in the voice and filling the rest with silence.

For example, let's say I have a voice with a time signature 4/4. If my user adds a 1/4 note, then I add a 1/2 and a 1/4 silence, which all adds up to "1", and fills the voice correctly.

Now, I'm wondering if what I'm doing isn't completely overkill and if there isn't something already done in Vexflow? I've managed to make it work correctly, but wondering if it was the best approach.

Still about the voices, how do you "auto-beam" notes that are in a voice? The examples doesn't show the use of auto beam with voices.

Another question, not related, is that I'd like to add a second stave under the first one with a second voice. I can't find any example anywhere on how to do this.

**Comment by allan-simon** [comment]
how and actually for the second stave, you can use a "System" for this
