### ISSUE TITLE
Percussion uses double sharp for cross notehead

### ISSUE THREAD

**Issue by PieterHartzer** [0xfe/vexflow#640]
When displaying a cross for the note head (`keys: ["g/5/x2"]`) a double sharp symbol is displayed instead of a cross.

![image](https://user-images.githubusercontent.com/1129284/44336673-1fb44380-a470-11e8-9e9d-6c8ca2dc4bc1.png)

![image](https://user-images.githubusercontent.com/1129284/44336634-fabfd080-a46f-11e8-8a29-a4a8c8df3e08.png)

Use glyph v3e instead of v7f?

**edit**

I will make this change once I get home tonight.  In the meantime I noticed the following code:
`  'X': {
    index: 6,
    accidental: '',
    octave: 4,
    code: 'v3e',
    shift_right: 5.5,
  },`

Using `keys: ["x/"]` seems to use the correct glyph but I cannot seem to adjust the note.  Should this be used instead?  The tests use a mixture, although the `keys: ['x/']` always draws the note on b/4.

**Comment by Insomgla** [comment]
👍 

As a drummer, this note head really needed an update

**Comment by PieterHartzer** [comment]
This is now merged in - PR #641
