### ISSUE TITLE
How to represent ghost notes in drums

### ISSUE THREAD

**Issue by ghost** [0xfe/vexflow#654]
In drum notation, ghost notes are represented with the note head surrounded by parenthesis (see https://en.wikipedia.org/wiki/Ghost_note#/media/File:Ghost_note_drumming.png). I see that this notation exists for tablatures, however I was wondering how I could use it with "standard" notation ?

**Comment by jeroenlammerts** [comment]
There is _noteheadBlackParens_ in Smufl.
https://w3c.github.io/smufl/gitbook/tables/noteheads.html

**Comment by rvilarl** [comment]
_noteheadBlackParens_ can be found in http://www.smufl.org/files/smufl-1.18.pdf

**Comment by rvilarl** [comment]
@0xfe I would suggest to use `p` for Parenthesised. Would you agree to add this feature?

**Comment by 0xfe** [comment]
Yes, that sounds good.
