### ISSUE TITLE
potentital bug for auto beam

### ISSUE THREAD

**Issue by zfan40** [0xfe/vexflow#669]
Hi, Thanks for all the brilliant work that has been done.
When I use automatic beam with easyScore, I found something sort of tricky.
I had a measure with notes: `'c4/q, d4/8, e4/8, f4/q, g4/q'`, I got error `Beams can only be applied to notes shorter than a quarter note.`
Well it works when I just convert the sequence to `d4/8, e4/8, c4/q, f4/q, g4/q`.Not sure if this is by design.
Below is a minimal example.
https://jsfiddle.net/9gqy6due
Another suggestion: is it possible score.beam could neglect errors and just present actual notes without beam?

**Comment by jeroenlammerts** [comment]
This can be done by this code:

```
system.addStave({
  voices: [
    score.voice(
      score.notes('c4/q')
      .concat(score.beam(score.notes('d4/8, e4/8'),{autoStem: true}))
      .concat(score.notes('f4/q, g4/q'))  
    )
  ]
}).addClef('treble').addTimeSignature('4/4');
```

https://github.com/0xfe/vexflow/wiki/Using-EasyScore#beams-and-tuplets--jsfiddle-
