### ISSUE TITLE
rhythm whole note & double whole note display incorrect

### ISSUE THREAD

**Issue by dolphinxx** [0xfe/vexflow#670]
Bellow condition is always true for whole note and false for double whole note.
[`if (Flow.durationToFraction(duration).equals(0.5)) {`](https://github.com/0xfe/vexflow/blob/master/src/notehead.js#L55)

change this line to `if (Flow.durationToFraction(duration).value() == 0.5) {` or make Fraction.equals support numeric parameter fix it.

```javascript
  equals(compare) {
  if(typeof compare === 'number') return this.value() === compare;
    const a = Fraction.__compareA.copy(compare).simplify();
    const b = Fraction.__compareB.copy(this).simplify();

    return (a.numerator === b.numerator) && (a.denominator === b.denominator);
  }
```

![breve](https://user-images.githubusercontent.com/2149808/47615108-98c1be00-dae5-11e8-86a6-5b4a1a290558.png)

**Comment by sug1no** [comment]
jsfiddle: <http://jsfiddle.net/eo47gvmc/4/>
