### ISSUE TITLE
Style is not cleared after applying on note with accidental

### ISSUE THREAD

**Issue by jhkst** [0xfe/vexflow#672]
Trying to colorize only one note with its accidental, but the rest of notes on stave is colored too:

        var VF = Vex.Flow;
        var container = $(this.element);
        container.empty();
        var renderer = new VF.Renderer(container[0], VF.Renderer.Backends.SVG);
        renderer.resize(700, 300);
        var context = renderer.getContext();
        context.setFont('Arial', 10, '').setBackgroundFillStyle('#eed');
        var voices = [
            new VF.Voice({num_beats:4, beat_value: 4, resolution: VF.RESOLUTION}),
            new VF.Voice({num_beats:4, beat_value: 4, resolution: VF.RESOLUTION})
        ];

        voices[0].setStrict(false);
        voices[1].setStrict(false);

        var notes = [
            [
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["g/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["a/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["b/4"], duration: '4', stem_direction: 1}),
                new VF.BarNote(Vex.Flow.Barline.type.SINGLE),
                new VF.StaveNote({keys: ["c/5"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["d/5"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/5"], duration: '4', stem_direction: 1}),
                new VF.StaveNote({keys: ["f/5"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#'))
            ], [
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.BarNote(Vex.Flow.Barline.type.SINGLE),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#')),
                new VF.StaveNote({keys: ["f/4"], duration: '4', stem_direction: 1}).addAccidental(0, new Vex.Flow.Accidental('#'))

            ]
        ];

        notes[0][2].setStyle({fillStyle: "blue", strokeStyle: "blue"});

        voices[0].addTickables(notes[0]);
        voices[1].addTickables(notes[1]);

        var formatter = new VF.Formatter();
        formatter.joinVoices([voices[0], voices[1]]);

        formatter.preCalculateMinTotalWidth(voices);
        var width = formatter.getMinTotalWidth();

        var staves = [
            new VF.Stave(10, 20, width*3)
        ];

        staves[0].addClef('treble', 'default', '8vb').addTimeSignature(stave.timeSig.n + '/' + stave.timeSig.d).setKeySignature(stave.key.keyName);

        formatter.formatToStave(voices, staves[0]);

        staves[0].setContext(context).draw();

        voices[0].draw(context, staves[0]);
        voices[1].draw(context, staves[0]);

This is the result
![image](https://user-images.githubusercontent.com/7606266/47929991-f0d43800-deca-11e8-8caf-8330c5a9ca8f.png)

If you change apply it on non-accidental note (e.g notes[0][3] in this example), it works properly.

**Comment by sug1no** [comment]
test case (jsfiddle): <http://jsfiddle.net/s5cg3fq2/4/>

**Comment by sschmidTU** [comment]
Thanks for the fix! This was also a problem in OSMD where suddenly half of the score was colored. I was looking to fix this myself, but hadn't found the cause yet.
