### ISSUE TITLE
Blanket color change for every element

### ISSUE THREAD

**Issue by iforce2d** [0xfe/vexflow#674]
Sorry if I missed it somewhere, but is there a way to simply change every thing that would normally be black, to some other color? For example if I want to draw on a black background, I might want the foreground color to be white, etc.

I can change the color of notes and beams with their setStyle() function. But oddly the setStyle() function of a stave only changes the color of the horizontal lines and nothing else.

![selection_134](https://user-images.githubusercontent.com/2474537/48213130-fe655280-e3e1-11e8-9ca4-f1e078739430.png)

**Comment by sug1no** [comment]
Does this solve the problem (set {fill, stroke}Style to context before draw)?

<http://jsfiddle.net/9cd3s0v2/2/>

![image](https://user-images.githubusercontent.com/3293067/48236084-03d39480-e404-11e8-87b4-b5f0d90c01b9.png)

**Comment by iforce2d** [comment]
Yes, it does. Once before drawing the Staves, and once before drawing the StaveConnectors (for grand staff).

![selection_136](https://user-images.githubusercontent.com/2474537/48243569-ea533c80-e445-11e8-8f18-652faf53234b.png)

Thank you very much :)
