### ISSUE TITLE
Tuplet TextNotes

### ISSUE THREAD

**Issue by eric-chong** [0xfe/vexflow#686]
Does anyone know how to align 3 `TextNote` with 3 tuplet notes?

I tried sending an array of 3 `TextNote`s to `Tuplet`, but doesn't seems to be working.

**Comment by mscuthbert** [comment]
The Tuplet element applies the display of Tuplets, which doesn't apply to the TextNotes, and also sets Note.applyTickMultiplier.  So the trick is to call TextNote.applyTickMultiplier(normalNotes, actualNotes), such as (2, 3).  See http://web.mit.edu/music21/music21j/doc/music21_vfShow.js.html line 885.

**Comment by eric-chong** [comment]
Thanks @mscuthbert
