### ISSUE TITLE
Changing the key signature.

### ISSUE THREAD

**Issue by markmeeus** [0xfe/vexflow#695]
I've been trying to find way to change the key signature in the middle of a score, but it looks not possible at the moment.
I'm not that familiar with the code, but a first glance, it looks like the same pattern as ClefNote could be applied to key signatures.
I would be happy to work on this and submit a PR.

**Comment by sschmidTU** [comment]
It's already possible.
Have a look at the KeySignature tests.
You'll find the code in vexflow/tests, you can use it as an example.
http://public.vexflow.com/tests/
(Search for KeySignature)

**Comment by markmeeus** [comment]
Hi,
Thanks for chiming in.

Here's what I found out so far:
The KeySignature class derives from StaveModifier, so it can be added on stave (either at the begin or at the end).
Adding more StaveModifiers to the same stave causes them to be queued-up at the beginning (or end) of that Stave.

What I want to achieve is a key signature in between a voice. It is the exact same case as the TimeSignature.
TimeSignatures can be added to a voice by using the TimeSigNote class.

I wrote a basic implementation of a KeyChangeNote class, my test result currently looks like this:

![image](https://user-images.githubusercontent.com/123377/54234472-7918b880-450f-11e9-8ea6-758ccafcd42b.png)

Changing from Bb to D and back, with and without cancelling the previous one and the last one with an alteration.

**Comment by sschmidTU** [comment]
I see. I don't think i've ever seen a score with a key change inside a measure (only at the start of one).
If i'd write a score where the piece changes keys during a measure, i'd just use accidentals and place the key change in the next measure.

But it's surely possible, and could be nice to have if you need it.

Nice that you're already implementing it, looking forward to a PR!

**Comment by sschmidTU** [comment]
Though the barline looks a bit confusing in your example.
It looks like the end of measure, but it's after quarter notes in a 4/4 time signature.

**Comment by sschmidTU** [comment]
That's perhaps why i wouldn't write a key signature in the middle of a measure.

**Comment by markmeeus** [comment]
Hi,
You are right, the test example does not make sense, I changed it to whole notes.

![image](https://user-images.githubusercontent.com/123377/54257231-f6b7e500-455e-11e9-99ef-66d762a5893f.png)

**Comment by 0xfe** [comment]
This is useful for VexTab, which uses the *old* way of rendering measures (using `BarNote`). If you're writing scores with VexFlow, then you use one `Stave` per measure. Thanks for the fix.
