### ISSUE TITLE
Tuplets with num_notes >= 10 drawn with reversed text

### ISSUE THREAD

**Issue by ColeDeanShepherd** [0xfe/vexflow#699]
This is how a 12-tuplet (over 4 beats) is rendered with VexFlow 1.2.89:

![image](https://user-images.githubusercontent.com/4631326/56462316-57181e80-6376-11e9-8c91-ea81995b6c30.png)

**Comment by sug1no** [comment]
![image](https://user-images.githubusercontent.com/3293067/56536980-5c55b300-659a-11e9-8ead-d52b05959934.png)

The drawing order of the glyphs may be wrong.

**Comment by mscuthbert** [comment]
can we change "11" to another number like 12 or 10 so we can see if the problem affects both sides of the colon?

**Comment by mscuthbert** [comment]
Fix:  in tuplet.js:
```
  resolveGlyphs() {
    this.num_glyphs = [];
    let n = this.num_notes;
    while (n >= 1) {
      this.num_glyphs.push(new Glyph('v' + (n % 10), this.point));
      n = parseInt(n / 10, 10);
    }

    this.denom_glyphs = [];
    n = this.notes_occupied;
    while (n >= 1) {
      this.denom_glyphs.push(new Glyph('v' + (n % 10), this.point));
      n = parseInt(n / 10, 10);
    }
  }
```
add before closing parentheses:
```
this.num_glyphs.reverse();
this.denom_glyphs.reverse();
```
might also rename `num_glyphs` to `numerator_glyphs` since I read this as saying "number of glyphs"

Would push right now but away from dev environment.

**Comment by sug1no** [comment]
@mscuthbert san:
thank you for your comment!

> add before closing parentheses:
```
this.num_glyphs.reverse();
this.denom_glyphs.reverse();
```
or repalce the `this.*_glyphs.push(...)` to  `this.*_glyphs.unshift(...)`.

> might also rename num_glyphs to numerator_glyphs since I read this as saying "number of glyphs"

me too...
