### ISSUE TITLE
how to dynamic control note size on long stave ?

### ISSUE THREAD

**Issue by imiskolee** [0xfe/vexflow#702]
how to control note size if stave included a lots notes.

**Comment by khaldrago96** [comment]
hi there, off topic but since you are the latest one who posted an issue, I want to ask you one simple question. Using Vexflow.js I got an error message 'Vex is not defined'. I just followed the tutorial but somehow it doenst work. Vexflow is installed using NPM. Thanks!

**Comment by imiskolee** [comment]
@khaldrago96 ok. i think you are not included Vex library on your HTML file, maybe you can trying to add a script tag and src to the vex library js.

**Comment by khaldrago96** [comment]
actually I've installed the vexflow with npm, so I suppose the library is already there? I tried to add 'https://cdnjs.cloudflare.com/ajax/libs/vexflow/1.2.89/vexflow-debug.js' in my script as well, didn't work though. Otherwise, what do u have in your script tag?

**Comment by sschmidTU** [comment]
@khaldrago96 try this at the top of your js:
`import Vex = require("vexflow");`

@imiskolee try this when creating a StaveNote:
```js
let vfnoteStruct = {
        // other options,
        glyph_font_scale: 50, // 39 is default (see tables.js, DEFAULT_NOTATION_FONT_SCALE: 39 in Vexflow)
vfnote = new new Vex.Flow.StaveNote(vfnoteStruct);
```
you may also be able to change the size after the note has been created, but then you're messing with internal variables of the note, which is not how things should work:
```js
vfnote.render_options.glyph_font_scale = 39;
```
