### ISSUE TITLE
Invalid note initialization object

### ISSUE THREAD

**Issue by 3dd13** [0xfe/vexflow#705]
# Version

1.2.89

# Steps to Reproduce

```index.html
<html>
  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vexflow/1.2.89/vexflow-min.js"></script>
  </head>
  <body>
    <div>
      Vexflow test
    </div>
    <div>
      <canvas id="vexflow-test"></canvas>
    </div>

    <script>
      var vf = Vex.Flow;
      var factory = new vf.Factory({ renderer: { elementId: 'vexflow-test' } })
      var score = factory.EasyScore()
      score.parse('c3//x')
    </script>
  </body>
</html>
```

# Expected 

the note line should be parsed with success and no exception

# What happened

exception was raised

```
Invalid note initialization object: {"keys":["c/3"],"duration":"8","dots":0,"type":"x","clef":"treble","auto_stem":true}
```

**Comment by rvilarl** [comment]
@0xfe I think you missed this question

**Comment by AaronDavidNewman** [comment]
I don't know the original intent, but it looks like a bug that has always been there.  Maybe just a typo when pushing 's'.

The difference now is that we enforce the type in notestruct being valid.  Going back to 1.x it doesn't look like that was checked.

**Comment by rvilarl** [comment]
> The problem has to do with the type 'x'. `Score.parse` accepts `x` but `Flow.validTypes` does not. @AaronDavidNewman @0xfe should `x` be accepted? Is this a bug?

@0xfe do you have a oppinion on this one?

**Comment by rvilarl** [comment]
After analysing #654 I believe that this is a bug and that
```
  TYPES(): Rule {
    return { token: '[rRsSxX]' };
  }
 ```
should be 
```
  TYPES(): Rule {
    return { token: '[rRsSmM]' };
  }
 ```
in `EasyScoreGrammar`. The valid note types in `Tables` are:
```
const validNoteTypes: Record<string, { name: string }> = {
  n: { name: 'note' },
  r: { name: 'rest' },
  h: { name: 'harmonic' },
  m: { name: 'muted' },
  s: { name: 'slash' },
};
```
where `m` ("muted") corresponds to the `noteheadX...` glyphs.

**Comment by 0xfe** [comment]
Actually `x` (muted) is used in the guitar tabs, so we'll have to support it.

I think the valid note types should be `x` for muted (I think that's the bug.) Maybe an easy fix is to add `x` to `validNoteTypes` and assigning `name: 'muted'` to it.

**Comment by Kolic822** [comment]
I have simmilar problem, but with TabNote. 

```
 const tabs: TabNote[] = [
      new TabNote({
        positions: [{ str: 1, fret: 3 }],
      }),
    ];
```

I get this error: 
core.mjs:6494 ERROR Error: [RuntimeError] BadArguments: Invalid note initialization object: {"positions":[{"str":1,"fret":3}]}
    at new Note (note.js:14:1)
    at new StemmableNote (stemmablenote.js:8:1)
    at new TabNote (tabnote.js:66:1)
    at AppComponent.ngOnInit (app.component.ts:41:7)
    at callHook (core.mjs:2551:1)
    at callHooks (core.mjs:2520:1)
    at executeInitAndCheckHooks (core.mjs:2471:1)
    at refreshView (core.mjs:9510:1)
    at renderComponentOrTemplate (core.mjs:9612:1)
    at tickRootContext (core.mjs:10866:1)

  "dependencies": {
    "@angular/animations": "~13.3.0",
    "@angular/common": "~13.3.0",
    "@angular/compiler": "~13.3.0",
    "@angular/core": "~13.3.0",
    "@angular/forms": "~13.3.0",
    "@angular/platform-browser": "~13.3.0",
    "@angular/platform-browser-dynamic": "~13.3.0",
    "@angular/router": "~13.3.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    **"vexflow": "^4.0.3",**
    "vextab": "^3.0.6",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.3.3",
    "@angular/cli": "~13.3.3",
    "@angular/compiler-cli": "~13.3.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.6.2"
  }
  
  Does anyone know why this happens?

**Comment by sschmidTU** [comment]
@Kolic822 which vexflow version are you using?
I think you are missing the `duration` parameter in the TabNote struct (in addition to positions).

@rvilarl Is it possible that `duration` should be a non-optional parameter? Currently it's optional. In the Vexflow 1.2.93 definitions from DefinitelyTyped, it's non-optional.
<img width="448" alt="image" src="https://user-images.githubusercontent.com/33069673/175547504-ad64f638-f06c-411b-ace4-6ffd2bba7b33.png">

**Comment by Kolic822** [comment]
@sschmidTU Yes, that was the problem. Thank you!

**Comment by rvilarl** [comment]
@sschmidTU this is rigth duration is required. The reason why it is optional is that within the code this possibility is accepted ending up in a runtime error message. Not a good approach.
