### ISSUE TITLE
Rendering Clefs

### ISSUE THREAD

**Issue by MarianneAK** [0xfe/vexflow#708]
I was wondering if there is a way to render a treble clef down 15/up 15 in Vexflow. I couldn't find anything that allows that.

**Comment by sschmidTU** [comment]
Not yet.

You'd have to add a 'v15' glyph in clef.js:annotations(),
then either add a new single glyph that renders 15, or add a way to render both the 'v1' and 'v5' glyphs in clef.js, via a `code: ['v1', 'v5']
You can see the currently supported glyphs [here](http://groovemechanic.net/public/vexflow/src/glyphs.html) or by opening src/glyphs.html in the repository.

By the way, do you by chance need this for the garklein (sopranissimo) recorder? I haven't seen a lot of double octave shifts (15 up) in sheet music.

**Comment by sschmidTU** [comment]
Or you could just render it yourself by using `fillText(text, x, y)` above a normal treble clef,

probably by getting the `let bbox = clef.getBoundingBox()` and setting `x=bbox.getY() + bbox.getH()+1` etc., see boundingbox.js

**Comment by MarianneAK** [comment]
Actually I need them to represent some scores known as Modal Monodies (a type of old arabic music), but I guess the fillText suggestion might be my best option.

> Or you could just render it yourself by using `ctx.fillText(text, x, y)` above a normal treble clef,
> 
> probably by getting the `let bbox = clef.getBoundingBox()` and setting `x=bbox.getY() + bbox.getH()+1` etc., see boundingbox.js

**Comment by MarianneAK** [comment]
> Not yet.
> 
> You'd have to add a 'v15' glyph (two octaves up) in clef.js:annotations(),
> then either add a new single glyph that renders 15, or add a way to render both the 'v1' and 'v5' glyphs in clef.js, via a `code: ['v1', 'v5']
> You can see the currently supported glyphs [here](http://groovemechanic.net/public/vexflow/src/glyphs.html) or by opening src/glyphs.html in the repository.
> 
> By the way, do you by chance need this for the garklein (sopranissimo) recorder? I haven't seen a lot of double octave shifts (15 up) in sheet music.

Actually I need them to represent some scores known as Modal Monodies (a type of old arabic music), but I guess the fillText suggestion might be my best option.
