### ISSUE TITLE
Build error in 1.2.89

### ISSUE THREAD

**Issue by amitgur** [0xfe/vexflow#709]
I'm building with webpack 4.35 and importing vexflow
On vexflow@1.2.84 it's OK
On vexflow@1.2.89 I get:
ReferenceError: window is not defined

Window should be part of the build? Shouldn't it be a "browser free build"?

**Comment by bneumann** [comment]
AFAIK vexflow only builds for the browser thus making window mandatory

**Comment by amitgur** [comment]
Thank you, It seems I ran some parts of vexflow on Node.
Anyway you know to use vexflow consts (like Vex.Flow.Barline.type.BEGIN for example) without importing the whole library?

**Comment by sschmidTU** [comment]
just copy the relevant code like the barline type to your own file in your project and import it.
(you can call it VexflowUtils or something)
