### ISSUE TITLE
Support for some Arabic Accidentals

### ISSUE THREAD

**Issue by MarianneAK** [0xfe/vexflow#710]
The two arabic accidentals I am looking for are "Arabic Flat Half Flat" and "Arabic Sharp Half Sharp" (shown below)
Does vexflow support these ?

![Arabic_Flat_Half_Flat](https://user-images.githubusercontent.com/40365554/61513046-7ae61180-aa04-11e9-9765-06f5e79960fc.png)
![Arabic_Sharp_Half_Sharp](https://user-images.githubusercontent.com/40365554/61513052-7faac580-aa04-11e9-9e39-6cd82d212982.png)

**Comment by infojunkie** [comment]
Yes, take a look at https://github.com/0xfe/vexflow/wiki/Microtonal-Support

**Comment by sschmidTU** [comment]
You can fake these accidentals by splitting them in two,
e.g. first the b, then the b with the slash.

OSMD for example creates a triple sharp by first adding a double sharp, then a normal sharp (the first one added will be on the right):
![image](https://user-images.githubusercontent.com/33069673/65985140-7f598c80-e481-11e9-895b-466423050756.png)
```js
if (accidentals[i] === "++") { // triple sharp
  vfnote.addAccidental(i, new Vex.Flow.Accidental("##"));
  vfnote.addAccidental(i, new Vex.Flow.Accidental("#"));
```
