### ISSUE TITLE
Resizing renderer changes SVG's elements positions in DOM

### ISSUE THREAD

**Issue by DavidGildour** [0xfe/vexflow#712]
Hey, I've been working on a musical notation app using your wonderful library, but I ran into a problem.

I'm currently implementing adding multiple measures to the score and splitting them into new rows after certain max cap of measures per line is reached. Everything works fine, however I realized that after resizing the renderer to match the number of rows rendered (e.g. initial height of the renderer (with one measure in one row) is 200 px, therefore when you add another row of measures, you need twice that height, etc.) the SVG's elements (`<rect>`s to be specific, but my guess is all of them) change their y, top and bottom positions (after getting them with `getBoundingClientRect()`) by exactly the added height to the renderer (e.g. 200 px). Quite frankly, I'm baffled, because in order to determine the measure the mouse cursor is currently over I'm using it's bar lines positions (which are rendered as `<rect>` elements) and this creates an annoying problem to deal with.

My question is: is it a bug? Or is it a way the renderer is supposed to be working?

**Comment by DavidGildour** [comment]
Update > upon some debugging I've noticed something peculiar:

First I try to select the note in the first and only measure and check it's DOM position alongside with DOM position of the measure's bar lines - everything works well.
Then I add some measures to get a new row and try to selected the same note once again, and this time everything gets messed up, BUT the note position is still the same, no Y-axis offset added, yet the bar lines DO HAVE this Y-axis offset, and, strangely enough, when I add only one row it's 100 px (so half of the new row's height), two rows or more - 200 px. I'm helpless.

**Comment by AaronDavidNewman** [comment]
I know its old but I just saw this.  SVG elements are in viewbox space, but mouse events are in client (screen) space.  To convert between, them you need to use  something like this on results from getBoundingClientRect (dom space) and inverse on coordinates from svg elements:

```
static domToSvg(svg, point) {
		var pt = svg.createSVGPoint();
		pt.x = point.x;
		pt.y = point.y;
		var sp = pt.matrixTransform(svg.getScreenCTM().inverse());		
			return {
				x: sp.x,
				y: sp.y
		};		
```
I have this working here:
https://aarondavidnewman.github.io/Smoosic/build/html/editor.html

**Comment by sschmidTU** [comment]
> `static domToSvg(svg, point) {`

Typescript version (for reference):
```typescript
    public domToSvg(svgBackend: SvgVexFlowBackend, point: PointF2D): PointF2D {
        const svg: SVGSVGElement = svgBackend.getSvgElement() as SVGSVGElement;
        const pt: SVGPoint = svg.createSVGPoint();
        pt.x = point.x;
        pt.y = point.y;
        const sp: SVGPoint = pt.matrixTransform(svg.getScreenCTM().inverse());
        return new PointF2D(sp.x, sp.y);
    }
```
    
`PointF2D` is simply a type that contains x and y, you can replace it with `{x: number, y: number}`.

**Comment by sschmidTU** [comment]
See #504
(i hope this solves the issue)

**Comment by rvilarl** [comment]
@AaronDavidNewman @sschmidTU can this be closed?

**Comment by sschmidTU** [comment]
For me, yes. The issue seems resolved anyways. (and it's very old)
