### ISSUE TITLE
Placing a single note at specified X position

### ISSUE THREAD

**Issue by Morpheus0x** [0xfe/vexflow#713]
Hi,
sorry for opening an issue but I am at a loss how to use vexflow. I tried many things mentioned in the wiki and other issues but I just can't find the right functions.

My Goal is to place a note on a stave at a specified x value while ignoring the space needed for the accidental. The note should stay at the same position whether it has an accidental or not.
I tried to use tick context: `VF.TickContext().addTickable(notes[0]).preFormat().setX(50)` but I don't know how to draw the note onto the stave. Another attempt was to take the example here: [https://jsfiddle.net/7y74r86s/4/](https://jsfiddle.net/7y74r86s/4/) and modify it so that the quarter notes align: [https://jsfiddle.net/1t4a9gmh/13/](https://jsfiddle.net/1t4a9gmh/13/) I the first two notes to be are at the same x position. Also if I don't use ghost notes I get this error `t {code: "IncompleteVoice", message: "Voice does not have enough notes."}` and I have no idea why.

Thanks in advance for you help.

**Comment by rvilarl** [comment]
`setX(...)`can be called in the note's `TickContext` after `Formatter.format()`

https://jsfiddle.net/erf6zw5b/

**Comment by sschmidTU** [comment]
@rvilarl @ronyeh This can probably be closed now.
