### ISSUE TITLE
Security Issue: https-proxy-agent

### ISSUE THREAD

**Issue by mix3d** [0xfe/vexflow#726]
Building a new project with vexflow@latest (v1.2.89 at time of writing) trips 21 _high_ security advisories, all for the sub-dependency `https-proxy-agent` being below 2.2.3: https://npmjs.com/advisories/1184

**Comment by 0xfe** [comment]
Thanks, yes I need to do a dependency update. It should simply be a bump in the `package.json` file, but it'll need to be tested. (I'll happily accept a PR if you're up for it.)

**Comment by rvilarl** [comment]
@0xfe you can close this one we are now on version 5.0.0
