### ISSUE TITLE
Is it possible to set a default ledger line style?

### ISSUE THREAD

**Issue by newlandsvalley** [0xfe/vexflow#729]
(I haven't found a way to do it so far)

**Comment by rvilarl** [comment]
@0xfe @newlandsvalley is right, there is no way to set a default. `protected ledgerLineStyle: ElementStyle;` is an attribute for each `StaveNote`. Is it expected to have different styles on each `StaveNote`? There indeed examples with different colours.

**Comment by 0xfe** [comment]
It's part of the note head. Open to an API to set a default -- perhaps at the `Stave`.

**Comment by rvilarl** [comment]
@0xfe Stave does not hold a list of the notes so I decided to place it in system. I hope this is fine :)

**Comment by 0xfe** [comment]
`System` is not that widely used, but notes are always rendered onto a `Stave`. So you can get the style from the stave during render time. (Alternatively, we can make it a global default setting in `Flow`.)

**Comment by rvilarl** [comment]
@0xfe now in Stave as suggested, we can close this once we merge #1069
