### ISSUE TITLE
Setting accidental color

### ISSUE THREAD

**Issue by jkopyto** [0xfe/vexflow#731]
Hi!

I'm wondering if there is any possibility to set color on particular accidentals.
I see that I can do something like 
`notes[0][2].setStyle({fillStyle: "blue", strokeStyle: "blue"})`
but this is setting color also on note head and stem

**Comment by sschmidTU** [comment]
It doesn't seem to be possible currently.
I've tried using setStyle on an Accidental, but it doesn't do anything.
(Accidental extends Modifier which extends Element which has setStyle)

sample:
https://jsfiddle.net/njyfs5xv/

**Comment by h-sug1no** [comment]
Hi!

<https://jsfiddle.net/njyfs5xv/> with the current master branch, the modifier style is applied at render time (#693) as follows:
![image](https://user-images.githubusercontent.com/59550999/73043759-e58f7280-3ea9-11ea-8d51-601770cffeb6.png)

But  last release binaries does not contains #693. orz...

**Comment by mscuthbert** [comment]
> But last release binaries does not contains #693. orz...

so we should release!

**Comment by sschmidTU** [comment]
@mscuthbert @0xfe did you see the comment i made about how to give npm release permissions? @mscuthbert you'd just have to give 0xfe your npmjs user name.
https://github.com/0xfe/vexflow/pull/721#issuecomment-577751363

**Comment by 0xfe** [comment]
Okay, version 1.2.90 released from master.
