### ISSUE TITLE
Method for Auto-Tying

### ISSUE THREAD

**Issue by davidmreichert** [0xfe/vexflow#733]
Hello, I was wondering if there was a method for automatically splitting up notes in a voice that cross beat boundaries. Say I have something like:
```       
var notes2 = [
            new VF.StaveNote({clef: "bass", keys: ["c/2"], duration: "8" }),
            new VF.StaveNote({clef: "bass", keys: ["d/2"], duration: "8" }),
            new VF.StaveNote({clef: "bass", keys: ["e/2"], duration: "8" }),
            new VF.StaveNote({clef: "bass", keys: ["f/2"], duration: "4" }),
            new VF.StaveNote({clef: "bass", keys: ["a/2"], duration: "8" }),
            new VF.StaveNote({clef: "bass", keys: ["b/2"], duration: "8" }),
            new VF.StaveNote({clef: "bass", keys: ["c/3"], duration: "8" })
        ]
```
I'd want it to look something like this:
<img width="360" alt="Screen Shot 2019-11-27 at 10 03 28 AM" src="https://user-images.githubusercontent.com/25554091/69734589-3af31180-10fd-11ea-9878-b88be1f1e5ca.png">

**Comment by 0xfe** [comment]
Vexflow tries to remain semantically agnostic, so this is kind of out of scope. You can use VexTab or a MusicXML layer (like OpenSheetMusic) to do this automatically.
