### ISSUE TITLE
Incrorrect x-position when showing Vex.Flow.Repetition.type.DS with "B" key signature

### ISSUE THREAD

**Issue by compilelife** [0xfe/vexflow#735]
example code:

```js
            VF = Vex.Flow;
            var div = document.getElementById("boo")
            var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);

            renderer.resize(500, 500);
            var context = renderer.getContext();
            context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

            var stave = new VF.Stave(10, 40, 400);
            stave.addClef("treble").addTimeSignature("4/4");
            stave.setKeySignature("B");
            stave.addModifier(new Vex.Flow.Repetition(Vex.Flow.Repetition.type.DS, 0, 50), Vex.Flow.StaveModifier.Position.RIGHT);

            stave.setContext(context).draw();
```

which rendered as: 

![image](https://user-images.githubusercontent.com/3362269/72673021-0406ff80-3a9f-11ea-96b1-6efbb758be75.png)

The x-position of "D.S." goes too far away to the end of stave.

**Comment by compilelife** [comment]
I'm trying to fix it with modification as follow(in `stave.js`):

```js
  getModifierXShift(index = 0) {
    if (typeof index !== 'number') {
      throw new Vex.RERR('InvalidIndex', 'Must be of number type');
    }

    if (!this.formatted) this.format();

    if (this.getModifiers(StaveModifier.Position.BEGIN).length === 1) {
      return 0;
    }

    //fix by compilelife: for modifiers goes to right position, zero-shift seems to work correctly
    if (this.modifiers[index].getPosition() === StaveModifier.Position.RIGHT) {
      return 0;
    }

    let start_x = this.start_x - this.x;
    const begBarline = this.modifiers[0];
    if (begBarline.getType() === Barline.type.REPEAT_BEGIN && start_x > begBarline.getWidth()) {
      start_x -= begBarline.getWidth();
    }

    return start_x;
  }
```

rendered as follow:

![image](https://user-images.githubusercontent.com/3362269/72673439-724ec080-3aa5-11ea-9ddf-3ac0309f553d.png)

Could you please help me examine that?

**Comment by compilelife** [comment]
Another related x-position issue is the right space seems too large.

![image](https://user-images.githubusercontent.com/3362269/72673477-0ae54080-3aa6-11ea-9102-05213547d6c5.png)

Compare to musescore:

![image](https://user-images.githubusercontent.com/3362269/72673537-cf974180-3aa6-11ea-9da5-34383c6b9e52.png)


which is exactly close to the end barline

I would guess it's releated to the code below:

```js
drawSymbolText(stave, x, text, draw_coda) {
    //……
    if (this.symbol_type === Repetition.type.CODA_LEFT) {
      // Offset Coda text to right of stave beginning
      text_x = this.x + stave.options.vertical_bar_width;
      symbol_x = text_x + ctx.measureText(text).width + 12;
    } else {
      // Offset Signo text to left stave end
      //comment by me: -5 and -12 here is magic to me, which introduce the right space of 'D.S.'
      symbol_x = this.x + x + stave.width - 5 + this.x_shift;
      text_x = symbol_x - + ctx.measureText(text).width - 12;
    }
```

Could you please give me some info about the -5 and -12?

**Comment by compilelife** [comment]
Same issure happens to "volta".

code:

```js
            VF = Vex.Flow;
            var div = document.getElementById("boo")
            var renderer = new VF.Renderer(div, VF.Renderer.Backends.SVG);

            renderer.resize(500, 500);
            var context = renderer.getContext();
            context.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

            var stave = new VF.Stave(10, 40, 400);
            stave.addClef("treble").addTimeSignature("4/4");
            stave.setKeySignature("B");

            stave.setVoltaType(Vex.Flow.Volta.type.BEGIN_END, 1, 0);
            stave.setContext(context).draw();
```

![image](https://user-images.githubusercontent.com/3362269/72674083-b5149680-3aad-11ea-9958-c03012b98d18.png)

correct result should be:

![image](https://user-images.githubusercontent.com/3362269/72674102-f73dd800-3aad-11ea-94a7-f0c95e480a08.png)

The responsible code would be(in `stavevolta.js`):

```js
draw(stave, x) {
    const ctx = stave.checkContext();
    this.setRendered();

    //let width = stave.width;
    //we should not include x(offset) for width
    let width = stave.width - x;
```

**Comment by 0xfe** [comment]
Thanks for the report -- will take a look.

**Comment by birdofpreyru** [comment]
I also bumped into this issue with volta, and the fix above looks correct, it will be cool if you apply it to the codebase soon :)

**Comment by sschmidTU** [comment]
I'll check this for side effects and make a PR, if noone's on it already ^^

for the DS spacing, could this be to leave space for the coda sign in "D.S. al [coda sign]"?
![image](https://user-images.githubusercontent.com/33069673/76352577-92656800-630f-11ea-9666-fca2a397fc48.png)
Of course it should only take the space if we have an added "al coda".
I'll take a look.

**Comment by sschmidTU** [comment]
I submitted PR #796 that should fix these issues, if anyone wants to take a look.
