### ISSUE TITLE
No key signature should create empty space

### ISSUE THREAD

**Issue by amitgur** [0xfe/vexflow#738]
I'm using Vexflow for a multi-staff system. The problem is that different key signature takes different space. How can I change the first note in all staffs to start from the same point in X coord.
![vexdemo](https://user-images.githubusercontent.com/4021701/73952778-0fb04e00-4908-11ea-8dc5-d98b3843eaeb.png)

**Comment by 0xfe** [comment]
You can use `setNoteStartX(...)` to align the voices. See example here: https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#how-do-i-align-multiple-voices-across-staves
