### ISSUE TITLE
Question: Drawing lines over notes

### ISSUE THREAD

**Issue by CrystalShardz** [0xfe/vexflow#739]
Hi,
Im creating an application to transcribe music for the anglo concertina. A popular way of displaying weather a note should be played on the push or the pull is to put a line over the top of the notes which are played on the pull, wich continues over all those in the range. Is this possible with VexFlow? I've put an image for an example:

<a href="https://ibb.co/tY6gNHF"><img src="https://i.ibb.co/P1yKbr0/Screenshot-2020-02-06-at-21-51-39.png" alt="Screenshot-2020-02-06-at-21-51-39" border="0"></a>

**Comment by 0xfe** [comment]
Yes, you can use Brackets or PedalMarkings as an example to build off of.
<img width="676" alt="Screen Shot 2020-02-07 at 7 12 58 AM" src="https://user-images.githubusercontent.com/241299/74028862-65710e80-4979-11ea-9ed9-55ebe3646241.png">

**Comment by sschmidTU** [comment]
For reference, you can find these tests [here](http://www.vexflow.com/tests/), and looking at them in the code base can be helpful to see how to use them.
For example, these tests are in textbrackets_tests.js. (just search for "super uncool")

**Comment by CrystalShardz** [comment]
This is great thanks! I started making slow progress on making a plugin to draw the lines  but this will make it faster! Thanks!

**Comment by mscuthbert** [comment]
(@0xfe -- I am so impressed with the flurry of activity here lately -- Vexflow is incredibly amazing)
