### ISSUE TITLE
Missing 'breath-mark' articulation

### ISSUE THREAD

**Issue by compilelife** [0xfe/vexflow#740]
<img width="117" alt="image" src="https://user-images.githubusercontent.com/3362269/74132577-d20e3680-4c21-11ea-8f17-43829845585f.png">

musicxml reference: http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-breath-mark.htm?Highlight=breath-mark

breath-mark is quite different to other articulatios(like 'Staccato'). It's drawn after/between note, not above/below note.

Much more like a "note".

Any idea how I can implement it ?

**Comment by mscuthbert** [comment]
This breath mark is similar enough to "up bow" would that suffice for now?  I think up bow is implemented in Gonville.

**Comment by compilelife** [comment]
> This breath mark is similar enough to "up bow" would that suffice for now? I think up bow is implemented in Gonville.

Yes, it looks like "up bow". However, "up bow" is not breath mark, check [this](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-up-bow.htm):

```
The up-bow element represents the symbol that is used both for up-bowing on bowed instruments, and up-stroke on plucked instruments.
``` 

The difference between up bow and breath mark is the x-position. up bow shows above the related note which shares the same x-position. breath mark shows on the right of the related note.

**Comment by sug1no** [comment]
Like this(use TextNote + glyph: 'breath')?

<https://jsfiddle.net/9qrc5uyj/4/>

![https://jsfiddle.net/9qrc5uyj/4/](https://user-images.githubusercontent.com/3293067/74229411-a49ab900-4d05-11ea-9851-d5c22c3bdff5.png)

**Comment by compilelife** [comment]
@sug1no Thanks.
