### ISSUE TITLE
Canvas Backend breaks at height > 32767 (browser limit)

### ISSUE THREAD

**Issue by sschmidTU** [0xfe/vexflow#742]
Using the Canvas backend, you can resize a canvas to height=32767 and it renders fine, but resize to height=32768 and it breaks, showing this in Chrome:
![image](https://user-images.githubusercontent.com/33069673/75064146-a2471480-54e6-11ea-96e4-bd026ed3cf9d.png)

Try it here:
https://jsfiddle.net/2Lsme8yd/
(setting the height back to 32767 fixes the problem)

This is because browsers limit the size of a canvas element:
https://stackoverflow.com/a/11585939/10295942

(It's funny that they just break without a real error message though.
And that a 16 bit signed integer seems to be the somewhat arbitrary limit. I guess you can fit width+height in one 32-bit register then.)

Btw, there's a npm module canvas-size that tells you the current browser's maximum canvas size, which could be used:
https://stackoverflow.com/a/53677532/10295942

So, @0xfe what do you think would be the best way to deal with this? OSMD logs a warning and simply reduces the height (and width) to the maximum of 32767.
I suppose Vexflow could do the same, outputting a warning with Vex.W(). Or exit with 1? ;)

I can make a PR for this, just wanted to discuss how to proceed first.

**Comment by 0xfe** [comment]
Thanks for reporting, this is interesting! :-)

I thing warning + clipping is the right first approach.

Longer term, I wonder if we can simply stitch multiple canvases together -- all Canvas calls go through our renderer, so it's definitely doable. Just like we do for scaling, we could write a function transform all x/y/w/h into (canvasContext, x/y/w/h, scale) and use that everywhere.
