### ISSUE TITLE
ReactJS and VexFlow - joinVoices() issue

### ISSUE THREAD

**Issue by tgallagher2017** [0xfe/vexflow#743]
I have the below functional component in ReactJS.   It is set up so that the VexFlow images are drawn after the ReactJS DOM rendered (using the useEffect() hook).  The Stave draws fine, when I try to add some notes, the browser display clears at this line (also shown below):
         var joined = formatter.joinVoices([voice]);
If I comment out this line, then the Stave draws, but of course I don't get any notes displayed.  Rightly so, I can not uncomment the lines that follow until this line works. Not sure if it is a config issue or not, but this kind of function does not seem to be related to the UI although and error in it does effect the UI.

Code: 
import React, { useEffect } from 'react';
import VF from 'vexflow'

export interface IMusicalNotesProps {
    renderDivName?: string;
    height: number;
    width: number;
    clef: string;
    keys: string[];
    duration: string;  // "q", 'h', 'f' 
}

export function MusicalNotesFunc(props: IMusicalNotesProps) {

    // render the clef with notes later due to the 
    // draw function in the VexFlow library
    useEffect(() => {
        let vexFlow: any;
        let renderDiv: any;
        let vfRenderer: any;
        let vfContext: any;
    
        vexFlow = VF.Flow;
            if (typeof (props.renderDivName) === 'undefined') {
            props.renderDivName = 'MusicalNotesFuncDiv';
        }
        renderDiv = document.getElementById(props.renderDivName);

        vfRenderer = new vexFlow.Renderer(renderDiv, vexFlow.Renderer.Backends.SVG);
        vfRenderer.resize(props.height, props.width);

        vfContext = vfRenderer.getContext();
        vfContext.setFont("Arial", 10, "").setBackgroundFillStyle("#eed");

        // render the notes on the stave
        // Create a stave at position 10, 40 of width 400 on the canvas.
        var stave = new vexFlow.Stave(10, 40, props.width - 20);

        // Add a clef and time signature.
        stave.addClef(props.clef).addTimeSignature("4/4");

        // Connect it to the rendering context and draw!
        stave.setContext(vfContext).draw();

        var notes = [
            // prop values are:
            //   clef='treble'
            //   keys={["C/4"]}
            //   duration='q' 
            new vexFlow.StaveNote({ clef: props.clef, keys: props.keys, duration: props.duration})
        ];
        // Create a voice in 4/4 and add above notes
        var voice = new vexFlow.Voice({num_beats: 4,  beat_value: 4});
        voice.addTickables(notes);

        // Format and justify the notes to 400 pixels.
        var formatter = new vexFlow.Formatter();
        var joined = formatter.joinVoices([voice]);
//        joined.format([voice],  props.width - 20);

        // Render voice
//        voice.draw(vfContext, stave);

    });

    return (
        <div id={props.renderDivName} />
    );
}

**Comment by mscuthbert** [comment]
Are you able to get this to work in a pure HTML/Javascript context?  I'm not sure that people in VexFlow can diagnose ReactJS issues unless we're absolutely sure that everything works in pure HTML/Javascript first.  I see a lot of props that aren't necessarily defined, such as height and width and clef.

**Comment by tgallagher2017** [comment]
Thanks fro the response. On additional research and review of the browser console, I found this comment: Voice does not have enough notes.  Since I want to build the notes on the clef individually based on user response, I ended up using voice.setMode(Voice.Mode.SOFT).
