### ISSUE TITLE
Request: support 15va and 15vb

### ISSUE THREAD

**Issue by rowild** [0xfe/vexflow#745]
I do not know if this is really the proper place for placing requests – if not, please direct me to the proper place. Thank you!

Currently is seems that "only" "8va" and "8vb" clef construction is supported. It would be great to have also "15va" and "15vb" available (code: v15?). 

I did look at the vex-glyph file for "v8", but so far i have no clue, how those symbols are generated beforehand and later on converted to SVG paths. The "v8"-"path" contains letters like a lowercase b, which is unknown to me, when it comes to SVG. Also, some white spaces (e.g. after the "m") confuse me. Any hints as to what I have to study in order to understand the font generation and eventually contributing to it would be most welcome!

Thank you!

**Comment by bneumann** [comment]
Hey, I think there is. I implemented the octava stuff for opensheetmusicdisplay. Check our demo https://opensheetmusicdisplay.github.io//demo/ and select OSMD Function Test - Expressions

As far as I remember you can set your own text to this bracket thingy

**Comment by rowild** [comment]
@bneumann This is most helpful - thank you very much! 
However, I am still looking for a **clef** with a 15va. It seems those are constructed using an extra glyph (as in "vexflow_font", key "v8") and a definition of its placement as an annotation (found in "clef.js" -> "static get annotation()").

As mentioned: currently I have (still) no idea, how the svg generation works, or, to be more precise, how the reduction to a glyph (as in vexflow-font.js) works.

Is there a Slack channel or sth similar for vexflow?

**Comment by rowild** [comment]
@0xfe Any recommendations?

**Comment by 0xfe** [comment]
Hi -- I just created the following Wiki page about adding custom glyphs: https://github.com/0xfe/vexflow/wiki/Adding-VexfFow-Glyphs

**Comment by rowild** [comment]
@0xfe I think I love you! ;-) Thank you very much!
