### ISSUE TITLE
Request: Textnote Figured Bass Continuation Line

### ISSUE THREAD

**Issue by johnameyer** [0xfe/vexflow#750]
In my music theory course, it is sometimes desired to add a line to show that the figures still apply later in the measure, like so:
![image](https://user-images.githubusercontent.com/3662655/77706050-acea4300-6f97-11ea-8c02-7f7544c74d12.png)
or to indicate that a chord has a function other than an inversion (so-called "cadential 64"):
![image](https://user-images.githubusercontent.com/3662655/77706074-ba9fc880-6f97-11ea-8f4d-4e0a1fb0a12a.png)
I know that in issue https://github.com/0xfe/vexflow/issues/180 it was shown that the figured bass is possible but I don't think I've seen how to do the lines in the library. Is there a simple way to do this in the library or otherwise?

**Comment by 0xfe** [comment]
Hi -- You can use `PedalMarking` or `StaveLine` to do this. Thanks.
