### ISSUE TITLE
Repeat measure

### ISSUE THREAD

**Issue by jeroenlammerts** [0xfe/vexflow#751]
Repeat the previous measure, or more (indicated with the number above and more slashes). Couldn't find this feature in the tests. Think this is a nice feature to add. This is used a lot by drummers.

![images](https://user-images.githubusercontent.com/4282711/77827889-81429680-7118-11ea-92a1-43988a47d3a8.png)

![Screenshot from 2020-03-28 17-30-24](https://user-images.githubusercontent.com/4282711/77828112-e3e86200-7119-11ea-9dbf-6a21c37b0242.png)

**Comment by sschmidTU** [comment]
+1, this is also sometimes used in orchestra, e.g. for viola:
![image](https://user-images.githubusercontent.com/33069673/78276940-07454f80-7514-11ea-958f-a8b326b3cbb9.png)

**Comment by 0xfe** [comment]
This is done. I added a new `GlyphNote` class that lets you add arbitrary glyphs to the stave. There's a new subclass called `RepeatNote` specifically for repetition glyphs.

<img width="311" alt="Screen Shot 2020-04-13 at 8 38 34 AM" src="https://user-images.githubusercontent.com/241299/79121038-571ce580-7d62-11ea-81af-74ab3687d63e.png">

**Comment by 0xfe** [comment]
See tests in `tests/glyphnote.js` for usage examples.

**Comment by jeroenlammerts** [comment]
> See tests in `tests/glyphnote.js` for usage examples.

tests/glyphnote_tests.js
