### ISSUE TITLE
How to draw a tie between notes on different staves?

### ISSUE THREAD

**Issue by DouglasWu** [0xfe/vexflow#757]
The `StaveTie` is used to draw a tie between two notes on the same staff.
But what if the second note is on another staff?
Like this:
![image](https://user-images.githubusercontent.com/9346436/78363411-4647d380-75ee-11ea-9bb8-ae1178c9d716.png)
![image](https://user-images.githubusercontent.com/9346436/78363445-53fd5900-75ee-11ea-90f6-93ef5b960a38.png)

Are there any workarounds to handle this situation?

**Comment by 0xfe** [comment]
If you set the start or end notes to `null` they render from the start or to the end of the staves respectively. See the `StaveTie` tests for examples.
