### ISSUE TITLE
Option to style stave text

### ISSUE THREAD

**Issue by jeroenlammerts** [0xfe/vexflow#762]
It is not possible to add styling to stave text.

```
new VF.Stave(x, y, 310)
    .setText('Lorem Ipsum', VF.Modifier.Position.ABOVE, { shift_x: 0, shift_y: 0 })
```

Maybe it would be nice overwrite the font settings with the options parameter

https://github.com/0xfe/vexflow/blob/edfa3fbe50271e4f642fe155a7b14a8f74461348/src/stavetext.js#L25

**Comment by 0xfe** [comment]
You can use `setFont` on `StaveText` to change the styling.

```javascript
const text = new VF.StaveText('Foo bar', VF.Modifier.Position.ABOVE, { shift... });
text.setFont({ ... })
new VF.Stave(x, y, 300).addModifier(text)
```

**Comment by jeroenlammerts** [comment]
Yes I tried this but StaveText is not exported in Vex.Flow. I created a PR https://github.com/0xfe/vexflow/pull/764
