### ISSUE TITLE
Find Bravura backup code points for missing glyphs

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#768]
- [ ] vba
- [ ] vbf
- [ ] v62
- [ ] v80
- [ ] v1e
- [ ] v45
- [ ] v8c
- [ ] v4d
- [ ] v72
- [ ] v33
- [ ] v36
- [ ] v5d
- [ ] v4b
- [ ] v34
- [ ] v6c
- [ ] v6f
- [ ] v1f
- [ ] v4a
- [ ] vb1
- [ ] v90
- [ ] v7a
- [ ] vd6
- [ ] vd7
- [ ] vf
- [ ] va3'
- [ ] vd5'
- [ ] vd4'

**Comment by mscuthbert** [comment]
Do you mean things like:  

vba = U+E522 (or U+1D191) = dyanmicForte
vbf = U+E520 (or U+1D18F)  = dynamicPiano

?  

I think that Cyril made a list somewhere.  I'll look

**Comment by mscuthbert** [comment]
the Astral plane alternates are already in Unicode.

v62 = U+E521 (or U+1D190) = dynamicMezzo
v80 = U+E525 (or U+1D18E) = dynamicX
v1e = U+E56C = ornamentMordent
v45 =U+E56D = ornamentMordentInverted 
v8c = U+E047 (or U+1D10B) = segno
v4d = U+E048 (or U+1D10C) = coda
v72 = U+E567 (or U+1D197) = ornamentTurn
v33 = U+E569 (or U+1D199) = ornamentTurnSlash
v36 = U+E650 (or U+1D1AE) = keyboardPedalPed
v5d = U+E655 (or U+1D1AF) = keyboardPedalUp
v4b = U+E4D4 = caesuraCurved
v34 = U+E4D1 (or U+1D113) = caesura

**Comment by mscuthbert** [comment]
v6c = U+E4CE (or U+1D112) = breathMarkComma
v6f = ??
v1f = U+E566 (or U+1D196) = ornamentTrill
v4a = U+E524(or U+1D18D) = dynamicSforzando
vb1 = U+E523 (or U+1D18C) = dynamicRinforzando

**Comment by ryaanahmed** [comment]
@mscuthbert and I are on a call right now, and I found the list that @Silverwolf90 produced ages ago right after Myke finished reconstructing it...

https://github.com/Silverwolf90/vexflow/blob/refactor/extract-hard-coded-glyphs/src/fonts/gonville_metrics.js

**Comment by ryaanahmed** [comment]
v6f = breathMarkTick

**Comment by 0xfe** [comment]
These are great, thanks. Here are the vexflow glyphs for reference.

<img width="835" alt="Screen Shot 2020-04-06 at 5 29 27 PM" src="https://user-images.githubusercontent.com/241299/78607123-7da3c380-782c-11ea-8433-a87b6051f9c4.png">
<img width="822" alt="Screen Shot 2020-04-06 at 5 29 35 PM" src="https://user-images.githubusercontent.com/241299/78607121-7c729680-782c-11ea-852e-18174a2e0ecb.png">

**Comment by 0xfe** [comment]
I also need Bravura codes for the following (adding to issue):

```
 'v90': true, // microtonal
  'v7a': true, // microtonal
  'vd6': true, // microtonal
  'vd7': true, // microtonal
  'vf': true, // muted breve (double whole)
  'va3': true, // squiggly stroke
  'vd5': true, // rectangle note head white
  'vd4': true, // rectangle note head black
```

**Comment by mscuthbert** [comment]
vf = ? I don't know the muted breve.. could it possibly be U+E4E0 restMaxima, or a variant of v59 percussion clef?  Or maybe it was a mistake for the stylistic alternative to v53 -- U+E0A1 noteheadDoubleWholeSquare? (which also functions as U+E1D1 -- noteDoubleWholeSquare.

**Comment by mscuthbert** [comment]
v90 -- not in SMuFL? or ligature of E442 (accidentalBakiyeFlat) and U+E441 accidentalKucukMucennebFlat -- same as normal flat).
v7a -- variation of accidentalThreeQuarterTonesSharpStein?  U+E283.
vd6 -- variation of accidentalThreeQuarterTonesSharpStein?  U+E283 or ligature of normal sharp U+E262 (and 266F) and U+E282.
vd7 -- not in SMuFL? or ligature of U+E441 accidentalKucukMucennebFlat -- same as normal flat) and E442 (accidentalBakiyeFlat).
va3 -- it's U+EAA9 (wiggleArpeggiatoUp), but unfortunately, U+EAA9 needs to be rotated 90-degrees to make this.
vd5 and vd4 I couldn't find a perfect match.

**Comment by 0xfe** [comment]
Thanks everyone. Got everything in and tuned, except the following. If we can't find SMuFL codes for them, I'll move them into a custom font. Can you (maybe @mscuthbert), provide some names for them with the custom prefix `vex`, so for example: `vexAccidentalThreeQuarterXXX`?

```
Missing SMuFL glyph: v90
Missing SMuFL glyph: v7a
Missing SMuFL glyph: vd6
Missing SMuFL glyph: vd7
Missing SMuFL glyph: vf
Missing SMuFL glyph: vd5
Missing SMuFL glyph: vd4
Missing SMuFL glyph: va3
```

**Comment by 0xfe** [comment]
All fixed. Full font stack working.
