### ISSUE TITLE
Weird misalignment with two voices

### ISSUE THREAD

**Issue by davidedelvento** [0xfe/vexflow#771]
I have a staff with two voices (as a possible workaround to #770 but that's irrelevant) as follows:

```javascript
var VF = Vex.Flow;
var voice_note;
var voice_text;
var ctx;
var topStaff;

var canvas = document.getElementById('spartito');
var renderer = new VF.Renderer(canvas, VF.Renderer.Backends.SVG);
ctx = renderer.getContext();
renderer.resize(500, 500);

topStaff = new VF.Stave(20, 100, 500);
topStaff.addClef('treble');

topStaff.setContext(ctx).draw();

var note_list = ['G/4', 'A/4', 'B/4', 'C/5'];

var total_notes = 4;

voice_note = new VF.Voice({num_beats: total_notes,  beat_value: 4});
voice_text = new VF.Voice({num_beats: total_notes,  beat_value: 4});
var js_note_list = [];
var js_text_list = [];

for (var upper_note of note_list) {
  var background_color = 'black';
  var position = 'A/5';

  var note = new VF.StaveNote({clef: "treble", keys: [upper_note], duration: "q", auto_stem: true });
  js_note_list.push(note);
  var word = new VF.StaveNote({ clef: "treble", keys: [position],  duration: 'q' });
  js_text_list.push(word);
}

voice_note.addTickables(js_note_list);
voice_text.addTickables(js_text_list);
var formatter = new VF.Formatter().joinVoices([voice_note, voice_text]).format([voice_note, voice_text], 500);
voice_note.draw(ctx, topStaff);
voice_text.draw(ctx, topStaff);
```

which results in the following misalignement:

![two_voices](https://user-images.githubusercontent.com/579771/79079001-87647580-7cc9-11ea-946c-8ac5596ea34c.png)

Am I doing anything wrong or is it a bug?

You may play with it at https://jsfiddle.net/kd9epLh7/

**Comment by 0xfe** [comment]
When you have multiple voices on a single stave, their stem directions should be different: https://jsfiddle.net/wgLt8hef/

**Comment by mscuthbert** [comment]
Wow!  In fact, the first two notes are properly aligned for the uncommon case of multiple voices on the same staff with stem directions going in the same direction -- generally when there are 3 or more voices on the same staff.  (See, for instance, Bach Violin pieces)  Great work whoever implemented it!
