### ISSUE TITLE
alignment issues with new formatter

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#778]
I am having issues when aligning voices in different staves, and the note lengths don't evenly match up:

![formatovf](https://user-images.githubusercontent.com/5438280/79673276-f9dbc680-819d-11ea-99f1-7fcc6bb369a2.png)

If I don't specify the justify width, the overflow doesn't happen but the notes are all scrunched up.  I played around with softmaxFactor but it didn't help this issue very much.  I know what the justify width is supposed to be, but the bounds of the rendered notes end up being way wider than that, whereas before (pre-softmax changes) the notes always fit in the width I specified.

I have a fiddle here:
https://jsfiddle.net/AaronDavidNewman/yrtao9bn/26/

Thanks, love the new fonts btw!

**Comment by 0xfe** [comment]
That's super weird. I'll dig in.

**Comment by 0xfe** [comment]
This was a fun one. All fixed.

**Comment by ramnivas** [comment]
One possibly related question. I modified the fiddle to remove the beams and give the formatter width as `stave.getNoteEndX() - stave.getNoteStartX()`. Now a part of last note goes out of the staff. Is there a way to avoid this?

https://jsfiddle.net/akhcm35b/

**Comment by 0xfe** [comment]
There's no more room for the notes, so this is the expected behavior. The
correct thing to do is to call getMinTotalWidth() to figure out the minimum
possible width for a stave, then draw the stave. (Ideally you'll give the
stave 20 - 50% more room than the minimum width.)

**Comment by ramnivas** [comment]
Thanks for the clarification.
