### ISSUE TITLE
Formatting issues with annotations

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#779]
I'm not sure if this is a bug, but it is definitely different that pre-softmaxFactor .  The actual width of a measure can vary greatly depending on some interaction that I don't understand, possibly between the proportions of the note values and the width of the annotations (I use annotations for lyrics).  

In the jsfiddle example, moving the 'z' from the 3rd word the 5th word causes the actual size of the measure to different by about 25%.  But increasing the measure width by about 2% fixes the issue.

In my application (smoosic) it is a real-time music editor, and it relies on estimates to determine system and page breaks.  The estimates don't have to be exact but I expect them to diverge gracefully.  

![image](https://user-images.githubusercontent.com/5438280/79813978-b8d0e700-8342-11ea-9f17-5c22463fdf1f.png)

Here is a fiddle that demonstrates the problem.
https://jsfiddle.net/AaronDavidNewman/jg8b0vsd/

**Comment by 0xfe** [comment]
This is another weird one. I'll take a look.

**Comment by 0xfe** [comment]
Okay, this should be fixed -- pushing to 3.0.9.

**Comment by AaronDavidNewman** [comment]
crazy fast, thanks!  It looks beautiful.

[image: image.png]
