### ISSUE TITLE
How to use EasyScore with Typescript definitions

### ISSUE THREAD

**Issue by alefz3r0** [0xfe/vexflow#780]
Hi, I have imported typescript definitions from @types/vexflow in my Angular project.

It works fine when using the Vexflow API, but I want to use EasyScore. But EasyScore is simply not defined in typescript definitions.

Am I doing something wrong?

To add some info, the following code works if I don't import typescript definitions, but fails to compile if I import them (Property 'Factory' does not exist on type 'typeof Flow'):

```
const vf = new Vex.Flow.Factory({
  renderer: {elementId: 'vf', width: 500, height: 200}
});

const score = vf.EasyScore();
const system = vf.System();

system.addStave({
  voices: [
    score.voice(score.notes('C#5/q, B4, A4, G#4', {stem: 'up'})),
    score.voice(score.notes('C#4/h, C#4', {stem: 'down'}))
  ]
}).addClef('treble').addTimeSignature('4/4');

vf.draw();
```

**Comment by 0xfe** [comment]
Hi -- I don't maintain the TypeScript definitions, but proper TypeScript support is on my roadmap.

**Comment by eisverticker** [comment]
The types for vexflow are incomplete, if you want to use them you have to fork them and add the missing definitions

**Comment by sschmidTU** [comment]
or add to the DefinitelyTyped definitions as necessary and create a pull request, which [has been done a few times](https://github.com/DefinitelyTyped/DefinitelyTyped/pulls?q=is%3Apr+vexflow).

**Comment by justinfagnani** [comment]
@0xfe how are you imagining proper TypeScript support? Would you be open to porting the project to TypeScript, or are you thinking of maintaining the declarations?

**Comment by 0xfe** [comment]
No plans to port in the near term (hope to in the future), and not maintaining the declarations. For now, I'll let someone else own that. :-)

**Comment by eisverticker** [comment]
@alefz3r0 my merge request was accepted by DefinitelyTyped, I added some more types regarding EasyScore and Flow.Factory, please check if your code works now

**Comment by sschmidTU** [comment]
You can of course always use everything without having definitions, like `(stavenote as any).whatever` or `const stavenote: any = ...`. But adding to the DefinitelyTyped definitions is pretty straightforward.

**Comment by rvilarl** [comment]
@alefz3r0 the library is now ported to TypeScript, @types/vexflow is no longer necessary :)

>No plans to port in the near term (hope to in the future)...

@0xfe you can close this one. The future arrived ;)

**Comment by 0xfe** [comment]
haha 🎉
