### ISSUE TITLE
VexFlow Canvas autoresize for responsive design

### ISSUE THREAD

**Issue by omarcaccia** [0xfe/vexflow#781]
Hi everyone,
is there any way to obtain a canvas that autoresizes for mobile device?
I tried to figure it out with CSS, but the JS definitively ignores my instructions.

PS I don't know JavaScript....

**Comment by 0xfe** [comment]
Hi, Sorry, there's no support for auto resizing -- you'll need to watch for resize events and render your score within the new dimensions.

**Comment by sschmidTU** [comment]
@omarcaccia you need to attach a handle to the window's "onresize" event:
```js
        if ((<any>window).attachEvent) {
            // Support IE<9
            (<any>window).attachEvent("onresize", yourResizeFunction);
        } else {
            window.addEventListener("resize", yourResizeFunction);
        }
```

example here:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/0.7.6/src/OpenSheetMusicDisplay/OpenSheetMusicDisplay.ts#L628
