### ISSUE TITLE
Double dots not working with EasyScore

### ISSUE THREAD

**Issue by alefz3r0** [0xfe/vexflow#782]
Double dot notation is parsing as single dot

Example Fiddle here: https://jsfiddle.net/jf6L38cy/

**Comment by sschmidTU** [comment]
This doesn't render anything for me.
in console:
```console
RuntimeError
code: "IncompleteVoice"
message: "Voice does not have enough notes."
```

**Comment by alefz3r0** [comment]
Exactly, but the measure is complete: C#5/q.., b4/16, B4/q, b4/q

Sum of note durations fits 4/4

The error message comes from the fact that EasyScore parses C#5/q.. as C#5/q.

Instead, the following measure is parsed with no errors: C#5/q.., b4/8, B4/q, b4/q
While in fact it does not fits a 4/4 measure ( https://jsfiddle.net/pwxov2qc/ )

**Comment by alefz3r0** [comment]
Thanks guys
