### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by burnedfaceless** [0xfe/vexflow#788]
These aren't necessarily issues with the software. More questions I had.

1. It said music playback was powered by flash. As I'm sure you know Flash won't be supported much longer. Is there any way for that functionality to be implemented with the HTML5 Canvas?
2. So how are you playing music? Are you generating an XML file? What is this file? Does it convert to MIDI. I have found when I am using professionally recording software the MIDI sounds incredibly real. I don't know if I would need to get another MIDI Engine (if that's what it's even called) that sounds better.

I'm not sure where else to post this question.

**Comment by 0xfe** [comment]
Playback can be implemented with the Web Audio API (or Web MIDI on limited modern browsers.) You don't need flash.

There are a number of JS audio libraries that can load midi wavetables/soundfonts and play them on your browser.

Please use the Vexflow Google Group to ask questions. Thanks. :-)
