### ISSUE TITLE
How to draw only a single note in a system?

### ISSUE THREAD

**Issue by philipp-siegmantel** [0xfe/vexflow#791]
I followed the VexFlow and the Easy Score tutorials, both give me an `IncompleteVoice` `RuntimeError`, when I try to add only a single note. Code is the same as in the tutorials.

**Comment by 0xfe** [comment]
You need to call `setStrict(false)` on the voice to disable the time-signature -> duration checks.

See https://jsfiddle.net/sh8wcu35/
