### ISSUE TITLE
Jazz ornaments/articulations/techniques

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#800]
I need jazz brass ornaments for my own projects, like drops, 'doit', turns etc.  I added them on my own branch and I can merge them into main  if there's any interest.

![image](https://user-images.githubusercontent.com/5438280/87367151-d5467f00-c53f-11ea-9ef7-62a5459ae272.png)

``` javascript
      var mod = new VF.JazzTechnique(VF.JazzTechnique.Type.SCOOP);
    ...
      new VF.StaveNote({ keys, duration }).addModifier(0, mod);
```

**Comment by 0xfe** [comment]
Yes, please add, thanks.

**Comment by AaronDavidNewman** [comment]
This has been merged, closing
