### ISSUE TITLE
'delayed' on ornament doesn't consider startX

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#802]
I noticed this when I was creating jazz ornaments, I wanted to use the same logic for ornaments that occur between 2 notes, e.g. mordant etc.

This fiddle shows the issue, the 2 measures should look the same.  The positioning of the ornament assumes the staff starts at position 0, which would only be true for the first staff in a system.

I have a pull request coming that fixes this with the incorporation of jazz ornaments (e.g 'doit').  So don't fix it ;)

https://jsfiddle.net/AaronDavidNewman/9z2owbh1/

![image](https://user-images.githubusercontent.com/5438280/87886998-d4ea3000-c9e6-11ea-9e53-dabffdde5086.png)

**Comment by 0xfe** [comment]
Good find, thanks. :-)

**Comment by sschmidTU** [comment]
@AaronDavidNewman interesting, delayed ornaments after the system start measure do seem to work in our OSMD demo.
![image](https://user-images.githubusercontent.com/33069673/87937996-23a2d300-ca96-11ea-872e-d2c8af44cd34.png)
https://opensheetmusicdisplay.github.io/demo/
(note that for our releases we're still working with Vexflow 1.2.93, though i've tested this with 3.0.9 as well)

Is it possible that you didn't set something correctly? Just an idea, maybe the ornament position relies on some positioning setting.

Here's our ornament generation code, though i don't think it's that interesting:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/blob/0.8.2/src/MusicalScore/Graphical/VexFlow/VexFlowConverter.ts#L443

But if it works for you with the changes and that doesn't have side effects, that should be fine.

**Comment by AaronDavidNewman** [comment]
@sschmidTU  I can't explain why it works for you :)  I can explain why it does not work in other cases.  The reason is this (original) code:

``` javascript
const nextContext = TickContext.getNextContext(this.note.getTickContext());
        if (nextContext) {
          delayXShift += (nextContext.getX() - glyphX) * 0.5;

```
But glyphX is absolute X, and tickContext is relative X.  I used the stave.x to fix it possibly I could have also used getAbsoluteX of tick context - I'll have to check it if is set there.

**Comment by AaronDavidNewman** [comment]
This has been merged, closing.
