### ISSUE TITLE
How To Build Custom Music Notation Support

### ISSUE THREAD

**Issue by imiskolee** [0xfe/vexflow#803]
Hi, team:

As well as we know Vexflow is a very powerful music nation render platform, but a lot of music notation just working special country(eg: China Numbered Music Notation), so,  can we have a solution for build a custom music notation(s) ?

A simple example of Numbered Music Notation:

![image](https://user-images.githubusercontent.com/4303880/89128256-14f0fd00-d527-11ea-8e97-1e5daf6d40df.png)

**Comment by dmgdwd** [comment]
Do you mean like the Nashville Number System
https://en.wikipedia.org/wiki/Nashville_Number_System

**Comment by imiskolee** [comment]
@dmgdwd Yes.

**Comment by imiskolee** [comment]
Hi,All:

In fact, I am starting working on it, and I planned the below steps:

#1. add new SVG graphics.
#2. create a new Note class like the existed TabNote.

Can you helping any other ideas ?  thanks all.

**Comment by sschmidTU** [comment]
@imiskolee you only need to render text, right? Then can't you just use StaveText?
Or new TimeSignature(), like in MultiMeasureRest?
https://github.com/0xfe/vexflow/blob/master/src/multimeasurerest.js#L218
If you can, then you don't need to create any graphics, i think.
(if the issue is hiding stafflines, then you can probably make them transparent)

**Comment by imiskolee** [comment]
> @imiskolee you only need to render text, right? Then can't you just use StaveText?
> Or new TimeSignature(), like in MultiMeasureRest?
> https://github.com/0xfe/vexflow/blob/master/src/multimeasurerest.js#L218
> If you can, then you don't need to create any graphics, i think.
> (if the issue is hiding stafflines, then you can probably make them transparent)

thanks! i will trying it now.

**Comment by imiskolee** [comment]
hi,all :

I am starting working on it, and already have an ugly demo now, please join us fighter together to make it happen.

![微信图片_20200909011928](https://user-images.githubusercontent.com/4303880/92508608-82393180-f23b-11ea-812b-dac0fe26ec43.png)

**Comment by sschmidTU** [comment]
@imiskolee have you completed your numbered notation implementation? Just curious. Would you share it? A few other Chinese developers have been asking for this.

**Comment by imiskolee** [comment]
@sschmidTU yes, but not very clear now, and I am try to using it on my product,  if any one interest it , please follow https://github.com/imiskolee/vexflow/tree/number-notation/src
