### ISSUE TITLE
User input decides which notes get rendered

### ISSUE THREAD

**Issue by rrosenb12** [0xfe/vexflow#805]
Hi! Maybe I am completely missing something, but I am trying to have the "keys" key in StaveNote be based dynamically on what a user has submitted in a form. Is there a way to make StaveNotes dynamic? In my second code snippet you'll see that I use "null" and a conditional as to what props to pass down; initially I had a conditional statement in my componentDidMount() but ended up getting me nowhere. Additionally, I am able to see the 'hello' in my console.log after submitting the letter in the form, but it then breaks with a runtime error. This is my code that is rendering the stave etc: 

`import Vex from 'vexflow'
import React from 'react'

const VF = Vex.Flow
let context;
let stave;
let div;
let renderer;

```
class Test extends React.Component {

    componentDidMount(){
            div = document.createElement('div')
            div.id = 'div'
            renderer = new VF.Renderer(div, 3)
            renderer.resize(500, 200)
            context = renderer.getContext()
            stave = new VF.Stave(10, 40, 400)
            stave.addClef("treble").addTimeSignature("4/4");
            stave.setContext(context).draw();
            this.refs.outer.appendChild(div)
    }

    componentDidUpdate(){
        div = document.createElement('div')
        div.id = 'div'
        renderer = new VF.Renderer(div, 3)
        renderer.resize(500, 200)
        context = renderer.getContext()
        stave = new VF.Stave(10, 40, 400)
        stave.addClef("treble").addTimeSignature("4/4");
        stave.setContext(context).draw();
        console.log('hello')
        let keys = this.props.note
        let note = new VF.StaveNote({clef: "treble", keys: [`"${keys}/4"`], duration: "q" })
        var voice = new VF.Voice({num_beats: 4,  beat_value: 4}).addTickables(note)
        new VF.Formatter().joinVoices([voice]).format([voice], 150);
        voice.draw(context, stave)
        this.refs.outer.appendChild(div)
    }

    render(){
        return(
            <div ref="outer"></div>
        )
    }

}

export default Test`,
```

and here is my App.js which is rendering the above component (the input form is a simple input, asks for a letter and on submit sends the letter to the app):

```
`import React from 'react';
import './App.css';
import Stave from './Test'
import NoteInput from './NoteInput'

class App extends React.Component {

  state = {
    note: ''
  }

  submitHandler = (note) => {
    this.setState({note: note})
  }

  render() {
    return (
      <div >
        <Stave note={this.state.note === '' ? null : this.state.note}/>
        <NoteInput submitHandler={this.submitHandler}/>
      </div>
    )}
}

export default App;`
```

And here is the error:

`RuntimeError {code: "BadArguments", message: "Invalid key name: "A"}`

**Comment by sschmidTU** [comment]
This is definitely possible.

Did you maybe create a chord (StaveNote) with multiple notes? Then you need to give each note separately, with its octave,
like this:
`keys: ["c/4", "e/4", "g/4"]`

this doesn't work:
`keys: ["a b c/4"]`

[example](https://github.com/0xfe/vexflow/wiki/The-VexFlow-Tutorial) c major chord stavenote:
`new VF.StaveNote({clef: "treble", keys: ["c/4", "e/4", "g/4"], duration: "q" })`

If not, it's not so easy to see what your app does exactly. Can you print the value of keys (this.props.note) when this error happens? And if possible, can you say at which line this error happens?

**Comment by sschmidTU** [comment]
Your line i'm referencing is this one:
`let note = new VF.StaveNote({clef: "treble", keys: [`"${keys}/4"`], duration: "q" })`

**Comment by rrosenb12** [comment]
The input that the user provided was a single note (either a, c, etc.). I'm able to retrieve the note (it is not the best name... should be note instead of keys). When I console.log (this.props.note) I get the correct value. The error isn't actually happening in the code I created but in `node_modiules/vexflow/src/tables.js at line 83.`

**Comment by sschmidTU** [comment]
did you try `keys.toLowerCase()`? It looks like you're giving 'A' instead of 'a'.

**Comment by rrosenb12** [comment]
yes i tried that as well unfortunately

**Comment by sschmidTU** [comment]
Hmm, this is a strange case, your usecase should be pretty simple.

It would be good to know at which line this error happens exactly.
If you can't debug the app, can you try this:

Instead of this line
```js
let note = new VF.StaveNote({clef: "treble", keys: [`"${keys}/4"`], duration: "q" })
```

insert this:
```js
let keyProperties = {
  clef: "treble",
  keys: [`"${keys}/4"`],
  duration: "q"
}
console.dir(keyProperties)
let note = new VF.StaveNote(keyProperties)
console.log("after new StaveNote")
```

This would at least tell us if the error happens in new StaveNote directly, and you can check which keyProperties cause the error and if they're formatted correctly.

**Comment by rvilarl** [comment]
@rrosenb12 @sschmidTU I believe that this can be closed, right?
