### ISSUE TITLE
Purpose of Factory({renderer: {context}})?

### ISSUE THREAD

**Issue by brian-armstrong** [0xfe/vexflow#811]
Hello,

First, thanks for this great library.

What is the intended purpose of `new VF.Factory({renderer: {context}})`? I noticed that factory.js seems to check if it exists but doesn't seem to consume it. If I slightly modify it to instead set `this.context = this.options.renderer.context` when `context` is set, it seems everything works fine.

https://github.com/0xfe/vexflow/blob/master/src/factory.js#L107

I'm curious about this specifically as I'd like to use EasyScore but I'm trying to build the container divs in React with `createRef` which just gives me the DOM element specifically. There is no unique `id` when using this method.

**Comment by rvilarl** [comment]
@0xfe you can close this, context is no longer an attribute of renderer.
