### ISSUE TITLE
Apply scale factor to the rendering?

### ISSUE THREAD

**Issue by NicolasLourenco** [0xfe/vexflow#815]
Hello,
I'm trying to make some things on iOS.
The problem is that 1 point = 3 pixel on iPhone 12 Pro Max for exemple.
So, here's the same code in iPad and iPhone:
| iPhone 12 Pro Max | iPad Pro (12,9') | 
|----------|------|
| ![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-15 at 18 04 52](https://user-images.githubusercontent.com/6010156/99191451-18726200-276d-11eb-99fb-e806503ea961.png) |  ![Simulator Screen Shot - iPad Pro (12 9-inch) (4th generation) - 2020-11-15 at 18 04 51](https://user-images.githubusercontent.com/6010156/99191453-1ad4bc00-276d-11eb-9111-e0cddc822e53.png)|

On the iPad:
- innerWidth = 664 
- innerHeight = 200
- scale factor = 2

On the iPhone:
- innerWidth = 980 
- innerHeight = 505
- scale factor = 3

How I can manage this scale factor?
thanks

**Comment by AaronDavidNewman** [comment]
I think scaling the rendering context is what you want (in svg, set the viewbox/width ratio).  Once you set this, you should be able to remain ignorant of client resolution, afa rendering is concerned.

`vf.context.scale(2,2);`

or:
`renderer.getContext().scale(2,2);`


https://jsfiddle.net/AaronDavidNewman/a4bpz5g0/

**Comment by NicolasLourenco** [comment]
> I think scaling the rendering context is what you want (in svg, set the viewbox/width ratio). Once you set this, you should be able to remain ignorant of client resolution, afa rendering is concerned.
> 
> `vf.context.scale(2,2);`
> 
> or:
> `renderer.getContext().scale(2,2);`
> 
> https://jsfiddle.net/AaronDavidNewman/a4bpz5g0/

Thanks you for your help, but I can't do in this way.
As you can see, the current rendering in iPhone is using all the width available. If I use `vf.context.scale(2,2);` it will zoom in and the end of the stave will not be rendered.

**_EDIT:_ It works**, what I've done is to continue to use the entire width (innerWidth), but with a limit in stave (`const stave = new VF.Stave(0, 0, scoreWidth);`)

<img src="https://user-images.githubusercontent.com/6010156/99196343-18358f00-278c-11eb-9793-688c44e93532.png" alt="alt text" width="200">
