### ISSUE TITLE
VF.ChordSymbol is not a constructor

### ISSUE THREAD

**Issue by martijnmichel** [0xfe/vexflow#822]
Hi Guys! 
Awesome library you have. I want to start using it in my app Sonid. But when testing I have an error which I find kind of odd.

If i try this snippet (https://jsfiddle.net/AaronDavidNewman/bpg6ow3n/) i get the above error. Using VexFlow 3.0.9. 

Looking at a console.log(Vex.Flow) I see there is no class for ChordSymbol, are you guys sure you've included it in the latest release?

**Comment by sschmidTU** [comment]
Yes, the ChordSymbol export was missing in 3.0.9 in `index.js`.
It's there now:
https://github.com/0xfe/vexflow/blob/master/src/index.js#L111

3.0.9 where the ChordSymbol export should be:
https://github.com/0xfe/vexflow/blob/3.0.9/src/index.js#L105

This would be solved by releasing a new version.

**Comment by martijnmichel** [comment]
Thanks! So how can I use it until the new release comes out? :))

**Comment by sschmidTU** [comment]
You probably need to replace the vexflow min.js you're using.
You could checkout this repository (master branch) and run `npm install` and `npm start` to find the builds in `/build/`.
The current master build will be this, you don't need the .map file if you don't want to debug vexflow.
[vexflow-master-build-min-20201217.zip](https://github.com/0xfe/vexflow/files/5711620/vexflow-master-build-min-20201217.zip)
You can either trust this build or build it yourself ;)

**Comment by martijnmichel** [comment]
Ok and when is the release with ChordSymbol included?

**Comment by martijnmichel** [comment]
Actually, when I replace the vexflow-min.js in node_modules, I still get the same error. Though there are references in the file to ChordSymbol...

**Comment by martijnmichel** [comment]
ok, thanks. I've just loaded the vexflow-min.js another way and it works. But, any estimate on a new release?

**Comment by Orabig** [comment]
In my project, I have the same issue, and can't fix it.
I do have my own fork of vexflow, which is directly referenced by another nodejs project (a fork of markdown-it-music).
I did delete package-lock.json, re-installed the project, but still have the issue.
What did I forget ? :(

**Comment by AaronDavidNewman** [comment]
The release directory is not updated automatically on a build.  So if you are using your own fork, you will need to copy the build directory to the release (or reference the build version directly).

**Comment by Orabig** [comment]
Thanks for the fast answer, but I don't know how to do that.
The only way I figured out how to have a working reference on my own fork is to do : 

`const Vex = require('vexflow').default; // Remove .default when vexflow is updated : see https://github.com/0xfe/vexflow/issues/822`

But I guess this is horrible. (and I get a weird error later : `TypeError: chordSymbol.setHorizontalJustification is not a function
    at Factory.ChordSymbol (factory.js:318)`)

**Comment by Orabig** [comment]
Actually, it looks like in the latest commit (656be044ae21053c32b2704b6c6fc7e26633f2fa) Factory is using ChordSymbol.setHorizontalJustification() method, but ChordSymbol class only defines setHorizontal().
Wut ?

**Comment by Orabig** [comment]
finally made it work by fixing https://github.com/0xfe/vexflow/blob/master/src/factory.js#L318 with

```
    chordSymbol.setHorizontal(params.hJustify);
    chordSymbol.setVertical(params.vJustify);
```

Is it possible that this code is broken since May 2nd 2020 ? (your commit 284dd67a3565869562bef0697ff0980d7dc3c25c @AaronDavidNewman )

**Comment by AaronDavidNewman** [comment]
No, I think it was always broken :(  Good catch though.  I don't use the factory in my unit test cases, which I should have.  I have a pull request out and I'll add it to that.

**Comment by AaronDavidNewman** [comment]
This was fixed in a Feb. 18th merge.  It can be closed.

**Comment by rvilarl** [comment]
@0xfe this one can be closed
