### ISSUE TITLE
How or When vexflow support drawing note-type 1024th and 512th

### ISSUE THREAD

**Issue by kubo0212monsterpixel** [0xfe/vexflow#824]
I checked source code and running test view but I cannot see any note kinds of type 512th or 1024th like below. Will we support that?
![image](https://user-images.githubusercontent.com/34226751/102739936-08a7f800-4381-11eb-925f-bdbe05d7b6ff.png)

**Comment by ronyeh** [comment]
Not currently in the roadmap. If you submit a PR for 1024th notes, we'll definitely take a look.
