### ISSUE TITLE
Alignment of chords

### ISSUE THREAD

**Issue by martijnmichel** [0xfe/vexflow#825]
Hi guys!
Awesome library. I've started implementing this in my app Sonid (with which you can learn music theory).

There is something that bugs me: chord symbols seem to be aligned depending on how long the text of it is.

I've made some screenshots to be more clear.
https://ibb.co/8jYvDPC
https://ibb.co/KVhWnWN

Any chance this can be fixed? :)

**Comment by AaronDavidNewman** [comment]
Did you try using center alignment?  The default is left.  Over notes they tend to be left-aligned with the center of the note, but over rests since there is no stem or note head, it looks more left-aligned to the right side of the rest, which looks kind of funny.  If you make a fiddle I'll look at it.

**Comment by martijnmichel** [comment]
Will try that tomorrow, thanks!

**Comment by martijnmichel** [comment]
I can only find about vertical alignment in the wiki... https://github.com/0xfe/vexflow/wiki/Chord-Symbols-and-Chord-Changes#chord-symbol-position

**Comment by AaronDavidNewman** [comment]
I see, try `setReportWidth(false)` (also not in the wiki).  This will cause the formatter to report 0 width for the symbol, so vex won't consider it when formatting the measure.

**Comment by martijnmichel** [comment]
where would I do this?

**Comment by sschmidTU** [comment]
> try `setReportWidth(false)`

@AaronDavidNewman `setReportWidth` or `reportWidth` doesn't exist in the Vexflow code base (ignoring case).
There's reportedWidth, but that's only used in the Ornament class.

**Comment by AaronDavidNewman** [comment]
Sorry, I missed this thread over Christmas.
@sschmidTU you are right!  But it should, I guess it is only on my branch and I never pushed it to main.  I also added this method to annotation (I use annotations for lyrics in smoosic). 

I meant to do this as part of adding textFont.  This is on https://github.com/AaronDavidNewman/vexflow_smoosic/tree/master/src.  I will add it to my vex branch and create a pull request for it.

**Comment by AaronDavidNewman** [comment]
This is submitted in https://github.com/0xfe/vexflow/pull/831 if you want to pull it early.

**Comment by AaronDavidNewman** [comment]
@martijnmichel  have you tried justifying the measures?  That works, even without the reportWidth feature.

![image](https://user-images.githubusercontent.com/5438280/105282145-4ca23e80-5b73-11eb-8119-ad48152bba90.png)

Here is a fiddle that shows justification, you just format the voices from different staves using the same formatter, 
https://jsfiddle.net/AaronDavidNewman/yrtao9bn/26/

**Comment by martijnmichel** [comment]
Thanks, that works! :)

**Comment by rvilarl** [comment]
@0xfe this issue can be closed
