### ISSUE TITLE
Add support for drawing lines

### ISSUE THREAD

**Issue by floka94** [0xfe/vexflow#828]
VexFlow does not support to add lines below or above the notes. See this example:

![image](https://user-images.githubusercontent.com/29139420/104808823-02befe80-57e9-11eb-865d-c6adf45250c0.png)

In MusicXML i can draw such lines with the following tag:
_Start of a line:_
```
      <direction placement="below">
        <direction-type>
          <bracket type="start" number="1" line-end="none" line-type="solid" default-y="-69.20"/>
          </direction-type>
        </direction>
```
_End of a line:_

```
      <direction placement="below">
        <direction-type>
          <bracket type="stop" number="1" line-end="none"/>
          </direction-type>
        </direction>
```

If vexflow supports to draw such lines, it would be possible to add this feature in the [opensheetmusicdisplay](https://github.com/opensheetmusicdisplay/opensheetmusicdisplay) project, to generate the intended sheet of music with lines.

**Comment by sschmidTU** [comment]
Actually vexflow does support this:
```js
ctx.beginPath();
ctx.moveTo(start.x, start.y);
ctx.lineTo(stop.x, stop.y);
ctx.lineWidth = lineWidth;
ctx.stroke();
```

I'm pretty sure I also wrote this in the OSMD issue:
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/issues/940

**Comment by rvilarl** [comment]
@0xfe this one can be closed
