### ISSUE TITLE
VexTab not showig # corectly 

### ISSUE THREAD

**Issue by Aduffy** [0xfe/vexflow#834]
Im trying to render a simple G Major scale with VexTab, but if i set the Key to G, (one sharp = F#) than I do NOT get the sharp symbol 

```
options width=600
tabstave notation=true key=G time=4/4
notes :16 =|:  3/6 5/6 7/6 3/5 5/5 7/5 4/4 5/4 7/4 4/3 5/3 7/3 5/2 7/2 8/2 5/1 
```
<img width="738" alt="Screen Shot 2021-01-24 at 12 52 12 PM" src="https://user-images.githubusercontent.com/265857/105643270-b5bfd580-5e43-11eb-889c-15feaeaaf502.png">

If i leave out the key=G from my notation than the # renders correctly 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/265857/105643302-ebfd5500-5e43-11eb-8529-7dcab09204a2.png">

**Comment by sschmidTU** [comment]
The general convention in music is that if the key signature (G) includes the accidental (the # in F#), it is not printed again before each note that has the accidental (F#).
If you still want to render the accidental for pedagogic purposes (courtesy accidental), you have to do that deliberately.
I'm not sure if that's possible in VexTab, but in VexFlow it's something like this:
`vfnote.addAccidental(0, new Vex.Flow.Accidental("#"))`

**Comment by Aduffy** [comment]
Ah! Thanks for the info Simon.
