### ISSUE TITLE
Style bleeding from Clef into 

### ISSUE THREAD

**Issue by clemens-tolboom** [0xfe/vexflow#836]
Trying to swap colors black versus white we tried

```js
      var clef = vf.Stave().addClef('treble');
      clef.setStyle({ fillStyle: 'red', strokeStyle: 'red' });
```

which resulted in a red lines but no red Clef when changed in `tests/clef_tests.js` lines 37,38

![image](https://user-images.githubusercontent.com/371014/107883639-5576fd80-6ef0-11eb-9fcb-14ad705d25c4.png)

How can we fix this?

**Comment by AaronDavidNewman** [comment]
If you want to make it all red, add this:
``` javascript
    this.stave.context.setFillStyle('#f00')
```
If you want the clef (which is not same as staff btw) to be a different color than other things,  It looks like there is no way to do that.  It would be easy enough to add by wrapping clef.js draw method in context.createGroup/context.closeGroup.

**Comment by clemens-tolboom** [comment]
Thanks for the workaround 👍 and the PR hint. If time permits I'll try create a PR

> the clef (which is not same as staff btw)
Not sure what you mean but I just copied code from within the test.

**Comment by AaronDavidNewman** [comment]
>> the clef (which is not same as staff btw)

Right, sorry if that sounded snarky.  VF.Clef is the modifier that you would change if you wanted the clef symbol to be different, and VF.Stave draws the staff lines and clef together.  But you get that :)

Now that I'm looking at it, it is unintuitive that your original code didn't work.  Element.setStyle and Element.applyStyle do different things, I'm not sure why.

**Comment by clemens-tolboom** [comment]
### Fill and Stroke

I can confirm both `context`s works

```js
    var clef = vf.Stave().addClef('treble');
    clef.context.setFillStyle('#0f0');

    vf.context.setFillStyle('white');
    vf.context.setStrokeStyle('white');
```

### Background

Manual set global background was not enough as some sub div gets **white**.

```css
#vexflow_testoutput {
	background-color: black;
}
/* stunn this white manually*/
div.testcanvas .vex-tabdiv {
	/* background: white; */
}
```

### Result

![image](https://user-images.githubusercontent.com/371014/107967171-1490ee80-6fad-11eb-87ed-1180b6fb2799.png)

**Comment by AaronDavidNewman** [comment]
That makes sense. `stave.setStyle`, only affects the stave lines, `stave.context.setStyle` only affects modifiers (ends, clef, time signature).  I thought that was a bug, but I see the logic behind it - we like grey lines but we want the clef to be same color as notes.

>> Manual set global background was not enough 

Any context changes apply the style directly to PATH element, so you won't be able to override that with css, no matter what 
you do.  So my PR suggestion isn't quite right.  If you wanted to style each staff modifier differently, you'd need to apply that at the 'draw' level of each element (clef, time signature, etc).  If what you've got is what you want, then I think that's the right solution 👍 

![image](https://user-images.githubusercontent.com/5438280/107972593-b1399900-6f79-11eb-8c1e-fd4a783cc163.png)

**Comment by clemens-tolboom** [comment]
If have to check back with my designer soon :)

**Comment by rvilarl** [comment]
I have decided to document this topic within the api. There I have also documented the possibiliy to use drawWithStyle:
```typescript
element.setStyle({ fillStyle: 'red', strokeStyle: 'red' });
element.drawWithStyle();
 ```
