### ISSUE TITLE
FontStack not doing what I expect

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#837]
I was playing around with a new Smufl font called Leland (from the MuseScore people).  It only has about 350+ glyphs atm, so it is missing quite a bit.  When I try to use diminished chord symbols for instance I get this;

![image](https://user-images.githubusercontent.com/5438280/107889743-42593300-6eda-11eb-8c11-acd34d085916.png)

I thought the point of fontstack was to look in other fonts, if a glyph doesn't appear in the chosen font, and get the font from the next one in the list.  (Edit: my font stack in this example is Leland, Gonville, Bravura, Custom).  Clearly this is not happening.  So my question is:
1. Is this something that the individual modules (e.g. chord symbol, ornament) are supposed to do at draw() time?  or 
2. is there some way to specify this in the font itself, or
3. some other way?

**Comment by 0xfe** [comment]
It should look in the other fonts, how did you configure the stack?

Also, did you follow [the instructions here](https://github.com/0xfe/vexflow/wiki/VexFlow-Font-Rendering) while adding support for Leland?

Also, is this in anyway related to your `TextFont` changes?

**Comment by AaronDavidNewman** [comment]
Ah, I see my error.  I just copied the Bravura codes, I need to remove the ones that don't apply.  In the past I've only added glyphs to existing fonts.

And no, it is not part of TextFont, I was just curious to see what the font looked like after watching this [video](https://www.youtube.com/watch?v=XGo4PJd1lng&t=991s).  I don't think it is worth considering Leland for the main vex branch until it is a little more complete.   

I will close this since there is no issue, although maybe I can add this note to the wiki linked above.

**Comment by AaronDavidNewman** [comment]
Actually, I think a small change is needed in smufl_fontgen.js.  The logic skips a glyph if the glyphnames.json doesn't contain it.  But it should also skip glyphs in valid_codes that aren't in the font file itself.  

``` javascript
  const code = glyphCode.codepoint.substring(2);
  const intCode = String.fromCodePoint(parseInt(code, 16));
  const testGlyph = font.charToGlyphIndex(intCode);
  // skip codes not in font file.
  if (testGlyph === 0) {
    console.log('No glyph for  ' + k);
  } else {
    const glyph = font.charToGlyph(intCode);
    fontData[k] = toVFPath(glyph);
  }
```
If I add this logic, the script correctly generates only 'real' glyphs.

btw if you're curious about the appeal of Leland - bigger black dots :) and slightly more streamlined artifacts like clef symbols.

Leland:
![image](https://user-images.githubusercontent.com/5438280/107985787-611a0100-6f90-11eb-9a31-a06827b88bc0.png)
Bravura:
![image](https://user-images.githubusercontent.com/5438280/107985767-565f6c00-6f90-11eb-9d53-db2dc3f63914.png)
Gonville:
![image](https://user-images.githubusercontent.com/5438280/107985937-b0f8c800-6f90-11eb-9e43-a9eec28439cd.png)

**Comment by AaronDavidNewman** [comment]
This pull request has been added so I'm closing this.
