### ISSUE TITLE
how to display the musical notes one by one ?

### ISSUE THREAD

**Issue by Sguitch** [0xfe/vexflow#841]
Hello, 
I just discovered vexflow. I looked at all the tutorials but I couldn't find how to add the notes one by one to the staff. I have a virtual accordion keyboard and I want each key pressed to display the corresponding solfeggio note on the staff. I used the function 
--------------------------------------------------------------------------------------------
"function writeNote (pitch, rhythm) { 
 document.getElementById ('score'); // add additional if statements to include more rhythmic options if (rhythm === '/ 8') { score.set ({time: "1/8"}) } else if (rhythm === '/ q') { score.set ({time: "1/4"}); } else if (rhythm === '/ h') { score.set ({time: "1/2"}); } system.addStave ({ voices: [score.voice (score.notes (pitch + rhythm))] }). addClef ('treble'); vf.draw (); } " 
----------------------------------------------------------------------------------------------
 I get the 1st note, but I cannot display other notes. It seems that each time vexflow expects the number of notes for a measure (4 in my case). If so, is there a solution and if so thanks for your help. 
Cordially 
Guy

**Comment by AaronDavidNewman** [comment]
If what you want is to put fewer notes than the time signature calls for, you want 'soft' voice mode.  You will need to fully re-render the measure to update it after every addition.

``` javascript
 const voice = new VF.Voice({
        num_beats: 4,
        beat_value: 4
      }).setMode(VF.Voice.Mode.SOFT);
```

**Comment by Sguitch** [comment]
It works very well. I can continue to progress thanks to you
