### ISSUE TITLE
formatter.joinVoices is different if called multiple times with multiple voices.

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#842]
``` javascript
formatter.joinVoices([voice1]);
formatter.joinVoices([voice2]);
```

Does something different than:

``` javascript
formatter.joinVoices([voice1, voice2]);
```
The fiddles show the issue.  It seems the single call is the one that is not behaving correctly, but I'm not sure what the intent was.  
Once difference I see in the code is that, with 2 calls, each tickable at the same location is added to a different modifierContext.  I'm not sure if that is causing the issue, though.

https://jsfiddle.net/AaronDavidNewman/3w1x76m0/
https://jsfiddle.net/AaronDavidNewman/mgfaLxcr/

1 join:

![image](https://user-images.githubusercontent.com/5438280/109427596-a7238b80-79b8-11eb-91ec-fd8ce12a9df4.png)

2 joins:

![image](https://user-images.githubusercontent.com/5438280/109427609-b73b6b00-79b8-11eb-822c-0d1603c405d6.png)

**Comment by rvilarl** [comment]
> ```js
> formatter.joinVoices([voice1]);
> formatter.joinVoices([voice2]);
> ```
> 
> Does something different than:
> 
> ```js
> formatter.joinVoices([voice1, voice2]);
> ```

@AaronDavidNewman I believe that one combined join should be used to render both voices in the same stave and two joins to render each voice on a different stave.

**Comment by AaronDavidNewman** [comment]
Ah...so it was pilot error.  Thanks.  We should have a wiki just about vertical alignment.  It gets raised in an issue every so often, and someone answers it and we close it.

**Comment by 0xfe** [comment]
Thanks folks -- this is described in the [FAQ](https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#formatting) -- but feel free to expand on it if it's not clear enough.
