### ISSUE TITLE
auto beam with dot note

### ISSUE THREAD

**Issue by imiskolee** [0xfe/vexflow#844]
Hi,all:

i am not sure the current version supports dot note for beam.
eg:
```
{
  note1.duration = 8
  note1.dots = 1
  note2.duration = 16
}
```

**Comment by rvilarl** [comment]
@0xfe if I understand correctly the question, the answer is yes and this can be closed.

![image](https://user-images.githubusercontent.com/22865285/137541755-df0ef62c-b208-49d8-8d34-60bc01f2c9b9.png)
