### ISSUE TITLE
How can I improve my code which seems poorly constructed?

### ISSUE THREAD

**Issue by Sguitch** [0xfe/vexflow#847]
Hello,
 I'm simulating an accordion keyboard with a button in the HTML code and a "note" note table in the JS part. With each click on the button I add a note in the staff and after 16 notes, a new staff is added below and so on. The code works fine but I have to remove the context each time for each addition of a note (see resetContext function). And also every time I add a scope I have to add a div (see creDiv function) otherwise I delete the previous scope. I think that I am complicating things and that something escaped me in the understanding of vexflow but I do not see. Thank you for enlightening me and suggesting your possible improvements.

You can see the code here --->https://jsfiddle.net/Guy44/68ghLuoj/7/

cordially
Guy

**Comment by AaronDavidNewman** [comment]
It is not you.  There is no easy way to do what you are trying to do.  

You don't have to reset the whole context though - you can remove the measures.  In smoosic I go:

``` javascript
  const group = context.openGroup();
  group.id = 'measure-1';
  // draw the measure ...
  context.closeGroup();
```

Then you can getElementById on the group, remove it, and re-render the measure in the same spot.  The issue there is calculating the dimensions of the measure - if your music takes up more room, it will run into the other measures, and they will need to be drawn, etc.  So if this is an interactive application, you probably want to allocate some extra space, and when that runs out, re-render the whole score.  That's essentially how I do it.

**Comment by Sguitch** [comment]
I will try to follow your advice
Thank you

**Comment by rvilarl** [comment]
@0xfe this one can be closed
