### ISSUE TITLE
'isValidIntervalValue' does not allow the interval `octave` (interval=12)

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#853]
Using the comparison from note will not allow the interval `octave`

_Originally posted by @rvilarl in https://github.com/0xfe/vexflow/pull/851#discussion_r594550434_

**Comment by rvilarl** [comment]
Details:
https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L178-L179
calls
https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L171-L173
which will return false with 12,https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L9
the value of octave
https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L100

**Comment by rvilarl** [comment]
I propose use the approach below to check the correct ranges, rather than the functions `IsValidNoteValue` and `IsValidIntervalValue`, and delete them.
https://github.com/0xfe/vexflow/blob/5eb92750f65fe07d6115073d8e3be1a8fa2c191c/src/music.js#L238-L245

**Comment by rvilarl** [comment]
@0xfe @mscuthbert would you agree that this is a bug? would you agree with my proposal above to remove the two functions? I would add those changes to the **airbnb** PR for **music** / **music_test**

**Comment by rvilarl** [comment]
@0xfe @mscuthbert I have learnt in #856 that we do not want to change the interface. I will not remove the functions.
Should I make a PR to resolve the bug on IsValidIntervalValue, as I wrote in the title, interval 12 should be allowed.

**Comment by 0xfe** [comment]
Thanks for filing this @rvilarl. Right now there's a bunch of changes going on, and I don't want to muddy the waters too much. Let's come back to this when we're a bit more stable on the TS side of things.

**Comment by rvilarl** [comment]
Added to #865
