### ISSUE TITLE
What symbols used for the duration of the notes ?

### ISSUE THREAD

**Issue by Sguitch** [0xfe/vexflow#854]
Hello,
I would like to use easyscore (example code below). Do you know where I could find the information regarding the duration of the notes (like / q in the example)

`// Create an SVG renderer and attach it to the DIV element named "boo".
var vf = new Vex.Flow.Factory({renderer: {elementId: 'div0'}});
var score = vf.EasyScore();
var system = vf.System();
system.addStave({
    voices: [score.voice(score.notes('C#5/q, B4, A4, G#4'))]
  }).addClef('treble').addTimeSignature('4/4');
  
vf.draw();`

**Comment by Sguitch** [comment]
I actually found it. We can use the numerical notation like the following example:
`voices: [score.voice (score.notes ('c6 / 4, B4 / 8, A4 / 8, C5 / 8, A4 / 8, C5 / 4'))]
}). addClef ('treble'). addTimeSignature ('4/4');`

But, I did not find for the silences and therefore if you can enlighten me on the subject.
Thank you

**Comment by sschmidTU** [comment]
With "silences", do you mean rest notes? Just add an "r", like this:
```js
score.voice(score.notes(
        'c5/16, g5, c5, c5/r, c5/r, (c4 e4 g4), d4, a5, c4, g4, c5, b4/r, (c4 e4), b4/r, b4/r, a4'
      ), { time: '4/4' });
```
I assume `b4 / 4r` also works.

**Comment by Sguitch** [comment]
Yes thanks !
