### ISSUE TITLE
Compile tests with typescript instead of concatinating

### ISSUE THREAD

**Issue by wassertim** [0xfe/vexflow#858]
In order to prepare tests to typescript migration we have to compile existing javascript files with typescript compiler

**Comment by wassertim** [comment]
I'm preparing a PR with this change. It depends on this PR https://github.com/0xfe/vexflow/pull/857 though

**Comment by 0xfe** [comment]
Good idea, created label. Not sure what you mean by "invite you as contributor" -- I think you're already one! :-)

**Comment by wassertim** [comment]
> Good idea, created label. Not sure what you mean by "invite you as contributor" -- I think you're already one! :-)

No, I'm just a guy with a fork of this repository. Would be nice to have a right for creating branches directly here, without updating the upstream and eventually create labels too :) Maybe I want too much

**Comment by 0xfe** [comment]
Gotcha -- Vexflow is a 10-year-old project with just 3 collaborators, and I try to keep that small. My criteria has been:

1) you have a long history of Vexflow contributions in many areas, and demonstrated sound technical judgement, and,
2) you are a stakeholder, i.e., you have things built with Vexflow, are you are thereby incentivized to keep Vexflow healthy, and,
3) you're generally kind and respectful, and music is a significant part of your life

I think you have some of these, but the "history of contributions" and "stakeholder" are really important to me. :-)

**Comment by rvilarl** [comment]
By the way I have my app built with Vexflow https://michaelecke.com/pianoplay :) This is why I arrived here.

**Comment by rvilarl** [comment]
@0xfe @wassertim I think this topic is closed

**Comment by rvilarl** [comment]
@0xfe you can close this
