### ISSUE TITLE
Avoid unsuccessful checks on PRs

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#859]
![image](https://user-images.githubusercontent.com/22865285/112712040-09df4880-8ecd-11eb-8be7-4ff1e295fccf.png)

**Comment by rvilarl** [comment]
Problem description:
1) npm test requires releases/vexflow-debug.js to be part of the commit.
2) it is not wished to have releases files in the PR

As a consequence PRs are being merged with failed checks (see red x)
![image](https://user-images.githubusercontent.com/22865285/112712139-c46f4b00-8ecd-11eb-9b48-dc7da1eb1bd3.png)

**Comment by rvilarl** [comment]
Proposed solution:
In order to address 1, package.json could be changed to generate the required file.
In order to address 2, .gitignore could be changed to config the exclusion of the releases directory.

Then @0xfe can decide when to add the releases in the repository. The files can be added even if they are in .gitignore.

**Comment by 0xfe** [comment]
`npm test` generates `releases/vexflow-debug.js` so it doesn't need to be part of the commit. It's usually added as part of `grunt publish` step while publishing a new version.

**Comment by 0xfe** [comment]
Looks like there's some other bug causing unsuccessful checks.

**Comment by rvilarl** [comment]
@0xfe what is the command in test (see below) generating `releases/vexflow-debug.js` ?

`"test": "npm run lint && npm run qunit && npm run generate && npm run diff"`

**Comment by 0xfe** [comment]
It's `qunit`, which requires `vexflow-debug.js`.

**Comment by rvilarl** [comment]
This one is generating `build/vexflow-debug.js` but it is not doing the copy on the `releases` folder.

`grunt.registerTask('test', 'Run qunit tests.', ['clean', 'webpack:buildDev', 'concat', 'qunit']);`

and for some reason the file is also required there to pass the tests.

I believe `'copy:release'` is missing on `qunit

**Comment by 0xfe** [comment]
I don't think that's why it's failing. It seems like it's an unhandled promise rejection: https://github.com/0xfe/vexflow/runs/2203535964#step:5:59

This may be beacause of the petalumascript web font that (I think) @AaronDavidNewman added. I'm seeing this in the terminal logs:

```
Failed to decode downloaded font: file:///Users/mmuthanna/git/vexflow/releases/fonts/petalumascript-webfont.woff2
OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
```

@AaronDavidNewman , can you look into that when you have a moment please?

**Comment by rvilarl** [comment]
@0xfe you were right 'copy:release' did not solve the problem. 

I assumed wrongly that this was the only significant difference when I solved the problem with 3ef74e86c128edc82b091f369e24d7761a2cec3f on the last PR. There must be other significant differences between `npm run lint && npm run qunit` and `npm run start`

@AaronDavidNewman FYI

**Comment by AaronDavidNewman** [comment]
I'm not sure exactly what I'm looking for.  Are you thinking the message about the petaluma font is causing the error later on?

```
 > vexflow@3.0.9 diff C:\Users\Daddy\Documents\GitHub\vextest\vexflow
> ./tools/visual_regression.sh

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vexflow@3.0.9 diff: `./tools/visual_regression.sh`
npm ERR! Exit status 1
``` 

I will try to solve the issue with the Petaluma font, maybe by loading it remotely, and see if the scripts still fail.  It's not obvious to me what the actual failure is.  I see the fail message you mention, but then I also see this:
```
.......................................OK
>> 1392 tests completed with 0 failed, 0 skipped, and 0 todo.
>> 6113 assertions (in 34478ms), passed: 6113, failed: 0
```
so I'm thinking maybe the real error happens later?  If the font couldn't be loaded, it would just fall back to something and soldier on. 

I see lots of these during the visual regression tests, also:
```
StaveTie :: No End Note
(process:15916): Pango-WARNING **: 14:54:25.109: couldn't load font "sans serif Not-Rotated 10px", falling back to "Sans Not-Rotated 10px", expect ugly output.
```

**Comment by AaronDavidNewman** [comment]
Oh, I bet I need to run this on a mac, don't I

**Comment by rvilarl** [comment]
I run it on linux

**Comment by AaronDavidNewman** [comment]
Update: I replaced the css font reference to my github project cdn.   It fixes the message generated by the test.  If it also turns out to fix the CI error, then we can decide what to do next - either push it, or maybe I'll just substitute it for a google webfont.  

I'd be a little surprised if it did, it seems this error predated my latest merge, and that reference has been in there a long time.  Honestly, I have no idea what that error is about.  Everything succeeds when I run it locally, despite the font message.

**Comment by rvilarl** [comment]
@0xfe @AaronDavidNewman looking into the failure I saw that the module `puppeteer` which was failing was quite outdated. I decided to update the packages.json in 7dd9284 and the tests are now running successfully in the PR #861
I also removed the outdated package `jscs` which was merged into `eslint`.

**Comment by rvilarl** [comment]
I left two files outdated so as not to break dependencies from `grunt-git` and `grunt-webpack`, probably it would make sense to ignore the `grunt-webpack` and update `webpack`
 
`[rodrigo@localhost vexflow]$ npm outdated
Package  Current  Wanted  Latest  Location                           Depended by
grunt        1.0.4      1.3.0      1.3.0    node_modules/grunt        vexflow
webpack  4.46.0    4.46.0    5.28.0  node_modules/webpack  vexflow`

**Comment by 0xfe** [comment]
That's awesome, thanks for addressing. @rvilarl, let's push that fix in first (before the fraction/tuning changes.)

**Comment by rvilarl** [comment]
I will do later today. I would also recommend to add the releases directory and package-lock.json to .gitignore
