### ISSUE TITLE
joinVoices parameters

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#860]
Inconsistent usage of joinVoices in formatter.js

**Comment by rvilarl** [comment]
In the typescript migration I have identified the following issue joinVoices is called with two parameters in:

https://github.com/0xfe/vexflow/blob/dbef7a746071671ca6a840f79d1f62144edce512/src/formatter.js#L220
https://github.com/0xfe/vexflow/blob/dbef7a746071671ca6a840f79d1f62144edce512/src/formatter.js#L267

however it is defined with only one parameter:

https://github.com/0xfe/vexflow/blob/dbef7a746071671ca6a840f79d1f62144edce512/src/formatter.js#L798

**Comment by 0xfe** [comment]
Good catch. The bug is in the usage on lines 220 and 267, you can remove it from there.
