### ISSUE TITLE
How to debug typescript

### ISSUE THREAD

**Issue by AaronDavidNewman** [0xfe/vexflow#862]
Second Edit:
I am getting this on _all_ javascript files also, not just the .ts.  So maybe there is some configuration change?  In other words, I see the webpack output for all javascript under /src, not just the .ts files.  Files under /tests still look like javascript (from the source map).

I am cheering you guys on in your typescript conversion!  And I'm sorry for bringing up a question that does not directly relate to Vex.  I am apparently one of the few web developers who has never used Angular and so I am just learning ts.

When I open music.ts, I see the output of webpack.  I know I've seen other screenshots of people with TS highlighting, public/interface and all that.  How do we get that?   Do we need to install Visual Studio Code?  That is where all the TS question about angular lead.  Is there some Chrome add-on?

If I can figure it out, I will add it to the wiki so other TS newbs won't have to ask the same question.

Edit: I should mention that I am generating the debug build so I have a source map.  The .ts shows up in the sidebar but I see the transpiled .js.

![image](https://user-images.githubusercontent.com/5438280/112757259-97df3000-8fae-11eb-8dc1-ea9acdc63f5c.png)
![image](https://user-images.githubusercontent.com/5438280/112757492-864a5800-8faf-11eb-84d7-03a42551fb94.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman good hint! I did not have to debug the migration. 
I believe it is required to set 

`"sourceMap": true`

under `CompilerOptions` in `tsconfig.json`

We will look into that

@wassertim FYI

**Comment by rvilarl** [comment]
@AaronDavidNewman @0xfe I will also make a minor PR fixing this one

@wassertim FYI

**Comment by sschmidTU** [comment]
@AaronDavidNewman  VSCode definitely has good typescript support.
There is an extension `Debugger for Chrome` that we use to debug our project OSMD (which uses Vexflow), and it works pretty well. (occasionally breakpoints don't register, usually unregistering and registering them again works)
https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome

**Comment by rvilarl** [comment]
@sschmidTU @AaronDavidNewman it is now working also in Chrome with #864. I agree with Simon the Debugger for Chrome was very well I have used it with OSMD as well.

PD: Simon please do not forget my PR :)
