### ISSUE TITLE
Typescript migration: Collection of issues

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#865]
TODO list on topics identified in the migration

**Comment by rvilarl** [comment]
**music.ts**
* [ ]  bug: 'isValidIntervalValue' does not `interval=12` which is a valid one
* [ ]  feature: add  missing scales: Ionian, Phyrgian, Lydian, Aeolian and Locrian
* [ ]  style: comments of function missing
* [ ]  style: refactor `NoteParts`as `NoteParts` & `KeyParts`

**Comment by rvilarl** [comment]
**tuning.ts**
* [ ]  style: delete ´tuningStrings´ (it is not used)
* [ ]  style: replace ´numStrings´ with ´tuningValues.length´

**Comment by rvilarl** [comment]
**Gruntfile.js**
* [ ] Tech Debt: remove -node.js file once the migration is complete

**Comment by wassertim** [comment]
👍

**Comment by rvilarl** [comment]
list completed

**Comment by 0xfe** [comment]
Yay!!!!
