### ISSUE TITLE
Typescript migration: formatter refactoring

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#867]
I have been working already in the class formatter. I have special interest to get this class in TypeScript in order to identify the formatting problems in 3.0.x when compared to 1.2.x

**Comment by rvilarl** [comment]
First problem identified:
`TickContext` extends `Tickable`
`ModifierContext` does not extend any other class

they have no class parent in common however we have a function 
`function createContexts(voices, ContextType, addToContext)`
returning either `TickContext` or `ModifierContext` depending on `ContextType`

This function is then only used twice once in:
`CreateModifierContext`
and once in:
`CreateTickContext`

My proposal is to remove `createContext` and include the specific implementation in the functions `CreateModifierContext` and `CreateTickContext`. 

We have some duplication but it is much easier to understand and I believe that it also helps to identify bugs.

@0xfe @mscuthbert @wassertim what do you think?

**Comment by 0xfe** [comment]
@rvilarl `createContext` is parameterized by `ContextType`, which is used only in one place in the function, so I think duplicating it isn't going to make it much easier to understand. I intentionally built it this way because the logic is hairy, and and duplicating it puts us at risk of bugs further down the line as we have to update it and keep it in sync.

**Comment by 0xfe** [comment]
Also, if it helps, the formatter is one of the most complex parts of the code, so I think we should ease into it by tackling things like the the `Tickable -> Note -> StemmableNote -> [StaveNote | TabNote]` hierarchy, `ModifierContext` and some modifiers,  and `Beam` first, which are also quite complex in the way they interact with the system.

**Comment by rvilarl** [comment]
> @rvilarl `createContext` is parameterized by `ContextType`, which is used only in one place in the function, so I think duplicating it isn't going to make it much easier to understand. I intentionally built it this way because the logic is hairy, and and duplicating it puts us at risk of bugs further down the line as we have to update it and keep it in sync.

@0xfe is it possible that I send you somewhere the proposal, I could also make a fake PR. I believe with this approach I have already found an error. The parameterized `contextType` and function `addToContext` makes it complicated. And then in Typescript too complicated.

**Comment by 0xfe** [comment]
Sure -- a PR sounds good, we can discuss there.

**Comment by wassertim** [comment]
I did not understand the proposal, but a PR would explain your idea very well @rvilarl

**Comment by mscuthbert** [comment]
I left a comment in #870 but I think it's too much code to duplicate.  Can't we type the ContextType parameter as:

```
function createContexts(
  voices: Voice[],
  ContextType: typeof ModifierContext|typeof TickContext,
  addToContext: Function  // or something with actual calls.
)
```

**Comment by rvilarl** [comment]
@mscuthbert I followed your topic in the PR. Please have a look there.
