### ISSUE TITLE
Typescript migration: Documentation

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#869]
I suggest to start the generation of documentation using typedoc for the migrated files

https://typedoc.org/

**Comment by rvilarl** [comment]
![image](https://user-images.githubusercontent.com/22865285/113249083-691ecd80-92be-11eb-87c7-5939e7220b6c.png)

![image](https://user-images.githubusercontent.com/22865285/113249198-95d2e500-92be-11eb-973a-fe7769c63259.png)

**Comment by wassertim** [comment]
Looks nice. But I would rather concentrate on typescript migration. Otherwise we start too many topics and finish to little

**Comment by rvilarl** [comment]
@0xfe @mscuthbert @wassertim 

Why am I proposing to use typedoc for typescript migration?

**Target**: Help on review activities

**How**:
- typedoc allows us to **check if we are naming the differenct elements consistently**. This is the overview of the elements so far.

![image](https://user-images.githubusercontent.com/22865285/113390746-9dfc5480-9392-11eb-8af4-062c824b12f8.png)

- typedoc helps to **check that the comments make sense**. They are presented in the right context.

![image](https://user-images.githubusercontent.com/22865285/113390973-08ad9000-9393-11eb-904f-b9a35d7cf931.png)

**Do not worry!!!**:
- It is automatically generated.
- It does not interfere with docco
- It does not force to provide the comments, if you don't, you still get a very good  representation (llok at the Type Aliases of the first capture of this comment)

**Comment by rvilarl** [comment]
@0xfe @mscuthbert your thoughts?

**Comment by rvilarl** [comment]
I will make a discussions PR. I believe that it helps to show concepts. I will include also the automatic generated files so that you can look into them without compilation.

**Comment by rvilarl** [comment]
Merged in #874
