### ISSUE TITLE
Create Scrum Board For Typescript Migration

### ISSUE THREAD

**Issue by wassertim** [0xfe/vexflow#876]
@0xfe Since now we can work in parallel and create many issues for the ts-migration like
- migrate Stave
- migrate StaveNote

we need a project in github-projects with a scrum board, so we will also see a progress bar and how much is done. @0xfe would be nice if you could organise it and give us rights to put tickets on the board. Or you do it yourself?

**Comment by rvilarl** [comment]
That would be very nice there is a lot to migrate and we could get perhaps other collaborators on board.

**Comment by 0xfe** [comment]
Seems like there isn't a way to create a project and give access to individuals without giving them access to the whole repo.

Are there other ways to do this? Maybe other tools?

**Comment by wassertim** [comment]
I don't know about other tools @0xfe which would show you progress on this repo. Even if we have issues on this repo, we can not assign them to ourselves.

**Comment by rvilarl** [comment]
@0xfe this one can also be closed.
