### ISSUE TITLE
Typescript migration tasks

### ISSUE THREAD

**Issue by wassertim** [0xfe/vexflow#884]
This ticket will contain everything about file by file migration tasks. Every migration should affect a corresponding test.

- [x] Add js files to ts-loader
- [x] Element
- [x] Tickable
- [x] Fraction
- [x] Tuning
- [x] Music
- [ ] Accidental
- [ ] StaveNote
- [ ] Voice
- [ ] NoteHead
- [ ] TabNote
- [x] TickContext
- [ ] ModifierContext
- [ ] Dot
- [ ] Bend
- [ ] Formatter
- [ ] Clef
- [ ] KeySignature
- [ ] TimeSignature
- [ ] StaveTie
- [ ] TabTie
- [x] Stave
- [x] TabStave
- [ ] TabSlide
- [x] Beam
- [ ] Barline
- [ ] AutoBeamFormatting
- [ ] GraceNote
- [x] GraceTabNote
- [x] Vibrato
- [ ] VibratoBracket
- [ ] Annotation
- [ ] ChordSymbol
- [ ] KeyManager
- [ ] Articulation
- [ ] StaveConnector
- [ ] MultiMeasureRest
- [ ] Percussion
- [ ] NoteSubGroup
- [ ] ClefKeySignature
- [ ] StaveHairpin
- [ ] Rhythm
- [ ] Tuplet
- [ ] BoundingBox
- [ ] Strokes
- [ ] StringNumber
- [ ] Rests
- [ ] ThreeVoices
- [x] Curve
- [ ] TextNote
- [ ] StaveLine
- [ ] Ornament
- [ ] PedalMarking
- [ ] TextBracket
- [ ] StaveModifier
- [ ] GhostNote
- [ ] Style
- [ ] Factory
- [ ] Parser
- [ ] EasyScore
- [ ] Registry
- [ ] BachDemo
- [x] GlyphNote

@0xfe please label it with typescript

I think it would be sufficient to add a comment when you take one of this tasks to work on. We should somehow know who works on what. Example: 

```
Working on Tuplet
```

Please don't add any comments other than that. For this we have other topics.

After the task is done we should check on the corresponding checkbox.

**Comment by rvilarl** [comment]
```
working on Element, Tickable, Note & Formatter
```

**Comment by wassertim** [comment]
I will take accidental

**Comment by rvilarl** [comment]
> 20% Typescript !!!!

**Comment by rvilarl** [comment]
25% Typescript!!!

@ronyeh help is more than welcome!  This is hard just peek the classes you want and make a coment like the one I have above saying what is `done`, `in review` or `working on`. I am leaving Test migration for a second step.

**Comment by ronyeh** [comment]
👨‍💻 Working on Parser.

Let me know if anyone else was planning to tackle Parser / EasyScore soon, so I don't step on your toes. I figure since this is my first attempt, I'll start out with a smaller class that is farther away from what you all are working on. :-)

**Comment by rvilarl** [comment]
@ronyeh the work done by @wassertim provides a lot of help to start:

https://github.com/wassertim/vexflow/tree/typescript_tests

on top we have decided:
- to use protected for attributes when possible.
- avoid the usage of `any` when possible.

Enjoy! And thank you!

**Comment by rvilarl** [comment]
@ronyeh how are you progressing with EasyScore?

**Comment by rvilarl** [comment]
More than 30% TS!!!

**Comment by rvilarl** [comment]
@ronyeh I believe RaphaelContext is the last one! Do you want to take it? your did the other contexts. :)

**Comment by ronyeh** [comment]
Sure I can migrate RaphaelContext. I'll wait until we catch up and merge
CanvasContext and some of your work first.

I don't think I've seen test cases for Raphael. Are we phasing it out since
we handle SVG internally now?

**Comment by ronyeh** [comment]
OK I'll turn on the RUN_RAPHAEL_TESTS and will also include the raphael.js back into flow.html. I will also upgrade raphael.js from 2.1.2 to 2.3.0 (the last published version from 2019). I'll make sure the tests are run against both 2.1.2 and 2.3.0.

**Comment by rvilarl** [comment]
@0xfe do we need Raphael? I cannot answer this question, I do not know

**Comment by ronyeh** [comment]
My guess is that long long term, the answer is no, since browsers now
support SVG natively and it can be hand coded (SVGContext can be improved
when needed).

But for completeness, we can port it during this migration and the new
TypeScript-ified VexFlow can be versioned 3.1 or something (once we fix all
the little bugs).

After the migration, Mohit can decide whether we want to move toward a 4.0
branch which has breaking changes that allow us to clean up APIs and types,
remove Raphael, remove IE polyfill, etc. :-)

**Comment by 0xfe** [comment]
@ronyeh @rvilarl Raphael can be eliminated! We don't need it anymore.

**Comment by ronyeh** [comment]
Sounds good. So when I "migrate" RaphaelContext.... should I just delete
all references to Raphael in the code base?

**Comment by 0xfe** [comment]
Sounds good.

**Comment by ronyeh** [comment]
I saw some merges today, and see a visual difference between the master
from yesterday.

Can someone compare your version's flow.html against:
https://vexflow-demo.vercel.app/tests/flow-master.html?module=MultiMeasureRest

The 12 and 9 multimeasure rests are shifted in the most recent version.

**Comment by rvilarl** [comment]
More than 35% TS!!!

**Comment by rvilarl** [comment]
@0xfe I believe that there is no longer need for this one, you can close it.

**Comment by 0xfe** [comment]
Okay cool, thanks!
