### ISSUE TITLE
Typescript migration: private members

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#901]
Looking into the migration of `StaveNote` and how often `context` is accessed I believe that it is not a good idea to use `getContext`: This will hava a negative impact on performance.

I suggest we go from `private` to `protected` for this variable in `element`

**Comment by 0xfe** [comment]
I don't have a strong opinion here, but `getContext` simplifies working with different rendering backends. How about instead if there are too many calls in a function to `getContext` we do something like this:

```typescript

function foobar() {
  const ctx = this.getContext();

  // ... do things with ctx instead of calling getContext
  voice.setContext(ctx);
  draw(ctx, ...);
}
```

**Comment by rvilarl** [comment]
My opinion and sugestion is to leave `context` protected due to the fact that `getContext` does not do any additional operation/check. It just returns `this.context`. With this we avoid the overhead associated with a function call.

**Comment by 0xfe** [comment]
Okay, that's fine.

**Comment by rvilarl** [comment]
@0xfe migrating `stave` I have realised that the right way is to use `checkContext` I change it back to private.

**Comment by mscuthbert** [comment]
> My opinion and sugestion is to leave `context` protected due to the fact that `getContext` does not do any additional operation/check. It just returns `this.context`. With this we avoid the overhead associated with a function call.

context is currently private not protected -- is that what you meant?  I was looking at TieNote migration in the future, which sets context to null (not undefined) so will either need to be changed there or made protected in Element.
