### ISSUE TITLE
Migration: Testing with Apps using VexFlow

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#909]
We have reached 20% of the migration. I think it would make sense to test with Apps using this library.
@sschmidTU could you test it with osmd?
@mscuthbert could you test it as well?

@0xfe any suggestion?

It would be depressing having to roll back the changes. It is taking a lot of work.

**Comment by AaronDavidNewman** [comment]
I am running (locally) with Smoosic right now.  The only bug I notice is that I don't have flags.  Maybe that interface has changed.  Beamed notes, rests, text, dynamics all look good.

![image](https://user-images.githubusercontent.com/5438280/115117241-3124b500-9f63-11eb-87f1-d343529b2c52.png)

**Comment by rvilarl** [comment]
@AaronDavidNewman Thanks a lot! How should this look correctly? Could you send the expected output?
@0xfe any idea?

**Comment by rvilarl** [comment]
I guess this has to do with the migration of `StemmableNote` and the `hasFlag`

**Comment by rvilarl** [comment]
How can I build a npm to try it with another application?

**Comment by 0xfe** [comment]
@rvilarl can you check the tests please? This is possibly something broken in `hasFlag`.

**Comment by 0xfe** [comment]
Thank's for reporting @AaronDavidNewman!

**Comment by 0xfe** [comment]
@rvilarl Let's hold off on merging anything else until this is fixed. It's pretty significant. :-)

**Comment by 0xfe** [comment]
Looking at current `StaveNote` tests:

<img width="759" alt="Screen Shot 2021-04-17 at 2 59 21 PM" src="https://user-images.githubusercontent.com/241299/115123945-8d043380-9f8d-11eb-8d75-81df477230ff.png">

They should look like this:

<img width="753" alt="Screen Shot 2021-04-17 at 2 57 14 PM" src="https://user-images.githubusercontent.com/241299/115123953-968d9b80-9f8d-11eb-96a3-c07b5491e2fd.png">

**Comment by rvilarl** [comment]
@0xfe I agree, I will look into that, but I have two questions:
- how can I create intermediates npm to check how the library progresses with an external app?
- why is `npm test` not identifying this important change in the output? `Success - All diffs under threshold!`

**Comment by 0xfe** [comment]
Thanks.

- Not sure if I understand your first question, but best way is to look at the tests for each element as you modify the code. They're are quite representative of the outside world. Alternatively, you can build `github.com/0xfe/vextab` and run those tests linked to your local Vexflow. (I do that sometimes when major changes occur.)

- I don't know why the visual regression didn't catch this. The images are being generated correctly, but something is definitely broken there.

**Comment by rvilarl** [comment]
The first question is related to continously testing with my app. There I use vexflow installed with `npm install vexflow` I know that this installs vexflow under `node_modules\vexflow` I have tried copying accross the compilation results but I did not get it to work.

**Comment by 0xfe** [comment]
I see, you can use `npm link` to point to your local instance of Vexflow. This is how I do it to test Vexflow + Vextab: https://github.com/0xfe/vextab#working-with-a-local-vexflow-installation

**Comment by rvilarl** [comment]
Thanks, error found, I will do a PR. It is related to the change from `null` to `undefined`. The classes which are still not migrated were checking with `null` to decide if the  `flag` had to be drawn.

The tests should have highlighted this test. :(

**Comment by rvilarl** [comment]
PR is there.

**Comment by rvilarl** [comment]
I have been looking through the results of the tests and I have seen that:

![image](https://user-images.githubusercontent.com/22865285/115139665-6dbfe180-a033-11eb-80d3-a3d5272c9afc.png)

The bug is not in 3.0.9 but already present in e9209f6 previous to the start of the Typescript migration.

**Comment by 0xfe** [comment]
> Thanks, error found, I will do a PR. It is related to the change from `null` to `undefined`. The classes which are still not migrated were checking with `null` to decide if the `flag` had to be drawn.
> 
> The tests should have highlighted this bug. :(

Agreed, it's very hard to test visual changes deterministically. I'm still looking at the regression tests to understand why this was below threshold. There are bunch of errors showing up in that test.

**Comment by 0xfe** [comment]
> I have been looking through the results of the tests and I have seen that:
> 
> ![image](https://user-images.githubusercontent.com/22865285/115139665-6dbfe180-a033-11eb-80d3-a3d5272c9afc.png)
> 
> The bug is not in 3.0.9 but already present in [e9209f6](https://github.com/0xfe/vexflow/commit/e9209f6853cd16c01c2c470fc36370a4aad69513) previous to the start of the Typescript migration.

This is okay -- Saggital accidental are not available in Petaluma.

**Comment by rvilarl** [comment]
> I see, you can use `npm link` to point to your local instance of Vexflow. This is how I do it to test Vexflow + Vextab: https://github.com/0xfe/vextab#working-with-a-local-vexflow-installation

@0xfe thanks I have now the version under development included in my app.
@sschmidTU I had to disable several options to get osmd building, are you planning to make it support strict?

**Comment by rvilarl** [comment]
As stated in #905 I have the visual testing now running. I have also created  two variants of `visual_regresion.sh` that check the difference between two different commits. I will proceed in the following manner.

1) I will check `PRs` against `master` with the variants of visual regression to make sure that no change is introduced before merging.
2) I will create "migration visual issues" with the differences between `master` and e9209f6 in order to investigate them. There are 6 differences.

Please note that now visual testing is running e9209f6 reporting 36 errors. These have nothing to do with the migration.

@0xfe please confirm that you agree that e9209f6 is an adequate reference to check on differences included in the migration.

**Comment by 0xfe** [comment]
Thanks for working through this. Yes, the 6 differences are enough to work with.

**Comment by 0xfe** [comment]
Also, can you send a PR that fixes `visual_regression.sh` please?

FYI, you probably already know this, but the tests are designed to check against the last _release_, and there have been no new releases in months, which is why there are 36 errors -- most of them are not really errors, they're repositioning from the formatting fixes.

**Comment by rvilarl** [comment]
@0xfe some answers and questions:
1) The `visual_regression.sh` fix was not related to the file. The problem was that I did not have ImageMagick installed and the script says that everything is ok without ImageMagick. It would make sense to change it so that it shows an error like "Error: ImageMagick not found.". **Would you agree?**
2) Yes, I have realised that the script checks against the latest release. I have made a `visual_regression_ref.sh` that checks the `current` images against the `current` images of a project situated in `../vexflow-ref`. This is very convenient to check that there are no errors introduced against for example `master` before making a `PR`. **Do you want me to do a PR including this script in tools?**
3) I have used the tool described in 2) to identify the 3 "Migration Visual Issues"(6 bugs) comparing  `master` against e9209f6. You have already commented that #913 might not be an error.  Probably e9209f6 is not a good reference, we should perhpas select one including the change from @AaronDavidNewman. **Which commit would you use to identify the errors introduced in the migration, perhaps one after the meintioned change?**

**Comment by 0xfe** [comment]
1. Agreed -- yes please! I'm surprised it does not already do that!
2. Instead of a separate script, can we add a flag to `visual_regression.sh` to use a ref instead?
3. Let's keep it, I think Aaron's change was after the typescript migration started.

Also, just want to say thank you for being very structured and methodical with this. We need more of this in VexFlow! :-)

**Comment by sschmidTU** [comment]
> @sschmidTU I had to disable several options to get osmd building, are you planning to make it support strict?

What do you mean, support strict?

I'll try to test the current build with OSMD soon.
