### ISSUE TITLE
bad alignment for fixed measure width

### ISSUE THREAD

**Issue by lwyj123** [0xfe/vexflow#911]
I wanna to implemented a player read musicXML, and want the measure and note match the timeline. But when I format the notes, alignment of the note seems not properly.

![image](https://user-images.githubusercontent.com/9214496/115223650-9f719f00-a13e-11eb-8b36-b6498e036f45.png)

Here is the core code:
```Typescript
formattedMeasures.forEach((measure, index) => {
  const stave = new VF.Stave(0, index * 60, width, {});
  stave.setContext(context).draw();

  const notes = measure.notes.map(note => {
    // some process
  })

  VF.Formatter.FormatAndDraw(context, stave, notes, {
    align_rests: true,
    auto_beam: true,
  });
});
```

**Comment by 0xfe** [comment]
Hi -- please see https://github.com/0xfe/vexflow/wiki/The-VexFlow-FAQ#how-do-i-align-multiple-voices-across-staves for how to align voices across staves.

**Comment by lwyj123** [comment]
@0xfe Thanks for your reply, I was try this method just now and still get wrong result.

![image](https://user-images.githubusercontent.com/9214496/115234106-3fcdc080-a14b-11eb-85e8-abad02f38af0.png)

**Comment by 0xfe** [comment]
Can you reproduce in jsfiddle please? (Also, what version of VexFlow are you using?)

**Comment by 0xfe** [comment]
You can use this starter example: https://jsfiddle.net/cr6vxo4k/

**Comment by AaronDavidNewman** [comment]
@lwyj123 if you could also post the xml you're using, that would be great.  I'm curious what OSMD and Smoosic do with it.

**Comment by lwyj123** [comment]
@0xfe Thanks, I just write a reproduce demo in [jsfiddle](https://jsfiddle.net/lwio/2ze6yugf/20/).

**Comment by lwyj123** [comment]
And for @AaronDavidNewman, the musixXML is a simple export from museScore.
[demo.zip](https://github.com/0xfe/vexflow/files/6337541/demo.zip)

**Comment by AaronDavidNewman** [comment]
I think you want the 2nd quarter note of the fiddle to have duration 4d.  The `dot=true` draws the dot, but doesn't change the duration afa formatting is concerned.

**Comment by mscuthbert** [comment]
That's definitely it.  Closing.
