### ISSUE TITLE
Migration Visual Issue: Vibrato

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#912]
The migration has introduced a bug in the representation of vibrato. 4 Tests are affected.

**Comment by rvilarl** [comment]
**Annotation.Fingerpicking**
New (including migration)
![Annotation Fingerpicking_new](https://user-images.githubusercontent.com/22865285/115335856-52251a00-a19e-11eb-89de-1d688cfb4366.png)
Ref (e9209f6)
![Annotation Fingerpicking_ref](https://user-images.githubusercontent.com/22865285/115335875-59e4be80-a19e-11eb-8e65-bacf7c8efe1c.png)
Difference
![Annotation Fingerpicking](https://user-images.githubusercontent.com/22865285/115335990-93b5c500-a19e-11eb-9b14-61aa1bf0564a.png)

**Comment by rvilarl** [comment]
**Vibrato.Harsh_Vibrato**
New (including migration)
![Vibrato Harsh_Vibrato_new](https://user-images.githubusercontent.com/22865285/115336132-db3c5100-a19e-11eb-83f2-85fcf46a1f51.png)
Ref (e9209f6)
![Vibrato Harsh_Vibrato_ref](https://user-images.githubusercontent.com/22865285/115336135-e0010500-a19e-11eb-971d-700c5b758ab7.png)
Difference
![Vibrato Harsh_Vibrato](https://user-images.githubusercontent.com/22865285/115336205-02931e00-a19f-11eb-889a-4e04b950ba51.png)

**Comment by rvilarl** [comment]
**Vibrato.Simple_Vibrato**
New (including migration)
![Vibrato Simple_Vibrato_new](https://user-images.githubusercontent.com/22865285/115336336-51d94e80-a19f-11eb-9bc4-63c399d36a4d.png)
Ref (e9209f6)
![Vibrato Simple_Vibrato_ref](https://user-images.githubusercontent.com/22865285/115336348-56056c00-a19f-11eb-921a-59349b5b679b.png)
Difference
![Vibrato Simple_Vibrato](https://user-images.githubusercontent.com/22865285/115336356-5b62b680-a19f-11eb-9fe4-222a2ac4b4c5.png)

**Comment by rvilarl** [comment]
**Vibrato.Vibrato_with_Bend**
New (including migration)
![Vibrato Vibrato_with_Bend_new](https://user-images.githubusercontent.com/22865285/115336505-a977ba00-a19f-11eb-9046-86254a2822ed.png)
Ref (e9209f6)
![Vibrato Vibrato_with_Bend_ref](https://user-images.githubusercontent.com/22865285/115336520-aed50480-a19f-11eb-98cd-3587f6869fc5.png)
Difference
![Vibrato Vibrato_with_Bend](https://user-images.githubusercontent.com/22865285/115336529-b1cff500-a19f-11eb-8efe-bb510415d0a9.png)

**Comment by 0xfe** [comment]
These look related to `Modifier` and `text_line`. Possibly: `stave.getYForTopText`, or `note.getYForTopText`

**Comment by rvilarl** [comment]
Resolved with #917
