### ISSUE TITLE
Migration Visual Issue: Lyrics

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#913]
The migration has introduced one bug related to the representation of lyrics, 1 test affected.

**Comment by rvilarl** [comment]
Annotation.Lyrics
New (including migration)
![Annotation Lyrics_new](https://user-images.githubusercontent.com/22865285/115336796-2440d500-a1a0-11eb-985d-19d27147ef73.png)
Ref (e9209f6)
![Annotation Lyrics_ref](https://user-images.githubusercontent.com/22865285/115336806-286cf280-a1a0-11eb-8489-dcde8212f549.png)
Difference
![Annotation Lyrics](https://user-images.githubusercontent.com/22865285/115336815-2e62d380-a1a0-11eb-9ca4-8a74e176bb62.png)

**Comment by 0xfe** [comment]
This might be okay, I think this is from @AaronDavidNewman's change.

**Comment by AaronDavidNewman** [comment]
Oh I get it, the test changed.  I made the clef correct in the last one.  This is fine.

**Comment by rvilarl** [comment]
I did not change the test. @AaronDavidNewman in the ref above you see the commit I compared against. Which one is the commit where you merged your changes?

**Comment by AaronDavidNewman** [comment]
This is OK.  Test was changed by me on 3/14 and the reference commit is 3/11.  This can  be closed.
