### ISSUE TITLE
Migration Visual Issue: Text Annotation

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#914]
The migration has introduced a bug with text annotations, one test affected.
The reference looks buggy already. I also do not understand why the difference does not higlight clerare the divergence.
This is one `text` overlapping a `10`

**Comment by rvilarl** [comment]
**Annotation.TabNote_Annotations**
New (including migration)
![Annotation TabNote_Annotations_new](https://user-images.githubusercontent.com/22865285/115337155-c52f9000-a1a0-11eb-83d9-c1b17b8e6f87.png)
Ref (e9209f6)
![Annotation TabNote_Annotations_ref](https://user-images.githubusercontent.com/22865285/115337168-c95bad80-a1a0-11eb-9e33-ca75003da121.png)
Difference
![Annotation TabNote_Annotations](https://user-images.githubusercontent.com/22865285/115337185-ce206180-a1a0-11eb-9f33-714eb7df0478.png)

**Comment by 0xfe** [comment]
This is possibly the same bug in #912

**Comment by AaronDavidNewman** [comment]
Most of it is probably my change.  Text is formatted by character width, but very short text means very small difference.

It's not really clear why 3rd 'Text' from left is different than the other ones, though.  Nothing about the annotations vertical placement would have changed, and all the other placements of text are pretty close.

**Comment by rvilarl** [comment]
Resolved with #917
