### ISSUE TITLE
Possible missing offsetYBaseStemUp: -2,

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#918]
https://github.com/0xfe/vexflow/blob/a61b6f59bcd9376c00bd853573cb3a487bc8264f/src/fonts/bravura_metrics.ts#L149

On my simple tests with EasyScore, I notice that my quarter notes with the stem going up look different from my quarter notes with the stem going down.

I assumed they should be just 180 degree rotations of one another, but the quarter note with the stem going up has a sharp edge where the stem meets the note head. 

When you zoom in on the web page, you see that the stem pokes out a little beyond the edge of the note head. It's not a smooth transition.

I traced it to the bravura_metrics.ts file, and when I add an extra line:

```
      noteheadBlack: {
        offsetYBaseStemUp: -2,    // <--- I added this line
        offsetYBaseStemDown: 2,
      },

```

Then the notes look great and symmetrical. They also match how it looks when I use the Bravura font in Affinity Designer and insert a quarter note with stem going upward.

So should we add this line? Or does it break other things? I am new to VexFlow so I am not sure if adding this line will break your visual regression tests.

Thanks!

**Comment by 0xfe** [comment]
I think this is right. We may have to fix this for Petaluma too.

Can you attach a before/after screenshot please?

**Comment by ronyeh** [comment]
I'll investigate and report back. I see some small issues with the half notes too, both in Bravura and Petaluma. Are you phasing out support for Gonville, or should I investigate that font too?

The only reason I noticed is because I'm making a sight-reading tool targeted at beginners and older adults with poor vision. Thus, I scaled up the SVG context by calling:

```
const renderer = new VF.Renderer(targetDIV, VF.Renderer.Backends.SVG);
const context = renderer.getContext();
context.scale(2, 2);
```

As a result, I noticed the small issues with the note stem poking through the note heads.

**Comment by ronyeh** [comment]
I'll try my best. :-) I'll work on a PR with fixes for Bravura, Petaluma, and Gonville.

**Comment by 0xfe** [comment]
Thank you -- :-)

**Comment by h-sug1no** [comment]
Hi!

smufl seems to define the position of the stem connection for each glyph:

https://w3c.github.io/smufl/latest/specification/glyph-registration-notes-flags.html

> Note that the stemUpSE attachment point corresponds to the bottom right-hand (or south-east) corner of the stem, while stemDownNW corresponds to the top left-hand (or north-west) corner of the stem. Likewise, for correct alignment, the flag glyphs must always be aligned precisely to the left-hand side of the stem, with the glyph origin positioned vertically at the end of the normal stem length.

For your reference, the json for Bravura and Petaluma (noteheadBlack) looks like this:

https://github.com/steinbergmedia/bravura/blob/3df1714e6f9d522a8d2b6ee6888fa3e68e71199d/redist/bravura_metadata.json#L43572

https://github.com/steinbergmedia/petaluma/blob/532dcc7c9ae9b9d1e92cedf4f1d326cf2509f7d1/redist/petaluma_metadata.json#L20233

you should refer to the json that matches the version used by vexflow. (I don't know which version of bravura and petaluma vexflow is using).

**Comment by 0xfe** [comment]
Welcome back @h-sug1no :-)

Thanks for the hints -- that's helpful.

**Comment by ronyeh** [comment]
Thanks for the links @h-sug1no 
I looked them over.

I put together a website where I could more easily debug the font changes visually:

https://vexflow-demo.surge.sh/fonts/

To see the changes, open up multiple tabs and switch between them quickly. You can also toggle the "Visual Debug" to ON to see the changes more easily.

I'll put together a PR later today.

**Comment by ronyeh** [comment]
Here is one of the changes, as an animated GIF:

![FontTest](https://user-images.githubusercontent.com/239113/115775457-c1019f00-a367-11eb-9b8e-761f15072952.gif)

**Comment by 0xfe** [comment]
Looks good!

**Comment by ronyeh** [comment]
Hi, I'm trying to run your visual regression tests, and I have a few questions.

I checked out a fresh copy of vexflow, installed all brew dependencies, and did:

```
npm run generate
npm run diff
```

I get output like:

```
All images with a difference over threshold, 0.01, are
available in ./build/images/diff, sorted by perceptual hash.


You have       13 warning(s):
............... complaints about some PNGs missing ...........

You have       46 fail(s):
```

I assume this is because HEAD has diverged from the last release, 3.0.9?


Now, if I want to see the diff between my patch and the current HEAD, do I just run `grunt reference` to copy the current build files from HEAD revision into vexflow/reference/ 

Then, I apply my patches and do:

```
npm run generate:reference
npm run diff:reference
```

Anyways, hopefully it will show that the visual diffs are minimal. Most of the tweaks only are noticeable at 2X or 4X scale.

**Comment by 0xfe** [comment]
Yes, that's right -- `npm run test:reference` is the right command, and you should expect almost no visual diffs.

**Comment by ronyeh** [comment]
OK I did what I described above and I got diff images that look like this:

![Auto_Beaming Even_Group_Stem_Directions](https://user-images.githubusercontent.com/239113/115802804-6af72080-a394-11eb-9f16-261b079f985e.png)

![Beam Mixed_Beam_1](https://user-images.githubusercontent.com/239113/115802823-777b7900-a394-11eb-90f7-d3eb3a38c99e.png)

![TextNote TextNote_Formatting](https://user-images.githubusercontent.com/239113/115802964-b6a9ca00-a394-11eb-982d-7cfb4cca2750.png)

This is for my patches to `bravura_metrics.ts`.

How do I test petaluma and gonville? I assume I should edit the the default font stack in one of the test files?

**Comment by 0xfe** [comment]
Great, those diffs are exactly what you should expect! Send a PR for bravura and then we can fix the others.

The tests run against all fonts, so when you update Petaluma (for example), they'll show up in the diffs.

**Comment by ronyeh** [comment]
Resolved via https://github.com/0xfe/vexflow/pull/926
