### ISSUE TITLE
Visual Issue: Articulation.Articulation___Inline_Multiple_Blessed

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#919]
I found the following issue in master compared to blessed. I believe that this issue was not introduced in the migration.

**Comment by rvilarl** [comment]
Blessed:
![Articulation Articulation___Inline_Multiple_Blessed](https://user-images.githubusercontent.com/22865285/115499953-b44e4f80-a270-11eb-9f62-64e7ce7dd67f.png)
Current:
![Articulation Articulation___Inline_Multiple_Current](https://user-images.githubusercontent.com/22865285/115499959-b7e1d680-a270-11eb-956e-443bb204d24e.png)
Diff:
![Articulation Articulation___Inline_Multiple](https://user-images.githubusercontent.com/22865285/115499975-bc0df400-a270-11eb-8fab-3b272919d8d4.png)

**Comment by 0xfe** [comment]
This is because of the new formatter. We just need to update the test to give the notes more room.

**Comment by rvilarl** [comment]
I have modified the test using `preCalculateMinTotalWidth` rather than a fix value (I think it is done properly):
```js
// bar 1
var voice1 = new VF.Voice().addTickables(notesBar1);
var formatter = new VF.Formatter();
var staveBar1 = new VF.Stave(10, 30, formatter.preCalculateMinTotalWidth([voice1]));
staveBar1.setContext(ctx).draw();
...
// bar 2 - juxtaposing second bar next to first bar
var voice2 = new VF.Voice().addTickables(notesBar2);
var staveBar2 = new VF.Stave(
  staveBar1.width + staveBar1.x,
  staveBar1.y,
  formatter.preCalculateMinTotalWidth([voice2])
);
staveBar2.setContext(ctx).draw();
...
// bar 3 - juxtaposing second bar next to first bar
var voice3 = new VF.Voice().addTickables(notesBar3);
var staveBar3 = new VF.Stave(
  staveBar2.width + staveBar2.x,
  staveBar2.y,
  formatter.preCalculateMinTotalWidth([voice3])
);
staveBar3.setContext(ctx).draw();
...
// bar 4 - juxtaposing second bar next to first bar
var voice4 = new VF.Voice().addTickables(notesBar4);
var staveBar4 = new VF.Stave(
  staveBar3.width + staveBar3.x,
  staveBar3.y,
  formatter.preCalculateMinTotalWidth([voice4])
);
staveBar4.setEndBarType(VF.Barline.type.END);
staveBar4.setContext(ctx).draw();
```
And I get this result which does not look good:
![Articulation Articulation___Inline_Multiple_Current](https://user-images.githubusercontent.com/22865285/115663183-67d24500-a340-11eb-8440-2b98b4cb5d25.png)

**Comment by 0xfe** [comment]
Yeah, `preCalculateMinTotalWidth` is very wrong (the more dense the score, the more wrong it is.) Let's just used fixed widths for now.

**Comment by rvilarl** [comment]
@0xfe I think it is better to leave failing rather than hiding the problem. No we have a test showing the `preCalculateMinTotalWidth` problem and we no longer need a jsfiddle :)

**Comment by rvilarl** [comment]
If you agree I can PR the change in the test

**Comment by 0xfe** [comment]
We have Formatter - Stavenote Justification, and Formatter Annotation tests that show it.

**Comment by rvilarl** [comment]
Ok
