### ISSUE TITLE
Migration Visual Issue: StaveNote

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#920]
Migrating StaveNote I get consistenly a new short grey line below the bottom left corner of the staves. Any tip on where this could be coming from is appreciated. :)

**Comment by rvilarl** [comment]
Current
![Accidental Accidental_Arrangement_Special_Cases_Current](https://user-images.githubusercontent.com/22865285/115535081-b88e6300-a298-11eb-8b4c-b8392794ee4d.png)
Master
![Accidental Accidental_Arrangement_Special_Cases_Reference](https://user-images.githubusercontent.com/22865285/115535332-eecbe280-a298-11eb-918c-f0e302e756aa.png)
Current
![Accidental Accidental_Padding_Current](https://user-images.githubusercontent.com/22865285/115535252-dc51a900-a298-11eb-95ba-baf5a871e4b5.png)
Master
![Accidental Accidental_Padding_Reference](https://user-images.githubusercontent.com/22865285/115535384-fe4b2b80-a298-11eb-91f9-d4c9ec395bc7.png)

**Comment by rvilarl** [comment]
![Annotation Test_Justification_Annotation_Stem_Down_Current](https://user-images.githubusercontent.com/22865285/115535644-3d797c80-a299-11eb-8dac-1c5f595d5dab.png)

**Comment by 0xfe** [comment]
This is most likely in `drawLedgerLines()` but also possibly `stave.getYForNote()` or related to `last_line` or `getLineNumber` or `getYForBottomText` in `stavenote.ts`.

**Comment by rvilarl** [comment]
@0xfe you are right, the first row of required ledger lines are moved to the left! I will look into that later.

**Comment by rvilarl** [comment]
PR is there #921 @0xfe thanks for the hint.
