### ISSUE TITLE
Migration issue: Note in Modifier

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#930]
Modifier has an attribute note of type Note. Tremolo expects this note to be a StemmableNote.
Are there childs from Note not derived from StemmableNote which have Modifiers ?

**Comment by 0xfe** [comment]
Yes, there can be, but I'll have to look them up.

I'm not sure I understand the issue here. For tremolo you can cast `note as StemmabeNote` and be fine right?

**Comment by rvilarl** [comment]
That is right but with this we tell typescript: forget it, we know it is a StemmableNote. If we want to follow this approach we should figure out an approach to fail if this is not the case, shouldn´t we?

**Comment by 0xfe** [comment]
We have two options:

1. Create a child of `Modifier`, called `StemmableModifier` that only takes `StemmableNote` as a parameter (and `Tremolo` can extend `StemmableModifier`), or,
2. Add a type-check in `Tremolo` for `StemmableNote` so it fails if it doesn't get one.

I think 1 is better if we can figure it out.

**Comment by rvilarl** [comment]
We have a third option:
3. Reduce the number of classes and go closer to the MusicXML format. That is merge `Note` and `StemmableNote` and perhaps even `StaveNote`

**Comment by rvilarl** [comment]
@ 0xfe I have done 3 as experiment. I will set a PR in draft for you to look into it.

**Comment by 0xfe** [comment]
No please :-) That would break the interfaces, and also break the semantics of `ClefNote`, `GraceNoteGroup`, `GhostNote` and various other notes. We can think of remodelling the class hierarchy separately, not part of typescript, with a deeper discussion,

**Comment by rvilarl** [comment]
Then as suggested in #934 I believe we should implement the functions used when accessing `Note` also in `Note` to allow the access to the overriden function in the child classes, do you agree? I will be adding them little by little as required by the migration. Do you agree?

**Comment by 0xfe** [comment]
Yes, I agree with that -- let's do it incrementally so we can figure out what the default implementations should be. (I made a suggestion for `getTieLeft/RightX` in the other PR.
