### ISSUE TITLE
Migration issues on voice

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#937]
1) `Draw` parameters do not correspond to those in `Element` and there is an error not allowing to overload.
2) constructor uses `StaveOptions` requiring an additional attribute `softmaxFactor`

@0xfe any tip on these issues?

**Comment by rvilarl** [comment]
> 1. `Draw` parameters do not correspond to those in `Element` and there is an error not allowing to overload.

Solution: `draw` is now allowing `any` in Element.

> 2. constructor uses `StaveOptions` requiring an additional attribute `softmaxFactor`

Solution: `StaveOptions` no longer used. `softmaxFactor` is inline

3. `Beam` uses `getTickables` from `Voice` which returns `Note`. Looking in details, the implementation of `Beam` check if the notes have stems. 

Solution: `Beam` adapted to allow `Note`

**Comment by 0xfe** [comment]
First two solutions seem good.

Re 3: it seems far more reasonable to downcast from `Note` to `StemmableNote` than to add `*Stem*` methods to `Note` or change beam's interface.
