### ISSUE TITLE
Stems & Flags are possibly too high on Bravura & Petaluma

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#941]
First off, I'm not an expert on how stems & flags should look. Someone with more expertise can chime in!

Here's what I noticed:

On the font sample that I typeset manually with the most recent versions of Bravura and Petaluma, I see that half, quarter, eighth and 16th notes are pretty much the same height.

https://vexflow-demo.vercel.app/images/font_sample.svg

This is mostly true with the Gonville sample that I rendered through LilyPond. Only the half note is a tiny bit shorter:

https://vexflow-demo.vercel.app/images/lilypond-gonville.svg

When a score is created with the most recent version of MuseScore, half, quarter, and eighth notes are the same height. 16th notes are a tiny bit taller, and then the stems grow noticeably higher on 32nd, 64th, and 128th notes.

![bravura_vs_gonville_musescore](https://user-images.githubusercontent.com/239113/116493062-c15fd580-a852-11eb-8548-628de6cb1df8.gif)

On my test page with VexFlow 3.0.9, it seems like Gonville is okay, but Bravura and Petaluma render very tall note stems.

![gonville_bravura_petaluma_vexflow](https://user-images.githubusercontent.com/239113/116493696-19e3a280-a854-11eb-968e-f06d3716eab7.gif)

In the samples generated by LilyPond, MuseScore, and manually in Affinity Designer, the innermost flag's tip is close to the note head. In the VexFlow 3.0.9 example, this is true for Gonville, but not for Bravura and Petaluma. In the latter two fonts, the 32nd, 64th, and 128th flags are far away from their note heads.

**Comment by ronyeh** [comment]
I dug around and discovered that in `tables.js`, each note type has properties called `stem_up_extension` and `stem_down_extension`:

```
       code_flag_upstem: 'flag64thUp',
       code_flag_downstem: 'flag64thDown',
       stem_up_extension: 13,
       stem_down_extension: 13,
```

If I go and set all of those to 0, it fixes Bravura and Petaluma, but breaks Gonville.

https://user-images.githubusercontent.com/239113/116494624-0df8e000-a856-11eb-9d55-33a48f1b4b51.mp4

Is there a way to customize the `stem_up_extension` and `stem_down_extension` values via each font's metrics file?

**Comment by 0xfe** [comment]
You're right -- those are wrong heights.

Not entirely sure why Gonville behaves differently, but it certainly has something to do with `stem_up/down_extension`. You might have to turn those into font-specific metrics (which is good -- I'd like to move more of the constants into metrics files.)

I'd say:

- find where in the code `stem_up_extension` and `stem_down_extension` is used.
- replace them with calls to `this.musicFont.lookupMetric(...)` -- see `stemmablenote.ts` for an example.
  + you'll need to create new entries in the metrics files for stem up and down extensions
- remove `stem_up/down_extension` from `tables.js`

**Comment by h-sug1no** [comment]
Please refer to the following for future reference:

https://w3c.github.io/smufl/latest/specification/glyphswithanchors.html#fn_11

> It is typical for noteheads and flags to be drawn using font glyphs, while stems themselves are drawn using primitive lines or rectangles. Flag glyphs in SMuFL-compliant fonts are registered such that y=0 represents the end of a stem drawn at its normal length, i.e. typically 3.5 staff spaces, so for simple drawing, any flag can be drawn at the same position relative to the stem and give the correct visual stem length. Modern drawing APIs typically provide sub-pixel RGB anti-aliasing for font glyphs, but may only provide grayscale anti-aliasing for primitive shapes. If the stem is drawn at its normal length with a flag glyph continuing beyond the end of the stem, there may be a poor visual appearance resulting from the primitive stem using standard anti-aliasing and the flag glyph using sub-pixel anti-aliasing. Therefore, it is recommended to extend the stem by the additional height of the flag such that the primitive stem stops at the end (or just short of the end) of the flag. Because the amount by which the stem should be extended is highly dependent on the design of the flag in a particular font, this value should be specified for each flag glyph in the metadata JSON file
