### ISSUE TITLE
Have search.exclude in .vscode/settings.json also exclude releases/ directory

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#946]
On my local repo, I have modified .vscode/settings.json to look like this:
```
  "search.exclude": {
    "build/": true,
    "node_modules/": true,
    "docs": true,
    "releases": true   // <=== I added this line
  },
```

This makes me more efficient as I explore migrating JS to TS.

For example, I was trying to find out where `renderHeightAdjustment` was used. But a search revealed many instances, mostly in rendered *.js and *.js.map files.

After excluding the releases directory, I discover only three source files reference this.

![search_exclude](https://user-images.githubusercontent.com/239113/116750578-862ae700-a9b7-11eb-9d50-8d59b4950369.gif)

Would others be interested in this modification? If so, I can submit a PR.

My .vscode/settings.json file currently looks like:

```
// Place your settings in this file to overwrite default and user settings.
{
  "eslint.enable": true,
  "files.associations": {
    "src/*.js": "javascript"
  },
  "search.exclude": {
    "build/": true,
    "node_modules/": true,
    "docs/": true,
    "releases/": true
  },
  "editor.tabSize": 2,
  "eslint.format.enable": true,
  "javascript.format.enable": false,
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "esbenp.prettier-vscode"
}
```

**Comment by 0xfe** [comment]
Yes please!

**Comment by ronyeh** [comment]
Moved to PR: https://github.com/0xfe/vexflow/pull/949
