### ISSUE TITLE
grunt watch + flow.html on a fresh git clone fails

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#966]
I will try to investigate this webpack issue, but at the moment I'm out of my element.

When webpack compiles the TEST_SOURCES, it seems to insert `run.js` before `vexflow_test_helpers.js`. When I load flow.html, it complains that `VF.Test.run` is not defined, because run.js needs to happen at the end.

So we either need to figure out a way to tell webpack to order the entry files correctly.... or maybe we can just load `run.js` directly in flow.html (via a script tag that is directly after vexflow-tests.js).

**Comment by ronyeh** [comment]
Wait... I reset everything and tried again and now it works! :-( :-) ?

webpack is like magic to me.

Anyways, fingers crossed that it won't break again.

**Comment by ronyeh** [comment]
OK, it looks like it is fine on master.

However, on my migration branch for EasyScore, I also migrated the EasyScore tests.

It seems like the additional imports I added somehow triggers webpack to reorder the TEST_SOURCES, so that VF.Test.run will try to be assigned too early (and it will fail).

This might be an issue as we move forward with migrating more of the tests to typescript. There needs to be a way to specify to webpack the particular ordering of the test sources, such that run.js goes last.

Maybe eventually the approach will be the same as having a single entry point (e.g., index.js) for the production build. So maybe we will need to refactor the webpack test configuration to have a single point of entry with the appropriate imports.

**Comment by ronyeh** [comment]
@0xfe @rvilarl I'm in the middle of improving Gruntfile.js so that the webpack config for tests uses a single entry: `tests/run.js`

run.js will look something like this:
```
import { VFT } from './vexflow_test_helpers';
import { MT } from './mocks';
import { AccidentalTests } from './accidental_tests';
import { StaveNoteTests } from './stave_tests';
import { VoiceTests } from './voice_tests';
... more imports here ...

VFT.run = function () {
  MT.touch();
  AccidentalTests.Start();
  StaveNoteTests.Start();
  VoiceTests.Start();
  ... more test cases here ...
};
```

The benefit of doing all the imports is that webpack will order the js/ts files correctly. I was having an issue earlier today (while trying to migrate EasyScore to TS) where I couldn't test because webpack had decided to shuffle around some of my JS files inside the output `vexflow-tests.js`.

Just checking to make sure it's OK that I'm doing this. :-)

I can submit a PR for this when I'm done.

**Comment by rvilarl** [comment]
@wassertim could you look into that? you know quite well the new test infrastructure

**Comment by 0xfe** [comment]
@ronyeh Yes, this is much better if you can ensure that both the JS and TS tests run on a single page -- the old method was a remnant of the JS test bundle which was simply a concatenation.

**Comment by ronyeh** [comment]
[Please see this PR](https://github.com/0xfe/vexflow/pull/968). Closing this issue to move discussion over to the PR.
