### ISSUE TITLE
Add support for cross stave beams.

### ISSUE THREAD

**Issue by 0xfe** [0xfe/vexflow#97]
This would require small changes to the beam and stem drawing code.

Also, ghost notes will have to be added to partner staves for synchronization.

**Comment by apendua** [comment]
Does anyone know what's the current status of this ticket?

**Comment by dfcreative** [comment]
Yep, very interested too )

**Comment by mscuthbert** [comment]
If you haven't seen the Steinberg development blog, it's fun reading in general for anyone developing VexFlow but this post is particularly relevant: http://blog.steinberg.net/2015/03/development-diary-part-10/  The takeaway is that making the beams on cross-staff beaming is really hard and except for Lilypond, none of the current software gets it right.  I suggest merging this pull request when we can get the code working with the latest VexFlow version and then making the remaining problems be separate tickets to work on later.

**Comment by dfcreative** [comment]
Seems that it is very requested feature, maybe we should set bounty on that?

**Comment by Silverwolf90** [comment]
Sorry I totally dropped the ball on this. I simply don't have time to contribute actively anymore :/ [I've pushed my branch with my work](https://github.com/Silverwolf90/vexflow/tree/feature/cross-stave-beams). It's *really* old (~2 years). And it's a **massive** hack that barely works, and is without any sophistication, ie: does not avoid the beam-corners that Daniel identifies in that blog post.

**Comment by 0xfe** [comment]
No problem -- thanks for everything so far!

**Comment by mscuthbert** [comment]
Maybe beam corners in cross-staff beaming aren't as important as people think they are.  Here from two consecutive measures of a Brahms Piano part (Cl. sonata, op. 120 nr 1 mvmt 2), Breitkopf and Härtel -- superstar engraver still does two consecutive, nearly identical cross-staff beam corners differently:

![screen shot 2016-07-16 at 18 48 29](https://cloud.githubusercontent.com/assets/3521479/16897665/e789378a-4b85-11e6-9d97-705645020329.png)

If this is the best of the best screwing up manually, I think we can accept "pretty good" automatedly. :-)

(note also the impossible rhythm in the r.h. soprano of the piano)

**Comment by Silverwolf90** [comment]
I'm doing some refactoring around beams/stems at the moment. I suspect cross-stave beams will be a bit easier to implement when I'm done. Maybe I'll give it another shot!

**Comment by SalahAdDin** [comment]
Holly good, it's really awesome.

**Comment by 0xfe** [comment]
Closing old issue.

**Comment by SalahAdDin** [comment]
@0xfe finally, was it a new feature?

**Comment by compilelife** [comment]
It's 2022 now, try latest commit, this issue still exists……

Cross stave beams is very helpful for students to understand some sheet.

Any plan for this ?

**Comment by rvilarl** [comment]
This is related to #1373 and I plan to look into it.

**Comment by rvilarl** [comment]
Now supported
