### ISSUE TITLE
Typescript migration: formatter

### ISSUE THREAD

**Issue by rvilarl** [0xfe/vexflow#974]
I have completed the migration and I am getting some differences in the images.
I will share them here to get some tips to fix bugs.

**Comment by rvilarl** [comment]
![Auto_Beaming Break_Beams_on_Middle_Rests_Only](https://user-images.githubusercontent.com/22865285/117550553-51670180-b041-11eb-92c4-2334fd37040f.png)
**Migrated (third rest is lower):**
![Auto_Beaming Break_Beams_on_Middle_Rests_Only_Current](https://user-images.githubusercontent.com/22865285/117550516-18c72800-b041-11eb-9607-9a0e19e4d26c.png)
**Reference(master):**
![Auto_Beaming Break_Beams_on_Middle_Rests_Only_Reference](https://user-images.githubusercontent.com/22865285/117550517-1c5aaf00-b041-11eb-882b-12dc04768537.png)

**Comment by rvilarl** [comment]
![Bend Double_Bends](https://user-images.githubusercontent.com/22865285/117550651-c0dcf100-b041-11eb-9c77-2c9587654476.png)
**Migrated (yellow bar):**
![Bend Double_Bends_Current](https://user-images.githubusercontent.com/22865285/117550656-c5090e80-b041-11eb-8d08-fbbc5630259f.png)
**Reference(master)**
![Bend Double_Bends_Reference](https://user-images.githubusercontent.com/22865285/117550659-c89c9580-b041-11eb-8b69-fdccf6761f62.png)

**Comment by rvilarl** [comment]
![Three_Voice_Rests Auto_Adjust_Rest_Positions___Two_Voices](https://user-images.githubusercontent.com/22865285/117550792-7d36b700-b042-11eb-9c51-71884df8eaa4.png)
**Migrated(Default rest positions are different, but I would say better located)**
![Three_Voice_Rests Auto_Adjust_Rest_Positions___Two_Voices_Current](https://user-images.githubusercontent.com/22865285/117550793-8162d480-b042-11eb-93c8-a1bac99c614f.png)
**Reference(Master)**
![Three_Voice_Rests Auto_Adjust_Rest_Positions___Two_Voices_Reference](https://user-images.githubusercontent.com/22865285/117550798-858ef200-b042-11eb-801f-6d254c805ccf.png)

**Comment by AaronDavidNewman** [comment]
Regarding the last example (3 voice rests), it looks like the default setting to `align_rests` was false but now it's true.

**Comment by rvilarl** [comment]
@0xfe do you have a clue where the yellow lines are coming from.d

> Regarding the last example (3 voice rests), it looks like the default setting to `align_rests` was false but now it's true.

@AaronDavidNewman I do not find the error on the default, I am considering doing a draft PR so that you can have it a look.
