### ISSUE TITLE
How to hide barlines

### ISSUE THREAD

**Issue by bambax** [0xfe/vexflow#980]
Is it possible to hide barlines?

Erik Satie didn't like the concepts of measures, bars or time in general, and therefore some believe that a faithful rendition of his scores should not include barlines (although most do).

Is it possible in vexflow to simply not draw the barlines, while still having proper voices? (not just setting the voice strict mode to false).

**Comment by sschmidTU** [comment]
```js
stave.setEndBarType(Vex.Flow.Barline.type.NONE);
```
something like that should do it.
(it works in OSMD)

**Comment by bambax** [comment]
Thank you!
