### ISSUE TITLE
EasyScore: should concat(accids) be changed to push(...accids)?

### ISSUE THREAD

**Issue by ronyeh** [0xfe/vexflow#998]
https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/easyscore.js#L313

The above line uses concat, which does not modify the accidentals array.  Should it be changed to "push" as in the line before ([line 312](https://github.com/0xfe/vexflow/blob/3e13b92cc7437d5c6ac2b23fa2d056bb1f0f1564/src/easyscore.js#L312))? I encountered this during the migration of EasyScore to TS.

**Comment by ronyeh** [comment]
It seems like it should either be:

```
this.elements.accidentals = accids;
```

or

```
this.elements.accidentals.push(...accids);
```

**Comment by 0xfe** [comment]
That's a good catch. Definitely should be fixed.

We haven't noticed so far because the accidentals are attached to the notes, and there's no good usecase for "just give me the accidentals without the notes".

**Comment by ronyeh** [comment]
Got it. So to fix it should I actually not use the accids array? Because that's only strings (or nulls).

`this.elements.notes.push(note);` actually pushes on StaveNote objects created by `factory.StaveNote({})`, so to maintain consistency I feel like I should be pushing on arrays of Accidental objects created by `factory.Accidental({ type: accid })`.

I'll try it this way and show you the diff.

**Comment by ronyeh** [comment]
Here's the diff: https://github.com/ronyeh/vexflow/commit/901e278a6a2e4861787a4cdc69f4c5b29a028d8b

I added the fix into the EasyScore migration PR.
